### ISSUE TITLE
Nuxt generate won't finish when there is mode: 'hash' in router

### ISSUE THREAD

**Issue by yangwao** [nuxt/nuxt.js#1009]
To reproduce
```
vue init nuxt/starter router.mode
cd router.mode;npm i
```
add `router: { mode: 'hash' },` to `nuxt.config.js`
then `npm run generate`
```
⫸  npm run generate

> router.mode@1.0.0 generate /Users/wao/Projects/router.mode
> nuxt generate

[nuxt] Generating...
  nuxt:build App root: /Users/wao/Projects/router.mode +0ms
  nuxt:build Generating /Users/wao/Projects/router.mode/.nuxt files... +1ms
  nuxt:build Generating files... +24ms
  nuxt:build Generating routes... +31ms
  nuxt:build Building files... +72ms
Build completed in 7.53s

[nuxt:build:client]
 Hash: d40647ac3d151e6fc802
Version: webpack 2.6.1
Time: 7534ms
                                Asset       Size  Chunks             Chunk Names
0.nuxt.bundle.39a9a9f2f9eff960c6c0.js    7.65 kB       0  [emitted]  pages/index
1.nuxt.bundle.01cb7331534f6ba0471e.js    2.79 kB       1  [emitted]  layouts/default
vendor.bundle.6743fffbb1eeceb23dde.js     135 kB       2  [emitted]  vendor
  nuxt.bundle.5357e85de24767dadc0e.js    23.9 kB       3  [emitted]  app
     manifest.d40647ac3d151e6fc802.js    1.51 kB       4  [emitted]  manifest
                           index.html  132 bytes          [emitted]
                 client-manifest.json    5.54 kB          [emitted]
[nuxt:build:server]
 Hash: a24e14f4c74d9a412fe6
Version: webpack 2.6.1
Time: 774ms
             Asset    Size  Chunks             Chunk Names
server-bundle.json  100 kB          [emitted]
  nuxt:generate Destination folder cleaned +9s
  nuxt:generate Static & build files copied +16ms
TypeError: Cannot read property 'forEach' of undefined
    at decorateWithPayloads (/Users/wao/Projects/router.mode/node_modules/nuxt/dist/nuxt.js:1330:29)
    at Nuxt._callee2$ (/Users/wao/Projects/router.mode/node_modules/nuxt/dist/nuxt.js:1430:20)
    at tryCatch (/Users/wao/Projects/router.mode/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/wao/Projects/router.mode/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/wao/Projects/router.mode/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/wao/Projects/router.mode/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/wao/Projects/router.mode/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! router.mode@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the router.mode@1.0.0 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wao/.npm/_logs/2017-07-01T22_07_00_879Z-debug.log
```
```
⫸  node -v
v6.11.0
⫸  npm --version
5.0.4
⫸  grep 'version' node_modules/nuxt/package.json
  "version": "1.0.0-alpha.4"
```
Tips?

**Comment by yangwao** [comment]
I would like also motivate someone to help fix this for $10-$30 in Bitcoin/Litecoin/Ethereum and put it into npm release. 
As I see Nuxt.js is not part of [tip4commits](https://tip4commit.com/projects) and at Opencollective you needs proof-of-expense.
Is someone interested to lookup?

**Comment by husayt** [comment]
Seems like hash mode is broken with server side rendering. Happens with both run dev and run generate

**Comment by pi0** [comment]
@yangwao @husayt Is this bug still exists with latest `rc3` release?

**Comment by husayt** [comment]
@pi0 yes, I see it in version rc3. 

>  [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render

**Comment by Atinux** [comment]
Hi @husayt this is normal in `hash` mode since the server-side does not know the right URL (the # is not given to the server).

Closing it since the generate now finishes with `rc3`
