### ISSUE TITLE
Request API fail inside asyncData on generate static files.

### ISSUE THREAD

**Issue by mena234** [nuxt/nuxt.js#10360]
I'm building static pages with Nuxtjs, I have each page has multiple languages, to get the text of the page, I send a request to the backend by the language I need ( I get the language I need by URLpath, for example, if path = 'fr/pageName' so I request to get the page text with French, if path = en/pageName, I request the backend to get the page text with English.
In development mode ( nuxt dev ), I don't face any issue.
But when I generate the static files with this command "nuxt generate", there is a mysterious error produced inside the asyncData.

error stack

Not Found                                                                                              19:22:41

  at fn (server.js:3076:15)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async http_HTTP.module.exports.http_HTTP.<computed> [as post] (server.js:7445:24)
  at async fetchPageText (server.js:6139:20)
  at async Promise.all (index 0)
  at async asyncData (server.js:6239:22)

Nuxt version: 2.15.3

**Comment by BartekZienkiewicz** [comment]
@mena234 did you manage to solve this issue? I'm stuck here as well
