### ISSUE TITLE
Erro on generate

### ISSUE THREAD

**Issue by raisiqueira** [nuxt/nuxt.js#1042]
I'm running the npm run generate (nuxt generate) command, and return this:
```
[nuxt:build:server]
 Hash: 79f40749579db25e5ea5
Version: webpack 2.6.0
Time: 4379ms
             Asset    Size  Chunks                    Chunk Names
server-bundle.json  922 kB          [emitted]  [big]  
  nuxt:generate Destination folder cleaned +25s
  nuxt:generate Static & build files copied +159ms
  nuxt:render Rendering url / +3ms
  nuxt:render Rendering url /sobre +186ms
  nuxt:render Rendering url /representantes +3ms
  nuxt:render Rendering url /produtos +2ms
  nuxt:render Rendering url /noticias +1ms
  nuxt:render Rendering url /contato +2ms
  nuxt:render Rendering url /rh-estagio +1ms
[Vue warn]: Error in beforeCreate hook: "ReferenceError: document is not defined"

found in

---> <Parallax> at /Users/jjuszczak/Projekte/Privat/vue-parallax/src/components/Parallax.vue
       <Anonymous>
         <Nuxt>
           <Anonymous>
             <Root>
  nuxt:generate Generate file: /sobre/index.html +158ms
  nuxt:generate Generate file: /contato/index.html +2ms
  nuxt:generate Generate file: /representantes/index.html +2s
  nuxt:generate Generate file: /rh-estagio/index.html +4ms
(node:8007) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 404
  nuxt:generate Generate file: /index.html +294ms
  nuxt:generate Generate file: /noticias/index.html +270ms
  nuxt:generate Generate file: /produtos/index.html +271ms
  nuxt:generate HTML Files generated in 27.8s +5ms
==== Error report ==== 
Route: '/sobre'
ReferenceError: document is not defined
    at addStyle (/home/rai/projetos/novo-site-imec/node_modules/vue-parallaxy/dist/vue-parallaxy.js:2369:23)
    at addStylesToDom (/home/rai/projetos/novo-site-imec/node_modules/vue-parallaxy/dist/vue-parallaxy.js:2353:21)
    at module.exports (/home/rai/projetos/novo-site-imec/node_modules/vue-parallaxy/dist/vue-parallaxy.js:2307:4)
    at Object.<anonymous> (/home/rai/projetos/novo-site-imec/node_modules/vue-parallaxy/dist/vue-parallaxy.js:122:37)
    at __webpack_require__ (/home/rai/projetos/novo-site-imec/node_modules/vue-parallaxy/dist/vue-parallaxy.js:30:30)
    at VueComponent.injectStyle (/home/rai/projetos/novo-site-imec/node_modules/vue-parallaxy/dist/vue-parallaxy.js:74:4)
    at callHook (/home/rai/projetos/novo-site-imec/node_modules/vue/dist/vue.runtime.common.js:2554:21)
    at VueComponent.Vue._init (/home/rai/projetos/novo-site-imec/node_modules/vue/dist/vue.runtime.common.js:3994:5)
    at new VueComponent (/home/rai/projetos/novo-site-imec/node_modules/vue/dist/vue.runtime.common.js:4167:12)
    at createComponentInstanceForVnode (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5384:10)
    at renderComponentInner (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5531:40)
    at renderComponent (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5506:5)
    at RenderContext.renderNode (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5422:5)
    at RenderContext.next (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:2179:14)
    at RenderContext.cachedWrite [as write] (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:1648:9)
    at RenderContext.next (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:2182:14)

Route: '/sobre'
Error: HTML minification failed. Make sure the route generates valid HTML. Failed HTML:
 undefined
    at Nuxt._callee$ (/home/rai/projetos/novo-site-imec/node_modules/nuxt/dist/nuxt.js:1408:49)
    at tryCatch (/home/rai/projetos/novo-site-imec/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/rai/projetos/novo-site-imec/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as throw] (/home/rai/projetos/novo-site-imec/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/rai/projetos/novo-site-imec/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/rai/projetos/novo-site-imec/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13

Route: '/contato'
Error: render function or template not defined in component: anonymous
    at normalizeRender (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5413:13)
    at renderComponentInner (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5535:3)
    at renderComponent (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5506:5)
    at renderNode (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5422:5)
    at renderComponentInner (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5542:3)
    at renderComponent (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5506:5)
    at renderNode (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5422:5)
    at renderComponentInner (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5542:3)
    at renderComponent (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5506:5)
    at RenderContext.renderNode (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:5422:5)
    at RenderContext.next (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:2179:14)
    at RenderContext.cachedWrite [as write] (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:1648:9)
    at RenderContext.next (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:2182:14)
    at RenderContext.next (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:2188:12)
    at RenderContext.cachedWrite [as write] (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:1648:9)
    at RenderContext.next (/home/rai/projetos/novo-site-imec/node_modules/vue-server-renderer/build.js:2182:14)

Route: '/contato'
Error: HTML minification failed. Make sure the route generates valid HTML. Failed HTML:
 undefined
    at Nuxt._callee$ (/home/rai/projetos/novo-site-imec/node_modules/nuxt/dist/nuxt.js:1408:49)
    at tryCatch (/home/rai/projetos/novo-site-imec/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/rai/projetos/novo-site-imec/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as throw] (/home/rai/projetos/novo-site-imec/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/rai/projetos/novo-site-imec/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/rai/projetos/novo-site-imec/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13

Route: '/rh-estagio'
Error: Request failed with status code 404
    at createError (/home/rai/projetos/novo-site-imec/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/home/rai/projetos/novo-site-imec/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/rai/projetos/novo-site-imec/node_modules/axios/lib/adapters/http.js:191:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Route: '/rh-estagio'
Error: HTML minification failed. Make sure the route generates valid HTML. Failed HTML:
 undefined
    at Nuxt._callee$ (/home/rai/projetos/novo-site-imec/node_modules/nuxt/dist/nuxt.js:1408:49)
    at tryCatch (/home/rai/projetos/novo-site-imec/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/rai/projetos/novo-site-imec/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as throw] (/home/rai/projetos/novo-site-imec/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/rai/projetos/novo-site-imec/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/rai/projetos/novo-site-imec/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
[nuxt] Generate done
```

**Comment by pi0** [comment]
> ReferenceError: document is not defined

Hey. This seems you are using a library which is not supporting SSR. Please see this references:

- https://nuxtjs.org/faq/window-document-undefined
- https://github.com/egoist/vue-no-ssr (to wrap Parallax inside it)
