### ISSUE TITLE
Nuxt generates error when installing dependencies

### ISSUE THREAD

**Issue by ejlocop** [nuxt/nuxt.js#10427]
### Versions

- nuxt: ^2.15.8
- node: v18.1.0

### Reproduction

I've created the project by running `npm init nuxt-app <project-name>`
but when it goes to install the dependencies, it generates an error.

<details open>
<summary>error log</summary>

```
9293 info run deasync@0.1.26 install node_modules/deasync node ./build.js
9294 info run deasync@0.1.26 install { code: 1, signal: null }
9295 timing reify:rollback:createSparse Completed in 19158ms
9296 timing reify:rollback:retireShallow Completed in 0ms
9297 timing command:install Completed in 211869ms
9298 verbose stack Error: command failed
9298 verbose stack     at ChildProcess.<anonymous> (C:\Users\{user}\AppData\Roaming\nvm\v18.1.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
9298 verbose stack     at ChildProcess.emit (node:events:527:28)
9298 verbose stack     at maybeClose (node:internal/child_process:1090:16)
9298 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
9299 verbose pkgid deasync@0.1.26
9300 verbose cwd D:\Projects\_javascript\nuxtproj
9301 verbose Windows_NT 10.0.19042
9302 verbose node v18.1.0
9303 verbose npm  v8.8.0
9304 error code 1
9305 error path D:\Projects\_javascript\nuxtproj\node_modules\deasync
9306 error command failed
9307 error command C:\WINDOWS\system32\cmd.exe /d /s /c node ./build.js
9308 error gyp info it worked if it ends with ok
9308 error gyp info using node-gyp@9.0.0
9308 error gyp info using node@18.1.0 | win32 | x64
9308 error gyp info find Python using Python version 3.10.4 found at "C:\Users\{user}\AppData\Local\Programs\Python\Python310\python.exe"
9308 error gyp ERR! find VS 
9308 error gyp ERR! find VS msvs_version not set from command line or npm config
9308 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
9308 error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
9308 error gyp ERR! find VS looking for Visual Studio 2015
9308 error gyp ERR! find VS - not found
9308 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
9308 error gyp ERR! find VS 
9308 error gyp ERR! find VS **************************************************************
9308 error gyp ERR! find VS You need to install the latest version of Visual Studio
9308 error gyp ERR! find VS including the "Desktop development with C++" workload.
9308 error gyp ERR! find VS For more information consult the documentation at:
9308 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
9308 error gyp ERR! find VS **************************************************************
9308 error gyp ERR! find VS 
9308 error gyp ERR! configure error 
9308 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
9308 error gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\{user}\AppData\Roaming\nvm\v18.1.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
9308 error gyp ERR! stack     at C:\Users\{user}\AppData\Roaming\nvm\v18.1.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
9308 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\{user}\AppData\Roaming\nvm\v18.1.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
9308 error gyp ERR! stack     at C:\Users\{user}\AppData\Roaming\nvm\v18.1.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
9308 error gyp ERR! stack     at C:\Users\{user}\AppData\Roaming\nvm\v18.1.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
9308 error gyp ERR! stack     at C:\Users\{user}\AppData\Roaming\nvm\v18.1.0\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
9308 error gyp ERR! stack     at C:\Users\{user}\AppData\Roaming\nvm\v18.1.0\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
9308 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:395:5)
9308 error gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
9308 error gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
9308 error gyp ERR! System Windows_NT 10.0.19042
9308 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\{user}\\AppData\\Roaming\\nvm\\v18.1.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
9308 error gyp ERR! cwd D:\Projects\_javascript\nuxtproj\node_modules\deasync
9308 error gyp ERR! node -v v18.1.0
9308 error gyp ERR! node-gyp -v v9.0.0
9308 error gyp ERR! not ok 
9308 error Build failed
```
</details>

<details open>
<summary>nuxt.config.js</summary>

```
export default {
	// Disable server-side rendering: https://go.nuxtjs.dev/ssr-mode
	ssr: false,

	// Target: https://go.nuxtjs.dev/config-target
	target: 'static',

	// Global page headers: https://go.nuxtjs.dev/config-head
	head: {
		title: 'nuxtproj',
		meta: [
			{ charset: 'utf-8' },
			{ name: 'viewport', content: 'width=device-width, initial-scale=1' },
			{ hid: 'description', name: 'description', content: '' },
			{ name: 'format-detection', content: 'telephone=no' }
		],
		link: [
			{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
		]
	},

	// Global CSS: https://go.nuxtjs.dev/config-css
	css: [
	],

	// Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
	plugins: [
	],

	// Auto import components: https://go.nuxtjs.dev/config-components
	components: true,

	// Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
	buildModules: [
		// https://go.nuxtjs.dev/typescript
		'@nuxt/typescript-build',
		// https://go.nuxtjs.dev/tailwindcss
		'@nuxtjs/tailwindcss',
	],

	// Modules: https://go.nuxtjs.dev/config-modules
	modules: [
		// https://go.nuxtjs.dev/pwa
		'@nuxtjs/pwa',
	],

	// PWA module configuration: https://go.nuxtjs.dev/pwa
	pwa: {
		manifest: {
			lang: 'en'
		}
	},

	// Build Configuration: https://go.nuxtjs.dev/config-build
	build: {
	}
}
```
</details>

**Comment by ejlocop** [comment]
seems like some of the dependencies are not compatible with node 18. had to use node 16 for this to install

**Comment by ks221197** [comment]
@ejlocop does nuxt@2.15.8 not compatible with node v14.19.3 and npm@6.14.17?
i am getting error like below while deploying,

internal/modules/cjs/loader.js:1102
ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
/var/app/current/node_modules/wrap-ansi/index.js | Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:
/var/app/current/node_modules/wrap-ansi/index.js from /var/app/current/node_modules/@nuxt/cli/dist/cli-index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /var/app/current/node_modules/wrap-ansi/package.json. | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /var/app/current/node_modules/wrap-ansi/package.json.
at new NodeError (internal/errors.js:322:7) | at new NodeError (internal/errors.js:322:7)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13) | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
at Module.load (internal/modules/cjs/loader.js:950:32) | at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12) | at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Module.require (internal/modules/cjs/loader.js:974:19) | at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:101:18) | at require (internal/modules/cjs/helpers.js:101:18)
at Object. (/var/app/current/node_modules/@nuxt/cli/dist/cli-index.js:15:18) | at Object. (/var/app/current/node_modules/@nuxt/cli/dist/cli-index.js:15:18)
