### ISSUE TITLE
Node.JS preset runs out of memory

### ISSUE THREAD

**Issue by mishushakov** [nuxt/nuxt.js#10436]
### Versions

- nuxt: 3.0.0-rc.1
- node: v16.15.0

### Reproduction

Config

```js
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  nitro: {
    preset: 'node-server'
  }
})
```

Commands

```sh
npm run build
```

```sh
npm run preview
```

### What is Expected?

The app should be served from localhost:3000

### What is actually happening?

Connection times out and Node.JS runs out of memory

```sh
mish@ushakov typosaur % npm run build   

> build
> nuxt build

Nuxt CLI v3.0.0-rc.1                                                                                                                    16:52:47
ℹ Vite client warmed up in 1272ms                                                                                                       16:52:53
ℹ Client built in 2688ms                                                                                                                16:52:54
ℹ Building server...                                                                                                                    16:52:54
✔ Server built in 1268ms                                                                                                                16:52:56
✔ Generated public .output/public                                                                                                 nitro 16:52:56
start Building server...                                                                                                          nitro 16:52:56

 WARN  Multiple major versions of package whatwg-url are being externalized. Picking latest version.                                    16:53:02
  - /Users/mish/Downloads/typosaur/node_modules/jsdom/node_modules/whatwg-url@10.0.0
  - /Users/mish/Downloads/typosaur/node_modules/data-urls/node_modules/whatwg-url@11.0.0

start Writing server bundle...                                                                                                    nitro 16:53:02
✔ Server built                                                                                                                    nitro 16:53:03
  ├─ .output/server/package.json (2.09 kB) (819 B gzip)
  ├─ .output/server/index.mjs.map (105 B) (100 B gzip)
  ├─ .output/server/index.mjs (398 B) (228 B gzip)
  ├─ .output/server/chunks/vue3.mjs.map (355 B) (237 B gzip)
  ├─ .output/server/chunks/vue3.mjs (317 B) (226 B gzip)
  ├─ .output/server/chunks/nitro/static.mjs.map (2.16 kB) (604 B gzip)
  ├─ .output/server/chunks/nitro/static.mjs (2.77 kB) (1.15 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs.map (15.2 kB) (2.82 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs (12.6 kB) (4.1 kB gzip)
  ├─ .output/server/chunks/index.mjs.map (1.81 MB) (84.2 kB gzip)
  ├─ .output/server/chunks/index.mjs (405 kB) (92.2 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs.map (29.9 kB) (4.82 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs (23.6 kB) (6.52 kB gzip)
  ├─ .output/server/chunks/check.post.mjs.map (5.75 kB) (1.59 kB gzip)
  ├─ .output/server/chunks/check.post.mjs (5.41 kB) (2.08 kB gzip)
  ├─ .output/server/chunks/app/server.mjs.map (172 kB) (24.4 kB gzip)
  ├─ .output/server/chunks/app/server.mjs (149 kB) (37.4 kB gzip)
  ├─ .output/server/chunks/app/client.manifest.mjs.map (354 B) (234 B gzip)
  └─ .output/server/chunks/app/client.manifest.mjs (314 B) (211 B gzip)
Σ Total size: 10.1 MB (2.12 MB gzip)
✔ You can preview this build using node .output/server/index.mjs                                                                  nitro 16:53:04
mish@ushakov typosaur % npm run preview

> preview
> nuxt preview

Nuxt CLI v3.0.0-rc.1                                                                                                                    16:53:12
ℹ Node.js version: 16.15.0                                                                                                              16:53:13
ℹ Preset: node-server                                                                                                                   16:53:13
ℹ Working dir: .output                                                                                                                  16:53:13
ℹ Starting preview command: node ./server/index.mjs                                                                                     16:53:13
                                                                                                                                        16:53:13
Listening on http://0.0.0.0:3000/

<--- Last few GCs --->

[82682:0x7fab21100000]    54511 ms: Mark-sweep (reduce) 2053.0 (2060.6) -> 2046.9 (2054.7) MB, 10.9 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 43 ms) (average mu = 0.657, current mu = 0.770)[82682:0x7fab21100000]    54541 ms: Mark-sweep (reduce) 2052.9 (2060.6) -> 2052.8 (2060.6) MB, 1.9 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 25 ms) (average mu = 0.777, current mu = 0.937) 

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10abc8a85 node::Abort() [/usr/local/bin/node]
 2: 0x10abc8c08 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x10ad41a87 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10ad41a23 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x10aee0465 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x10aedeccc v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x10aeeb640 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 8: 0x10aeeb6c1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x10aeb285d v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [/usr/local/bin/node]
10: 0x10aeb9d2c v8::internal::Factory::NewStringFromOneByte(v8::base::Vector<unsigned char const> const&, v8::internal::AllocationType) [/usr/local/bin/node]
11: 0x10b2b8f65 v8::internal::Uri::Encode(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, bool) [/usr/local/bin/node]
12: 0x10adc12e7 v8::internal::Builtin_GlobalEncodeURI(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x10b6087b9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]

 ERROR  Command was killed with SIGABRT (Aborted): node ./server/index.mjs                                                              16:54:08

  at makeError (node_modules/nuxt/node_modules/nuxi/dist/chunks/index5.mjs:1242:11)
  at handlePromise (node_modules/nuxt/node_modules/nuxi/dist/chunks/index5.mjs:2071:26)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.invoke (node_modules/nuxt/node_modules/nuxi/dist/chunks/preview.mjs:224:5)
  at async _main (node_modules/nuxt/node_modules/nuxi/dist/cli.mjs:46:20)
```

**Comment by mishushakov** [comment]
There was an issue in my project's imports

**Comment by hadelnasr** [comment]
@mishushakov will you please share the way you fixed your issue?

**Comment by mishushakov** [comment]
Hey folks, sorry, I'm no longer using Nuxt

**Comment by hadelnasr** [comment]
> 

Just tell us how you managed to solve this issue before?
