### ISSUE TITLE
Plugin not found: C:\Users\-----\test-nuxt\.nuxt\components\plugin.js

### ISSUE THREAD

**Issue by Gumbraise** [nuxt/nuxt.js#10444]
### Versions

- nuxt: v2.15.8
- node: v16.15.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>
The nuxt.config.js is the basic one.
<br>
This problem is only on Windows, I tried with my Debian and it works perfectly. So I uninstalled Node and removed all its folders (node, npm, yarn) everywhere (%appdata%, Program Files, etc...) and reinstalled Node and I always have the same problem.
</details>

### Steps to reproduce

``npx create-nuxt-app test-nuxt``
```
JavaScript
Yarn
TailwindCSS (or not)
Axios (or not)
None
None
Universal
Static
Dependabot (or not)
```
``cd test-nuxt``
``yarn dev``

### What is Expected?

Nuxt start

### What is actually happening?

Nuxt won't start and give me the following error:

```sh
yarn run v1.22.18
$ nuxt

   ╭───────────────────────────────────────────────────────╮
   │                                                       │
   │   Nuxt @ v2.15.8                                      │
   │                                                       │
   │   ▸ Environment: development                          │
   │   ▸ Rendering:   server-side                          │
   │   ▸ Target:      static                               │
   │                                                       │
   │   Listening: http://localhost:3000/                   │
   │                                                       │
   │   Tailwind Viewer: http://localhost:3000/_tailwind/   │
   │                                                       │
   ╰───────────────────────────────────────────────────────╯

i Preparing project for development                                                                           13:40:00
i Initial build may take a while                                                                              13:40:00
i Discovered Components: .nuxt/components/readme.md                                                           13:40:00
√ Builder initialized                                                                                         13:40:00
√ Nuxt files generated                                                                                        13:40:00

 ERROR  Plugin not found: C:\Users\-----\test-nuxt\.nuxt\components\plugin.js                          13:40:00

  at node_modules\@nuxt\builder\dist\builder.js:740:15
  at async Promise.all (index 0)
  at async Builder.build (node_modules\@nuxt\builder\dist\builder.js:324:5)
  at async Object._buildDev (node_modules\@nuxt\cli\dist\cli-dev.js:107:5)
  at async Object.startDev (node_modules\@nuxt\cli\dist\cli-dev.js:65:7)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-dev.js:52:5)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:413:7)
```

**Comment by SzymonLisowiec** [comment]
https://github.com/nuxt/nuxt.js/issues/10440#issuecomment-1126714019

**Comment by vencho-mdp** [comment]
same problem here

**Comment by Jernasai04** [comment]
same problem

**Comment by ottschoThomas** [comment]
I have the same problem

**Comment by Gumbraise** [comment]
> [#10440 (comment)](https://github.com/nuxt/nuxt.js/issues/10440#issuecomment-1126714019)

Duuuuude, you saved my whole life ! Thank you
