### ISSUE TITLE
Server will print recursive errors in undefined routes

### ISSUE THREAD

**Issue by SaeedP11** [nuxt/nuxt.js#10542]
- nuxt: v3.0.0-rc.4
- node: v17.0.0

### Problem
i have a nuxtjs project with express (for server middleware) ... in dev everythings is okay but when i build app, in wrong routes or better i say not found routes server not respond to client and will print recursive errors ... i solve this problems for my routes in express but for assets (img, css, ...) i stil have this problem ... for example in build app when i try to change img tag src and client send requetst to server to get new image, server print that recursive errors and i should restart the app in terminal

my nuxt config file for server middleware is:
```
serverMiddleware: [
      {
          path: "/",
          handler: "./server/main"
      }
  ],
```

and in ./server/main file i have different modules, routes and middlewares

and this is a part of recursive error in my terminal
`2526data%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252526statusCode=500%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252526statusMessage=Internal%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252BServer%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252BError%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252526message=Cannot%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252Bset%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252Bproperties%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525`

**all errors are duplicate and say can't set property on undefined variable (location) and it seems this is related to h3 module**

### What is Expected?
i excepted to server response to client with 404 status code 

### What is actually happening?
server responsed with 500 (internal server error) and server print recursive and repeat errors and i should stop server and run it again

**Comment by Morpheu5** [comment]
Not sure if this is related, but I'm seeing this on a fairly basic nuxt v3 + tailwind project. This error is literally all I get and I can't figure out where the problem might be. The 500 pops up randomly, it may appear and then disappear on refresh, and then appear again.

```[Vue warn]: Failed to resolve component: string
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[h3] [unhandled] H3Error: Invalid value used as weak map key
    at createError (file:///Users/morpheu5/web/afnuxt/node_modules/h3/dist/index.mjs:196:15)
    at Server.nodeHandler (file:///Users/morpheu5/web/afnuxt/node_modules/h3/dist/index.mjs:386:21) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
[nuxt] [request error] Invalid value used as weak map key
  at createError (./node_modules/h3/dist/index.mjs:196:15)  
  at Server.nodeHandler (./node_modules/h3/dist/index.mjs:386:21)
                                                                                                                                                                                                                                                     15:20:38
[TypeScript] Found 0 errors. Watching for file changes.
[Vue warn]: Failed to resolve component: string
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/Users/morpheu5/web/afnuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3966:11)
    at createComponentInstance (/Users/morpheu5/web/afnuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6957:23)
    at renderComponentVNode (/Users/morpheu5/web/afnuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)
    at Module.ssrRenderComponent (/Users/morpheu5/web/afnuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at _sfc_ssrRender (file:///Users/morpheu5/web/afnuxt/.nuxt/dist/server/server.mjs:2998:31)
    at renderComponentSubTree (/Users/morpheu5/web/afnuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (/Users/morpheu5/web/afnuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at renderVNode (/Users/morpheu5/web/afnuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:295:22)
    at renderVNode (/Users/morpheu5/web/afnuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:301:17)```
    
These are my deps:

```  "devDependencies": {
    "@nuxtjs/google-fonts": "^3.0.0-0",
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/typography": "^0.5.4",
    "@types/animejs": "^3.1.4",
    "@types/three": "^0.141.0",
    "animejs": "^3.2.1",
    "autoprefixer": "^10.4.7",
    "cssnano": "^5.1.12",
    "nuxt": "3.0.0-rc.6",
    "postcss": "^8.4.14",
    "postcss-import": "^14.1.0",
    "postcss-mixins": "^9.0.3",
    "postcss-nested": "^5.0.6",
    "postcss-preset-env": "^7.7.2",
    "tailwindcss": "^3.1.3",
    "three": "^0.141.0",
    "typescript": "^4.7.4"
  }
```
