### ISSUE TITLE
Can't use sass library  (bulma) in global css

### ISSUE THREAD

**Issue by vladzur** [nuxt/nuxt.js#1067]
I have this error on  `version "1.0.0-alpha.5"`:

```
/home/vladzur/MisProyectos/vladzur-front/node_modules/bulma/bulma.sass:2
@charset "utf-8"
^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at r (/home/vladzur/MisProyectos/vladzur-front/node_modules/vue-server-renderer/build.js:5812:16)
    at Object.<anonymous> (webpack:/external "bulma":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 594496abdc56668c5e68:25:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:1696:64)
    at __webpack_require__ (webpack:/webpack/bootstrap 594496abdc56668c5e68:25:0)
    at Object.<anonymous> (.nuxt/App.vue:3:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 594496abdc56668c5e68:25:0)
```

I have this dev dependencies:
```
"devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^3.15.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-promise": "^3.4.1",
    "eslint-plugin-standard": "^2.0.1",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6"
  }
```
And the `nuxt.config.js`

```
css: [
    {src: 'bulma', lang: 'sass'}
  ],
```

**Comment by vladzur** [comment]
I resolve it creating an asset like `app.scss` and importing bulma  `@import "~bulma/bulma"; ` then in nuxt.conf.js just 
```
css: [{ src: '~assets/sass/app.scss', lang: 'scss' }],
```
but the documentation says otherwise

**Comment by uptownhr** [comment]
can you point us to the docs?

**Comment by chengwudji** [comment]
I had the same problem; my solution is download the bulma.min.css then add it in nuxt.conf.js

**Comment by vladzur** [comment]
In the Docs https://nuxtjs.org/api/configuration-css just adding this config is enought
```
{ src: 'bulma', lang: 'sass' }
```
But `SyntaxError: Invalid or unexpected token` is triggered

**Comment by geodeveloper** [comment]
Same problem here.

nuxt.config.js:
```
module.exports = {
    css: [
        {
            src: 'bulma',
            lang: 'sass'
        },
    ]
};
```
In browser:
```
Nuxt.js Error:

/Users/geo/GitProjects/nuxt-project/node_modules/bulma/bulma.sass:2
@charset "utf-8"
^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at r (/Users/geo/GitProjects/nuxt-project/node_modules/vue-server-renderer/build.js:5812:16)
    at Object.<anonymous> (webpack:/external "bulma":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap c678f0ba86d589d6890f:25:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:1516:64)
    at __webpack_require__ (webpack:/webpack/bootstrap c678f0ba86d589d6890f:25:0)
    at Object.<anonymous> (.nuxt/App.vue:3:0)
    at __webpack_require__ (webpack:/webpack/bootstrap c678f0ba86d589d6890f:25:0)
    at Object.module.exports.__webpack_exports__.a (server-bundle.js:969:68)
```

**Comment by selmonal** [comment]
Did anyone solve this problem?

**Comment by BjornMelgaard** [comment]
yes, bulma from nuxtjs/modules (community) works fine

**Comment by BjornMelgaard** [comment]
https://github.com/nuxt-community/modules/tree/master/modules/bulma

**Comment by strathausen** [comment]
It has been hanged to https://github.com/nuxt-community/modules/tree/master/packages/bulma
