### ISSUE TITLE
Nuxt 2: FrontChat widget is not working

### ISSUE THREAD

**Issue by abdullah-336** [nuxt/nuxt.js#10869]
### Versions
    nuxt: 2.15.8
    node: v16.16.0

### Problem:
I am integrating the `frontapp` with my nuxt site. https://dev.frontapp.com/docs/chat-sdk-reference
 It's already working fine with my previous vue site. 
Add the bundle in the script tag of the `nuxt.config.js` file.
```
 head: {
   script: [{ src: 'https://chat-assets.frontapp.com/v1/chat.bundle.js' }]
  },
```
I am integrating the rest of the script in the `Pages/index.vue` file. Like that
```
<script>
if (process.client) {
   window.FrontChat('init', {
    chatId: 'XXXXXXXXXXXXXXX',
    useDefaultLauncher: true
  });
 }
</script>
```
But I am getting this **warning** & **error**.
`[FrontChat][Front] SDK Version: 4.19.0`
```
 Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at chat.bundle.js:1:11569
    at chat.bundle.js:1:11585
    at chat.bundle.js:1:11589
    at chat.bundle.js:1:11593
```
By the way, `FreshChat` https://wchat.freshchat.com/js/widget.js is working fine with Nuxt2. 
But the `frontapp` is not working https://dev.frontapp.com/docs

**Comment by abdullah-336** [comment]
I resolved it by just adding `body: true` because the

`The Front Chat script should be positioned just before the closing body tag.`
```
head: {
   script: [{ 
     src: 'https://chat-assets.frontapp.com/v1/chat.bundle.js' 
     body: true, 
    }]
  },
```
