### ISSUE TITLE
Nodejs 19 compilation error.

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt.js#10881]
Node.js v19.3.0
npm 9.2.0

```
root@HZ1 ~/11 # npm run build 

> bbhxwl@1.0.0 build
> nuxt build


 WARN  vendor has been deprecated due to webpack4 optimization

ℹ Production build
ℹ Bundling for server and client side
ℹ Target: server
ℹ Using components loader to optimize imports
ℹ Discovered Components: .nuxt/components/readme.md
✔ Builder initialized
✔ Nuxt files generated

● Client █████████████████████████ building (10%) 1/2 modules 1 ac
tive
 node_modules/@nuxt/components/lib/installComponents.js

◯ Server
  

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/root/11/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/root/11/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/root/11/node_modules/webpack/lib/NormalModule.js:471:10)
    at /root/11/node_modules/webpack/lib/NormalModule.js:503:5
    at /root/11/node_modules/webpack/lib/NormalModule.js:358:12
    at /root/11/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/root/11/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/root/11/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/root/11/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /root/11/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /root/11/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

```

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt.js/issues/10844.
