### ISSUE TITLE
example with-apollo: "Cannot read property 'collect' of undefined"

### ISSUE THREAD

**Issue by lyquocnam** [nuxt/nuxt.js#1088]
this error in 'with-apollo' example:
```
Nuxt.js Error:

TypeError: Cannot read property 'collect' of undefined
    at _callee$ (middleware/apollo.js:3:39)
    at tryCatch (F:\dev\nuxt\vue-apollo\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (F:\dev\nuxt\vue-apollo\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (F:\dev\nuxt\vue-apollo\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (~/babel-runtime/helpers/asyncToGenerator.js:17:0)
    at server-bundle.js:246:14
    at F (F:\dev\nuxt\vue-apollo\node_modules\core-js\library\modules\_export.js:35:28)
    at server-bundle.js:225:12
    at server-bundle.js:1655:18
    at promisify (.nuxt/utils.js:117:14)
    at middlewareSeries (.nuxt/utils.js:97:9)
    at Object._callee$ (.nuxt/server.js:80:27)
    at tryCatch (F:\dev\nuxt\vue-apollo\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (F:\dev\nuxt\vue-apollo\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (F:\dev\nuxt\vue-apollo\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (~/babel-runtime/helpers/asyncToGenerator.js:17:0)
```

**Comment by jvbianchi** [comment]
related to https://github.com/nuxt/nuxt.js/issues/504
