### ISSUE TITLE
Cannot find module 'node:module'   

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt.js#10887]
I don't know why it can't be started. This error occurred.
<img width="932" alt="image" src="https://user-images.githubusercontent.com/26525599/211047821-e9360859-2b62-4b0f-97a4-2340cd6766ac.png">
```
{
  "name": "bbhxwl",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/proxy": "^2.1.0",
    "@syncfusion/ej2-vue-buttons": "^20.3.58",
    "@syncfusion/ej2-vue-navigations": "^20.3.60",
    "@syncfusion/ej2-vue-querybuilder": "^20.3.59",
    "core-js": "^3.19.3",
    "element-ui": "^2.15.11",
    "nuxt": "^2.15.8",
    "vue": "^2.6.14",
    "vue-server-renderer": "^2.6.14",
    "vue-template-compiler": "^2.6.14",
    "cookie-universal-nuxt": "^2.2.2",
    "webpack": "^4.46.0"
  },
  "devDependencies": {
    "@nuxt/types": "^2.15.8",
    "@nuxt/typescript-build": "^2.1.0"
  }
}

```

**Comment by danielroe** [comment]
What version of node are you using?

**Comment by bbhxwl** [comment]
> What version of node are you using?

I have 2 projects, one of which cannot run, and the other is normal. This is strange.


nodejs v14.17.6

error log 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle bbhxwl@1.0.0~predev: bbhxwl@1.0.0
6 info lifecycle bbhxwl@1.0.0~dev: bbhxwl@1.0.0
7 verbose lifecycle bbhxwl@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle bbhxwl@1.0.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/xuzhibin/Project/gitea/bbhxwl/node_modules/.bin:/Users/xuzhibin/opt/anaconda3/bin:/Users/xuzhibin/opt/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/xuzhibin/Library/Application Support/JetBrains/Toolbox/scripts
9 verbose lifecycle bbhxwl@1.0.0~dev: CWD: /Users/xuzhibin/Project/gitea/bbhxwl
10 silly lifecycle bbhxwl@1.0.0~dev: Args: [ '-c', 'nuxt' ]
11 silly lifecycle bbhxwl@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle bbhxwl@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: bbhxwl@1.0.0 dev: `nuxt`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid bbhxwl@1.0.0
15 verbose cwd /Users/xuzhibin/Project/gitea/bbhxwl
16 verbose Darwin 22.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error bbhxwl@1.0.0 dev: `nuxt`
22 error Exit status 1
23 error Failed at the bbhxwl@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by danielroe** [comment]
You will probably be fine on v14.18.0+. Would you try that?

**Comment by bbhxwl** [comment]
> You will probably be fine on v14.18.0+. Would you try that?

I updated to nodejs 19, but there was still an error.
I ran the following code and also made an error. Mac computer. M1 chip.


export NODE_OPTIONS=--openssl-legacy-provider
```
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/xuzhibin/Project/WebStorm/bbhxwl/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/xuzhibin/Project/WebStorm/bbhxwl/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/xuzhibin/Project/WebStorm/bbhxwl/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/xuzhibin/Project/WebStorm/bbhxwl/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/xuzhibin/Project/WebStorm/bbhxwl/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/xuzhibin/Project/WebStorm/bbhxwl/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/xuzhibin/Project/WebStorm/bbhxwl/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/xuzhibin/Project/WebStorm/bbhxwl/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.4.0



```

**Comment by manniL** [comment]
Let's track in #10889
