### ISSUE TITLE
TypeError: app.use() requires middleware functions (using nuxt ^1.0.0-alpha.3)

### ISSUE THREAD

**Issue by BjornMelgaard** [nuxt/nuxt.js#1138]
can someone help me, error from [here](https://github.com/nuxt-community/express-template/issues/62) :smile:
```js
import Nuxt from 'nuxt'
import express from 'express'

const app = express()
const host = process.env.HOST || '127.0.0.1'
const port = process.env.PORT || 3000

app.set('port', port)

// Start nuxt.js
async function start() {
  // Import and Set Nuxt.js options
  let config = require('../nuxt.config.js')
  config.dev = !(process.env.NODE_ENV === 'production')
  // Instanciate nuxt.js
  const nuxt = new Nuxt(config)
  // Add nuxt.js middleware
  app.use(nuxt.render) # !!!!! error here (seems like) !!!!!!!
  // Listen the server
  app.listen(port, host)
  console.log('Server listening on ' + host + ':' + port) // eslint-disable-line no-console
}

start()
```

full error on `yarn run dev` (`backpack dev`)
```
 DONE  Compiled successfully in 65ms                                                                                          9:44:32 PM

(node:11837) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: app.use() requires middleware functions
```

**Comment by pi0** [comment]
Hi. I've added a basic test for using with express as a middleware. [express.test.js](https://github.com/nuxt/nuxt.js/blob/dev/test/express.test.js). Please ensure that `node_modules` is cleaned up and `nuxt@1.0.0-alpha.5` is installed I think the problem is with the old version that needs waiting on nuxt constructor.

**Comment by BjornMelgaard** [comment]
@pi0  thats weird, I installed all as you said, but it dont want to work with backpack

```
 ~/projects/vue-todolist/client   master ●  yarn run build
yarn run v0.27.5
$ nuxt build && backpack build
[nuxt] Building...
  nuxt:build App root: /home/bjorn/projects/vue-todolist/client +0ms
  nuxt:build Generating /home/bjorn/projects/vue-todolist/client/.nuxt files... +0ms
  nuxt:build Generating files... +11ms
  nuxt:build Generating routes... +20ms
  nuxt:build Building files... +21ms
Build completed in 9.501s

[nuxt:build:client]
 Hash: 0d51da793876fb2f636d
Version: webpack 2.7.0
Time: 9507ms
                                Asset       Size  Chunks             Chunk Names
                 img/logo.a04e995.png    14.3 kB          [emitted]
0.nuxt.bundle.0ed7f002f1def8736bc6.js    2.31 kB       0  [emitted]  layouts/default
1.nuxt.bundle.221ab8237cd2f6ecaaee.js    1.95 kB       1  [emitted]  pages/index
2.nuxt.bundle.f5cb1980a42ca009c51b.js    1.82 kB       2  [emitted]  pages/id
vendor.bundle.547c6a42b8d20e95c7a6.js     138 kB       3  [emitted]  vendor
  nuxt.bundle.4f3f0af98df2bd1c36f4.js    21.7 kB       4  [emitted]  app
     manifest.0d51da793876fb2f636d.js    1.54 kB       5  [emitted]  manifest
                           index.html  132 bytes          [emitted]
                 client-manifest.json    6.78 kB          [emitted]
[nuxt:build:server]
 Hash: 1691a00a4caf87a91e30
Version: webpack 2.7.0
Time: 1057ms
             Asset     Size  Chunks             Chunk Names
server-bundle.json  93.3 kB          [emitted]
[nuxt] Building done


 WARNING  Compiled with 1 warnings                                                                                           10:26:39 AM

 warning
 ✘  ~/projects/vue-todolist/client   master ●  yarn run start
yarn run v0.27.5
$ cross-env NODE_ENV=production node build/main.js
Server listening on 127.0.0.1:3000
```


and when I go to http://localhost:3000/ I get page with this error

```
Nuxt.js Error:

Error: Request failed with status code 404
    at createError (/home/bjorn/projects/vue-todolist/client/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/bjorn/projects/vue-todolist/client/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/bjorn/projects/vue-todolist/client/node_modules/axios/lib/adapters/http.js:191:11)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

and this error in console
```
(node:15929) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 404
```

[source](https://github.com/BjornMelgaard/vue-todolist/blob/master/client/server/index.js)

**Comment by BjornMelgaard** [comment]
maybe this would help 

```
$ yarn upgrade vue-template-compiler vue-loader vue vue-server-renderer
$ rm -rfR node_modules
$  yarn install
$ yarn run dev
yarn run v0.27.5
cross-env PORT=$CLIENT_PORT_DEV backpack dev


 WARNING  Compiled with 1 warnings                                                                                            2:48:31 PM

 warning


Server listening on 127.0.0.1:3000
Build completed in 5.48s



 DONE  Compiled successfully in 5482ms                                                                                        2:48:38 PM

> Open http://127.0.0.1:3000

[Vue warn]: Property or method "_ssrNode" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <NuxtError> at /home/bjorn/projects/vue-todolist/client/layouts/error.vue
       <Nuxt> at /home/bjorn/projects/vue-todolist/client/.nuxt/components/nuxt.vue
         <Default> at /home/bjorn/projects/vue-todolist/client/layouts/default.vue
           <Root>
[Vue warn]: Property or method "_ssrAttr" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <NuxtError> at /home/bjorn/projects/vue-todolist/client/layouts/error.vue
       <Nuxt> at /home/bjorn/projects/vue-todolist/client/.nuxt/components/nuxt.vue
         <Default> at /home/bjorn/projects/vue-todolist/client/layouts/default.vue
           <Root>
[Vue warn]: Error in render function: "TypeError: _vm._ssrAttr is not a function"

found in

---> <NuxtError> at /home/bjorn/projects/vue-todolist/client/layouts/error.vue
       <Nuxt> at /home/bjorn/projects/vue-todolist/client/.nuxt/components/nuxt.vue
         <Default> at /home/bjorn/projects/vue-todolist/client/layouts/default.vue
           <Root>
(node:8443) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 500

```

**Comment by BjornMelgaard** [comment]
`yarn add vue-loader@13.0.2` fixed error above but now i have this (browser)

```
Nuxt.js Error:

Error: render function or template not defined in component: anonymous
    at normalizeRender (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5413:13)
    at renderComponentInner (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5535:3)
    at renderComponent (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5506:5)
    at RenderContext.renderNode (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5422:5)
    at RenderContext.next (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:2179:14)
    at RenderContext.next (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:2188:12)
    at cachedWrite (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:1648:9)
    at renderElement (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5564:5)
    at renderNode (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5425:7)
    at renderComponentInner (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5542:3)
    at renderComponent (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5506:5)
    at RenderContext.renderNode (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5422:5)
    at RenderContext.next (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:2179:14)
    at cachedWrite (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:1648:9)
    at renderElement (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5573:5)
    at renderNode (/home/bjorn/projects/vue-todolist/client/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5425:7)
```

**Comment by BjornMelgaard** [comment]
solved, thanks to @hotspurs
