### ISSUE TITLE
syntax-optional-chaining isn't working

### ISSUE THREAD

**Issue by BjornMelgaard** [nuxt/nuxt.js#1252]
im trying to get `babel-plugin-syntax-optional-chaining` working, my nuxt.config.js looks like

```js
    vendor: ['babel-polyfill'],
    babel: {
      plugins: ['lodash', 'syntax-optional-chaining']
    }
```

but I get an error

```bash
 ✘  ~/projects/vue-todolist/client   master ●  PORT=$CLIENT_PORT_TEST API_PORT=$SERVER_PORT_TEST yr build
yarn run v0.28.4
$ nuxt build
  nuxt:build Building... +0ms
[AXIOS] Base URL: http://localhost:3003/api/edge , Browser: http://localhost:3003/api/edge
  nuxt:build App root: /home/bjorn/projects/vue-todolist/client +85ms
  nuxt:build Generating /home/bjorn/projects/vue-todolist/client/.nuxt files... +1ms
  nuxt:build Generating files... +9ms
  nuxt:build Generating routes... +10ms
  nuxt:build Building files... +38ms
  build [=============       ] 65%Hash: 5f8d64c5bd0752fddef1
Version: webpack 3.4.1
Time: 16536ms
             Asset     Size  Chunks                    Chunk Names
server-bundle.json  2.88 MB          [emitted]  [big]

ERROR in ./node_modules/babel-loader/lib?{"plugins":["lodash","syntax-optional-chaining"],"presets":["vue-app"],"babelrc":false,"cacheDirectory":false}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./components/account/SigninForm.vue
Module build failed: SyntaxError: Unexpected token (54:33)

  52 |         console.log(err.response)
  53 |         // const errors = _.get(err, ['response', 'data', 'errors'])
> 54 |         const errorMessage = err?.response?.data?.errors?.join('\n')
     |                                  ^
  55 |         if (errorMessage) {
  56 |           this.error.text = errorMessage
  57 |         } else {

 @ ./components/account/SigninForm.vue 3:0-248
 @ ./node_modules/babel-loader/lib?{"plugins":["lodash","syntax-optional-chaining"],"presets":["vue-app"],"babelrc":false,"cacheDirectory":false}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/account/signin.vue
 @ ./pages/account/signin.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js
Error: Webpack build exited with errors
    at /home/bjorn/projects/vue-todolist/client/node_modules/nuxt/lib/builder/builder.js:379:27
    at emitRecords.err (/home/bjorn/projects/vue-todolist/client/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/home/bjorn/projects/vue-todolist/client/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/home/bjorn/projects/vue-todolist/client/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/home/bjorn/projects/vue-todolist/client/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/home/bjorn/projects/vue-todolist/client/node_modules/tapable/lib/Tapable.js:200:11)
    at Compiler.compiler.plugin (/home/bjorn/projects/vue-todolist/client/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/bjorn/projects/vue-todolist/client/node_modules/tapable/lib/Tapable.js:204:13)
    at Compiler.afterEmit (/home/bjorn/projects/vue-todolist/client/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/home/bjorn/projects/vue-todolist/client/node_modules/webpack/lib/Compiler.js:360:15)
    at /home/bjorn/projects/vue-todolist/client/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/bjorn/projects/vue-todolist/client/node_modules/async/dist/async.js:998:13)
    at /home/bjorn/projects/vue-todolist/client/node_modules/async/dist/async.js:906:16
    at /home/bjorn/projects/vue-todolist/client/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by BjornMelgaard** [comment]
[code here](https://github.com/BjornMelgaard/vue-todolist/blob/master/client/nuxt.config.js#L39)

**Comment by BjornMelgaard** [comment]
so...how its going? am I using old config?

**Comment by BjornMelgaard** [comment]
can someone help me, plz, im waiting 4 days
[minimal_complete_example](https://mega.nz/#!d51UmDJS!7yFf64avywQGmleHFgswuhnbcC0I2f9M8wb7P3f_9HI)

**Comment by alexchopin** [comment]
Should be fixed with the last release
