### ISSUE TITLE
[HELP] Get store in plugin file

### ISSUE THREAD

**Issue by frankspin89** [nuxt/nuxt.js#1264]
I'm not sure how to get the store context in my apollo plugin file. Read this comment https://github.com/nuxt-community/modules/issues/89#issuecomment-318107891 but i'm not sure how to implement this in my situation.

**plugins/apollo.js**

```
import { ApolloClient, createNetworkInterface } from 'apollo-client';
import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws';

const ssr = process.SERVER_BUILD

// Create the network interface
const networkInterface = createNetworkInterface({
  uri: '',
  transportBatching: true,
});

networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {};  // Create the header object if needed.
    }

    const token = // get from store

    req.options.headers.authorization = token ? `Bearer ${token}` : null;
    next();
  }
}]);

let networkInterfaceWithSubscriptions;

// Create the subscription websocket client
if (! ssr) {
  const wsClient = new SubscriptionClient('', {
    reconnect: true,
    timeout: 20000
  });

  // Extend the network interface with the subscription client
  networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
    networkInterface,
    wsClient,
  );
}


// Create the apollo client with the new network interface
const apolloClient = new ApolloClient({
  networkInterface : ssr ? networkInterface : networkInterfaceWithSubscriptions,
   dataIdFromObject: r => r.id,
   ssrForceFetchDelay: process.browser ? 1 : 0,
    ...(ssr ? {
      ssrMode: true
    } : {
      connectToDevTools: process.env.NODE_ENV !== 'production'
    })
});

export default apolloClient;

```

Tried this but it isn't quite right

```
import { ApolloClient, createNetworkInterface } from 'apollo-client';
import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws';

const ssr = process.SERVER_BUILD

export default ({store}) => {

  // Create the network interface
const networkInterface = createNetworkInterface({
  uri: '',
  transportBatching: true,
});

networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {};  // Create the header object if needed.
    }

    const token = store.auth.token;


    req.options.headers.authorization = token ? `Bearer ${token}` : null;
    next();
  }
}]);

let networkInterfaceWithSubscriptions;

// Create the subscription websocket client
if (! ssr) {
  const wsClient = new SubscriptionClient('', {
    reconnect: true,
    timeout: 20000
  });

  // Extend the network interface with the subscription client
  networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
    networkInterface,
    wsClient,
  );
}


// Create the apollo client with the new network interface
const apolloClient = new ApolloClient({
  networkInterface : ssr ? networkInterface : networkInterfaceWithSubscriptions,
   dataIdFromObject: r => r.id,
   ssrForceFetchDelay: process.browser ? 1 : 0,
    ...(ssr ? {
      ssrMode: true
    } : {
      connectToDevTools: process.env.NODE_ENV !== 'production'
    })
});

return apolloClient;

}
```

**Comment by krestaino** [comment]
Check this out.

https://github.com/nuxt/nuxt.js/blob/dev/examples/i18n/plugins/i18n.js

**Comment by frankspin89** [comment]
@pi0 please don't close issues so quickly.

@krestaino I tried to implement your suggestion. But it's resulting in a error

``` TypeError: Cannot set property 'middleware' of null ```


```
import { ApolloClient, createNetworkInterface } from 'apollo-client';
import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws';
import Vue from 'vue'

const ssr = process.SERVER_BUILD

Vue.use(ApolloClient)

export default ({ app, store }) => {
  // Create the network interface
  const networkInterface = createNetworkInterface({
    uri: '',
    transportBatching: true,
  });

  networkInterface.use([{
    applyMiddleware(req, next) {
      if (!req.options.headers) {
        req.options.headers = {};  // Create the header object if needed.
      }

      const token = store.auth.token;

      console.log('token', token)

      req.options.headers.authorization = token ? `Bearer ${token}` : null;
      next();
    }
  }]);

  let networkInterfaceWithSubscriptions;

  // Create the subscription websocket client
  if (! ssr) {
    const wsClient = new SubscriptionClient('', {
      reconnect: true,
      timeout: 20000
    });

    // Extend the network interface with the subscription client
    networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
      networkInterface,
      wsClient,
    );
  }


  // Create the apollo client with the new network interface
  app.apolloClient = new ApolloClient({
    networkInterface : ssr ? networkInterface : networkInterfaceWithSubscriptions,
    dataIdFromObject: r => r.id,
    ssrForceFetchDelay: process.browser ? 1 : 0,
      ...(ssr ? {
        ssrMode: true
      } : {
        connectToDevTools: process.env.NODE_ENV !== 'production'
      })
  });

}

```

**Comment by frankspin89** [comment]
Minimal example of the error.

```
import { ApolloClient, createNetworkInterface } from 'apollo-client';
import Vue from 'vue'

Vue.use(ApolloClient)

export default ({ app, store }) => {
  console.log('app', app)
  console.log('store', store)

  const networkInterface = createNetworkInterface({
    uri: '',
    transportBatching: true,
  });

  app.apolloClient = new ApolloClient({
    networkInterface
  })
}
```

```
TypeError: Cannot set property 'middleware' of null
    at ApolloClient (.../node_modules/apollo-client/apollo.umd.js:3610:25)
    at Function.Vue.use (..../node_modules/vue/dist/vue.runtime.common.js:4116:14)
    at Object.<anonymous> (plugins/apollo.js:9:4)
    at __webpack_require__ (webpack:/webpack/bootstrap 3411bc355c6d3a86a470:25:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:2304:77)
    at __webpack_require__ (webpack:/webpack/bootstrap 3411bc355c6d3a86a470:25:0)
    at webpackContext (webpack:/store ^\.\/.*\.(js|ts)$:9:0)
    at getModule (.nuxt/store.js:50:15)
    at Object.<anonymous> (.nuxt/store.js:35:19)
    at __webpack_require__ (webpack:/webpack/bootstrap 3411bc355c6d3a86a470:25:0)
    at Object.<anonymous> (server-bundle.js:1145:68)
    at __webpack_require__ (webpack:/webpack/bootstrap 3411bc355c6d3a86a470:25:0)
    at Object.<anonymous> (server-bundle.js:1733:65)
    at __webpack_require__ (webpack:/webpack/bootstrap 3411bc355c6d3a86a470:25:0)
    at server-bundle.js:95:18
    at Object.<anonymous> (server-bundle.js:98:10)
```

**Comment by frankspin89** [comment]
Related: https://github.com/nuxt-community/apollo-module/issues/6#issuecomment-320920623
