### ISSUE TITLE
Running in Node v5.12.0 doesn't work

### ISSUE THREAD

**Issue by ryeballar** [nuxt/nuxt.js#1276]
The `engines` definition in the `package.json` specifies that Node `v5.12.0` should work. 

```
npm run dev

> nuxt-sample@1.0.0 dev /home/ryeballar/workspace/legalmatch/nuxt-sample
> nuxt

/home/ryeballar/workspace/legalmatch/nuxt-sample/node_modules/nuxt/bin/nuxt-dev:11
const { Nuxt, Builder } = require('../')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ryeballar/workspace/legalmatch/nuxt-sample/node_modules/nuxt/bin/nuxt:31:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

npm ERR! Linux 4.8.0-59-generic
npm ERR! argv "/home/ryeballar/.nvm/versions/node/v5.12.0/bin/node" "/home/ryeballar/.nvm/versions/node/v5.12.0/bin/npm" "run" "dev"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! nuxt-sample@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nuxt-sample@1.0.0 dev script 'nuxt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nuxt-sample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nuxt-sample
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nuxt-sample
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ryeballar/workspace/legalmatch/nuxt-sample/npm-debug.log

```

**Comment by pi0** [comment]
Hey. Thanks for reporting we may need to  update engine in package.json as `6.x` is current LTS branch of node which is minimum required. Is there any reason you need to stick with 5.x for Nuxt ?
