### ISSUE TITLE
ReferenceError: navigator is not defined when using bodymovin 

### ISSUE THREAD

**Issue by t42ji2ji** [nuxt/nuxt.js#1278]
when I using [bodymovin](https://github.com/bodymovin/bodymovin)

`import bodymovin from 'bodymovin'
`

It give me this error.
I found the bodymovin is work fine on this vue project [vue-lottie](https://github.com/chenqingspring/vue-lottie/tree/master/src)
Can anyone tell me how to fix it?

```
ReferenceError: navigator is not defined
    at /Users/User/WebApp/nuxt_test/node_modules/bodymovin/build/player/bodymovin.js:4:54
    at svgNS (/Users/User/WebApp/nuxt_test/node_modules/bodymovin/build/player/bodymovin.js:1:224)
    at Object.<anonymous> (/Users/DORA/WebApp/nuxt_test/node_modules/bodymovin/build/player/bodymovin.js:1:275)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at r (/Users/DORA/WebApp/nuxt_test/node_modules/vue-server-renderer/build.js:7739:16)
    at Object.<anonymous> (webpack:/external "bodymovin":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 5360a58a867ded86c8c9:25:0)
    at Object.62 (0.server-bundle.js:79:68)
    at __webpack_require__ (webpack:/webpack/bootstrap 5360a58a867ded86c8c9:25:0)
    at Object.58 (0.server-bundle.js:9:189)
```

**Comment by yunyu** [comment]
See https://nuxtjs.org/faq/window-document-undefined/

Use `process.browser` for RC3

**Comment by uptownhr** [comment]
what is the error you get in production?

**Comment by jadczakd** [comment]
Cannot read property writeText of undefined. Works fine when running it locally.
// I managed to run around with executing the copy command on an input, but still don't get how is this so different in two environments. It seems like parts of Chrome are blocked off the moment I push it up.

**Comment by uptownhr** [comment]
hmm that is interesting. Looks like clipboard is somehow not there... Can you try logging, navigator.clipboard on production right before your `writeText` statement?
