### ISSUE TITLE
[nuxt] store/index.js should export a method which returns a Vuex instance.

### ISSUE THREAD

**Issue by danielsalles** [nuxt/nuxt.js#1280]
Im configuring **Vuex Classic** according to the documentation and am returning the following error.
```
Nuxt.js Error:
   
   Error: [nuxt] store/index.js should export a method which returns a Vuex instance.
       at getModule (.nuxt/store.js:58:10)
       at Object.module.exports.map../index.js (.nuxt/store.js:21:14)
       at __webpack_require__ (webpack:/webpack/bootstrap a643748ba1b66033c6f3:25:0)
       at Object.<anonymous> (server-bundle.js:1570:69)
       at __webpack_require__ (webpack:/webpack/bootstrap a643748ba1b66033c6f3:25:0)
       at Object.<anonymous> (server-bundle.js:1057:65)
       at __webpack_require__ (webpack:/webpack/bootstrap a643748ba1b66033c6f3:25:0)
       at server-bundle.js:92:18
       at Object.<anonymous> (server-bundle.js:95:10)
       at evaluateModule (/home/daniel/dev/kino/site/node_modules/vue-server-renderer/build.js:7747:21)
       at /home/daniel/dev/kino/site/node_modules/vue-server-renderer/build.js:7805:18
       at Promise (<anonymous>)
       at /home/daniel/dev/kino/site/node_modules/vue-server-renderer/build.js:7797:14
       at Object.renderToString (/home/daniel/dev/kino/site/node_modules/vue-server-renderer/build.js:7951:9)
       at P (/home/daniel/dev/kino/site/node_modules/nuxt/node_modules/pify/index.js:49:6)
       at Promise (<anonymous>)
```
Other error random:
```
Nuxt.js Error:

Error: [vuex] must call Vue.use(Vuex) before creating a store instance.
    at assert (/home/daniel/dev/kino/site/node_modules/vuex/dist/vuex.js:102:27)
    at new Store (/home/daniel/dev/kino/site/node_modules/vuex/dist/vuex.js:249:3)
    at Object.<anonymous> (store/index.js:3:14)
    at __webpack_require__ (webpack:/webpack/bootstrap a643748ba1b66033c6f3:25:0)
    at Object.<anonymous> (server-bundle.js:1506:65)
    at __webpack_require__ (webpack:/webpack/bootstrap a643748ba1b66033c6f3:25:0)
    at webpackContext (webpack:/middleware nonrecursive ^\.\/.*\.(js|ts)$:5:0)
    at getModule (.nuxt/middleware.js:6:13)
    at Object.<anonymous> (.nuxt/middleware.js:16:21)
    at __webpack_require__ (webpack:/webpack/bootstrap a643748ba1b66033c6f3:25:0)
    at Object.<anonymous> (server-bundle.js:1056:70)
    at __webpack_require__ (webpack:/webpack/bootstrap a643748ba1b66033c6f3:25:0)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10)
    at evaluateModule (/home/daniel/dev/kino/site/node_modules/vue-server-renderer/build.js:7747:21)
    at /home/daniel/dev/kino/site/node_modules/vue-server-renderer/build.js:7805:18
```

store/index.js
```javascript
import Vuex from 'vuex'

const store = new Vuex.Store({
  state: {
    counter: 0
  },
  mutations: {
    increment (state) {
      state.counter++
    }
  }
})

export default store

```
From what I understood in the documentation **nuxt** would take care of me.

**Comment by pi0** [comment]
Hi. Sorry for inconveniences. Docs are under heavy changes and STILL indicating 0.10.x so. For list of breaking changes please see [1.x release notes](https://github.com/nuxt/nuxt.js/releases). Also store should be like this:

```js
import Vuex from 'vuex'

const store = new Vuex.Store({
  state() {
    counter: 0
  },
  mutations: {
    increment (state) {
      state.counter++
    }
  }
})

export default store

```

For a smooth migration suggest still using 0.x until docs arrive as there are many more changes to be applied in your project.

**Comment by danielsalles** [comment]
I switched to **version 0.10.6** and it worked, but without me doing anything this error happened after a while.
@pi0 
```
Error: [vuex] must call Vue.use(Vuex) before creating a store instance.
    at assert (/home/daniel/dev/kino/site/node_modules/vuex/dist/vuex.js:102:27)
    at new Store (/home/daniel/dev/kino/site/node_modules/vuex/dist/vuex.js:249:3)
    at Object.<anonymous> (store/index.js:3:14)
    at __webpack_require__ (webpack:/webpack/bootstrap c93ead54417a948b7935:25:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:2294:65)
    at __webpack_require__ (webpack:/webpack/bootstrap c93ead54417a948b7935:25:0)
    at webpackContext (webpack:/middleware nonrecursive ^\.\/.*\.js$:5:0)
    at getModule (.nuxt/middleware.js:6:13)
    at Object.module.exports.__webpack_exports__.f (.nuxt/middleware.js:16:21)
    at __webpack_require__ (webpack:/webpack/bootstrap c93ead54417a948b7935:25:0)
    at Object.<anonymous> (server-bundle.js:1968:70)
    at __webpack_require__ (webpack:/webpack/bootstrap c93ead54417a948b7935:25:0)
    at server-bundle.js:95:18
    at Object.<anonymous> (server-bundle.js:98:10)
    at evaluateModule (/home/daniel/dev/kino/site/node_modules/vue-server-renderer/build.js:7747:21)
    at /home/daniel/dev/kino/site/node_modules/vue-server-renderer/build.js:7783:17
```

**Comment by pi0** [comment]
Did you restored old usage of nuxt? (`state: {`)

**Comment by danielsalles** [comment]
Yes.
```javascript
import Vuex from 'vuex'

const store = new Vuex.Store({
  state: {
    mobile: null
  },
  mutations: {
    CHANGE_MOBILE (state, mobile) {
      state.mobile = mobile
    }
  }
})

export default store

```

**Comment by pi0** [comment]
Please try removing yarn.lock and node_modules after the downgrade to see if it fixes?

**Comment by danielsalles** [comment]
Error is here @pi0  . The error is in this commit, I did not quite understand the reason. This file is middleware.
```javascript
import _ from 'ramda'
import MobileDetect from 'mobile-detect'
import store from '../store'

const getAgent = context => context.isServer ? context.req.headers['user-agent'] : navigator.userAgent
const md = userAgent => new MobileDetect(userAgent)
const getMobile = md => md.mobile()
const sendStore = mobile => store.commit('CHANGE_MOBILE', mobile)
const registerMobile = _.pipe(getAgent, md, getMobile)

export default context => sendStore(registerMobile(context))

```

**Comment by pi0** [comment]
And please `rm -r .nuxt` :D Sorry for inconveniences during to temporary downgrade too :(
