### ISSUE TITLE
server crash after nuxt 3 update

### ISSUE THREAD

**Issue by mihail727** [nuxt/nuxt.js#13669]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27487080.ec32cf9`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `privateRuntimeConfig`, `app`, `nitro`, `router`, `components`, `srcDir`, `build`, `buildModules`, `modern`, `tailwindcss`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.2`, `@vueuse/nuxt@8.2.4`
------------------------------

### Reproduction

-

### Describe the bug

Today after update i cant start my project.

<details>
  <summary>errors:</summary>

```
 ERROR  09:16:23 [vite] Internal server error: ENOENT: no such file or directory, open '/_nuxt/pages/auth/login.vue'
      at Object.openSync (node:fs:585:3)
      at Object.readFileSync (node:fs:453:35)
      at getDescriptor (/home/supp/Документы/Code/admin.tm-santrek/node_modules/@vitejs/plugin-vue/dist/index.js:4025:81)
      at Context.load (/home/supp/Документы/Code/admin.tm-santrek/node_modules/@vitejs/plugin-vue/dist/index.js:4702:28)
      at Object.load (/home/supp/Документы/Code/admin.tm-santrek/node_modules/vite/dist/node/chunks/dep-611778e0.js:36509:50)
      at runNextTicks (node:internal/process/task_queues:61:5)
      at processImmediate (node:internal/timers:437:9)
      at async doTransform (/home/supp/Документы/Code/admin.tm-santrek/node_modules/vite/dist/node/chunks/dep-611778e0.js:55446:24)


 ERROR  09:16:23 [vite] Internal server error: ENOENT: no such file or directory, open '/_nuxt/pages/auth/register.vue'
      at Object.openSync (node:fs:585:3)
      at Object.readFileSync (node:fs:453:35)
      at getDescriptor (/home/supp/Документы/Code/admin.tm-santrek/node_modules/@vitejs/plugin-vue/dist/index.js:4025:81)
      at Context.load (/home/supp/Документы/Code/admin.tm-santrek/node_modules/@vitejs/plugin-vue/dist/index.js:4702:28)
      at Object.load (/home/supp/Документы/Code/admin.tm-santrek/node_modules/vite/dist/node/chunks/dep-611778e0.js:36509:50)
      at runNextTicks (node:internal/process/task_queues:61:5)
      at processImmediate (node:internal/timers:437:9)
      at async doTransform (/home/supp/Документы/Code/admin.tm-santrek/node_modules/vite/dist/node/chunks/dep-611778e0.js:55446:24)


 ERROR  09:16:23 [vite] Internal server error: ENOENT: no such file or directory, open '/_nuxt/@fs/home/supp/Документы/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-404.vue'
      at Object.openSync (node:fs:585:3)
      at Object.readFileSync (node:fs:453:35)
      at getDescriptor (/home/supp/Документы/Code/admin.tm-santrek/node_modules/@vitejs/plugin-vue/dist/index.js:4025:81)
      at Context.load (/home/supp/Документы/Code/admin.tm-santrek/node_modules/@vitejs/plugin-vue/dist/index.js:4702:28)
      at Object.load (/home/supp/Документы/Code/admin.tm-santrek/node_modules/vite/dist/node/chunks/dep-611778e0.js:36509:50)
      at async doTransform (/home/supp/Документы/Code/admin.tm-santrek/node_modules/vite/dist/node/chunks/dep-611778e0.js:55446:24)

[Vue Router warn]: No match found for location with path "/_nuxt/@vite/client"

 ERROR  09:16:23 [vite] Internal server error: ENOENT: no such file or directory, open '/_nuxt/@fs/home/supp/Документы/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-500.vue'
      at Object.openSync (node:fs:585:3)
      at Object.readFileSync (node:fs:453:35)
      at getDescriptor (/home/supp/Документы/Code/admin.tm-santrek/node_modules/@vitejs/plugin-vue/dist/index.js:4025:81)
      at Context.load (/home/supp/Документы/Code/admin.tm-santrek/node_modules/@vitejs/plugin-vue/dist/index.js:4702:28)
      at Object.load (/home/supp/Документы/Code/admin.tm-santrek/node_modules/vite/dist/node/chunks/dep-611778e0.js:36509:50)
      at runNextTicks (node:internal/process/task_queues:61:5)
      at processImmediate (node:internal/timers:437:9)
      at async doTransform (/home/supp/Документы/Code/admin.tm-santrek/node_modules/vite/dist/node/chunks/dep-611778e0.js:55446:24)

[Vue Router warn]: No match found for location with path "/_nuxt/@vite/client"
[Vue Router warn]: No match found for location with path "/__error?url=/_nuxt/@vite/client&statusCode=404&statusMessage=Page+Not+Found&message=Page+not+found:+/_nuxt/@vite/client&description"
[Vue Router warn]: No match found for location with path "/_nuxt/@vite/client"
[meta] useMeta has been renamed to useHead.
[Vue Router warn]: No match found for location with path "/_nuxt/pages/auth/login.vue?vue&type=style&index=0&scoped=true&lang.css"

 ERROR  09:16:23 [vite] Internal server error: ENOENT: no such file or directory, open '/_nuxt/@fs/home/supp/Документы/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-dev.vue'
      at Object.openSync (node:fs:585:3)
      at Object.readFileSync (node:fs:453:35)
      at getDescriptor (/home/supp/Документы/Code/admin.tm-santrek/node_modules/@vitejs/plugin-vue/dist/index.js:4025:81)
      at Context.load (/home/supp/Документы/Code/admin.tm-santrek/node_modules/@vitejs/plugin-vue/dist/index.js:4702:28)
      at Object.load (/home/supp/Документы/Code/admin.tm-santrek/node_modules/vite/dist/node/chunks/dep-611778e0.js:36509:50)
      at async doTransform (/home/supp/Документы/Code/admin.tm-santrek/node_modules/vite/dist/node/chunks/dep-611778e0.js:55446:24)


 ERROR  09:16:23 [vite] Internal server error: ENOENT: no such file or directory, open '/_nuxt/app.vue'       09:16:23
      at Object.openSync (node:fs:585:3)
      at Object.readFileSync (node:fs:453:35)
      at getDescriptor (/home/supp/Документы/Code/admin.tm-santrek/node_modules/@vitejs/plugin-vue/dist/index.js:4025:81)
      at Context.load (/home/supp/Документы/Code/admin.tm-santrek/node_modules/@vitejs/plugin-vue/dist/index.js:4702:28)
      at Object.load (/home/supp/Документы/Code/admin.tm-santrek/node_modules/vite/dist/node/chunks/dep-611778e0.js:36509:50)
      at async doTransform (/home/supp/Документы/Code/admin.tm-santrek/node_modules/vite/dist/node/chunks/dep-611778e0.js:55446:24)

[Vue Router warn]: No match found for location with path "/_nuxt/pages/auth/login.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/__error?url=/_nuxt/pages/auth/login.vue?vue%26type=style%26index=0%26scoped=true%26lang.css&statusCode=404&statusMessage=Page+Not+Found&message=Page+not+found:+/_nuxt/pages/auth/login.vue?vue%26type=style%26index=0%26scoped=true%26lang.css&description"
[Vue Router warn]: No match found for location with path "/_nuxt/pages/auth/login.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/_nuxt/pages/auth/register.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/_nuxt/pages/auth/register.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/__error?url=/_nuxt/pages/auth/register.vue?vue%26type=style%26index=0%26scoped=true%26lang.css&statusCode=404&statusMessage=Page+Not+Found&message=Page+not+found:+/_nuxt/pages/auth/register.vue?vue%26type=style%26index=0%26scoped=true%26lang.css&description"
[Vue Router warn]: No match found for location with path "/_nuxt/pages/auth/register.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/supp/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-404.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/supp/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-404.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/__error?url=/_nuxt/@fs/home/supp/%25D0%2594%25D0%25BE%25D0%25BA%25D1%2583%25D0%25BC%25D0%25B5%25D0%25BD%25D1%2582%25D1%258B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-404.vue?vue%26type=style%26index=0%26scoped=true%26lang.css&statusCode=404&statusMessage=Page+Not+Found&message=Page+not+found:+/_nuxt/@fs/home/supp/%25D0%2594%25D0%25BE%25D0%25BA%25D1%2583%25D0%25BC%25D0%25B5%25D0%25BD%25D1%2582%25D1%258B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-404.vue?vue%26type=style%26index=0%26scoped=true%26lang.css&description"
[Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/supp/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-404.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/_nuxt/assets/css/tailwind.css"
[Vue Router warn]: No match found for location with path "/_nuxt/assets/css/tailwind.css"
[Vue Router warn]: No match found for location with path "/__error?url=/_nuxt/assets/css/tailwind.css&statusCode=404&statusMessage=Page+Not+Found&message=Page+not+found:+/_nuxt/assets/css/tailwind.css&description"
[Vue Router warn]: No match found for location with path "/_nuxt/assets/css/tailwind.css"
[Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/supp/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-500.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/supp/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-500.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/__error?url=/_nuxt/@fs/home/supp/%25D0%2594%25D0%25BE%25D0%25BA%25D1%2583%25D0%25BC%25D0%25B5%25D0%25BD%25D1%2582%25D1%258B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-500.vue?vue%26type=style%26index=0%26scoped=true%26lang.css&statusCode=404&statusMessage=Page+Not+Found&message=Page+not+found:+/_nuxt/@fs/home/supp/%25D0%2594%25D0%25BE%25D0%25BA%25D1%2583%25D0%25BC%25D0%25B5%25D0%25BD%25D1%2582%25D1%258B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-500.vue?vue%26type=style%26index=0%26scoped=true%26lang.css&description"
[Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/supp/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-500.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/supp/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-dev.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/supp/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-dev.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/__error?url=/_nuxt/@fs/home/supp/%25D0%2594%25D0%25BE%25D0%25BA%25D1%2583%25D0%25BC%25D0%25B5%25D0%25BD%25D1%2582%25D1%258B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-dev.vue?vue%26type=style%26index=0%26scoped=true%26lang.css&statusCode=404&statusMessage=Page+Not+Found&message=Page+not+found:+/_nuxt/@fs/home/supp/%25D0%2594%25D0%25BE%25D0%25BA%25D1%2583%25D0%25BC%25D0%25B5%25D0%25BD%25D1%2582%25D1%258B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-dev.vue?vue%26type=style%26index=0%26scoped=true%26lang.css&description"
[Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/supp/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/Code/admin.tm-santrek/node_modules/@nuxt/ui-templates/dist/templates/error-dev.vue?vue&type=style&index=0&scoped=true&lang.css"
[Vue Router warn]: No match found for location with path "/_nuxt/app.vue?vue&type=style&index=0&lang.css"
[Vue Router warn]: No match found for location with path "/_nuxt/app.vue?vue&type=style&index=0&lang.css"
[Vue Router warn]: No match found for location with path "/__error?url=/_nuxt/app.vue?vue%26type=style%26index=0%26lang.css&statusCode=404&statusMessage=Page+Not+Found&message=Page+not+found:+/_nuxt/app.vue?vue%26type=style%26index=0%26lang.css&description"
[Vue Router warn]: No match found for location with path "/_nuxt/app.vue?vue&type=style&index=0&lang.css"
[Vue Router warn]: No match found for location with path "/_nuxt/entry.mjs"
[Vue Router warn]: No match found for location with path "/_nuxt/entry.mjs"
[Vue Router warn]: No match found for location with path "/__error?url=/_nuxt/entry.mjs&statusCode=404&statusMessage=Page+Not+Found&message=Page+not+found:+/_nuxt/entry.mjs&description"
[Vue Router warn]: No match found for location with path "/_nuxt/entry.mjs"
```
</details>

<details>
   <summary><code>nuxt.config.ts</code></summary>

```ts
import { defineNuxtConfig } from 'nuxt3';

export default defineNuxtConfig({
	privateRuntimeConfig: {
		DATABASE_HOST: process.env.DATABASE_HOST,
		DATABASE_NAME: process.env.DATABASE_NAME,
		DATABASE_USER: process.env.DATABASE_USER,
		DATABASE_PASS: process.env.DATABASE_PASS,
	},
	app: {
		buildAssetsDir: 'assets/',
		head: {
			title: 'Santrek Admin',
			link: [
				{
					rel: 'icon',
					href: '/favicon.svg',
					type: 'image/svg+xml',
				},
			],
		},
	},
	nitro: {
		output: {
			dir: 'build',
		},
		externals: {
			inline: ['uuid'],
		},
	},
	router: {
		prefetchLinks: false,
	},
	components: ['components'],
	srcDir: 'src/',
	build: {
		splitChunks: {
			pages: true,
			layouts: true,
		},
	},
	buildModules: ['@nuxtjs/tailwindcss', '@vueuse/nuxt'],
	modern: true,
	tailwindcss: {
		configPath: '~~/tailwind.config.js',
		viewer: false,
	},
});
```
</details>

### Additional context

I replaced all mine `useMeta` to `useHead`

**Comment by AsgarovAsgar** [comment]
Hello, I see the same error after installing nuxt-ui module

**Comment by danielroe** [comment]
@AsgarovAsgar Would you create a new issue with a reproduction? Probably in https://github.com/nuxt/ui.
