### ISSUE TITLE
How to introduce wangEditor in nuxt3

### ISSUE THREAD

**Issue by chen-ccll** [nuxt/nuxt.js#13938]

**Comment by RomwelFeliciano** [comment]
Hello are you guys still here? how about this error, Im using nuxtjs and wangeditor and everytime I reload the page I got this error in my terminal

 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  Cannot set property crypto of #<Object> which has only a getter

  at node_modules\.pnpm\@wangeditor+editor@5.1.23\node_modules\@wangeditor\editor\dist\index.js:69:25
  at node_modules\.pnpm\@wangeditor+editor@5.1.23\node_modules\@wangeditor\editor\dist\index.js:2:66
  at Object.<anonymous> (node_modules\.pnpm\@wangeditor+editor@5.1.23\node_modules\@wangeditor\editor\dist\index.js:5:3)
  at Module._compile (node:internal/modules/cjs/loader:1480:14)
  at Object..js (node:internal/modules/cjs/loader:1564:10)
  at Module.load (node:internal/modules/cjs/loader:1287:32)
  at Function._load (node:internal/modules/cjs/loader:1103:12)
  at cjsLoader (node:internal/modules/esm/translators:318:15)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:258:7)
  at ModuleJob.run (node:internal/modules/esm/module_job:262:25)

**Comment by chapus** [comment]
Same for me, when reload page i think this code try to execute in SSR side and maybe the error. 

```

// 必须是 node 环境
if (typeof global === 'object') {
  // 用于 nodejs ，避免报错
  const globalProperty = Object.getOwnPropertyDescriptor(global, 'window')

  // global.window 为空则直接写入
  // 部分框架下已经定义了global.window且是不可写属性
  if (!global.window || globalProperty.set) {
    global.window = global
    global.requestAnimationFrame = () => {}
    global.navigator = {
      userAgent: '',
    }
    global.location = {
      hostname: '0.0.0.0',
      port: 0,
      protocol: 'http:',
    }
    global.btoa = () => {}
    global.crypto = {
      getRandomValues: function (buffer: any) {
        return nodeCrypto.randomFillSync(buffer)
      },
    }
  }
```
