### ISSUE TITLE
config = useRuntimeConfig() in composables show me -> Error: nuxt instance unavailable

### ISSUE THREAD

**Issue by hermesalvesbr** [nuxt/nuxt.js#14164]
### Environment

```
npx nuxi info
Nuxt CLI v3.0.0-rc.4                                                                                                                                                15:15:34
RootDir: /home/hermes/Projetos/nuxt/painel-sapl                                                                                                                     15:15:35
Nuxt project info:                                                                                                                                                  15:15:35

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `components`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.1.2`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                    15:15:35

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

```

### Reproduction

I need to get .env values, i'm trying to do this:

### composables/useSessao.ts
```
class SessaoPlenaria {
  config = useRuntimeConfig()
  async sessaoPlenaria(params: {id?: number, hoje?: String, atualizar?: Boolean}) {
    try {
      const headers = { Authorization: `Bearer ${this.config.saplToken}` }
      if (params.hoje) {
        const { data }: { data: any } = await useFetch(
          `${this.config.saplUrl}s?data_inicio=${params.hoje}`,
          {
            headers: headers
          }
        )
        return data.value.results
      }
    } catch (e) {
      console.log(e)
    }
  }
```

the fetch works, it grabs the data. But an error pops up in the console.

### Describe the bug

**useFetch works**, get the data. But show me this error in terminal:

```
Error: nuxt instance unavailable
    at Module.useNuxtApp (file:///home/hermes/Projetos/nuxt/painel-sapl/.nuxt/dist/server/server.mjs:407:13)
    at Module.useAsyncData (file:///home/hermes/Projetos/nuxt/painel-sapl/.nuxt/dist/server/server.mjs:786:38)
    at Module.useFetch (file:///home/hermes/Projetos/nuxt/painel-sapl/.nuxt/dist/server/server.mjs:1047:43)
    at SessaoPlenaria.sessaoPlenaria (file:///home/hermes/Projetos/nuxt/painel-sapl/.nuxt/dist/server/server.mjs:3016:52)
    at Timeout._onTimeout (file:///home/hermes/Projetos/nuxt/painel-sapl/.nuxt/dist/server/server.mjs:3142:34)

```

_How can i fix this error message?_ 

### Additional context

```
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  runtimeConfig: {
    saplToken: '',
    public: {
      saplUrl: ''
    }
  },
  components: true,
  buildModules: ['@nuxtjs/tailwindcss']
})
```

**Comment by dev2-conan** [comment]
.
