### ISSUE TITLE
nuxt generate failing on `1.0.0-rc4` ELIFECYCLE errno1

### ISSUE THREAD

**Issue by andreliem** [nuxt/nuxt.js#1416]
Hey guys,

I'm not entirely sure if this is related to being on 1.0.0-rc4 or something else, but a site that was generating fine for me is failing on`npm run generate` now. The site runs fine on dev mode so seems like I have something failing for static site generation specifically.

I left the log below (excuse the line numbers)... not sure if that helps at all, I'll play around with removing things to see if that helps or reverting to older versions.

```
 1 0 info it worked if it ends with ok
  2 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'generate' ]
  3 2 info using npm@5.3.0
  4 3 info using node@v8.2.1
  5 4 verbose run-script [ 'pregenerate', 'generate', 'postgenerate' ]
  6 5 info lifecycle vuecms@0.1.0~pregenerate: vuecms@0.1.0
  7 6 info lifecycle vuecms@0.1.0~generate: vuecms@0.1.0
  8 7 verbose lifecycle vuecms@0.1.0~generate: unsafe-perm in lifecycle true
  9 8 verbose lifecycle vuecms@0.1.0~generate: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/andreliem/Mids
 10 9 verbose lifecycle vuecms@0.1.0~generate: CWD: /Users/andreliem/...
 11 10 silly lifecycle vuecms@0.1.0~generate: Args: [ '-c', 'nuxt generate' ]
 12 11 silly lifecycle vuecms@0.1.0~generate: Returned: code: 1  signal: null
 13 12 info lifecycle vuecms@0.1.0~generate: Failed to exec generate script
 14 13 verbose stack Error: vuecms@0.1.0 generate: `nuxt generate`
 15 13 verbose stack Exit status 1
 16 13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
 17 13 verbose stack     at emitTwo (events.js:125:13)
 18 13 verbose stack     at EventEmitter.emit (events.js:213:7)
 19 13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
 20 13 verbose stack     at emitTwo (events.js:125:13)
 21 13 verbose stack     at ChildProcess.emit (events.js:213:7)
 22 13 verbose stack     at maybeClose (internal/child_process.js:921:16)
 23 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
 24 14 verbose pkgid vuecms@0.1.0
 25 15 verbose cwd /Users/andreliem/....
 26 16 verbose Darwin 16.4.0
 27 17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "generate"
 28 18 verbose node v8.2.1
 29 19 verbose npm  v5.3.0
 30 20 error code ELIFECYCLE
 31 21 error errno 1
 32 22 error vuecms@0.1.0 generate: `nuxt generate`

```

**Comment by andreliem** [comment]
Oh looks like it's related to a node package and UglifyJs failing.

```
ERROR in vendor.bundle.ce86c4183b4f2e4b8167.js from UglifyJs
Unexpected token: operator (>) 
```

**Comment by andreliem** [comment]
Looks like for now I can just follow this tip here and disable uglify

https://github.com/nuxt/nuxt.js/issues/250
