### ISSUE TITLE
problem with vuex-persistedstate

### ISSUE THREAD

**Issue by krasevych** [nuxt/nuxt.js#1427]
Hi guys! I have a problem:
I have store:
```
import Vuex from 'vuex';
import auth from 'src/store/modules/auth';
import createPersistedState from 'vuex-persistedstate';

export const plugins = [
  createPersistedState(),
];

export default new Vuex.Store({
  strict: process.env.NODE_ENV !== 'production',
  modules: {
    auth,
  },
});
```
and I got a error:
```
ReferenceError: window is not defined
    at createPersistedState (D:\Projects\Vue\Smart Landing\smart-landing-client\node_modules\vuex-persistedstate\dist\vuex-persistedstate.js:54:66)
    at Object.module.exports.Object.defineProperty.value (src/store/index.js:6:2)
    at __webpack_require__ (webpack:/webpack/bootstrap 9f07d01ff16351a90719:25:0)
    at webpackContext (webpack:/src/store ^\.\/.*\.js$:6:0)
    at getModule (.nuxt/store.js:9:13)
    at Object.module.exports.Object.defineProperty.value (.nuxt/store.js:31:19)
    at __webpack_require__ (webpack:/webpack/bootstrap 9f07d01ff16351a90719:25:0)
    at Object.<anonymous> (.nuxt/index.js:6:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 9f07d01ff16351a90719:25:0)
    at Object.module.exports.Object.defineProperty.value (.nuxt/server.js:10:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 9f07d01ff16351a90719:25:0)
    at module.exports.$Object (webpack:/webpack/bootstrap 9f07d01ff16351a90719:93:0)
    at Object.<anonymous> (server-bundle.js:98:10)
    at evaluateModule (D:\Projects\Vue\Smart Landing\smart-landing-client\node_modules\vue-server-renderer\build.js:6967:21)
    at D:\Projects\Vue\Smart Landing\smart-landing-client\node_modules\vue-server-renderer\build.js:6985:15
    at D:\Projects\Vue\Smart Landing\smart-landing-client\node_modules\vue-server-renderer\build.js:6983:12
```
what do I do  wrong?

**Comment by cretueusebiu** [comment]
`vuex-persistedstate` uses `window.localStorage` to save the state and it's not available on the server.

You'll have to add `mode: 'spa'` to your `nuxt.config.js` so it only runs on the client side.

**Comment by krasevych** [comment]
@cretueusebiu thank you! but I have Nuxt v 1.0.5, how can I update my project with nuxt@1.0.05 to rc5?

**Comment by cretueusebiu** [comment]
Just run `yarn add nuxt` or `npm install nuxt`. Then see what changes you have to make to your project: https://github.com/nuxt/nuxt.js/releases

**Comment by krasevych** [comment]
and what about files in dir `.nuxt`  will they changes automatic?

**Comment by cretueusebiu** [comment]
Yes, when you build it the env variables from your code will be replaced with the actual values.

**Comment by Atinux** [comment]
@cretueusebiu answers are the same as mine :)

**Comment by krasevych** [comment]
@cretueusebiu @Atinux 
I updated Nuxt and set mode: SPA and vuex-persistedstate works good, but I got new problem, ssr stopped works, when I refresh page I see empty page and localhost:3000 - return html without current 
 rendered page, how can I fix it?
