### ISSUE TITLE
Nitro `normalizeError()` removing the `file://` prefix from an error stack of the server-side error, it's prevents navigation from output in the terminal to the file in JetBrains IDE

### ISSUE THREAD

**Issue by mrauhu** [nuxt/nuxt.js#14284]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-k2vwrb?file=app.vue

### Describe the bug

Hello.

The [`normalizeError()`](https://github.com/unjs/nitro/blob/3e99f81ea3b29b3c8ead61647c4e0f78ae32baa4/src/runtime/utils.ts#L43-L43) function from the `nitro` package is used for preparing a error stack in the default Nitro `errorhandler()` function:

https://github.com/nuxt/framework/blob/728a0a5ef48ea8257a53d37d9a1cfb4f3641bebe/packages/nuxt/src/core/runtime/nitro/error.ts#L8-L8

Then, the same error stack is used for `console.error()` output:

https://github.com/nuxt/framework/blob/728a0a5ef48ea8257a53d37d9a1cfb4f3641bebe/packages/nuxt/src/core/runtime/nitro/error.ts#L26-L29

Nitro `normalizeError()` removing the `file://` prefix from an error stack, it's prevents navigation from output in the terminal to the file in JetBrains IDE (Webstorm, as example).

So a user can't click to a line in the stack trace, and go to a file.

Best wishes,
Sergey.

### Additional context

Example of the output parsing, in the Terminal of JetBrains IDE (with enabled sourcemaps):

* `console.log()` — clickable output;
* `throw` — non-clickable output.

![image](https://user-images.githubusercontent.com/2821574/177904359-8f1d6eb9-afa4-4264-b3aa-bc48a24264be.png)

### Logs

```shell
Error: Fri, 08 Jul 2022 02:06:57 GMT
    at eval (file:///home/projects/github-k2vwrb/.nuxt/dev/index.mjs:413:17)
    at eval (file:///home/projects/github-k2vwrb/node_modules/h3/dist/index.mjs:367:14)
    at Object.eval [as handler] (file:///home/projects/github-k2vwrb/node_modules/h3/dist/index.mjs:567:12)
    at eval (file:///home/projects/github-k2vwrb/node_modules/h3/dist/index.mjs:478:31)
    at async Server.nodeHandler (file:///home/projects/github-k2vwrb/node_modules/h3/dist/index.mjs:428:7)

[nuxt] [request error] Fri, 08 Jul 2022 02:06:57 GMT
  at eval (./.nuxt/dev/index.mjs:413:17)  
  at eval (./node_modules/h3/dist/index.mjs:367:14)  
  at Object.eval [as handler] (./node_modules/h3/dist/index.mjs:567:12)  
  at eval (./node_modules/h3/dist/index.mjs:478:31)  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:428:7)
```

**Comment by Flo0806** [comment]
@danielroe  - Can be closed. Works with current nitro as well. Created a boom.ts

```typescript
import { defineEventHandler } from 'nitro/h3'

export default defineEventHandler(() => {
  throw new Error('boom — #14284 server error stack test')
})
```

<img width="796" height="225" alt="Image" src="https://github.com/user-attachments/assets/70949206-77a9-43c0-a0e8-325ea7ef7bdd" />

LInk to file is clickable ans works as expected!

**Comment by danielroe** [comment]
nuxtathon closed @Flo0806
