### ISSUE TITLE
cann't deploy on my ubuntu server

### ISSUE THREAD

**Issue by ontheway1215** [nuxt/nuxt.js#1451]
# I want to deploy on server,and use command: npm run build,but it give those error

```
root@VM-49-9-ubuntu:/var/www/html/public/dong2# npm run build
> dong2@1.0.0 build /var/www/html/public/dong2
> nuxt build

  nuxt:build Building... +0ms
  nuxt:build App root: /var/www/html/public/dong2 +0ms
  nuxt:build Generating /var/www/html/public/dong2/.nuxt files... +1ms
  nuxt:build Generating files... +24ms
  nuxt:build Generating routes... +10ms
  nuxt:build Building files... +47ms
  build [============== ] 91%Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! dong2@1.0.0 build: `nuxt build`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the dong2@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-23T07_03_04_626Z-debug.log
root@VM-49-9-ubuntu:/var/www/html/public/dong2# 
```
# and the debug log show this:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle dong2@1.0.0~prebuild: dong2@1.0.0
6 info lifecycle dong2@1.0.0~build: dong2@1.0.0
7 verbose lifecycle dong2@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle dong2@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/var/www/html/public/dong2/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle dong2@1.0.0~build: CWD: /var/www/html/public/dong2
10 silly lifecycle dong2@1.0.0~build: Args: [ '-c', 'nuxt build' ]
11 silly lifecycle dong2@1.0.0~build: Returned: code: 137  signal: null
12 info lifecycle dong2@1.0.0~build: Failed to exec build script
13 verbose stack Error: dong2@1.0.0 build: `nuxt build`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid dong2@1.0.0
15 verbose cwd /var/www/html/public/dong2
16 verbose Linux 4.4.0-53-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 137
22 error dong2@1.0.0 build: `nuxt build`
22 error Exit status 137
23 error Failed at the dong2@1.0.0 build script.
```

**Comment by Atinux** [comment]
This code `137` seems to indicate that your server killed the running process https://stackoverflow.com/questions/1041182/why-does-my-perl-script-exit-with-137

Try to add more RAM into your server or using a server with better performance.

**Comment by ontheway1215** [comment]
@Atinux thanks,i will make a try
