### ISSUE TITLE
Rollup error: Could not resolve './_nuxt/style.de09fa41.js'

### ISSUE THREAD

**Issue by CodeDredd** [nuxt/nuxt.js#14657]

**Comment by InerkyJad** [comment]
This isn't just an Algolia  module issue, it happens even if we're importing a `CSS` file inside of the `script` part in a template, so I  guess this is worth some investigating.

for example I'm including a style inside of the `@/app.vue` file following the guide in [Nuxt 3 Docs](https://nuxt.com/docs/getting-started/styling#the-css-property) and vue docs as well:
```javascript
<script>
// Note: the same issue is present even if the import statement was to be used inside of any other page.
import("@/style.css");
</script>

<template>
  <NuxtPage />
</template>
```


when I run `npm run dev` everything works as expected, but when I run `npm run build` it doesn't build, the error log is the following:
```bash
PS D:\CODE\X-DASHBOARD> npm run build

> build
> nuxt build

Nuxi 3.5.3                                                                                                                                                                                                                                              8:01:31 PM
Nuxt 3.5.3 with Nitro 2.5.1                                                                                                                                                                                                                             8:01:31 PM
ℹ Using default Tailwind CSS file                                                                                                                                                                                                      nuxt:tailwindcss 8:01:33 PM
ℹ Building client...                                                                                                                                                                                                                                    8:01:35 PM
ℹ vite v4.3.9 building for production...                                                                                                                                                                                                                8:01:35 PM
ℹ ✓ 130 modules transformed.                                                                                                                                                                                                                            8:01:37 PM  
ℹ .nuxt/dist/client/manifest.json                        2.91 kB │ gzip:  0.53 kB                                                                                                                                                                       8:01:37 PM  
ℹ .nuxt/dist/client/_nuxt/style.a4ce5984.css             0.33 kB │ gzip:  0.25 kB                                                                                                                                                                       8:01:37 PM
ℹ .nuxt/dist/client/_nuxt/error-500.b63a96f5.css         2.02 kB │ gzip:  0.75 kB                                                                                                                                                                       8:01:37 PM  
ℹ .nuxt/dist/client/_nuxt/error-404.8bdbaeb8.css         3.70 kB │ gzip:  1.13 kB                                                                                                                                                                       8:01:37 PM  
ℹ .nuxt/dist/client/_nuxt/entry.f2350f0e.css            12.51 kB │ gzip:  3.32 kB                                                                                                                                                                       8:01:37 PM  
ℹ .nuxt/dist/client/_nuxt/auth.db233364.js               0.27 kB │ gzip:  0.23 kB                                                                                                                                                                       8:01:37 PM  
ℹ .nuxt/dist/client/_nuxt/login.8d5ba838.js              1.05 kB │ gzip:  0.63 kB                                                                                                                                                                       8:01:37 PM  
ℹ .nuxt/dist/client/_nuxt/error-component.d703e9c4.js    1.12 kB │ gzip:  0.61 kB                                                                                                                                                                       8:01:37 PM  
ℹ .nuxt/dist/client/_nuxt/error-500.e025afee.js          1.88 kB │ gzip:  0.99 kB                                                                                                                                                                       8:01:37 PM  
ℹ .nuxt/dist/client/_nuxt/index.7ff73429.js              2.28 kB │ gzip:  0.91 kB                                                                                                                                                                       8:01:37 PM  
ℹ .nuxt/dist/client/_nuxt/error-404.43f5cad4.js          6.50 kB │ gzip:  2.88 kB                                                                                                                                                                       8:01:37 PM  
ℹ .nuxt/dist/client/_nuxt/fetch.a9da3656.js             11.44 kB │ gzip:  4.65 kB                                                                                                                                                                       8:01:37 PM  
ℹ .nuxt/dist/client/_nuxt/entry.274a5e48.js            155.38 kB │ gzip: 58.25 kB                                                                                                                                                                       8:01:37 PM  
ℹ ✓ built in 2.17s                                                                                                                                                                                                                                      8:01:37 PM  
✔ Client built in 2201ms                                                                                                                                                                                                                                8:01:37 PM  
ℹ Building server...                                                                                                                                                                                                                                    8:01:37 PM  
ℹ vite v4.3.9 building SSR bundle for production...                                                                                                                                                                                                     8:01:37 PM  
ℹ ✓ 81 modules transformed.                                                                                                                                                                                                                             8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/error-404-styles.88dd483b.mjs        0.08 kB                                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/error-500-styles.f7652148.mjs        0.08 kB                                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/styles.mjs                                 0.35 kB                                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/index-e12b288f.js                    0.22 kB │ map:  5.28 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/css-styles-2.mjs-4619f099.js         0.44 kB │ map:  0.11 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/island-renderer-cbbea6bd.js          1.17 kB │ map:  1.39 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/login-34f29fec.js                    1.37 kB │ map:  1.51 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/error-component-75195197.js          2.04 kB │ map:  2.71 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-cf69c072.js   2.23 kB │ map:  0.12 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/error-dev-styles-1.mjs-a4b72ba9.js   2.59 kB │ map:  0.12 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/error-500-95744b2c.js                3.16 kB │ map:  3.79 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/index-d716c650.js                    3.37 kB │ map:  3.45 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-00a5a0fd.js   3.93 kB │ map:  0.12 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/auth-7afa8e14.js                     6.51 kB │ map: 14.86 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/error-404-5e22edf7.js                9.79 kB │ map: 18.88 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/_nuxt/css-styles-1.mjs-6e20aa38.js        12.35 kB │ map:  0.11 kB                                                                                                                                                                  8:01:38 PM  
ℹ .nuxt/dist/server/server.mjs                                32.06 kB │ map: 75.97 kB                                                                                                                                                                  8:01:38 PM  
ℹ ✓ built in 1.05s                                                                                                                                                                                                                                      8:01:38 PM  
✔ Server built in 1061ms                                                                                                                                                                                                                                8:01:38 PM  
✔ Generated public .output/public                                                                                                                                                                                                                 nitro 8:01:38 PM
ℹ Building Nitro Server (preset: node-server)                                                                                                                                                                                                     nitro 8:01:38 PM  

 ERROR  RollupError: Could not resolve "./_nuxt/style-15c73386.js" from ".nuxt/dist/server/server.mjs"                                                                                                                                            nitro 8:01:44 PM  


undefined


 ERROR  Could not resolve "./_nuxt/style-15c73386.js" from ".nuxt/dist/server/server.mjs"                                                                                                                                                               8:01:44 PM  

  at error (/D:/CODE/X-DASHBOARD/node_modules/rollup/dist/es/shared/node-entry.js:2213:30)
  at ModuleLoader.handleInvalidResolvedId (/D:/CODE/X-DASHBOARD/node_modules/rollup/dist/es/shared/node-entry.js:24219:24)
  at ModuleLoader.resolveDynamicImport (/D:/CODE/X-DASHBOARD/node_modules/rollup/dist/es/shared/node-entry.js:24277:58)
  at async /D:/CODE/X-DASHBOARD/node_modules/rollup/dist/es/shared/node-entry.js:24166:32
```

Op system: Win11 (but this has nothing to do with the issue since i have tested the same code on a Linux machine and everything is the same)
Node version: 18.16.0

My package.json:
```json
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@types/node": "^18",
    "@types/toastify-js": "^1.11.1",
    "nuxt": "^3.5.2"
  },
  "dependencies": {
    "@nuxtjs/harlem": "^1.3.0",
    "toastify-js": "^1.12.0"
  }
}
```

Note: this isn't really an issue and it can totally be ignored since we can add styles in other methods such as in the `nuxt.congif.ts` file just as the [Nuxt 3 Docs](https://nuxt.com/docs/getting-started/styling#the-css-property) point out 
```typescript
export default defineNuxtConfig({
    css: ['@/style.css']
})
```

**Comment by danielroe** [comment]
Would you open a new issue with a reproduction, please? 🙏

**Comment by InerkyJad** [comment]
added #21803
