### ISSUE TITLE
deploy on server error

### ISSUE THREAD

**Issue by ontheway1215** [nuxt/nuxt.js#1477]
## when i deploy my project on server using nuxt build it give some error, but is running successfully on my local server
```
ERROR in ./node_modules/babel-loader/lib?{"presets":["/opt/node/lib/node_modules/nuxt/node_modules/babel-preset-vue-app/dist/index.common.js"],"babelrc":false,"cacheDirectory":false}!/opt/node/lib/node_modules/nuxt/node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/category.vue
Module not found: Error: Can't resolve '~assets/js/api/category' in '/var/www/html/dong2/pages'
 @ ./node_modules/babel-loader/lib?{"presets":["/opt/node/lib/node_modules/nuxt/node_modules/babel-preset-vue-app/dist/index.common.js"],"babelrc":false,"cacheDirectory":false}!/opt/node/lib/node_modules/nuxt/node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/category.vue 27:0-91
 @ ./pages/category.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
```
## there is lots of those error ,and finaly it gives:
```
Error: Webpack build exited with errors
    at /opt/node/lib/node_modules/nuxt/lib/builder/builder.js:489:27
    at emitRecords.err (/opt/node/lib/node_modules/nuxt/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/opt/node/lib/node_modules/nuxt/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/opt/node/lib/node_modules/nuxt/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/opt/node/lib/node_modules/nuxt/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/opt/node/lib/node_modules/nuxt/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/opt/node/lib/node_modules/nuxt/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/opt/node/lib/node_modules/nuxt/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/opt/node/lib/node_modules/nuxt/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/opt/node/lib/node_modules/nuxt/node_modules/webpack/lib/Compiler.js:354:15)
    at /opt/node/lib/node_modules/nuxt/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/opt/node/lib/node_modules/nuxt/node_modules/async/dist/async.js:998:13)
    at /opt/node/lib/node_modules/nuxt/node_modules/async/dist/async.js:906:16
    at /var/www/html/dong2/node_modules/graceful-fs/graceful-fs.js:43:10
    at /opt/node/lib/node_modules/nuxt/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
```
how can i resolve this problem

**Comment by Atinux** [comment]
It seems that you are using an old version of Nuxt on local, run `npm update` or `yarn upgrade` on your project and run again nuxt
