### ISSUE TITLE
Netlify preset 'netlify-edge' Error

### ISSUE THREAD

**Issue by markus-gx** [nuxt/nuxt.js#14938]
### Environment

Netlify 

### Reproduction

Just create a Nuxt 3 Project and deploy it on netlify with the following preset: 

```
nitro: {
  preset: 'netlify-edge'
}
```

### Describe the bug

Netlify support suggested to raise a bug ticket here: 

> 
>  believe this is a problem with Nuxt and the way they're generating an Edge Function. It could be worth trying to post an issue here: https://github.com/nuxt/framework/issues.
>  
> The reason why I believe it is because, Nuxt is responsible for generating an Edge Function and there seems to be something wrong with that is being generated. But again, if they have any other ideas, you can let us know.

### Logs

```shell
────────────────────────────────────────────────────────────────
3:03:21 PM:   2. Edge Functions bundling                                    
3:03:21 PM: ────────────────────────────────────────────────────────────────
3:03:21 PM: ​
3:03:21 PM: Packaging Edge Functions from .netlify/edge-functions directory:
3:03:21 PM:  - server
3:03:24 PM: ​
3:03:24 PM: ────────────────────────────────────────────────────────────────
3:03:24 PM:   Internal error during "Edge Functions bundling"               
3:03:24 PM: ────────────────────────────────────────────────────────────────
3:03:24 PM: ​
3:03:24 PM:   Error message
3:03:24 PM:   Error: [
3:03:24 PM:     {
3:03:24 PM:       "instancePath": "/routes/0/pattern",
3:03:24 PM:       "schemaPath": "#/properties/routes/items/properties/pattern/errorMessage",
3:03:24 PM:       "keyword": "errorMessage",
3:03:24 PM:       "params": {
3:03:24 PM:         "errors": [
3:03:24 PM:           {
3:03:24 PM:             "instancePath": "/routes/0/pattern",
3:03:24 PM:             "schemaPath": "#/properties/routes/items/properties/pattern/format",
3:03:24 PM:             "keyword": "format",
3:03:24 PM:             "params": {
3:03:24 PM:               "format": "regexPattern"
3:03:24 PM:             },
3:03:24 PM:             "message": "must match format \"regexPattern\"",
3:03:24 PM:             "emUsed": true
3:03:24 PM:           }
3:03:24 PM:         ]
3:03:24 PM:       },
3:03:24 PM:       "message": "must match format /^\\^.*\\$$/"
3:03:24 PM:     }
3:03:24 PM:   ]
```

**Comment by koronowicz** [comment]
I also have a problem with running Nuxt 3.2.3, SSR on Netlify with netlify-edge preset. When opening URL I got Netlify 404 error. In logs no errors and in Edge Functions part nothing:
```
11:47:41 AM:   2. Edge Functions bundling                                    
11:47:41 AM: ────────────────────────────────────────────────────────────────
11:47:41 AM: ​
11:47:41 AM: ​
11:47:41 AM: (Edge Functions bundling completed in 494ms)
```

I don't have any ideas how to fix that, anyone? I'm planning to run an empty Nuxt project maybe it's something else.

**Comment by koronowicz** [comment]
@XanderStoffels in my situation the build paths are the same in ```netlify``` and ```netlify-edge``` preset. I deployed a fresh installation of Nuxt only with ```preset: 'netlify-edge'``` and I get the same, no errors in build, no edge functions build and 404 error when visiting the website. I will try to ask guys in Nitro repository.

**Comment by dosstx** [comment]
Did you guys ever get your app deployed using the `netlify-edge` preset? I am trying for the first time (got the latest nuxt version) and I get this error during build stage:

```
11:11:15 AM: [success] Server built in 3136ms
11:11:15 AM: [success] [nitro] Generated public dist
11:11:15 AM: [info] [nitro] Initializing prerenderer
11:11:18 AM: [info] [nitro] Prerendering 1 routes
11:11:18 AM: [log] [nitro]   ├─ /api/_content/cache.1684944666954.json (254ms)
11:11:18 AM: [nitro] Nitro now uses `isr` option to configure ISR behavior on Netlify. Backwards-compatible support for `static` and `swr` support with Builder Functions will be removed in the future versions.
11:11:18 AM: [info] [nitro] Building Nitro Server (preset: `netlify-edge`)
11:11:55 AM: [success] [nitro] Nitro server built
11:11:55 AM:   └─ .netlify/edge-functions/server/server.js (2.04 MB) (587 kB gzip)
11:11:55 AM: Σ Total size: 2.04 MB (587 kB gzip)
11:11:55 AM: ​
11:11:55 AM: (build.command completed in 49.7s)
11:11:55 AM: ​
11:11:55 AM: Edge Functions bundling                                       
11:11:55 AM: ────────────────────────────────────────────────────────────────
11:11:55 AM: ​
11:11:55 AM: Packaging Edge Functions from .netlify/edge-functions directory:
11:11:55 AM:  - server
11:11:56 AM: ReferenceError: __dirname is not defined
11:11:56 AM:     at file:///opt/build/repo/.netlify/edge-functions/server/server.js:1:1128946
11:11:56 AM: ​
11:11:56 AM: Bundling of edge function failed                              
11:11:56 AM: ────────────────────────────────────────────────────────────────
11:11:56 AM: ​
11:11:56 AM:   Error message
11:11:56 AM:   Could not load edge function at '/opt/build/repo/.netlify/edge-functions/server/server.js'. More on the Edge Functions API at https://ntl.fyi/edge-api.
11:11:56 AM: ​
11:11:56 AM:   Error location
11:11:56 AM:   While bundling edge function
11:11:56 AM: ​
11:11:56 AM:   Resolved config
11:11:56 AM:   build:
11:11:56 AM:     command: npm run build
11:11:56 AM:     commandOrigin: ui
11:11:56 AM:     environment:
11:11:56 AM:       - NUXT_OPENAI_API_KEY
11:11:56 AM:     publish: /opt/build/repo/dist
11:11:56 AM:     publishOrigin: ui
11:11:57 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
11:11:57 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:11:57 AM: Failing build: Failed to build site
11:11:58 AM: Finished processing build request in 1m10.594s
```

**Comment by besteskinderbuch** [comment]
I have the same issue like @dosstx 😞
Can somebody help us please 🙏?

**Comment by besteskinderbuch** [comment]
I found the issue and the fix: https://github.com/nuxt/image/issues/602

**Comment by PatoGordo** [comment]
Same issue in 2024

Nuxt version: `3.10.3`

This code does not use Nuxt Image
```
4:49:58 PM: Edge Functions bundling                                       
4:49:58 PM: ────────────────────────────────────────────────────────────────
4:49:58 PM: ​
4:49:58 PM: Packaging Edge Functions from .netlify/edge-functions directory:
4:49:58 PM:  - server
4:50:04 PM: TypeError: Cannot read properties of undefined (reading "exec")
4:50:04 PM:     at file:///opt/build/repo/.netlify/edge-functions/server/server.js:1:353021
4:50:04 PM: ​
4:50:04 PM: Bundling of edge function failed                              
4:50:04 PM: ────────────────────────────────────────────────────────────────
4:50:04 PM: ​
4:50:04 PM:   Error message
4:50:04 PM:   Could not load edge function at "/opt/build/repo/.netlify/edge-functions/server/server.js". More on the Edge Functions API at https://ntl.fyi/edge-api.
4:50:04 PM: ​
4:50:04 PM:   Error location
4:50:04 PM:   While bundling edge function
4:50:04 PM: ​
4:50:04 PM:   Resolved config
4:50:04 PM:   build:
4:50:04 PM:     base: /opt/build/repo
4:50:04 PM:     command: yarn build
4:50:04 PM:     commandOrigin: ui
4:50:04 PM:     environment:
4:50:04 PM:       - <My envs>
4:50:04 PM:     publish: /opt/build/repo/dist
4:50:04 PM:     publishOrigin: ui
4:50:04 PM:   functions:
4:50:04 PM:     "*":
4:50:04 PM:       node_bundler: esbuild
4:50:04 PM:   functionsDirectory: /opt/build/repo/.netlify/edge-functions
4:50:05 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
4:50:05 PM: Failing build: Failed to build site
4:50:05 PM: Finished processing build request in 1m21.187s
4:50:05 PM: Failed during stage "building site": Build script returned non-zero exit code: 2
```
