### ISSUE TITLE
 Unexpected character '�'  when generating build

### ISSUE THREAD

**Issue by arek125** [nuxt/nuxt.js#15057]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`

### Reproduction

I Tried to reproduce but looks like problem appears only in local windows 10

https://github.com/arek125/nuxt3-ant-sql

### Describe the bug

Dev runs fine, but when tries to generate build: 

``` ERROR                                                                                                                                                                                          nitro 09:14:51  

1: MZ�♥♦���☺♫▼�♫�       �!�☺L�!This program cannot be run in DOS mode.
     ^
3�H��(H�%ÿ☺3�H��(�������������H�♣!H☻H�☺H�H�H�������������H�H�♣ED☻H��H☼E�����������������������������@SH�� H�♣�G☻H��H�☺��☺txt�☺►�☺♦ `.rdata^��☺��☺@@.datax▼�☻♫�☻@�.pdata�↓�☻→�☻@@.rsrc�☺�☻☻�☻@@.reloc�♠��☻@BH�   
3: �►�ҔH��H�� [������H�☺�������������@SH�� H�Q@H��H��►r-H�I(H��H��►r↑L�A�H��'I+�H�A�H��▼wMI���t�H�C8H�♣IG☻H�C@☼�C(H�♥H�S↑H��t↑�{ u


 ERROR  Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)                                                                                                 09:14:51  

  at error (/C:/Users/agolen/Desktop/nuxt3/nuxt3-ant-sql/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (/C:/Users/agolen/Desktop/nuxt3/nuxt3-ant-sql/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
  at Module.tryParse (/C:/Users/agolen/Desktop/nuxt3/nuxt3-ant-sql/node_modules/rollup/dist/es/shared/rollup.js:12806:25)
  at Module.setSource (/C:/Users/agolen/Desktop/nuxt3/nuxt3-ant-sql/node_modules/rollup/dist/es/shared/rollup.js:12711:24)
  at ModuleLoader.addModuleSource (/C:/Users/agolen/Desktop/nuxt3/nuxt3-ant-sql/node_modules/rollup/dist/es/shared/rollup.js:21959:20)
```

**Comment by productdevbook** [comment]
![CleanShot 2024-01-13 at 20 23 33](https://github.com/nuxt/nuxt/assets/38668796/5379877a-9522-43eb-b495-c3059502a29d)

nuxt 3.9.1 this problem

**Comment by productdevbook** [comment]
[pr](https://github.com/oku-ui/pergel/pull/113)

1. cd packages/nuxt
2. pnpm build

**Comment by productdevbook** [comment]
https://github.com/paulmillr/chokidar/issues/1202#issuecomment-1839120365


```ts
 rollupOptions: {
      external: ["fsevents"]
    }
``` 

and 

```ts
  "pnpm": {
    "overrides": {
      "rollup": "^4.2.0"
    }
  },
```

**Comment by meirroth** [comment]
In case anyone else runs into this, I'm getting a similar error when running build on windows, not getting any error on Mac or Linux:
<details>
  <summary>Expand to see full error.</summary>
<pre>
[plugin inject] node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-arm64-glibc-115.node: rollup-plugin-inject: failed to parse C:/.../nuxt/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-arm64-glibc-115.node. Consider restricting the plugin to particular files via options.include

[nitro 20:37:30]  ERROR  RollupError: node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-darwin-x64-93.node (1:0): Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)


�♠��☺↓(☻__TEXT��♣♣♠__text...
   ^
2: ☺♀*►♀0↑☻♥�♦☺/usr/lib/libc++.1.dylib♀8↑☻▼♣☺/usr/lib/libSystem.B.dyl...
3: I�v►I��♠H��L��I���H�E�H�}��MM���M��H�E�toH��L��H��H�UUUUUUUUH!�L��H)�H�33333333H��H!�H��☻H!�H☺�H��H��♦H☺�H�...


[20:37:30]  ERROR  node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-darwin-x64-93.node (1:0): Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)

  at getRollupError (/C:/.../nuxt/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
  at ParseError.initialise (/C:/.../nuxt/node_modules/rollup/dist/es/shared/node-entry.js:11332:28)
  at convertNode (/C:/.../nuxt/node_modules/rollup/dist/es/shared/node-entry.js:13082:10)
  at convertProgram (/C:/.../nuxt/node_modules/rollup/dist/es/shared/node-entry.js:12399:12)
  at Module.setSource (/C:/.../nuxt/node_modules/rollup/dist/es/shared/node-entry.js:14243:24)
  at async ModuleLoader.addModuleSource (/C:/.../nuxt/node_modules/rollup/dist/es/shared/node-entry.js:18896:13)



[20:37:30]  ERROR  node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-darwin-x64-93.node (1:0): Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
</pre>
</details>

We're using the Sentry recipe from https://github.com/manniL/nuxt3-sentry-recipe

**Comment by cernymatej** [comment]
I'm going to close this as the issue is quite old and is most likely resolved. The reproduction is also no longer accessible. Please raise a new issue if you encounter any problems.
