### ISSUE TITLE
Help!! Nuxt js (npm run generate) cannot read property session 

### ISSUE THREAD

**Issue by JeffryWu** [nuxt/nuxt.js#1506]
![21083675_2040868842597352_6355083002986054469_o](https://user-images.githubusercontent.com/31407373/29772431-f616e372-8c22-11e7-97d0-90381df91968.jpg)

Hi
I am getting the following error when i  trying to generate my project. any idea 

```
Route: '/'
TypeError: Cannot read property 'session' of undefined
    at nuxtServerInit (server-bundle.js:1974:12)
    at Array.wrappedActionHandler (C:\xampp\htdocs\chr\local\chr\node_modules\vuex\dist\vuex.js:604:15)
    at Store.dispatch (C:\xampp\htdocs\chr\local\chr\node_modules\vuex\dist\vuex.js:347:15)
    at Store.boundDispatch [as dispatch] (C:\xampp\htdocs\chr\local\chr\node_modules\vuex\dist\vuex.js:272:21)
    at Object._callee$ (server-bundle.js:1587:79)
    at tryCatch (C:\xampp\htdocs\chr\local\chr\node_modules\regenerator-runtime\runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\xampp\htdocs\chr\local\chr\node_modules\regenerator-runtime\runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\xampp\htdocs\chr\local\chr\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (server-bundle.js:228:30)
    at server-bundle.js:239:13
```

pls,help 
thank you so much

**Comment by paulgv** [comment]
Can you share some code? Especially your `nuxtServerInit` method.

**Comment by JeffryWu** [comment]
@paulgv thank you sir, here is my some code about nuxtServerInit. 

> export

 const state = () => ({
  authUser: null
})

export const mutations = {
  SET_USER: function (state, user) {
    state.authUser = user
  }
}

export const actions = {
  nuxtServerInit ({ commit }, { req }) {
    if (req.session && req.session.authUser) {
      commit('SET_USER', req.session.authUser)
    }
  }
}

**Comment by Atinux** [comment]
@JeffryWu See https://nuxtjs.org/api/context

`req` & `res` are **not available via nuxt generate**.

It's normal since the generated page will be hosted on a static hosting, so no `req.session` available.
