### ISSUE TITLE
'Named export not found' in SSR rendered component.

### ISSUE THREAD

**Issue by felixdenoix** [nuxt/nuxt.js#15320]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------		

### Reproduction

https://github.com/felixdenoix/contentful-nuxt-repro

### Describe the bug

I'm trying to render content from the contentful richtext field. I created a component to handle this and it uses `enums` imported from the '@contentful/rich-text-types' module.
The component is supposed to be able render the content server side but it seems that the module cannot be load after building it. 
```
import { MARKS, BLOCKS, INLINES, helpers, Node, Block, Inline, Document } from '@contentful/rich-text-types'
```

If I import the enums as the example above and bild the project then start it, the following error appears in the console and the error page is rendered (and the same happens if I do as suggested).
```
[nuxt] [request error] [unhandled] [500] Named export 'MARKS' not found. The requested module '@contentful/rich-text-types' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@contentful/rich-text-types';
const { MARKS, BLOCKS, INLINES, helpers } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
  at async ./server/chunks/handlers/renderer.mjs:305:24
  at async ./server/chunks/handlers/renderer.mjs:369:64
  at async ./server/chunks/handlers/renderer.mjs:29:22
  at async Object.handler (./server/node_modules/h3/dist/index.mjs:634:19)
  at async Server.toNodeHandle (./server/node_modules/h3/dist/index.mjs:698:7)
```

when using the [build transpile option](https://v3.nuxtjs.org/api/configuration/nuxt-config#transpile) from the `nuxt.config.ts` file, the website will break in dev mode and the rich-text renderer from the `RichText` component will throw an error in the browser console stating that the values (only the objects such as BLOCK but not the typescript types) are undefined as in the example bellow but will work when built and started.

```
❌ RichText.ts:2 Uncaught SyntaxError: The requested module '/_nuxt/node_modules/@contentful/rich-text-types/dist/index.js?v=2aad74db' does not provide an export named 'BLOCKS' (at RichText.ts:2:1)
```

### Additional context

I saw the page about the [valid imports in a nodejs context](https://v3.nuxtjs.org/guide/concepts/esm/#what-are-valid-imports-in-a-nodejs-context) in the documentation but I could not figure if the module is correctly setup or if I'm commiting a mistake using the SSR or if I should open an issue on the [@contentful/rich-text](https://github.com/contentful/rich-text) project.

**Comment by apttx** [comment]
having the same issue with `@elastic/search-ui` & `@searchkit/sdk`. 

```ts
import { SearchDriver } from '@elastic/search-ui'
```

works fine in dev, but crashes the build

```
[nuxt] [request error] [unhandled] [500] Named export 'SearchDriver' not found. The requested module '@elastic/search-ui' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@elastic/search-ui';
const { SearchDriver } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

[transpiling](https://nuxt.com/docs/guide/concepts/esm#transpiling-libraries) the offending packages works in my case.

the issue only appears when using named imports;
```ts
import ElasticsearchAPIConnector from '@elastic/search-ui-elasticsearch-connector'
```

works without transpiling the package.

all of those 3 packages have both a `"main"` and a `"module"`.

**Comment by danielroe** [comment]
Would you try something like this?

```ts
export default defineNuxtConfig({
  nitro: {
    externals: {
      inline: ['@elastic/search-ui']
    }
  }
})
```
