### ISSUE TITLE
Cannot retreive data from createError when uploading files

### ISSUE THREAD

**Issue by niddu85** [nuxt/nuxt.js#15390]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `publicRuntimeConfig`, `privateRuntimeConfig`, `modules`, `css`, `typescript`, `alias`, `build`
- Runtime Modules:  `@nuxtjs/svg@0.1.12`, `nuxt-lodash@2.3.0`
- Build Modules:    `-`
------------------------------

### Reproduction

create a server api
`\server\routes\webapi\[...].post.ts`

content:
```
export default defineEventHandler(async (event) => {
try {
   const body = await useRawBody(event, false);

    const res = await $fetch(url + queryStr, {
      baseURL,
      method: "POST",
      body,
    });

    return res;
  } catch (error: any) {
    const err = createError({
      statusCode: error?.response?.status || 500,
      data: error?.data,  --> error.data is: {message: 'please insert a valid amount for the current offer'}
      message: "Error fetching from WebAPI, URL " + url,
    });
    throw err;
}
});
```

call the api using 

```
const formData= new FormData();
formData.append('filename', fileContent);

 try {
      const { data, error } = await useFetch<T>(url, {
        baseURL: "/webapi",
        method: "POST",
        body: formData
      });

     if (error && error.value != null) {
        throw error.value;  --> here error.value.data is not the object i expect but is an html like:  '<!DOCTYPE html><html><head><title>400 -  | Nuxt</title><meta charset="utf-8"><meta content="width=device-width,initial-scale=1,minimum-scale=1" name="viewport"><style>.spotlight{background:linear-gradient(45deg, #00DC82 0%, #36E4DA 50%, #0047E1 100%);opacity:0.8;filter:blur(30vh);height:60vh;bottom:-40vh}*,:before,:after{-webkit-box-sizing:border-box;box-sizing:border-box;border-width:0;border-style:solid;border-color:#e5e7eb}*{--tw-ring-inset:var(--tw-empty, );--tw-ring-offset-width:0px;--tw-r…dex.mjs:35:15)</span>\n<span class="stack">at /D:/root_git/ale.frontend/.nuxt/dev/index.mjs:967:17</span>\n<span class="stack internal">at processTicksAndRejections (node:internal/process/task_queues:96:5)</span>\n<span class="stack internal">at async Object.handler (/D:/root_git/ale.frontend/node_modules/h3/dist/index.mjs:567:19)</span>\n<span class="stack internal">at async Server.toNodeHandle (/D:/root_git/ale.frontend/node_modules/h3/dist/index.mjs:631:7)</span></pre></pre></div></body></html>'

      }

      return data.value as T;
    } catch (err) {
      throw err;
    }
  };
```

### Describe the bug

When calling a server route to try to upload a file to a backend (multipart/form-data header is present), if a error is thrown the data property of the error is not the expected object but the default HTML error by nuxt
This does not happen if the error is thrown when doing a normal POST/GET

![image](https://user-images.githubusercontent.com/28997550/200341443-7dd88491-656a-42c2-98ba-f3e77a40703d.png)

**Comment by madebyfabian** [comment]
@niddu85 Hey there! Could you upgrade your reproduction to the latest nuxt version and check if this still happens?, thank you 🙏🏻💚

**Comment by niddu85** [comment]
Hello,
i updated the code but the issue still happens

**Comment by OrbisK** [comment]
Workaround:

```diff
    const { data, error } = await useFetch('/webapi/dummyEndpoint', {
      method: 'POST',
      body: formData,
+      headers: {
+        accept: 'application/json',
+      },
    });
```

**Comment by OrbisK** [comment]
@danielroe I think this is how ofetch behaves. It does add the `accepts` header for form data. So maybe this is a won't fix or an upstream bug for ofetch.

**Comment by danielroe** [comment]
nuxtathon closed @OrbisK
