### ISSUE TITLE
[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'meta')

### ISSUE THREAD

**Issue by michealroberts** [nuxt/nuxt.js#15454]

**Comment by dante4rt** [comment]
I also found same error in my app:
```
playground-webapp:dev: [Vue warn]: Component <Anonymous> is missing template or render function.
playground-webapp:dev: [nitro] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'body')
playground-webapp:dev:     at /Users/dantezy/Downloads/Vonix/web2-nuxt/packages/ui/dist/runtime/components/footer/Footer.vue:18:23
playground-webapp:dev:     at /Users/dantezy/Downloads/Vonix/web2-nuxt/node_modules/.pnpm/@vue+runtime-core@3.4.6/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7820:14
playground-webapp:dev:     at ReactiveEffect.fn (/Users/dantezy/Downloads/Vonix/web2-nuxt/node_modules/.pnpm/@vue+reactivity@3.4.6/node_modules/@vue/reactivity/dist/reactivity.cjs.js:986:13)
playground-webapp:dev:     at ReactiveEffect.run (/Users/dantezy/Downloads/Vonix/web2-nuxt/node_modules/.pnpm/@vue+reactivity@3.4.6/node_modules/@vue/reactivity/dist/reactivity.cjs.js:165:19)
playground-webapp:dev:     at get value [as value] (/Users/dantezy/Downloads/Vonix/web2-nuxt/node_modules/.pnpm/@vue+reactivity@3.4.6/node_modules/@vue/reactivity/dist/reactivity.cjs.js:997:68)
playground-webapp:dev:     at unref (/Users/dantezy/Downloads/Vonix/web2-nuxt/node_modules/.pnpm/@vue+reactivity@3.4.6/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1110:29)
playground-webapp:dev:     at Object.get (/Users/dantezy/Downloads/Vonix/web2-nuxt/node_modules/.pnpm/@vue+reactivity@3.4.6/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1116:35)
playground-webapp:dev:     at Object.get (/Users/dantezy/Downloads/Vonix/web2-nuxt/node_modules/.pnpm/@vue+runtime-core@3.4.6/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3050:26)
playground-webapp:dev:     at _sfc_ssrRender (/Users/dantezy/Downloads/Vonix/web2-nuxt/packages/ui/dist/runtime/components/footer/Footer.vue:30:16)
playground-webapp:dev:     at renderComponentSubTree (/Users/dantezy/Downloads/Vonix/web2-nuxt/node_modules/.pnpm/@vue+server-renderer@3.4.6_vue@3.4.6/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:710:9)
```

Any advice?
