### ISSUE TITLE
Velocity.js render function or template not defined in component: anonymous

### ISSUE THREAD

**Issue by atmar** [nuxt/nuxt.js#1555]
I can't get velocity.js to work with nuxt, using it as a plugin with ssr false but no luck there. 

Error is "render function or template not defined in component: anonymous"

-> nuxt.config.js
```
plugins: [{
    src: '~/plugins/vue-carousel',
    ssr: false
  }, {
    src: '~/plugins/velocity',
    ssr: false
  }],
```

-> plugins/velocity.js

```
import Velocity from 'velocity-animate'

export {
  Velocity
}
```

-> my component
```
<script>
import _ from 'lodash'
import axios from 'axios'
import Velocity from '~/plugins/velocity'

export default {
  data() {
    return {
      options: [],
    }
  },
  methods: {
    beforeEnter: function(el) {
      el.style.opacity = 0
      el.style.height = 0
    },
    enter: function(el, done) {
      var delay = el.dataset.index * 150
      setTimeout(function() {
        Velocity(
          el,
          { opacity: 1, height: '1.6em' },
          { complete: done }
        )
      }, delay)
    },
    leave: function(el, done) {
      var delay = el.dataset.index * 150
      setTimeout(function() {
        Velocity(
          el,
          { opacity: 0, height: 0 },
          { complete: done }
        )
      }, delay)
    }
}
</script>
```

**Comment by gedgud** [comment]
Same here

**Comment by atmar** [comment]
Updated all packages but same issue for me. Either with 
```
import Velocity from 'velocity-animate'
```
or 
```
import Velocity from '~/plugins/velocity'
```
in the component.
(Node is 6.11.2, npm 3.10.10)

**Comment by vanoorschot** [comment]
I had the same error and it was cause by an anonymous import.
In my case I used `import '~/assets/svg/youtube.svg';` inside of a component.

**Comment by alexchopin** [comment]
Should work with the last release, feel free to comment/reopen if the bug persists.

**Comment by iamdubx** [comment]
It doesn't work, I got error

```
[vue-router] Failed to resolve async component default: ReferenceError: window is not defined
[vue-router] uncaught error during route navigation:
ReferenceError: window is not defined

```

**Comment by iamdubx** [comment]
My code is the same as above

**Comment by jackxueman** [comment]
Nuxt.js Error:

Error: render function or template not defined in component: anonymous
    at normalizeRender (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:5413:13)
    at renderComponentInner (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:5535:3)
    at renderComponent (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:5506:5)
    at RenderContext.renderNode (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:5422:5)
    at RenderContext.next (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:2179:14)
    at RenderContext.next (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:2188:12)
    at cachedWrite (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:1648:9)
    at renderElement (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:5564:5)
    at renderNode (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:5425:7)
    at renderComponentInner (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:5542:3)
    at renderComponent (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:5506:5)
    at RenderContext.renderNode (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:5422:5)
    at RenderContext.next (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:2179:14)
    at cachedWrite (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:1648:9)
    at renderElement (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:5573:5)
    at renderNode (/usr/local/app/justyeh.com/node_modules/vue-server-renderer/build.js:5425:7)

**Comment by andysay** [comment]
not worked

**Comment by uptownhr** [comment]
Another discussion about t his here, https://github.com/nuxt/nuxt.js/issues/2026
But, I've deen using this for about 6 months

```
// my velocity plugin
import velocity from 'velocity-animate/velocity.min.js'

export default (ctx, inject) => {
  ctx.$velocity = velocity
  inject('velocity', velocity)
}
```

```
plugins: [
   ...,
   { src: '~plugins/velocity.js', ssr: false }
]
```
