### ISSUE TITLE
example auth-routes not working

### ISSUE THREAD

**Issue by wargt** [nuxt/nuxt.js#1608]
**Hello! Not working example**
nuxtjs version = v1.0.0-rc11

https://nuxtjs.org/examples/auth-routes

```
const Nuxt = require('nuxt')
const bodyParser = require('body-parser')
const session = require('express-session')
const app = require('express')()

.
.
.
.
const isProd = process.env.NODE_ENV === 'production'
const nuxt = new Nuxt({ dev: !isProd })
```

                 ^
TypeError: Nuxt is not a constructor
    at Object.<anonymous> (/Users/Documents/Projects/test/server.js:22:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139

pls - help me - thanks

**Comment by wargt** [comment]
**fix if use** 
const Nuxt = require('nuxt').Nuxt

**Comment by wargt** [comment]
but I have next error

`const promise = (isProd ? Promise.resolve() : nuxt.build())`

                                                     ^
TypeError: nuxt.build is not a function
    at Object.<anonymous> (/Users/Documents/Projects/test/server.js:24:52)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by NicoPennec** [comment]
your Nuxt import is wrong: `Nuxt` => `{ Nuxt }`
```
const { Nuxt } = require("nuxt");
```

check this official example of custom server: https://github.com/nuxt/nuxt.js/blob/dev/examples/custom-server/server.js

**Comment by Atinux** [comment]
@wargt please check https://github.com/nuxt/nuxt.js/tree/dev/examples/auth-routes
