### ISSUE TITLE
Nuxt Js while refreshing date picker is not working([vue-router] Failed to resolve async component default: SyntaxError: Unexpected token <)

### ISSUE THREAD

**Issue by venugopalsundaram** [nuxt/nuxt.js#1645]
While refreshing the page it throws error

[vue-router] Failed to resolve async component default: SyntaxError: Unexpected token <
[vue-router] uncaught error during route navigation:
/data/nuxt/node_modules/vue-date-picker/src/datepicker.vue:1
(function (exports, require, module, __filename, __dirname) { <style scoped>
^

SyntaxError: Unexpected token <
at createScript (vm.js:74:10)
at Object.runInThisContext (vm.js:116:10)
at Module._compile (module.js:533:28)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at r (/data/nuxt/node_modules/vue-server-renderer/build.js:7739:16)
at Object. (server-bundle.js:4211:18)
at webpack_require (server-bundle.js:27:30)
at Object.129 (pages/modules/_module/add.515b290012e443c855fd.js:773:74)
at webpack_require (server-bundle.js:27:30)
at Object.128 (pages/modules/_module/add.515b290012e443c855fd.js:738:279)
at webpack_require (server-bundle.js:27:30)

My code snippet is:
_

<script> import Vue from 'vue' import datepicker from 'vue-date-picker' Vue.use(datepicker) export default { name: 'TextInput', props: ['data', 'modelData', 'readOnly'], data () { return { date: '' } }, components: { datepicker } </script>

**Comment by fabiobalielo** [comment]
@alexchopin you get some fix?
