### ISSUE TITLE
SyntaxError: Unexpected token - in nuxt.config.js

### ISSUE THREAD

**Issue by rlam3** [nuxt/nuxt.js#1788]
How do we add custom elements into nuxt.config.js for javascript?

```bash

        data-chownow-company-id: 'XXX'
            ^

SyntaxError: Unexpected token -
 at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)


```

```js
// nuxt.config.js
    script: [
      {
        src: 'https://cf.chownowcdn.com/latest/static/integrations/ordering-modal.min.js',
        data-chownow-company-id: 'XXX'
      }
    ]
```

**Comment by alexchopin** [comment]
Hi @rlam3, `dataChownowCompanyId` instead of `data-chownow-company-id` should work.

**Comment by rlam3** [comment]
@alexchopin the external script requires it to be in kebab form otherwise it won't recognize it....

**Comment by alexchopin** [comment]
@rlam3 my bad, I answered to fast.
Have you tried this syntax?
```js
// nuxt.config.js
    script: [
      {
        "src": 'https://cf.chownowcdn.com/latest/static/integrations/ordering-modal.min.js',
        "data-chownow-company-id": 'XXX'
      }
    ]
```
Nuxt.js uses [vue-meta](https://github.com/declandewet/vue-meta#script-object) to inject script into the document.
Can you open and refer this issue [here](https://github.com/declandewet/vue-meta/issues)? Thanks
