### ISSUE TITLE
SPA deployed on netlify not loading

### ISSUE THREAD

**Issue by maziarz** [nuxt/nuxt.js#1866]
I have deployed my page on netlify, which is not loading, instead i get following error which i have zero success debugging:

```
client.js:60 [nuxt] Error while initializing app TypeError: i.Config is not a constructor
    at Object.s (https://nuxt.testpage.com/_nuxt/app.425851a1d95d8b38d6b4.js:2:117827)
    at J2Ti.k (https://nuxt.testpage.com/_nuxt/app.425851a1d95d8b38d6b4.js:2:9751)
    at https://nuxt.testpage.com/_nuxt/app.425851a1d95d8b38d6b4.js:2:111429
    at r (https://nuxt.testpage.com/_nuxt/app.425851a1d95d8b38d6b4.js:2:12416)
    at Generator._invoke (https://nuxt.testpage.com/_nuxt/app.425851a1d95d8b38d6b4.js:2:13461)
    at Generator.e.(anonymous function) [as next] (https://nuxt.testpage.com/_nuxt/app.425851a1d95d8b38d6b4.js:2:12595)
    at r (https://nuxt.testpage.com/_nuxt/common.e173e702484a35932444.js:2:118568)
    at https://nuxt.testpage.com/_nuxt/common.e173e702484a35932444.js:2:118716
    at new Promise (<anonymous>)
    at new e (https://nuxt.testpage.com/_nuxt/common.e173e702484a35932444.js:2:130100)
(anonymous) @ client.js:60
```

**Comment by Atinux** [comment]
Hi @maziarz 

Please give us more informations and how to reproduce this error you have.

Then, you can re-open this issue.

**Comment by maziarz** [comment]
@Atinux, sorry for that. Let me do a minimal install and get back to you ASAP :-)

**Comment by maziarz** [comment]
So i tried to narrow down the problem, and it seems to be related to the my vuex store. I basically removed the file from `store` folder and the application ran smoothly. Thing is that i reproduced this in development mode. Is there a way to switch on debugging in production mode?

**Comment by maziarz** [comment]
Issue updated with an minimal reproducable examples!

**Comment by maziarz** [comment]
No matter how i include `shopify-buy` in the project it is always messing up the build. I am not able to reprduce this error in a clean vuejs project. Something i am only seeing in Nuxt.

**Comment by maziarz** [comment]
@Atinux, could you check this issue again and comment if it has sufficient information to re-open it? Cheers.
