### ISSUE TITLE
Cannot find module 'vue-template-compiler'

### ISSUE THREAD

**Issue by cawa-93** [nuxt/nuxt.js#1967]
Today I decided to upgrade from rc4 to rc11.
I also decided to remove the extra dependencies. From this [issue](https://github.com/nuxt/nuxt.js/issues/1084)
```
npm un vue vue-server-renderer vue-template-compiler
```
After that, for every file I get the following error:
```
Module build failed: Error: Cannot find module 'vue-template-compiler'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Develop\fb-scaner\node_modules\vue-loader\lib\parser.js:1:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Develop\fb-scaner\node_modules\vue-loader\lib\loader.js:3:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

 @ ./.nuxt/router.js 42:8-112
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=3000&path=/__webpack_hmr ./.nuxt/client.js
```
Tell me, is the `vue-template-compiler` not in the key depending on the Nuxt? Or how can I fix the problem?

**Comment by cawa-93** [comment]
Updated npm and reinstalled the nuxt. It helped. Strange ...

**Comment by jrudnik** [comment]
I had similar issue. In my case I first had to install css-loader and then re install vue-template-compiler. This solver the issue.
