### ISSUE TITLE
Nuxt Generate failing on dynamic routes

### ISSUE THREAD

**Issue by levimichael** [nuxt/nuxt.js#2146]
Hello! I have set up the nuxt.config.js file as in the documentation. I'm querying my API endpoint to populate the routes array with the list of blog post slugs. 

I get this error:

`TypeError: Cannot read property 'forEach' of undefined
    at Generator.decorateWithPayloads (/Users/levi/Desktop/dev-projects/semper-vita-institute/node_modules/nuxt/dist/nuxt.js:4855:21)
    at Generator._callee2$ (/Users/levi/Desktop/dev-projects/semper-vita-institute/node_modules/nuxt/lib/builder/generator.js:63:19)
    at tryCatch (/Users/levi/Desktop/dev-projects/semper-vita-institute/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/levi/Desktop/dev-projects/semper-vita-institute/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/levi/Desktop/dev-projects/semper-vita-institute/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/levi/Desktop/dev-projects/semper-vita-institute/node_modules/nuxt/dist/nuxt.js:954:30)
    at /Users/levi/Desktop/dev-projects/semper-vita-institute/node_modules/nuxt/dist/nuxt.js:965:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)`

Here's a gist of my nuxt.config.js:

https://gist.github.com/levimichael/7c3f4758200b58552cb4d2778314e4fe

**Comment by levimichael** [comment]
I was trying to use the promise method and not the callback method. it worked with the callback method. :)
