### ISSUE TITLE
router base error in Nuxt version rc11

### ISSUE THREAD

**Issue by biigpongsatorn** [nuxt/nuxt.js#2187]
When i set 
`router: {
    base: '/th/'
  },`

in file `nuxt.config.js` then my console show this error

> promise.then(resolve).catch(reject)
      ^
TypeError: Cannot read property 'then' of undefined
    at Immediate.<anonymous> (/Users/biig/Desktop/MyWork/Sellsuki/sellsuki-invoice2.0/build/webpack:/app.js:38:7)
    at runCallback (timers.js:674:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by biigpongsatorn** [comment]
update : i found solution that i have to fix it in middleware.
