### ISSUE TITLE
Cannot find module 'reduce-function-call'

### ISSUE THREAD

**Issue by abelovic** [nuxt/nuxt.js#220]
I got this error when trying to install the starter template. I was able to resolve it by installing this dependency manually but it should probably be included in nuxt.

ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-b155f86e&scoped=true!./~/vue-loader/lib/selector.js?type=styles&index=0!./pages/index.vue
Module build failed: Error: Cannot find module 'reduce-function-call'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\dev\nuxt\node_modules\reduce-css-calc\index.js:5:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-b155f86e&scoped=true!./~/vue-loader/lib/selector.js?type=styles&index=0!./pages/index.vue 4:14-223
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js

**Comment by Atinux** [comment]
What's your version of node.js and npm please?

**Comment by abelovic** [comment]
node: 7.5.0
npm: 4.1.2

**Comment by Atinux** [comment]
I just tried with:
```bash
$node -v
v7.3.0
$npm -v
4.2.0
```

And it works fine, can you update npm with `npm install -g npm` @abelovic and try again?

**Comment by abelovic** [comment]
@Atinux - Just tried your suggestion and I can no longer reproduce this error. Must have been something with my environment :/ Sorry for the inconvenience
