### ISSUE TITLE
Error: Cannot find module './dist/nuxt'

### ISSUE THREAD

**Issue by Darkside73** [nuxt/nuxt.js#2210]
Error thrown then trying to run ```nuxt``` command (latest dev branch)

**Comment by kdar** [comment]
The solution is in issue #688

**Comment by tonyrewin** [comment]
did not work for me
```sh
***

$ npm run build

> nuxt@1.0.0-alpha.5 build /Users/kindus/Downloads/DEV/WorldChess/worldchess-vue/node_modules/nuxt
> webpack

No configuration file found and no output filename configured via CLI option.
A configuration file could be named 'webpack.config.js' in the current directory.
Use --help to display the CLI options.
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! nuxt@1.0.0-alpha.5 build: `webpack`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the nuxt@1.0.0-alpha.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
...
```

**Comment by rhwilr** [comment]
I get the same error. I narrowed it down to the following commit: c7a0d3d55a376db52008e7295f5e70bae3b0b5fc
But I can't find out what exactly is causing the issue, since there is nothing in this commit that seems related.

I get this error when I run `npm run dev`: 
```
npm run dev                                                                                                           09:14:07

> adonis-client@1.0.0 dev /home/ralph/webDev/atropos-client
> nuxt

Error: Cannot find module './dist/nuxt'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ralph/webDev/atropos-client/node_modules/nuxt/index.js:16:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adonis-client@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the adonis-client@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
 If I checkout one commit before this (79ce2ebc5d098843991435578014976ce94d579d) I can get passed that point, but then I get an error "These dependencies were not found".
This error was also already reported here: https://github.com/nuxt/nuxt.js/issues/2222

**Comment by pi0** [comment]
Please see https://github.com/nuxt/nuxt.js/issues/2142#issuecomment-347193288 for a better approach for testing edge releases.
