### ISSUE TITLE
Module not found: Error: Can't resolve 'plugin0'

### ISSUE THREAD

**Issue by xxxxxccc** [nuxt/nuxt.js#2314]
"nuxt": "^1.0.0-rc11";

Module not found: Error: Can't resolve 'plugin0' in '/root/.jenkins/workspace/frontend-demo/.nuxt'
 @ ./.nuxt/index.js 176:0-30
 @ ./.nuxt/client.js[39m[22m
Error: Webpack build exited with errors
    at /root/.jenkins/workspace/frontend-versa-demo/node_modules/nuxt/lib/builder/builder.js:498:27
    at emitRecords.err (/root/.jenkins/workspace/frontend-demo/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/root/.jenkins/workspace/frontend-demo/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/root/.jenkins/workspace/frontend-demo/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/root/.jenkins/workspace/frontend-demo/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/root/.jenkins/workspace/frontend-demo/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/root/.jenkins/workspace/frontend-demo/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/root/.jenkins/workspace/frontend-demo/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/root/.jenkins/workspace/frontend-demo/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/root/.jenkins/workspace/frontend-demo/node_modules/webpack/lib/Compiler.js:350:15)
    at /root/.jenkins/workspace/frontend-versa-demo/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/root/.jenkins/workspace/frontend-demo/node_modules/async/dist/async.js:1050:13)
    at /root/.jenkins/workspace/frontend-demo/node_modules/async/dist/async.js:958:16
    at /root/.jenkins/workspace/frontend-demo/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by SilenceZeng** [comment]
check your plugin path you wrote
