### ISSUE TITLE
TypeError: Cannot assign to read only property 'name' of function 'function () { [native code] }'

### ISSUE THREAD

**Issue by sokyrko** [nuxt/nuxt.js#2326]
Nuxt: 1.0.0-rc8
Error appears sometimes only on prod load or while load testing (`loadtest -n 100000 -c 100 --insecure http://0.0.0.0:15333`)
Full stacktrace:
```
TypeError: Cannot assign to read only property 'name' of function 'function () { [native code] }'
at Renderer.errorMiddleware (/www/node_modules/nuxt/lib/core/renderer.js:320:5)
at call (/www/node_modules/connect/index.js:235:7)
at next (/www/node_modules/connect/index.js:183:5)
at Renderer._callee5$ (/www/node_modules/nuxt/dist/nuxt.js:2510:17)
at tryCatch (/www/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:65:40)
at Generator.invoke [as _invoke] (/www/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:299:22)
at Generator.prototype.(anonymous function) [as throw] (/www/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:117:21)
at step (/www/node_modules/nuxt/dist/nuxt.js:954:30)
at /www/node_modules/nuxt/dist/nuxt.js:967:13
at process._tickCallback (internal/process/next_tick.js:109:7)

```

**Comment by clarkdo** [comment]
Can you have try on `1.0.0-rc8` or `next` ?
