### ISSUE TITLE
i18n example error

### ISSUE THREAD

**Issue by mixty1** [nuxt/nuxt.js#236]
When i set wrong language, it shows error.
url: `http://i18n.nuxtjs.org/wronglang`
```
Vue.js error

TypeError: Cannot read property 'links' of undefined
    at __vue_ssr_bundle__:1971:18
    at Array.forEach (native)
    at Proxy.module.exports.__WEBPACK_IMPORTED_MODULE_0_vue___default.a.$t (__vue_ssr_bundle__:1970:8)
    at Proxy.render (__vue_ssr_bundle__:4717:42)
    at VueComponent.Vue._render (/home/nowuser/src/node_modules/vue/dist/vue.runtime.common.js:2216:22)
    at renderComponent (/home/nowuser/src/node_modules/vue-server-renderer/build.js:6078:25)
    at renderNode (/home/nowuser/src/node_modules/vue-server-renderer/build.js:6061:7)
    at next (/home/nowuser/src/node_modules/vue-server-renderer/build.js:6197:9)
    at next (/home/nowuser/src/node_modules/vue-server-renderer/build.js:6189:7)
    at cachedWrite (/home/nowuser/src/node_modules/vue-server-renderer/build.js:36:9)
```

**Comment by Atinux** [comment]
Nice catch @mixty1 

It's fixed: http://i18n.nuxtjs.org/

Code: https://github.com/nuxt/nuxt.js/tree/master/examples/i18n
