### ISSUE TITLE
render function or template not defined in component

### ISSUE THREAD

**Issue by nucamoz** [nuxt/nuxt.js#238]
I am trying to run `npm run generate` but it throws error:

```
Error: render function or template not defined in component: anonymous
    at normalizeRender (/home/zman/pkr-crdrz/node_modules/vue-server-renderer/build.js:6011:13)
    at renderComponent (/home/zman/pkr-crdrz/node_modules/vue-server-renderer/build.js:6077:3)
    at renderNode (/home/zman/pkr-crdrz/node_modules/vue-server-renderer/build.js:6061:7)
    at renderComponent (/home/zman/pkr-crdrz/node_modules/vue-server-renderer/build.js:6084:3)
    at renderNode (/home/zman/pkr-crdrz/node_modules/vue-server-renderer/build.js:6061:7)
    at next (/home/zman/pkr-crdrz/node_modules/vue-server-renderer/build.js:6197:9)
    at cachedWrite (/home/zman/pkr-crdrz/node_modules/vue-server-renderer/build.js:36:9)
    at renderElement (/home/zman/pkr-crdrz/node_modules/vue-server-renderer/build.js:6121:5)
    at renderNode (/home/zman/pkr-crdrz/node_modules/vue-server-renderer/build.js:6065:7)
    at renderComponent (/home/zman/pkr-crdrz/node_modules/vue-server-renderer/build.js:6084:3)

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "generate"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! pkr-crdrz@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pkr-crdrz@1.0.0 generate script 'nuxt generate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pkr-crdrz package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt generate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pkr-crdrz
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pkr-crdrz
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zman/pkr-crdrz/npm-debug.log
```

What can cause this problem?

**Comment by nucamoz** [comment]
I guess it's vue-router problem, but how I can diagnose where exactly the problem is?

**Comment by nucamoz** [comment]
The problem was next: I had empty .vue in Pages that I never use. Delete it and problem fixed.
