### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by jesperlandberg** [nuxt/nuxt.js#2392]
Hi,

I'm getting this error, using import in a mixin.

```
[vue-router] Failed to resolve async component default: SyntaxError: Unexpected token import
[vue-router] uncaught error during route navigation:
C:\Program Files (x86)\Ampps\www\2\node_modules\smooth-scrolling\index.js:1
(function (exports, require, module, __filename, __dirname) { import classes from 'dom-classes'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at r (C:\Program Files (x86)\Ampps\www\2\node_modules\vue-server-renderer\build.js:7758:16)
    at Object.<anonymous> (server-bundle.js:4064:18)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.<anonymous> (pages\studio.59180a60d0b870bbbb46.js:387:75)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.<anonymous> (pages\studio.59180a60d0b870bbbb46.js:762:77)
    at __webpack_require__ (server-bundle.js:27:30)
```

Any idea why this is and how it can be fixed?

**Comment by clarkdo** [comment]
Try adding `dom-classes` to externals 😺 

```js
const nodeExternals = require('webpack-node-externals')

module.exports = {
  /*
  ** Add Vuetify into vendor.bundle.js
  */
  build: {
    extend(config, ctx) {
      if (ctx.isServer) {
        config.externals = [
          nodeExternals({
            whitelist: [/^dom-classes/]
          })
        ]
      }
    }
  }
}
```

**Comment by manniL** [comment]
For all googlers coming here, there is now a [`transpile` option](https://nuxtjs.org/api/configuration-build#transpile)
