### ISSUE TITLE
Error deploying to AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by ianaya89** [nuxt/nuxt.js#2464]
I am trying to deploy a nuxt application using EB CLI and I get the following npm error:

```
91612 verbose lifecycle uws@0.14.5~install: unsafe-perm in lifecycle false
91613 verbose lifecycle uws@0.14.5~install: PATH: /opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/tmp/deployment/application/node_modules/uws/node_modules/.bin:/tmp/deployment/application/node_modules/.bin:/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin:/opt/elasticbeanstalk/lib/ruby/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
91614 verbose lifecycle uws@0.14.5~install: CWD: /tmp/deployment/application/node_modules/uws
91615 silly lifecycle uws@0.14.5~install: Args: [ '-c', 'node-gyp rebuild > build_log.txt 2>&1 || exit 0' ]
91616 verbose stack Error: spawn ENOMEM
91616 verbose stack     at exports._errnoException (util.js:1020:11)
91616 verbose stack     at ChildProcess.spawn (internal/child_process.js:328:11)
91616 verbose stack     at exports.spawn (child_process.js:369:9)
91616 verbose stack     at spawn (/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:21:13)
91616 verbose stack     at runCmd_ (/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:247:14)
91616 verbose stack     at /opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:211:7
91616 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:73:7)
91616 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
91617 verbose cwd /tmp/deployment/application
91618 error Linux 4.9.62-21.56.amzn1.x86_64
91619 error argv "/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/npm" "--production" "install"
91620 error node v6.11.5
91621 error npm  v3.10.10
91622 error code ENOMEM
91623 error errno ENOMEM
91624 error syscall spawn
91625 error spawn ENOMEM
91626 error If you need help, you may report this error at:
91626 error     <https://github.com/npm/npm/issues>
91627 verbose exit [ 1, true ]
```

I could not find much information about EB deployment with Nuxt, so not sure if the issue is related to Nuxt or EB. Here are some information about the environment:

- OS: 64bit Amazon Linux 2017.09 v4.4.1
- Node 8.9.3
- Nuxt 1.0.0-rc11

**Comment by ianaya89** [comment]
I found the solution. EB instance was getting out of memory, I was using `t2.micro`, after increasing to `t2.medium` problem was solved. 💯

**Comment by venkatreddyputhana7** [comment]
how to increasing from t2.micro to t2.medium

**Comment by Imanullah** [comment]
if Nuxt production generated.. it shoud be SSR static website......... 
in AWS is very simple deploy in S3 

check this video 
[(https://www.youtube.com/watch?v=g9NbuTcos18)]
