### ISSUE TITLE
Error: Cannot find module 'vue-meta'

### ISSUE THREAD

**Issue by binggg** [nuxt/nuxt.js#2535]
## nuxt@1.0.0
```
Error: Cannot find module 'vue-meta' from '/Users/benzhao/Sites/movie.xunlei.com'
    at Function.module.exports [as sync] (/Users/benzhao/Sites/movie.xunlei.com/node_modules/resolve/lib/sync.js:40:15)
    at r (/Users/benzhao/Sites/movie.xunlei.com/node_modules/vue-server-renderer/build.js:8149:44)
    at Object.module.exports.__webpack_exports__.a (server-bundle.js:4521:18)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.<anonymous> (server-bundle.js:3076:67)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.<anonymous> (server-bundle.js:2649:65)
    at __webpack_require__ (server-bundle.js:27:30)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10)
    at evaluateModule (/Users/benzhao/Sites/movie.xunlei.com/node_modules/vue-server-renderer/build.js:8155:21)
    at /Users/benzhao/Sites/movie.xunlei.com/node_modules/vue-server-renderer/build.js:8213:18
    at new Promise (<anonymous>)
    at /Users/benzhao/Sites/movie.xunlei.com/node_modules/vue-server-renderer/build.js:8205:14
    at Object.renderToString (/Users/benzhao/Sites/movie.xunlei.com/node_modules/vue-server-renderer/build.js:8380:9)
    at Renderer.renderRoute (/Users/benzhao/Sites/movie.xunlei.com/node_modules/nuxt/lib/core/renderer.js:303:41)
```

**Comment by NicoPennec** [comment]
the node module `vue-meta` seems not install.

have you re-run `npm install` (or `yarn`) after updating your `package.json` file?

else please share your `"dependencies": { ... }` here

**Comment by Andrei997** [comment]
These packages used to be included within the previous version, but with the update to 1.0 that is no longer the case. 
You can do `npm install` or 'yarn add' for those packages (vue, vue-meta, vuex, etc.)

**Comment by NicoPennec** [comment]
vue-meta is included in 1.0 https://github.com/nuxt/nuxt.js/blob/dev/package.json#L109

**Comment by Andrei997** [comment]
That is weird. I was facing the same problem as @binggg and I had to run `npm install` for vue, vue-meta, vue-router and vuex in order to fix it.

**Comment by NicoPennec** [comment]
can you try to clear your deps before? and tell us if you have the same issue

1. `rm -rf node_modules`
2. `npm install`
3. `npm list --depth 0` (optional, to check version)

**Comment by KindWizzard** [comment]
Same issue here.

I get the message `Cannot find module 'vue' from` caused by `.nuxt/server.js:1`. Looks like webpack looking for the vue in root node_modules directory, instead of node_modules/nuxt.

After adding "vue" dep. manually to package.json I get the same message for the "vue-meta".

**Comment by binggg** [comment]
@NicoPennec It works, Thanks

**Comment by mashpie** [comment]
...just to note:

upgrade to nuxt 1.3.0 (`npm i nuxt@1.3.0`) required me to also remove `package-lock.json`, so:

```bash
rm -rf node_modules
rm -f package-lock.json
npm cache clean --force
npm i
```

finally worked out
