### ISSUE TITLE
render function or template not defined in component: anonymous

### ISSUE THREAD

**Issue by mingliao** [nuxt/nuxt.js#2576]
hi ， I create a new nuxt project as the command ```vue init nuxt-community/starter-template <project-name>``` and install the package in my project and when I open the **http://localhost:3000/** it show me these info 
![](https://note.youdao.com/yws/public/resource/25a314442a4ca732e2b3d617b1c6d2ca/xmlnote/D617032309D14E91BD3D3A2BD3D42E73/22651)

> Nuxt.js Error:
Error: render function or template not defined in component: anonymous
    at normalizeRender (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5413:13)
    at renderComponentInner (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5535:3)
    at renderComponent (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5506:5)
    at RenderContext.renderNode (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5422:5)
    at RenderContext.next (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:2179:14)
    at RenderContext.next (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:2188:12)
    at cachedWrite (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:1648:9)
    at renderElement (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5564:5)
    at renderNode (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5425:7)
    at renderComponentInner (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5542:3)
    at renderComponent (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5506:5)
    at RenderContext.renderNode (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5422:5)
    at RenderContext.next (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:2179:14)
    at cachedWrite (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:1648:9)
    at renderElement (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5573:5)
    at renderNode (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5425:7)
    at render (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5676:5)
    at Object.renderToString (C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:5720:9)
    at C:\Users\think\AppData\Roaming\npm\node_modules\nuxt\node_modules\_vue-server-renderer@2.3.4@vue-server-renderer\build.js:6027:22
    at <anonymous>

this is my *package.json* it generate my nuxt start template.

> {
  "name": "nuxt-demo",
  "version": "1.0.0",
  "description": "Nuxt.js project",
  "author": "765132065@qq.com <765132065@qq.com>",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "nuxt": "^1.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^4.3.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.1.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1"
  }
}

and my node version  is *node-v8.9.3-x64.msi*  and 
```
>node -v
v8.9.3

>npm -v
5.5.1
```
i dont know what to do next . is nuxt version 1.x need a suitable node version?

**Comment by mingliao** [comment]
when i reinstall the node,and update the version to the node  lastest version  ,the problem solved.

**Comment by NicoPennec** [comment]
be careful ! the following path refers to your "npm global" repository : C:\Users\think\AppData\Roaming\npm\node_modules\nuxt

so you have 2 instances of nuxt
global: `npm -g list nuxt`
local: `npm list nuxt`

Start your nuxt server from local instance: `npm run dev`

**Comment by mingliao** [comment]
@NicoPennec  thank very much ，when I run *nuxt *  the problem show again，and when i run *npm run dev* it‘s no problem， haha，but I dont remember I have install nuxt global .
