### ISSUE TITLE
 TypeError: logError is not a function

### ISSUE THREAD

**Issue by davidboom95** [nuxt/nuxt.js#2577]
Hi, I have this error when nuxt tries to throw an error
**node version:** 8.9.1
**nuxt:** ^1.0.0
```bash
yarn run v0.17.6
$ nuxt
  nuxt:build App root: /Users/DavidP/SendTest +0ms
  nuxt:build Generating /Users/DavidP/SendTest/.nuxt files... +2ms
  nuxt:build Generating files... +61ms
  nuxt:build Generating routes... +12ms
  nuxt:build Building files... +31ms
  nuxt:build Adding webpack middleware... +1s
  ████████████████████ 15% building modules/Users/DavidP/SendTest/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: logError is not a function
    at process.on._error (/Users/DavidP/SendTest/node_modules/nuxt/bin/nuxt:7:3)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at processEmit [as emit] (/Users/DavidP/SendTest/node_modules/signal-exit/index.js:155:32)
    at methodName (/Users/DavidP/SendTest/node_modules/bluebird/js/release/debuggability.js:189:33)
    at activeFireEvent (/Users/DavidP/SendTest/node_modules/bluebird/js/release/debuggability.js:232:44)
    at fireRejectionEvent (/Users/DavidP/SendTest/node_modules/bluebird/js/release/debuggability.js:617:14)
    at Promise._notifyUnhandledRejection (/Users/DavidP/SendTest/node_modules/bluebird/js/release/debuggability.js:64:9)
    at Timeout._onTimeout (/Users/DavidP/SendTest/node_modules/bluebird/js/release/debuggability.js:43:14)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by pi0** [comment]
Thanks for the report. Will be fixed in next release.
