### ISSUE TITLE
when npm run dev ,promisify is not a function

### ISSUE THREAD

**Issue by wufuxi** [nuxt/nuxt.js#2604]
E:\myDemos\nuxtTest\node_modules\.1.1.1@nuxt\lib\builder\builder.js:32
const glob = promisify(Glob)
             ^

TypeError: promisify is not a function
    at Object.<anonymous> (E:\myDemos\nuxtTest\node_modules\.1.1.1@nuxt\lib\builder\builder.js:32:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\myDemos\nuxtTest\node_modules\.1.1.1@nuxt\lib\builder\index.js:1:79)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2267">#c2267</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
The minimum Node.js version required for Nuxt.js is also increased to 8.0.0 (Current LTS) since Nuxt release 1.0 (https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0)

And `promosify()` is a new utility function from Node 8

So you seem not on node >=8 
Please upgrade your stack 😉

**Comment by NicoPennec** [comment]
https://github.com/nuxt/nuxt.js/issues/2545

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
