### ISSUE TITLE
Unable to build on remote when using nvm

### ISSUE THREAD

**Issue by JonathanAlumbaugh** [nuxt/nuxt.js#2649]
I have updated to the latest releases of Nuxt.js, npm, and Node.js on a shared server using nvm, and when I attempt to run ```nuxt build```, I get this:

```
jonatha8 [~/public_html]# npm run build

> website-nuxt@1.0.0 build /home/jonatha8/public_html
> nuxt build

  nuxt:pwa Adding manifest +0ms
  nuxt:pwa Adding meta +5ms
  nuxt:pwa Adding workbox +1ms
  ████████████████████ 91% additional chunk assets processingnode[861586]: pthread_create: Resource temporarily unavailable
internal/child_process.js:340
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at _errnoException (util.js:1003:13)
    at ChildProcess.spawn (internal/child_process.js:340:11)
    at exports.spawn (child_process.js:499:9)
    at Object.exports.fork (child_process.js:100:10)
    at fork (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/worker-farm/lib/fork.js:12:35)
    at Farm.startChild (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/worker-farm/lib/farm.js:106:16)
    at Farm.processQueue (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/worker-farm/lib/farm.js:279:10)
    at Farm.addCall (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/worker-farm/lib/farm.js:307:8)
    at Farm.<anonymous> (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/worker-farm/lib/farm.js:38:10)
    at _class.boundWorkers (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:71:24)
    at enqueue (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:96:17)
    at /home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:116:11
    at Array.forEach (<anonymous>)
    at _class.runTasks (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:94:13)
    at Compilation.<anonymous> (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/uglifyjs-webpack-plugin/dist/index.js:183:18)
    at next (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.compilation.plugin (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/webpack/lib/ProgressPlugin.js:119:6)
    at Compilation.applyPluginsAsyncSeries (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/webpack/lib/Compilation.js:666:10)
    at next (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin.callback (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/webpack/lib/ProgressPlugin.js:115:6)
    at Compilation.applyPluginsAsyncSeries (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/nuxt/node_modules/tapable/lib/Tapable.js:206:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website-nuxt@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the website-nuxt@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jonatha8/.npm/_logs/2018-01-20T04_49_16_069Z-debug.log
```
I'm not sure what to do about this. It seems like there's an issue with trying to use nvm, but I'm unable to update npm + Node.js globally since it's a shared environment, so nvm was my attempt to work around that. When I run -v, everything looks okay:

```
jonatha8 [~/public_html]# npm -v
5.6.0
jonatha8 [~/public_html]# node -v
v9.4.0
```

When I run ```nuxt``` or ```nuxt build``` locally, with npm 5.6.0 and Node.js 9.4.0, it runs and builds correctly.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2304">#c2304</a>)</em></sub></div>

**Comment by JonathanAlumbaugh** [comment]
After fiddling around, I now get this error instead:

```
jonatha8 [~/public_html]# npm run build

> website-nuxt@1.0.0 build /home/jonatha8/public_html
> nuxt build

  ████████████████████ 91% additional chunk assets processingnode[516986]: pthread_create: Resource temporarily unavailable
internal/child_process.js:340
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at _errnoException (util.js:1003:13)
    at ChildProcess.spawn (internal/child_process.js:340:11)
    at exports.spawn (child_process.js:499:9)
    at Object.exports.fork (child_process.js:100:10)
    at fork (/home/jonatha8/public_html/node_modules/worker-farm/lib/fork.js:12:35)
    at Farm.startChild (/home/jonatha8/public_html/node_modules/worker-farm/lib/farm.js:106:16)
    at Farm.processQueue (/home/jonatha8/public_html/node_modules/worker-farm/lib/farm.js:279:10)
    at Farm.addCall (/home/jonatha8/public_html/node_modules/worker-farm/lib/farm.js:307:8)
    at Farm.<anonymous> (/home/jonatha8/public_html/node_modules/worker-farm/lib/farm.js:38:10)
    at _class.boundWorkers (/home/jonatha8/public_html/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:71:24)
    at enqueue (/home/jonatha8/public_html/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:96:17)
    at /home/jonatha8/public_html/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:116:11
    at Array.forEach (<anonymous>)
    at _class.runTasks (/home/jonatha8/public_html/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:94:13)
    at Compilation.<anonymous> (/home/jonatha8/public_html/node_modules/uglifyjs-webpack-plugin/dist/index.js:183:18)
    at next (/home/jonatha8/public_html/node_modules/webpack/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.compilation.plugin (/home/jonatha8/public_html/node_modules/webpack/lib/ProgressPlugin.js:119:6)
    at Compilation.applyPluginsAsyncSeries (/home/jonatha8/public_html/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/home/jonatha8/public_html/node_modules/webpack/lib/Compilation.js:666:10)
    at next (/home/jonatha8/public_html/node_modules/webpack/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin.callback (/home/jonatha8/public_html/node_modules/webpack/lib/ProgressPlugin.js:115:6)
    at Compilation.applyPluginsAsyncSeries (/home/jonatha8/public_html/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website-nuxt@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the website-nuxt@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jonatha8/.npm/_logs/2018-01-20T17_03_04_127Z-debug.log
```

**Comment by JonathanAlumbaugh** [comment]
Continued fiddling, it will build and run locally, but not remotely. I can run `npm run dev` remotely and that gives me something that shows the website at least but it's in development build. Attempting to run `npm run build` remotely results in this log:

`0 info it worked if it ends with ok
1 verbose cli [ '/home/jonatha8/.nvm/versions/node/v9.4.0/bin/node',
1 verbose cli   '/home/jonatha8/.nvm/versions/node/v9.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle website-nuxt@1.0.0~prebuild: website-nuxt@1.0.0
6 info lifecycle website-nuxt@1.0.0~build: website-nuxt@1.0.0
7 verbose lifecycle website-nuxt@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle website-nuxt@1.0.0~build: PATH: /home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules
/npm-lifecycle/node-gyp-bin:/home/jonatha8/public_html/node_modules/.bin:/home/jonatha8/public_html:/home/jonatha8/.nvm/versio
ns/node/v9.4.0/bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/
lib/path-bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/cpanel/composer/bin:/home/jonatha8/bin
9 verbose lifecycle website-nuxt@1.0.0~build: CWD: /home/jonatha8/public_html
10 silly lifecycle website-nuxt@1.0.0~build: Args: [ '-c', 'nuxt build' ]
11 silly lifecycle website-nuxt@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle website-nuxt@1.0.0~build: Failed to exec build script
13 verbose stack Error: website-nuxt@1.0.0 build: `nuxt build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/n
pm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/jonatha8/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/n
pm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid website-nuxt@1.0.0
15 verbose cwd /home/jonatha8/public_html
16 verbose Linux 3.10.0-714.10.2.lve1.5.9.el7.x86_64
17 verbose argv "/home/jonatha8/.nvm/versions/node/v9.4.0/bin/node" "/home/jonatha8/.nvm/versions/node/v9.4.0/bin/npm" "run" "
build"
18 verbose node v9.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error website-nuxt@1.0.0 build: `nuxt build`
22 error Exit status 1
23 error Failed at the website-nuxt@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by rwatts3** [comment]
agreed, slightly different use case but I am no longer able to deploy to now.sh I get this error every time now tries to build the project. 

I'm wondering if there is an issue with production build.

**Comment by Bloodmsg** [comment]
I have the same problem, npm run dev remotely works , but npm run build remotely failed.
@JonathanAlumbaugh have you find the solution?
