### ISSUE TITLE
Error starting on fresh install

### ISSUE THREAD

**Issue by magick93** [nuxt/nuxt.js#2682]
# Description

I did a fresh install of nuxt.js but am getting an error when I try to run.

## Steps to reproduce

1. `vue init nuxt-community/starter-template website1` and fill in details
2. `cd website1`
3. `npm install`
4. `npm run dev`

```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1366:14)
    at listenInCluster (net.js:1407:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1522:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:102:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website1@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the website1@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anton/.npm/_logs/2018-01-24T23_54_12_825Z-debug.log


```

**Comment by ArStah** [comment]
`Error: listen EADDRINUSE 127.0.0.1:3000` mean that some program in your system already using 3000 port. You have to stop it, or specify different port for nuxt

**Comment by magick93** [comment]
Thanks! That was the problem!
