### ISSUE TITLE
Error trying to include vue-goodshare

### ISSUE THREAD

**Issue by drpebcak** [nuxt/nuxt.js#2720]
I'm trying to use vue-goodshare in my nuxt project, but I'm seeing errors like this:

```
{ /srv/code/node_modules/vue-goodshare/src/VueGoodshare.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^

SyntaxError: Unexpected token <
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at r (/srv/code/node_modules/vue-server-renderer/build.js:8147:16)
    at Object.<anonymous> (server-bundle.js:4039:18)
    at __webpack_require__ (webpack:/webpack/bootstrap fca6890a803abb53971a:25:0)
    at Object.<anonymous> (plugins/vue-goodshare.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap fca6890a803abb53971a:25:0)
    at Object.<anonymous> (.nuxt/index.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap fca6890a803abb53971a:25:0)
    at Object.<anonymous> (.nuxt/server.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap fca6890a803abb53971a:25:0)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10)
    at evaluateModule (/srv/code/node_modules/vue-server-renderer/build.js:8155:21)
    at /srv/code/node_modules/vue-server-renderer/build.js:8213:18 statusCode: 500, name: 'SyntaxError' }
```

**Comment by clarkdo** [comment]
Due to `VueGoodshare` didn't compiled `.vue` files and also didn't support SSR, so you should remove it from `external` and render it only in `client`

```js
// nuxt.config.js
const nodeExternals = require('webpack-node-externals')

module.exports = {
  build: {
    extend(config, ctx) {
      if (ctx.isServer) {
        config.externals = [
          nodeExternals({
            whitelist: [/^vue-goodshare/]
          })
        ]
      }
    }
  }
}

// pages/index.vue
<template>
  <div class="container">
    <component :is="goodshare"></component>
  </div>
</template>

<script>
export default {
  data: () => ({
    'goodshare': ''
  }),
  components: {
    VueGoodshare: () => import('vue-goodshare')
  },
  mounted() {
    this.goodshare = 'VueGoodshare'
  }
}
</script>
```

**Comment by msantore** [comment]
Anyone have luck loading a Single share element instead of the bundle?
