### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by 0pt1m1z3r** [nuxt/nuxt.js#2739]
I created my own npm package. It contains es6 modules.
I just import its in different pages.
Example: `import sessionApi from 'my_package/src/api/session'`

I fix `babel-loader` rule in config. Build is successful. But when I try open page, I see this error.
```
2018-02-01T20:14:30.747Z nuxt:render Rendering url /
{ /.../nuxt_project/node_modules/my_package/src/api/session.js:1
(function (exports, require, module, __filename, __dirname) { import apiClient from '../services/api-client'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at r (/.../nuxt_project/node_modules/vue-server-renderer/build.js:8147:16)
    at Object.<anonymous> (server-bundle.js:4648:18)
    at __webpack_require__ (webpack:/webpack/bootstrap 0305385e49828e49290b:25:0)
    at Object.<anonymous> (app/store/session.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 0305385e49828e49290b:25:0)
    at webpackContext (server-bundle.js:4534:9)
    at getModule (.nuxt/store.js:57:0)
    at Object.module.exports.map../index.js (.nuxt/store.js:41:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 0305385e49828e49290b:25:0)
    at Object.<anonymous> (.nuxt/index.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 0305385e49828e49290b:25:0)
    at Object.<anonymous> (.nuxt/server.js:1:0) statusCode: 500, name: 'SyntaxError' }
```

@alexchopin @pi0 @clarkdo I can't understand what the problem is. Help pls.
I can't find this code in `.nuxt/`.
```
(function (exports, require, module, __filename, __dirname) { import apiClient from '../services/api-client'
```

**Comment by 0pt1m1z3r** [comment]
#1011

**Comment by NicoPennec** [comment]
@0pt1m1z3r Have you see this similar issue ? https://github.com/nuxt/nuxt.js/issues/2392

**Comment by 0pt1m1z3r** [comment]
@NicoPennec thank you! Solved!
