### ISSUE TITLE
Error when running npm run dev after installing nuxtjs

### ISSUE THREAD

**Issue by mfaridzia** [nuxt/nuxt.js#2787]
I am getting the following error when i run npm run dev after installing nuxt.js

$ npm run dev
> simple-web-nuxtjs@1.0.0 dev D:\nuxtjs\learn-nuxtjs\simple-web-nuxtjs
> nuxt

2018-02-07T08:52:32.003Z nuxt:build App root: D:\nuxtjsv\learn-nuxtjs\simple-web-nuxtjs
2018-02-07T08:52:32.007Z nuxt:build Generating D:\nuxtjs\learn-nuxtjs\simple-web-nuxtjs\.nuxt files...
2018-02-07T08:52:32.066Z nuxt:build Generating files...
2018-02-07T08:52:32.081Z nuxt:build Generating routes...
2018-02-07T08:52:32.144Z nuxt:build Building files...
2018-02-07T08:52:34.101Z nuxt:build Adding webpack middleware...
 DONE  Compiled successfully in 7505ms15:52:41

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simple-web-nuxtjs@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simple-web-nuxtjs@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo B490\AppData\Roaming\npm-cache\_logs\2018-02-07T08_52_43_511Z-debug.log

nb:
I use npm@5.6.0 and  node@v8.9.1

**Comment by microcipcip** [comment]
@mfaridzia the error is saying that the port 3000 is in use. You've got to change the port number to something else.

**Comment by adrienNk** [comment]
@mfaridzia in case of need : https://nuxtjs.org/faq/host-port/

**Comment by adrienNk** [comment]
(but most probably you already have node runing nuxt on port 3000. You might want to check your processes in windows task manager and kill the corresponding node process)

**Comment by mfaridzia** [comment]
work like charm , i'm getting error because node running nuxt before on port 3000
thanks @microcipcip @adrienNk for your answer
