### ISSUE TITLE
[Error on yarn dev] Module build failed: Error: No ESLint configuration found.

### ISSUE THREAD

**Issue by kkitay** [nuxt/nuxt.js#2829]
Hi, I'm just getting started w/ the starter template. I haven't made any significant changes, but on yarn dev get the following error:
```
 ERROR  Failed to compile with 1 errors                                                                         7:58:49 AM

Module build failed: Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (/Users/kat/dev/listapp/src/node_modules/eslint/lib/config.js:256:39)
    at Config.getConfigHierarchy (/Users/kat/dev/listapp/src/node_modules/eslint/lib/config.js:180:43)
    at Config.getConfigVector (/Users/kat/dev/listapp/src/node_modules/eslint/lib/config.js:287:21)
    at Config.getConfig (/Users/kat/dev/listapp/src/node_modules/eslint/lib/config.js:330:29)
    at processText (/Users/kat/dev/listapp/src/node_modules/eslint/lib/cli-engine.js:162:33)
    at CLIEngine.executeOnText (/Users/kat/dev/listapp/src/node_modules/eslint/lib/cli-engine.js:618:17)
    at lint (/Users/kat/dev/listapp/src/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/Users/kat/dev/listapp/src/node_modules/eslint-loader/index.js:213:21)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
```

I have a `.eslintrc.js` in my root (`/src`):

```
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: [
    // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
    // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
    'plugin:vue/essential'
  ],
  // required to lint *.vue files
  plugins: [
    'vue'
  ],
  // add your custom rules here
  rules: {}
}

```

I already attempted `/yarn add eslint-config-vue` but that doesn't seem to have changed things.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2454">#c2454</a>)</em></sub></div>

**Comment by kkitay** [comment]
Pls note that I would rather have some linting instead of just removing the linting block altogether.

**Comment by NicoPennec** [comment]
I can't reproduce :-/

my workflow:
```
vue init nuxt-community/starter-template test
cd test
yarn
yarn dev
```

**Comment by volodalexey** [comment]
I had the same from starter template.
Solved with additional `options` line:
```
  build: {
    /*
    ** Run ESLint on save
    */
    extend (config, { isDev, isClient }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/,
          options: {
            configFile: '.eslintrc.js'
          }
        })
      }
    }
  },
```
