### ISSUE TITLE
Nuxt cannot initialize

### ISSUE THREAD

**Issue by padmaseenivasan** [nuxt/nuxt.js#2862]
async ready() {
        ^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Note:** node version is 8.9.4 npm version is 5.6.0

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2486">#c2486</a>)</em></sub></div>

**Comment by sourcoin** [comment]
Fresh install same issue.

**Comment by rkgarcia** [comment]
Some news about this?

**Comment by rkgarcia** [comment]
Minimum requirements
[https://github.com/nuxt/nuxt.js/blob/dev/package.json#L53](https://github.com/nuxt/nuxt.js/blob/dev/package.json#L53)
```
  "engines": {
    "node": ">=8.0.0",
    "npm": ">=5.0.0"
  },
```

**Comment by lingjieding** [comment]
thanks @rkgarcia
