### ISSUE TITLE
Error using npm run build

### ISSUE THREAD

**Issue by atmar** [nuxt/nuxt.js#2897]
Hello,

I've used to use an older version of nuxt (pre 1.0.0) and after updating to the latest version, I am unable to  run npm run build. Node version is 8.9.4, also tested latest 9.4.0. npm is 5.6.0. Same as #2649. Also using shared hosting (cpanel), but not using nvm.

```
91% additional chunk assets processinginternal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.fork (child_process.js:103:10)
    at fork (/home/devhome/home_frontend/node_modules/worker-farm/lib/fork.js:12:35)
    at Farm.startChild (/home/devhome/home_frontend/node_modules/worker-farm/lib/farm.js:106:16)
    at Farm.processQueue (/home/devhome/home_frontend/node_modules/worker-farm/lib/farm.js:279:10)
    at Farm.addCall (/home/devhome/home_frontend/node_modules/worker-farm/lib/farm.js:307:8)
    at Farm.<anonymous> (/home/devhome/home_frontend/node_modules/worker-farm/lib/farm.js:38:10)
    at _class.boundWorkers (/home/devhome/home_frontend/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:71:24)
    at enqueue (/home/devhome/home_frontend/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:96:17)
    at /home/devhome/home_frontend/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:116:11
    at Array.forEach (<anonymous>)
    at _class.runTasks (/home/devhome/home_frontend/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:94:13)
    at UglifyJsPlugin.optimizeFn (/home/devhome/home_frontend/node_modules/uglifyjs-webpack-plugin/dist/index.js:182:16)
    at next (/home/devhome/home_frontend/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.compilation.plugin (/home/devhome/home_frontend/node_modules/webpack/lib/ProgressPlugin.js:119:6)
    at Compilation.applyPluginsAsyncSeries (/home/devhome/home_frontend/node_modules/tapable/lib/Tapable.js:206:13)
    at applyPluginsAsync.err (/home/devhome/home_frontend/node_modules/webpack/lib/Compilation.js:663:10)
    at next (/home/devhome/home_frontend/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin.callback (/home/devhome/home_frontend/node_modules/webpack/lib/ProgressPlugin.js:115:6)
    at next (/home/devhome/home_frontend/node_modules/tapable/lib/Tapable.js:204:14)
node[23688]: pthread_create: Resource temporarily unavailable


```

**Comment by atmar** [comment]
Fixed it by using LVE manager to increase the memory and other resources. It was set to 1GB, which used to be enough, but not anymore. It used up to 2.5GB now while building.
