### ISSUE TITLE
mac 安装后运行dev，报错啦帮看下咋解决

### ISSUE THREAD

**Issue by felix668** [nuxt/nuxt.js#2958]
/Users/lichunxia/Desktop/work/2018/nuxtdemo/node_modules/nuxt/lib/core/middleware/nuxt.js:72
      const policies = this.options.render.csp.policies ? {...this.options.render.csp.policies} : null
                                                           ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/lichunxia/Desktop/work/2018/nuxtdemo/node_modules/nuxt/lib/core/renderer.js:19:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxtdemo@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxtdemo@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lichunxia/.npm/_logs/2018-03-07T03_29_09_100Z-debug.log

**Comment by fengjiel** [comment]
#2927

**Comment by fengjiel** [comment]
把node版本升级到8.6.0+ 就可以了。
