### ISSUE TITLE
Plugin“ “browser-sync” ” introduced does not take effect? How to deal with？

### ISSUE THREAD

**Issue by dajohnny** [nuxt/nuxt.js#2986]
used the nuxt starter template, the webpack browser-sync plugin was introduced into the nuxt.config.js file to run an error report. How do handle it ?

![image](https://user-images.githubusercontent.com/17939743/37240604-5e09ab86-2480-11e8-90ee-8c334de5afce.png)

```

/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/browser-sync/dist/public/init.js:20
            return args.cb(new Error("Instance: " + name + " is already running!"));
                        ^

TypeError: args.cb is not a function
    at Object.init (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/browser-sync/dist/public/init.js:20:25)
    at Compiler.compiler.plugin.stats (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/browser-sync-webpack-plugin/lib/BrowserSyncPlugin.js:47:28)
    at Compiler.applyPlugins (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/webpack/lib/Compiler.js:105:17)
    at compiler.emitRecords.err (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/webpack/lib/Compiler.js:79:19)
    at Compiler.emitRecords (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/webpack/lib/Compiler.js:371:38)
    at compiler.emitAssets.err (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/webpack/lib/Compiler.js:62:20)
    at applyPluginsAsyncSeries1.err (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/webpack/lib/Compiler.js:350:15)
    at /Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/async/dist/async.js:1050:13)
    at /Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/async/dist/async.js:958:16
    at MemoryFileSystem.writeFile (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/webpack/lib/Compiler.js:339:28)
    at require.forEach (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/webpack/lib/Compiler.js:345:12)
    at /Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/async/dist/async.js:1055:9)
    at eachOf (/Users/johnny/Codes/collect/nuxt/nuxt-origin/node_modules/async/dist/async.js:1103:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxt-origin@1.0.0 dev: `HOST=0.0.0.0 PORT=8083 nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nuxt-origin@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johnny/.npm/_logs/2018-03-10T09_29_16_402Z-debug.log


```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2588">#c2588</a>)</em></sub></div>

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
