### ISSUE TITLE
Cannot find module './lib/websocket'

### ISSUE THREAD

**Issue by samuells** [nuxt/nuxt.js#3079]
Hey,

I just updated nuxtjs (1.4.0) and all npm packages. And the result is that `npm run dev` doesn't work anymore. I am getting this:
````
module.js:544
    throw err;
    ^

Error: Cannot find module './lib/websocket'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/samuell/Wondrous/github/pidas-nlp/node_modules/ws/index.js:3:19)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/samuell/Wondrous/github/pidas-nlp/node_modules/webpack-bundle-analyzer/lib/viewer.js:104:17)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pidas-nlp@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pidas-nlp@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samuell/.npm/_logs/2018-03-21T15_44_27_461Z-debug.log
````
Any idea what it could be?

I am running `  mode: 'spa'`

**Comment by samuells** [comment]
I "fixed" it. I just removed project and clone/installed repo from scratch. Now everything is working as it should be. (I also slept on it... 😄  )

**Comment by LailaBouziani** [comment]
I have the same problem, did u find anny solution without remove project ?
