### ISSUE TITLE
第一次使用 Nuxt 坑太多

### ISSUE THREAD

**Issue by hsxiaoma** [nuxt/nuxt.js#310]
按官网示例来完成第一个 Nuxt 示例. 

在运行阶段, 报N个错误, 先是 babel 找不到, 然后又是一系列组件找不到, 难到非得一个一个安装吗?

即然都是依赖的必需组件, 为什么示例中的 package.json 中又没有依赖?

运行环境:  node: 6.9.4  npm: 3.1.0

请教高手解决. 到底要运行 nuxt 示例需要哪些必备的依赖组件? 给个依赖列表出来, 谢谢

**Comment by alexchopin** [comment]
Sorry, we don't speak Chinese. Issue have to be written in english only.

**Comment by leftjs** [comment]
nuxt 自身已经有了所有依赖， 不需要babel 等等

**Comment by hsxiaoma** [comment]
F:\dev\nodejs\vue\nuxt\starter-source>npm run dev

> nuxt-starter@1.0.0 dev F:\dev\nodejs\vue\nuxt\starter-source
> nuxt

module.js:471
    throw err;
    ^

Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.Object.defineProperty.value (F:\dev\nodejs\vue\nuxt\starter-source\node_modules\nuxt\dist\nuxt.js:92:18)
    at __webpack_require__ (F:\dev\nodejs\vue\nuxt\starter-source\node_modules\nuxt\dist\nuxt.js:21:30)
    at Object.<anonymous> (F:\dev\nodejs\vue\nuxt\starter-source\node_modules\nuxt\dist\nuxt.js:1908:84)
    at __webpack_require__ (F:\dev\nodejs\vue\nuxt\starter-source\node_modules\nuxt\dist\nuxt.js:21:30)
    at F:\dev\nodejs\vue\nuxt\starter-source\node_modules\nuxt\dist\nuxt.js:67:18
    at Object.<anonymous> (F:\dev\nodejs\vue\nuxt\starter-source\node_modules\nuxt\dist\nuxt.js:70:10)

**Comment by leftjs** [comment]
试试用 yarn  并且删掉node_modules 重新install 试试， 确实nuxt 自身提供了所有依赖 而且 regenerator 已经是nuxt 的默认插件选项 所以不可能存在没有的情况。

**Comment by hsxiaoma** [comment]
感谢 @leftjs , 使用 yarn 安装解决了问题.

**Comment by leftjs** [comment]
you are welcome :-)
