### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by oguzhanaslan** [nuxt/nuxt.js#315]
I am using an add-on. I have read the headlines of those who have encountered this error. But I could not produce a solution.

[Plugin Page ](https://github.com/surmon-china/vue-video-player)

<img width="604" alt="ekran resmi 2017-02-26 22 14 33" src="https://cloud.githubusercontent.com/assets/1280469/23342760/bc76ee40-fc68-11e6-8479-42e1934cd716.png">
<img width="517" alt="ekran resmi 2017-02-26 22 14 21" src="https://cloud.githubusercontent.com/assets/1280469/23342761/bc78657c-fc68-11e6-9092-f723c57b68ed.png">

Plugin Initial:
<img width="805" alt="ekran resmi 2017-02-26 22 14 13" src="https://cloud.githubusercontent.com/assets/1280469/23342762/bc79480c-fc68-11e6-8ba8-4dde3f688e20.png">

Message:
```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/oguzhan/dev/filmdili/filmdili-frontend/node_modules/vue-video-player/index.js:8:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.Object.defineProperty.value (__vue_ssr_bundle__:7275:18)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
```

**Comment by liyanlong** [comment]
**nuxt.config.js**
```js
module.exports = {
   plugins: ['plugin/vuex-router-sync']
}
```
**page.vue**
```js
if (process.BROWSER_BUILD) {
   const VideoPlayer = require('~plugins/vue-video-player')
   Vue.use(VideoPlayer)
}
```
Try it.
