### ISSUE TITLE
[edge] TypeError: Cannot read property 'rootDir' of undefined

### ISSUE THREAD

**Issue by bovas85** [nuxt/nuxt.js#3197]
### Version

[[nuxt-edge]](https://github.com/nuxt/nuxt.js/releases/tag/[nuxt-edge])

### Reproduction link

[https://antilophia-vue.nakedtesting.com/](https://antilophia-vue.nakedtesting.com/)

### Steps to reproduce

Installed nuxt-edge but can't make it work. I have no rootDir setup and using now for deployment.

Running npm run dev or npm run build locally produces this error:
```
/Users/developer2/Desktop/antilophia/node_modules/nuxt-edge/bin/common/utils.js:24
  if (typeof options.rootDir !== 'string') {
                     ^

TypeError: Cannot read property 'rootDir' of undefined
    at exports.loadNuxtConfig.argv (/Users/developer2/Desktop/antilophia/node_modules/nuxt-edge/bin/common/utils.js:24:22)
    at Object.<anonymous> (/Users/developer2/Desktop/antilophia/node_modules/nuxt-edge/bin/nuxt-dev:55:20)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/developer2/Desktop/antilophia/node_modules/nuxt-edge/bin/nuxt:43:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

### What is expected ?

it builds the project folders

### What is actually happening?

it produces an error

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6857">#c6857</a>)</em></sub></div>

**Comment by Imanullah** [comment]
updated and fixed

**Comment by bovas85** [comment]
Thanks, confirmed :)
