### ISSUE TITLE
npm run dev Error

### ISSUE THREAD

**Issue by cnhyk9527** [nuxt/nuxt.js#3272]
- Node Version:v8.0.0

- Npm Version:5.0.0

- nuxt:1.0.0

Error:
**> first@1.0.0 dev D:\nuxt\project
> nuxt

D:\nuxt\project\node_modules\nuxt\lib\core\middleware\nuxt.js:72
      const policies = this.options.render.csp.policies ? {...this.options.render.csp.policies} : null
                                                           ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\nuxt\project\node_modules\nuxt\lib\core\renderer.js:19:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! first@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the first@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LiuJIangshan\AppData\Roaming\npm-cache\_logs\2018-04-27T08_54_54_541Z-debug.log**

**Comment by cnhyk9527** [comment]
**It's Node version error.**

**Comment by cnhyk9527** [comment]
It's Node version error. NodeJS >= 8.3 supports spread operators natively.
