### ISSUE TITLE
[edge] nuxt doesnt launch if only production dependencies installed

### ISSUE THREAD

**Issue by aldarund** [nuxt/nuxt.js#3316]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[none](none)

### Steps to reproduce

yarn install --production=true
yarn start

It will fail with following error:
```
$ nuxt start
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'figures'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Dev\PycharmProjects\rasimplefront\t\node_modules\nuxt-edge\dist\nuxt.js:10:31)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Maybe there will be other modules if this one is added

### What is expected ?

no import error

### What is actually happening?

import error with module figures

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7043">#c7043</a>)</em></sub></div>

**Comment by aldarund** [comment]
It really matters for production deployments. For example with serverless lambda deployment only production packages uploaded to lambda, so it will lead to error figures manually added to project dependencies.

**Comment by aldarund** [comment]
@clarkdo tried now. It work now fine. Because right now there no import of figures at all in dist/nuxt.js. While in older build there was and it was causing this. I even have a copy of old one and here how it was looking dist/nuxt.js . Left one old edge build rigth recent edge build
https://i.imgur.com/lvHEZhS.png
