### ISSUE TITLE
[edge] nuxt stopped working on aws lambda since 2.0.0-25464211.1f0053c

### ISSUE THREAD

**Issue by aldarund** [nuxt/nuxt.js#3408]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/jeehyukwon/nuxt-edge-serverless-template](https://github.com/jeehyukwon/nuxt-edge-serverless-template)

### Steps to reproduce

2.0.0-25459710.0d0d83c - works fine
2.0.0-25464211.1f0053c and up ( 2.0.0-25465851.937ce61 at the moment of reporting issue) -> not working
Error says pretty much nothing ...

```
Unable to import module 'handler': Error
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/node_modules/express/lib/router/index.js:16:13)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
```
Or 
```
Unable to import module 'handler': Error
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/node_modules/express/lib/router/route.js:19:15)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/node_modules/express/lib/router/index.js:16:13)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
```

My handler.js

```
const { Nuxt } = require('nuxt-edge')
const serverless = require('serverless-http')
const express = require('express')
const nuxtConfig = require('./nuxt.config')

const config = { dev: false, ...nuxtConfig }
const nuxt = new Nuxt(config)

const app = express()
app.use((req, res) => setTimeout(() => nuxt.render(req, res), 0))

exports.render = serverless(app)
```
I`m pretty much use this template : https://github.com/jeehyukwon/nuxt-edge-serverless-template

As soon as i go back to 2.0.0-25459710.0d0d83c everything works fine. Anything higher - not working on aws lambda.
Locally and with local emulation of lambda all works fine.

I tried to revert that minify code locally but it doesnt seem to help. So i suspect its something with dependencies updated in that build.
@pi0 any ideas?

### What is expected ?

no errors :)

### What is actually happening?

import error

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7192">#c7192</a>)</em></sub></div>

**Comment by aldarund** [comment]
Ok, not exactly nuxt problem.
For some reason when updating to from 2.0.0-25464211.1f0053c to any version higher following command that is used for packaging needed packages for lambda

```npm ls --production=true ```

wasnt including methods package.

But after removing node_modules and reinstalling it from scratch without using 2.0.0-25464211.1f0053c straight 2.0.0-25465851.937ce61 it started to include that package.
Kind of strange.

**Comment by Atinux** [comment]
Thanks @aldarund
