### ISSUE TITLE
Unable to install nuxt.js

### ISSUE THREAD

**Issue by e200** [nuxt/nuxt.js#3414]
`npm i nuxt --save`

npm WARN deprecated postcss-cssnext@3.1.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https:/
/moox.io/blog/deprecating-cssnext/
npm ERR! Unexpected end of JSON input while parsing near '...t":"^3.0.2","broccoli'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/**/.npm/_logs/**-debug.log

**Comment by e200** [comment]
eleandro@e200:~$ cat /home/**/.npm/_logs/2018-06-04T12_01_03_775Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'nuxt' ]
2 info using npm@5.6.0
3 info using node@v10.2.1
4 verbose npm-session e66bd56632945adc
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 http://registry.npmjs.org/nuxt 6682ms (from cache)
8 silly pacote tag manifest for nuxt@latest fetched in 6719ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule nuxt@1.4.0 checking installable status
14 http fetch GET 200 http://registry.npmjs.org/@nuxtjs%2fyouch 55ms attempt #2 (from cache)
15 silly pacote range manifest for @nuxtjs/youch@^4.2.3 fetched in 58ms
16 silly resolveWithNewModule @nuxtjs/youch@4.2.3 checking installable status
17 http fetch GET 304 http://registry.npmjs.org/ansi-html 167ms (from cache)
18 silly pacote range manifest for ansi-html@^0.0.7 fetched in 168ms
19 silly resolveWithNewModule ansi-html@0.0.7 checking installable status
20 http fetch GET 200 http://registry.npmjs.org/connect 4ms (from cache)
21 silly fetchPackageMetaData error for connect@^3.6.5 Unexpected end of JSON input while parsing near '...1.1","negotiator":"0.'
22 http fetch GET 200 http://registry.npmjs.org/css-hot-loader 12ms (from cache)
23 silly fetchPackageMetaData error for css-hot-loader@^1.3.7 Unexpected end of JSON input while parsing near '...72e51","tarball":"htt'
24 http fetch GET 200 http://registry.npmjs.org/css-loader 7ms (from cache)
25 silly pacote range manifest for css-loader@^0.28.9 fetched in 10ms
26 silly resolveWithNewModule css-loader@0.28.11 checking installable status
27 http fetch GET 200 http://registry.npmjs.org/debug 3ms (from cache)
28 silly fetchPackageMetaData error for debug@^3.1.0 Unexpected end of JSON input while parsing near '...asShrinkwrap":false,"'
29 http fetch GET 200 http://registry.npmjs.org/es6-promise 1ms (from cache)
30 silly fetchPackageMetaData error for es6-promise@^4.2.4 Unexpected end of JSON input while parsing near '...t":"^3.0.2","broccoli'
31 http fetch GET 304 http://registry.npmjs.org/babel-core 256ms (from cache)
32 silly pacote range manifest for babel-core@^6.26.0 fetched in 262ms
33 silly resolveWithNewModule babel-core@6.26.3 checking installable status
34 http fetch GET 304 http://registry.npmjs.org/babel-preset-vue-app 285ms (from cache)
35 silly pacote range manifest for babel-preset-vue-app@^2.0.0 fetched in 286ms
36 silly resolveWithNewModule babel-preset-vue-app@2.0.0 checking installable status
37 http fetch GET 304 http://registry.npmjs.org/caniuse-lite 288ms (from cache)
38 silly pacote range manifest for caniuse-lite@^1.0.30000808 fetched in 291ms
39 silly resolveWithNewModule caniuse-lite@1.0.30000847 checking installable status
40 http fetch GET 304 http://registry.npmjs.org/chokidar 296ms (from cache)
41 silly pacote range manifest for chokidar@^2.0.1 fetched in 298ms
42 silly resolveWithNewModule chokidar@2.0.3 checking installable status
43 http fetch GET 304 http://registry.npmjs.org/autoprefixer 312ms (from cache)
44 silly pacote range manifest for autoprefixer@^7.2.5 fetched in 316ms
45 silly resolveWithNewModule autoprefixer@7.2.6 checking installable status
46 http fetch GET 304 http://registry.npmjs.org/clone 322ms (from cache)
47 silly pacote range manifest for clone@^2.1.1 fetched in 324ms
48 silly resolveWithNewModule clone@2.1.1 checking installable status
49 http fetch GET 304 http://registry.npmjs.org/chalk 342ms (from cache)
50 silly pacote range manifest for chalk@^2.3.1 fetched in 345ms
51 silly resolveWithNewModule chalk@2.4.1 checking installable status
52 http fetch GET 304 http://registry.npmjs.org/compression 300ms (from cache)
53 silly pacote range manifest for compression@^1.7.1 fetched in 303ms
54 silly resolveWithNewModule compression@1.7.2 checking installable status
55 http fetch GET 304 http://registry.npmjs.org/etag 155ms (from cache)
56 silly pacote range manifest for etag@^1.8.1 fetched in 164ms
57 silly resolveWithNewModule etag@1.8.1 checking installable status
58 http fetch GET 304 http://registry.npmjs.org/extract-text-webpack-plugin 120ms (from cache)
59 silly pacote range manifest for extract-text-webpack-plugin@^3.0.2 fetched in 124ms
60 silly resolveWithNewModule extract-text-webpack-plugin@3.0.2 checking installable status
61 http fetch GET 304 http://registry.npmjs.org/file-loader 108ms (from cache)
62 silly pacote range manifest for file-loader@^1.1.6 fetched in 109ms
63 silly resolveWithNewModule file-loader@1.1.11 checking installable status
64 http fetch GET 304 http://registry.npmjs.org/fresh 109ms (from cache)
65 silly pacote range manifest for fresh@^0.5.2 fetched in 110ms
66 silly resolveWithNewModule fresh@0.5.2 checking installable status
67 http fetch GET 304 http://registry.npmjs.org/friendly-errors-webpack-plugin 114ms (from cache)
68 silly pacote range manifest for friendly-errors-webpack-plugin@^1.6.1 fetched in 116ms
69 silly resolveWithNewModule friendly-errors-webpack-plugin@1.7.0 checking installable status
70 http fetch GET 304 http://registry.npmjs.org/fs-extra 134ms (from cache)
71 http fetch GET 304 http://registry.npmjs.org/hash-sum 103ms (from cache)
72 http fetch GET 304 http://registry.npmjs.org/glob 121ms (from cache)
73 silly pacote range manifest for fs-extra@^5.0.0 fetched in 138ms
74 silly resolveWithNewModule fs-extra@5.0.0 checking installable status
75 silly pacote range manifest for hash-sum@^1.0.2 fetched in 107ms
76 silly resolveWithNewModule hash-sum@1.0.2 checking installable status
77 silly pacote range manifest for glob@^7.1.2 fetched in 129ms
78 silly resolveWithNewModule glob@7.1.2 checking installable status
79 http fetch GET 304 http://registry.npmjs.org/html-minifier 134ms (from cache)
80 silly pacote range manifest for html-minifier@^3.5.9 fetched in 139ms
81 silly resolveWithNewModule html-minifier@3.5.16 checking installable status
82 http fetch GET 304 http://registry.npmjs.org/launch-editor-middleware 109ms (from cache)
83 http fetch GET 304 http://registry.npmjs.org/launch-editor 119ms (from cache)
84 silly pacote range manifest for launch-editor-middleware@^2.2.1 fetched in 111ms
85 silly resolveWithNewModule launch-editor-middleware@2.2.1 checking installable status
86 http fetch GET 304 http://registry.npmjs.org/html-webpack-plugin 135ms (from cache)
87 silly pacote range manifest for launch-editor@^2.2.1 fetched in 123ms
88 silly resolveWithNewModule launch-editor@2.2.1 checking installable status
89 http fetch GET 304 http://registry.npmjs.org/lodash 109ms (from cache)
90 http fetch GET 304 http://registry.npmjs.org/lru-cache 93ms (from cache)
91 silly pacote range manifest for html-webpack-plugin@^2.30.1 fetched in 143ms
92 silly resolveWithNewModule html-webpack-plugin@2.30.1 checking installable status
93 silly pacote range manifest for lodash@^4.17.5 fetched in 115ms
94 silly resolveWithNewModule lodash@4.17.10 checking installable status
95 silly pacote range manifest for lru-cache@^4.1.1 fetched in 102ms
96 silly resolveWithNewModule lru-cache@4.1.3 checking installable status
97 http fetch GET 304 http://registry.npmjs.org/memory-fs 84ms (from cache)
98 silly pacote range manifest for memory-fs@^0.4.1 fetched in 85ms
99 silly resolveWithNewModule memory-fs@0.4.1 checking installable status
100 http fetch GET 304 http://registry.npmjs.org/opencollective 93ms (from cache)
101 silly pacote range manifest for opencollective@^1.0.3 fetched in 94ms
102 silly resolveWithNewModule opencollective@1.0.3 checking installable status
103 http fetch GET 304 http://registry.npmjs.org/minimist 100ms (from cache)
104 silly pacote range manifest for minimist@^1.2.0 fetched in 101ms
105 silly resolveWithNewModule minimist@1.2.0 checking installable status
106 http fetch GET 304 http://registry.npmjs.org/postcss 77ms (from cache)
107 silly pacote range manifest for postcss@^6.0.17 fetched in 82ms
108 silly resolveWithNewModule postcss@6.0.22 checking installable status
109 http fetch GET 304 http://registry.npmjs.org/postcss-import 81ms (from cache)
110 silly pacote range manifest for postcss-import@^11.1.0 fetched in 83ms
111 silly resolveWithNewModule postcss-import@11.1.0 checking installable status
112 http fetch GET 304 http://registry.npmjs.org/postcss-import-resolver 87ms (from cache)
113 silly pacote range manifest for postcss-import-resolver@^1.1.0 fetched in 91ms
114 silly resolveWithNewModule postcss-import-resolver@1.1.0 checking installable status
115 http fetch GET 304 http://registry.npmjs.org/postcss-cssnext 108ms (from cache)
116 silly pacote range manifest for postcss-cssnext@^3.1.0 fetched in 112ms
117 warn deprecated postcss-cssnext@3.1.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
118 silly resolveWithNewModule postcss-cssnext@3.1.0 checking installable status
119 http fetch GET 304 http://registry.npmjs.org/postcss-loader 116ms (from cache)
120 silly pacote range manifest for postcss-loader@^2.1.0 fetched in 121ms
121 silly resolveWithNewModule postcss-loader@2.1.5 checking installable status
122 http fetch GET 304 http://registry.npmjs.org/postcss-url 125ms (from cache)
123 silly pacote range manifest for postcss-url@^7.3.0 fetched in 131ms
124 silly resolveWithNewModule postcss-url@7.3.2 checking installable status
125 http fetch GET 304 http://registry.npmjs.org/pretty-error 116ms (from cache)
126 silly pacote range manifest for pretty-error@^2.1.1 fetched in 118ms
127 silly resolveWithNewModule pretty-error@2.1.1 checking installable status
128 http fetch GET 304 http://registry.npmjs.org/progress-bar-webpack-plugin 104ms (from cache)
129 silly pacote range manifest for progress-bar-webpack-plugin@^1.10.0 fetched in 108ms
130 silly resolveWithNewModule progress-bar-webpack-plugin@1.11.0 checking installable status
131 http fetch GET 304 http://registry.npmjs.org/semver 119ms (from cache)
132 silly pacote range manifest for semver@^5.5.0 fetched in 121ms
133 silly resolveWithNewModule semver@5.5.0 checking installable status
134 http fetch GET 304 http://registry.npmjs.org/serialize-javascript 107ms (from cache)
135 silly pacote range manifest for serialize-javascript@^1.4.0 fetched in 108ms
136 silly resolveWithNewModule serialize-javascript@1.5.0 checking installable status
137 http fetch GET 304 http://registry.npmjs.org/serve-static 103ms (from cache)
138 silly pacote range manifest for serve-static@^1.13.2 fetched in 104ms
139 silly resolveWithNewModule serve-static@1.13.2 checking installable status
140 http fetch GET 304 http://registry.npmjs.org/server-destroy 96ms (from cache)
141 silly pacote range manifest for server-destroy@^1.0.1 fetched in 97ms
142 silly resolveWithNewModule server-destroy@1.0.1 checking installable status
143 http fetch GET 304 http://registry.npmjs.org/source-map 101ms (from cache)
144 silly pacote range manifest for source-map@^0.7.0 fetched in 104ms
145 silly resolveWithNewModule source-map@0.7.3 checking installable status
146 http fetch GET 304 http://registry.npmjs.org/style-resources-loader 99ms (from cache)
147 silly pacote range manifest for style-resources-loader@^1.0.0 fetched in 100ms
148 silly resolveWithNewModule style-resources-loader@1.1.0 checking installable status
149 http fetch GET 304 http://registry.npmjs.org/uglifyjs-webpack-plugin 93ms (from cache)
150 silly pacote range manifest for uglifyjs-webpack-plugin@^1.1.8 fetched in 96ms
151 silly resolveWithNewModule uglifyjs-webpack-plugin@1.2.5 checking installable status
152 http fetch GET 304 http://registry.npmjs.org/upath 99ms (from cache)
153 silly pacote range manifest for upath@^1.0.2 fetched in 101ms
154 silly resolveWithNewModule upath@1.1.0 checking installable status
155 http fetch GET 304 http://registry.npmjs.org/url-loader 99ms (from cache)
156 silly pacote range manifest for url-loader@^0.6.2 fetched in 103ms
157 silly resolveWithNewModule url-loader@0.6.2 checking installable status
158 http fetch GET 304 http://registry.npmjs.org/vue-meta 90ms (from cache)
159 silly pacote range manifest for vue-meta@^1.4.3 fetched in 92ms
160 silly resolveWithNewModule vue-meta@1.5.0 checking installable status
161 http fetch GET 304 http://registry.npmjs.org/vue 116ms (from cache)
162 http fetch GET 304 http://registry.npmjs.org/vue-loader 113ms (from cache)
163 silly pacote range manifest for vue@^2.5.13 fetched in 133ms
164 silly resolveWithNewModule vue@2.5.16 checking installable status
165 silly pacote version manifest for vue-loader@13.7.0 fetched in 131ms
166 silly resolveWithNewModule vue-loader@13.7.0 checking installable status
167 http fetch GET 304 http://registry.npmjs.org/vue-template-compiler 126ms (from cache)
168 http fetch GET 304 http://registry.npmjs.org/vue-router 163ms (from cache)
169 http fetch GET 304 http://registry.npmjs.org/vuex 118ms (from cache)
170 http fetch GET 304 http://registry.npmjs.org/vue-server-renderer 147ms (from cache)
171 silly pacote range manifest for vue-template-compiler@^2.5.13 fetched in 132ms
172 silly resolveWithNewModule vue-template-compiler@2.5.16 checking installable status
173 silly pacote range manifest for vue-router@^3.0.1 fetched in 169ms
174 silly resolveWithNewModule vue-router@3.0.1 checking installable status
175 silly pacote range manifest for vuex@^3.0.1 fetched in 124ms
176 silly resolveWithNewModule vuex@3.0.1 checking installable status
177 silly pacote range manifest for vue-server-renderer@^2.5.13 fetched in 153ms
178 silly resolveWithNewModule vue-server-renderer@2.5.16 checking installable status
179 http fetch GET 304 http://registry.npmjs.org/webpack 133ms (from cache)
180 silly pacote range manifest for webpack@^3.11.0 fetched in 144ms
181 silly resolveWithNewModule webpack@3.12.0 checking installable status
182 http fetch GET 304 http://registry.npmjs.org/webpack-bundle-analyzer 142ms (from cache)
183 silly pacote range manifest for webpack-bundle-analyzer@^2.10.0 fetched in 145ms
184 silly resolveWithNewModule webpack-bundle-analyzer@2.13.1 checking installable status
185 http fetch GET 304 http://registry.npmjs.org/webpack-dev-middleware 126ms (from cache)
186 silly pacote range manifest for webpack-dev-middleware@^2.0.5 fetched in 131ms
187 silly resolveWithNewModule webpack-dev-middleware@2.0.6 checking installable status
188 http fetch GET 304 http://registry.npmjs.org/webpack-hot-middleware 112ms (from cache)
189 silly pacote range manifest for webpack-hot-middleware@^2.21.0 fetched in 116ms
190 silly resolveWithNewModule webpack-hot-middleware@2.22.2 checking installable status
191 http fetch GET 304 http://registry.npmjs.org/webpack-node-externals 117ms (from cache)
192 silly pacote range manifest for webpack-node-externals@^1.6.0 fetched in 118ms
193 silly resolveWithNewModule webpack-node-externals@1.7.2 checking installable status
194 http fetch GET 304 http://registry.npmjs.org/babel-loader 6275ms (from cache)
195 silly pacote range manifest for babel-loader@^7.1.2 fetched in 6278ms
196 silly resolveWithNewModule babel-loader@7.1.4 checking installable status
197 silly saveTree bcs-app@0.0.1
197 silly saveTree └─┬ nuxt@1.4.0
197 silly saveTree   ├── @nuxtjs/youch@4.2.3
197 silly saveTree   ├── ansi-html@0.0.7
197 silly saveTree   ├─┬ autoprefixer@7.2.6
197 silly saveTree   │ ├── caniuse-lite@1.0.30000847
197 silly saveTree   │ └─┬ postcss@6.0.22
197 silly saveTree   │   └── chalk@2.4.1
197 silly saveTree   ├─┬ babel-core@6.26.3
197 silly saveTree   │ └── lodash@4.17.10
197 silly saveTree   ├── babel-loader@7.1.4
197 silly saveTree   ├── babel-preset-vue-app@2.0.0
197 silly saveTree   ├── caniuse-lite@1.0.30000847
197 silly saveTree   ├── chalk@2.4.1
197 silly saveTree   ├─┬ chokidar@2.0.3
197 silly saveTree   │ └── upath@1.1.0
197 silly saveTree   ├── clone@2.1.1
197 silly saveTree   ├── compression@1.7.2
197 silly saveTree   ├── css-loader@0.28.11
197 silly saveTree   ├── etag@1.8.1
197 silly saveTree   ├── extract-text-webpack-plugin@3.0.2
197 silly saveTree   ├── file-loader@1.1.11
197 silly saveTree   ├── fresh@0.5.2
197 silly saveTree   ├── friendly-errors-webpack-plugin@1.7.0
197 silly saveTree   ├── fs-extra@5.0.0
197 silly saveTree   ├── glob@7.1.2
197 silly saveTree   ├── hash-sum@1.0.2
197 silly saveTree   ├── html-minifier@3.5.16
197 silly saveTree   ├─┬ html-webpack-plugin@2.30.1
197 silly saveTree   │ └── pretty-error@2.1.1
197 silly saveTree   ├─┬ launch-editor-middleware@2.2.1
197 silly saveTree   │ └── launch-editor@2.2.1
197 silly saveTree   ├── launch-editor@2.2.1
197 silly saveTree   ├── lodash@4.17.10
197 silly saveTree   ├── lru-cache@4.1.3
197 silly saveTree   ├── memory-fs@0.4.1
197 silly saveTree   ├── minimist@1.2.0
197 silly saveTree   ├── opencollective@1.0.3
197 silly saveTree   ├── postcss-cssnext@3.1.0
197 silly saveTree   ├── postcss-import-resolver@1.1.0
197 silly saveTree   ├── postcss-import@11.1.0
197 silly saveTree   ├── postcss-loader@2.1.5
197 silly saveTree   ├── postcss-url@7.3.2
197 silly saveTree   ├── postcss@6.0.22
197 silly saveTree   ├── pretty-error@2.1.1
197 silly saveTree   ├── progress-bar-webpack-plugin@1.11.0
197 silly saveTree   ├── semver@5.5.0
197 silly saveTree   ├── serialize-javascript@1.5.0
197 silly saveTree   ├── serve-static@1.13.2
197 silly saveTree   ├── server-destroy@1.0.1
197 silly saveTree   ├── source-map@0.7.3
197 silly saveTree   ├── style-resources-loader@1.1.0
197 silly saveTree   ├── uglifyjs-webpack-plugin@1.2.5
197 silly saveTree   ├── upath@1.1.0
197 silly saveTree   ├── url-loader@0.6.2
197 silly saveTree   ├── vue-loader@13.7.0
197 silly saveTree   ├── vue-meta@1.5.0
197 silly saveTree   ├── vue-router@3.0.1
197 silly saveTree   ├── vue-server-renderer@2.5.16
197 silly saveTree   ├── vue-template-compiler@2.5.16
197 silly saveTree   ├── vue@2.5.16
197 silly saveTree   ├── vuex@3.0.1
197 silly saveTree   ├── webpack-bundle-analyzer@2.13.1
197 silly saveTree   ├── webpack-dev-middleware@2.0.6
197 silly saveTree   ├── webpack-hot-middleware@2.22.2
197 silly saveTree   ├── webpack-node-externals@1.7.2
197 silly saveTree   └── webpack@3.12.0
198 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...1.1","negotiator":"0.'
198 verbose stack     at JSON.parse (<anonymous>)
198 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
198 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
198 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
199 verbose cwd /media/eleandro/code/Projectos/bcs/app
200 verbose Linux 4.13.0-41-generic
201 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "nuxt"
202 verbose node v10.2.1
203 verbose npm  v5.6.0
204 error Unexpected end of JSON input while parsing near '...1.1","negotiator":"0.'
205 verbose exit [ 1, true ]
