### ISSUE TITLE
nuxt dev - 2.0.0

### ISSUE THREAD

**Issue by vankooch** [nuxt/nuxt.js#3577]
### Version

[v2.0](https://github.com/nuxt.js/releases/tag/v2.0)

### Reproduction link

[https://github.com/vankooch/nuxt2-typescript-template/tree/master/template](https://github.com/vankooch/nuxt2-typescript-template/tree/master/template)

### Steps to reproduce

```shell
git clone https://github.com/vankooch/nuxt2-typescript-template.git
cd  nuxt2-typescript-template/template
yarn install
yarn dev
```shell

### What is expected ?

Nuxt should run in development mode (server + watch)

### What is actually happening?

```javascript
error TypeError: Cannot read property '_buildStatus' of undefined
  [object Promise]
  at build (/Users/xyz/github/nuxt2-typescript-template/template/node_modules/nuxt/lib/builder/builder.js:99:14)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```javascript

### Additional comments?

I've tried the recent version from github (2.0.0) and tried to setup a template for typescript and scss.
I managed to get scss, ts-loader and webpack 4 configured. 
All nuxt functions do work expect dev. So nuxt, nuxt build, nuxt generate and nuxt start do work.

I've looked inside the failing file:

```lib/builder/builder.js```

The problem is that inside the async build method ```this```  is not recognized, so all work will fail.  
I'm not sure if the scope of the Promis in ```bin/nuxt-dev``` works as expected.

I'm on mac os x 10.13, node v10.1.0


<!--cmty--><!--cmty_prevent_hook-->
<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7431">#c7431</a>)</em></sub></div>

**Comment by manniL** [comment]
Have you tried it with a minimal `nuxt-edge` build?
I ran one recently and had no problems :thinking:

**Comment by vankooch** [comment]
Thx mate, indeed the nuxt-edge version is working without problems.

**Comment by manniL** [comment]
Happy it works now :+1: 

Be sure to close the issue/mark it as resolved :relaxed:

**Comment by vankooch** [comment]
I'm not sure if I have the rights toclose this.
