### ISSUE TITLE
Unexpected token nuxt:3

### ISSUE THREAD

**Issue by ghprod** [nuxt/nuxt.js#36]
Hi today i try nuxt by running this command

```
vue init nuxt/starter nuxt
cd nuxt
yarn install
npm run dev
```

And getting this error

```
$ npm run dev

> nuxt@1.0.0 dev /home/ferri/Developments/web/nuxt
> nuxt

/home/ferri/Developments/web/nuxt/node_modules/nuxt/bin/nuxt:3
const { join } = require('path')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

This is my system

```
$ npm --version
3.10.9

$ yarn --version
0.15.1

OS Freya / Ubuntu 14.04 64 bit
```

Thanks

**Comment by Bin4ryIO** [comment]
+1.

I ran:
```
vue init nuxt/starter myproject
cd nuxt
npm i
npm run dev
```

Error:
```
const { join } = require('path')
      ^
```

Env:
```
$ npm --version
4.0.3

Windows 10 Pro x64
```

**Comment by Atinux** [comment]
Thanks guys for trying Nuxt.js

What is your version of node.js?

**Comment by Bin4ryIO** [comment]
Updated nodejs from v4 to v6.x, it worked.

**Comment by frankmichel** [comment]
I am getting the same error... using Node v5.12.0 on Mac OS X 10.12

**Comment by ghprod** [comment]
mine

```
$ node -v
v4.6.0
```

Should i upgrade to v6?

**Comment by Atinux** [comment]
In the meantime upgrade to v6, I will work on make it compatible starting from node v4

**Comment by ghprod** [comment]
After upgrade to v6 LTS, then its working..

```
$ node -v
v6.9.1
```

So the solution just upgrade nodejs :+1: 

closed .. Thanks

**Comment by frankmichel** [comment]
I wouldn't consider this "closed" as long as it's not working with Node v4.x (which is stated as the minimum required version for nuxt.js)

**Comment by Atinux** [comment]
You're right. I did not close this issue but the todo is on the list :)

**Comment by Atinux** [comment]
It's now fixed in the [v0.8.8](https://github.com/nuxt/nuxt.js/releases/tag/v0.8.8)

**Comment by jeck5895** [comment]
I'm getting an error 
C:\Users\Jerick\Desktop\WEB-APPS\vue-nuxt\vue-nuxt-app\node_modules\nuxt\lib\core\module.js:14
  async ready() {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Jerick\Desktop\WEB-APPS\vue-nuxt\vue-nuxt-app\node_modules\nuxt\lib\co                                                                                      re\index.js:2:16)

steps to reproduce:
vue init nuxt-community/starter-template vue-nuxt-app
npm install
npm run dev

Node version 6.11.3 Windows 10

**Comment by NicoPennec** [comment]
@jeck5895  Nuxt needs Node.js  >= 8
