### ISSUE TITLE
use ant-design-vue report an error

### ISSUE THREAD

**Issue by lujunpeng** [nuxt/nuxt.js#3688]
{ D:\qdWEB\src\official\node_modules\_ant-design-vue@1.0.2@ant-design-vue\lib\style\index.css:6
@font-face {
^

SyntaxError: Invalid or unexpected token

**Comment by lujunpeng** [comment]
Use babel-plugin-import
"plugins": [["import", { "libraryName": "ant-design-vue", "style": "css" }]]


import { Button } from 'ant-design-vue';
Vue.component(Button.name, Button)

This will give an error

**Comment by lujunpeng** [comment]
Use babel-plugin-import
"plugins": [["import", { "libraryName": "ant-design-vue", "style": "css" }]]


import { Button } from 'ant-design-vue';
Vue.component(Button.name, Button)

This will give an error

**Comment by baoyadong** [comment]
@lujunpeng 我这边也是直接引入ant-design-vue报错：
`import Antd from 'ant-design-vue'
import 'ant-design-vue/dist/antd.css'
import '../assets/css/variable.less'
Vue.use(Antd)`
nuxt.config.js引入
`plugins: [
      '~plugins/antd-ui.js'
    ],`
也是直接报错：{ ReferenceError: Antd is not defined }
不知道是什么原因?大神们，赶紧看看吧

**Comment by lujunpeng** [comment]
@paulgv 
Global introduction no problem
Use babel-plugin-import Report an error
use muse-ui will also be errors
nuxt.config.js

babel: { 
      "plugins": [
        [
          "import",
          {
            "libraryName": "muse-ui",
            "libraryDirectory": "lib",
            "camel2DashComponentName": false
          }
        ]
      ]
    },
plugins[{
    src: '~/plugins/muse-ui',
    ssr: true
  }]
css:[{
      src: 'muse-ui/lib/styles/base.less',
      lang: 'less'
    },
    {
      src: 'muse-ui/lib/styles/theme.less',
      lang: 'less'
    }]

muse-ui.js

import Vue from 'vue'
import { Button, Select } from 'muse-ui'
export default () => {
  Vue.use(Button).use(Select)
}


{ D:\vueApp\vue-pc\node_modules\_muse-ui@3.0.0@muse-ui\lib\styles\components\button.less:1
(function (exports, require, module, __filename, __dirname) { @import "../import.less";
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\vueApp\vue-pc\node_modules\_muse-ui@3.0.0@muse-ui\lib\Button\index.js:7:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17) statusCode: 500, name: 'SyntaxError' }
