### ISSUE TITLE
[edge] Server-side rendering get vue-loader error

### ISSUE THREAD

**Issue by jackiecookie** [nuxt/nuxt.js#3740]
### Version

[edge](https://github.com/nuxt.js/releases/tag/edge)

### Reproduction link

[https://github.com/imow-frontend/imow/tree/feat-nuxt%40edge](https://github.com/imow-frontend/imow/tree/feat-nuxt%40edge)

### Steps to reproduce

Running nuxt@edge on Node 8.9.4 and Yarn 1.5.1:

1: run `yarn dev` to start the development server which builds on express .everything compiles susses. the Server listening on http://127.0.0.1:3000.
2: get the http://127.0.0.1:3000 you'll see the following error.

```
× error Error: Module build failed (from ./node_modules/vue-loader/index.js):
  TypeError: Cannot read property 'vue' of undefined
  at Object.module.exports (C:\code\imow\node_modules\vue-loader\lib\loader.js:61:18)
  at Object../.nuxt/components/nuxt-error.vue (server-bundle.js:372:7)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module../.nuxt/index.js (server-bundle.js:509:84)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module../.nuxt/server.js (server-bundle.js:1024:64)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at server-bundle.js:118:18
  at Object.<anonymous> (server-bundle.js:121:10)
  at evaluateModule (C:\code\imow\node_modules\vue-server-renderer\build.js:8349:21)
  at C:\code\imow\node_modules\vue-server-renderer\build.js:8407:18
  at new Promise (<anonymous>)
  at C:\code\imow\node_modules\vue-server-renderer\build.js:8399:14
  at Object.renderToString (C:\code\imow\node_modules\vue-server-renderer\build.js:8575:9)
  at Renderer.renderRoute (C:\code\imow\node_modules\nuxt\lib\core\renderer.js:343:41)
  at Renderer.nuxtMiddleware (C:\code\imow\node_modules\nuxt\lib\core\middleware\nuxt.js:13:31)
  at call (C:\code\imow\node_modules\connect\index.js:239:7)
```

### What is expected ?

The server should not throw an error.

### What is actually happening?

Cannot read property 'vue' of undefined

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7580">#c7580</a>)</em></sub></div>

**Comment by Atinux** [comment]
Could you try:

```js
rm -rf node_modules/
npm install
```

And confirm that it is still hapenning?

**Comment by manniL** [comment]
Receiving a different error after cloning:

```

 ERROR  Failed to compile with 6 errors                               2:59:53 PM

These dependencies were not found:

* @/components/index/favoritePane.vue in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"plugins":[["component",{"libraryName":"element-ui","styleLibraryName":"~theme"}]],"presets":[["/home/mannil/rm-imow/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue
* @/components/index/floor.vue in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"plugins":[["component",{"libraryName":"element-ui","styleLibraryName":"~theme"}]],"presets":[["/home/mannil/rm-imow/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue
* @/components/orderConfirm/commodity/Commodity.vue in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"plugins":[["component",{"libraryName":"element-ui","styleLibraryName":"~theme"}]],"presets":[["/home/mannil/rm-imow/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/memberCenter/batchDeliver/orderConfirm.vue, ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"plugins":[["component",{"libraryName":"element-ui","styleLibraryName":"~theme"}]],"presets":[["/home/mannil/rm-imow/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/memberCenter/batchDeliver/applyBatchDeliver.vue and 1 other
* @/components/product/detail/NologinHead in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"plugins":[["component",{"libraryName":"element-ui","styleLibraryName":"~theme"}]],"presets":[["/home/mannil/rm-imow/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/product/_id.vue

To install them, you can run: npm install --save @/components/index/favoritePane.vue @/components/index/floor.vue @/components/orderConfirm/commodity/Commodity.vue @/components/product/detail/NologinHead
```

**Comment by galvez** [comment]
@Atinux @manniL this is happening for me also :(

**Comment by clarkdo** [comment]
@jackiecookie `nuxt-edge`已经升级至`vue-loader 15.x`, 你可以移除`vue-loader`依赖 (nuxt已经依赖vue-loader 15):

```bash
yarn remove vue-loader

// 或者

npm uninstall vue-loader
```
