### ISSUE TITLE
Error during $style injection on cached components

### ISSUE THREAD

**Issue by henriqemalheiros** [nuxt/nuxt.js#3868]
### Reproduction link

[https://github.com/henriqemalheiros/nuxt-cached-component-css-modules](https://github.com/henriqemalheiros/nuxt-cached-component-css-modules)

### Steps to reproduce

- `yarn install`
- `yarn run build`
- `yarn run start`
- Open `http://localhost:3000/`
- Refresh the page

The error is also reproducible in development mode with `yarn run dev`.

### What is expected ?

The app should render properly.

### What is actually happening?

```
× error TypeError: Cannot set property '$style' of undefined
  at injectStyles (components/CachedComponent.vue:8:0)
  at hook (node_modules/vue-loader/lib/runtime/componentNormalizer.js:53:0)
  at C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:7467:15
  at C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:2487:40
  at C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:7465:11
  at C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:2487:40
  at renderComponent (C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:7463:7)
  at RenderContext.renderNode (C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:7418:5)
  at RenderContext.next (C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:2436:14)
  at cachedWrite (C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:2295:9)
  at renderElement (C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:7656:5)
  at renderNode (C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:7420:5)
  at renderComponentInner (C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:7538:3)
  at renderComponent (C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:7502:5)
  at renderNode (C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:7418:5)
  at renderComponentInner (C:\[...]\nuxt-cached-component-css-modules\node_modules\vue-server-renderer\build.js:7538:3)
```

### Additional comments?

If you remove the `serverCacheKey` from the cached component and try again, the app renders properly.

Maybe a bug from vue-loader or vue-server-renderer? I couldn't find the time to create a repro without Nuxt.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7715">#c7715</a>)</em></sub></div>

**Comment by prog666** [comment]
it reproduces without nuxt

**Comment by danielroe** [comment]
This is a live issue for us as well. At the moment CSS modules and component caching are not compatible.

**Comment by manniL** [comment]
If it reproduces without nuxt as @prog666 said, it's no nuxt issue :|

**Comment by danielroe** [comment]
@prog666 - I've been unable to reproduce with a plain Vue SSR setup using CSS modules and component caching. Would you help me reproduce it?

**Comment by henriqemalheiros** [comment]
@manniL @danielroe it is reproducible without Nuxt. I created a new issue (vuejs/vue#9010) and I'm closing this one.

**Comment by manniL** [comment]
@henriqemalheiros Thanks for the effort!
