### ISSUE TITLE
HMR in Docker doesn't work as expected

### ISSUE THREAD

**Issue by djbingham** [nuxt/nuxt.js#3887]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/djbingham/nuxt-docker/tree/6356bbe17775cf41ae4dc2f1b7e666ebf111d667](https://github.com/djbingham/nuxt-docker/tree/6356bbe17775cf41ae4dc2f1b7e666ebf111d667)

**EDIT: Changed reproduction link to point to a specific commit, rather than latest, as the repo has been updated to Nuxt v2 which now works**

### Steps to reproduce

1. Install dependencies by running `script/prepare`.
2. Start the server with `script/dev` and wait for initial build to complete. The container log shows:
```
OPEN http://localhost:80
```

3. Go to `localhost` in a web browser. The page loads, showing the heading "Hello World!".
4. Edit `app/pages/index.vue`, removing the "!" to leave the heading as "Hello World". The container logs show compiling progress, then:
```
DONE  Compiled successfully in -10560ms
```

The browser automatically shows the updates page, as expected. However, *this is where weird things start to happen:*

5. Once the browser has updated, the container logs show an error below the previous "Compiled successfully" message:
```
  nuxt:render Rendering url / +32s
{ Error: Module build failed: Error: ENOENT: no such file or directory, open '/srv/app/pages/index.vue'
    at Object.44 (pages/index.js:8:7)
    at __webpack_require__ (webpack:/webpack/bootstrap 55191ef2777bf995a655:25:0)
    at process._tickCallback (internal/process/next_tick.js:68:7) statusCode: 500, name: 'NuxtServerError' }
  nuxt:render Rendering url /HNAP1/ +1s
{ statusCode: 404,
  path: '/HNAP1/',
  message: 'This page could not be found' }
```
6. Refresh the browser. The page is replaced with an error message:
```
render function or template not defined in component: anonymous
```
The container logs show:
```
  nuxt:render Rendering url / +6m
  nuxt:render Data fetching /: 0ms +0ms
{ Error: render function or template not defined in component: anonymous
    at normalizeRender (/srv/app/node_modules/vue-server-renderer/build.js:7407:13)
    at renderComponentInner (/srv/app/node_modules/vue-server-renderer/build.js:7531:3)
    at renderComponent (/srv/app/node_modules/vue-server-renderer/build.js:7502:5)
    at renderNode (/srv/app/node_modules/vue-server-renderer/build.js:7418:5)
    at renderComponentInner (/srv/app/node_modules/vue-server-renderer/build.js:7538:3)
    at renderComponent (/srv/app/node_modules/vue-server-renderer/build.js:7502:5)
    at renderNode (/srv/app/node_modules/vue-server-renderer/build.js:7418:5)
    at renderComponentInner (/srv/app/node_modules/vue-server-renderer/build.js:7538:3)
    at renderComponent (/srv/app/node_modules/vue-server-renderer/build.js:7502:5)
    at renderNode (/srv/app/node_modules/vue-server-renderer/build.js:7418:5)
    at renderComponentInner (/srv/app/node_modules/vue-server-renderer/build.js:7538:3)
    at renderComponent (/srv/app/node_modules/vue-server-renderer/build.js:7502:5)
    at RenderContext.renderNode (/srv/app/node_modules/vue-server-renderer/build.js:7418:5)
    at RenderContext.next (/srv/app/node_modules/vue-server-renderer/build.js:2436:14)
    at cachedWrite (/srv/app/node_modules/vue-server-renderer/build.js:2295:9)
    at renderElement (/srv/app/node_modules/vue-server-renderer/build.js:7656:5) statusCode: 500, name: 'NuxtServerError' }
```

7. Edit `app/pages/index.vue`, adding an "s" to make the heading "Hello worlds". The container logs show an error:
```
 ERROR  Failed to compile with 1 errors                                                                                                                          12:09:39 PM

 error  in ./pages/index.vue

Module build failed: Error: ENOENT: no such file or directory, open '/srv/app/pages/index.vue'

 @ ./.nuxt/router.js 8:9-75
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js
```

8. Refresh the browser. The updated page is displayed with an overlay showing the build error:
```
ERROR in ./pages/index.vue
Module build failed: Error: ENOENT: no such file or directory, open '/srv/app/pages/index.vue'
```

### What is expected ?

I expect compilation to succeed and the web page to update after each change to `app/pages/index.vue`.

### What is actually happening?

Errors occur either during compilation or on page refresh after each change, as described in the rep steps.

### Additional comments?

Please see the `script/dev` script in the linked GitHub repo to see how my Docker container is setup with the relevant ports exposed, etc. I've made the repo as simple as I can to eliminate any potential conflicts with other dependencies. I have no other containers on my development machine currently and have reproduced this issue several times.

I'm very grateful for any assistance that can be provided and will happily test suggested solutions.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7736">#c7736</a>)</em></sub></div>

**Comment by djbingham** [comment]
So, I guess no one has been able to reproduce this issue? This stopped me from using Nuxt for the time being, so I would really appreciate any pointers to how I might resolve this issue.

**Comment by manniL** [comment]
@djbingham Quoting @lbogdan here:

> Webpack's HMR bases its file change detection on a kernel filesystem feature, which doesn't work with host mounts inside a docker container.

Using [watchOptions](https://webpack.js.org/configuration/watch/#watchoptions-poll) (with `poll`) could help you. You can change the options directly through the `watchers.webpack` key in your `nuxt.config.js` ([docs](https://nuxtjs.org/api/configuration-watchers#webpack))

**Comment by djbingham** [comment]
Hi @manniL. Thank you for looking at this for me, although I think you misunderstood the issue. I'm already using the polling feature as you suggested and Webpack is detecting changes. The problem is with the builds that Webpack produces after it has detected a change.

This is the content of `nuxt.config.js` in the repository I linked above for reproducing the issue:
```
module.exports = {
    watchers: {
        webpack: {
          aggregateTimeout: 300,
          poll: 1000
        }
    }
}
```

**Comment by manniL** [comment]
@djbingham Can you retry it with the latest `nuxt-edge` build?

**Comment by djbingham** [comment]
Sure, I'll give it a go when I next have a spare half hour.

**Comment by djbingham** [comment]
`nuxt-edge` gives me a different issue. In case it helps, I've tried the latest `1.x` and `2.x` builds too.

**`nuxt:1.4.4`**
Exactly the same issues described above.

**`nuxt:2.2.0`**
Different issue - the following error appears in the Nuxt logs:
```
Error: Cannot find module '/srv/app/.nuxt/server.js'
  at webpackMissingModule (server-bundle.js:96:45)
  at Object.<anonymous> (server-bundle.js:96:144)
  at __webpack_require__ (server-bundle.js:21:30)
  at server-bundle.js:85:18
  at Object.<anonymous> (server-bundle.js:88:10)
  at evaluateModule (/srv/app/node_modules/vue-server-renderer/build.js:8349:21)
  at /srv/app/node_modules/vue-server-renderer/build.js:8407:18
  at new Promise (<anonymous>)
  at /srv/app/node_modules/vue-server-renderer/build.js:8399:14
  at Object.renderToString (/srv/app/node_modules/vue-server-renderer/build.js:8575:9)
  at Renderer.renderRoute (/srv/app/node_modules/nuxt/dist/nuxt.js:2074:41)
  at Renderer.nuxtMiddleware (/srv/app/node_modules/nuxt/dist/nuxt.js:1629:31)
  at call (/srv/app/node_modules/connect/index.js:239:7)
  at next (/srv/app/node_modules/connect/index.js:183:5)
  at SendStream.error (/srv/app/node_modules/serve-static/index.js:121:7)
  at SendStream.emit (events.js:182:13)
```
The web page also shows the same error:
```
NuxtServerError
Cannot find module '/srv/app/.nuxt/server.js'
```

**`nuxt-edge:latest`**
The following error is shown from the Client compiler and overlaid on the web page:
```
 ERROR  Failed to compile with 1 errors                                                                                       friendly-errors 14:07:39


 ERROR  in ./.nuxt/client.js                                                                                                  friendly-errors 14:07:39

Module build failed (from ./node_modules/babel-loader/lib/index.js):                                                          friendly-errors 14:07:39
Error: ENOENT: no such file or directory, open '/srv/app/node_modules/babel-loader/package.json'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:724:20)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/srv/app/node_modules/babel-loader/lib/index.js:25:13)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
                                                                                                                              friendly-errors 14:07:39
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr/client ./.nuxt/client.js
```

The details shown after compilation are:
```
✖ Client
  Compiled with some errors in 2.84s

✔ Server
  Compiled successfully in 4.81s

ℹ Waiting for file changes                                                                                                                    14:07:41

   ╭─────────────────────────────────────────────╮
   │                                             │
   │   Nuxt.js v2.3.0-25704699.e21301f           │
   │   Running in development mode (universal)   │
   │   Memory usage: 122 MB (RSS: 193 MB)        │
   │                                             │
   │   Listening on: http://172.17.0.2:80        │
   │                                             │
   ╰─────────────────────────────────────────────╯
```

**Comment by manniL** [comment]
You could try it one more time with the latest nuxt edge build.

**Comment by djbingham** [comment]
After stopping the container and starting it again, I got a different error (this time with the client build, rather than the server build):

```
> my-app@ dev /srv/app
> nuxt

ℹ Preparing project for development                                                                                                                   11:29:29
ℹ Initial build may take a while                                                                                                                      11:29:29
✔ Builder initialized                                                                                                                                 11:29:29
✔ Nuxt files generated                                                                                                                                11:29:29

✖ Client
  Compiled with some errors in 3.45s

● Server █████████████████████████ building (14%) 40/40 modules 0 active



 ERROR  Failed to compile with 1 errors                                                                                               friendly-errors 11:29:36


 ERROR  in ./.nuxt/client.js                                                                                                          friendly-errors 11:29:36

Module build failed (from ./node_modules/babel-loader/lib/index.js):                                                                  friendly-errors 11:29:36
Error: ENOENT: no such file or directory, open '/srv/app/node_modules/babel-loader/package.json'
    at Object.openSync (fs.js:451:3)
    at Object.readFileSync (fs.js:351:35)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:739:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/srv/app/node_modules/babel-loader/lib/index.js:25:13)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
                                                                                                                                      friendly-errors 11:29:36
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
                                                                                                                                      friendly-errors 11:29:36

✖ Client
  Compiled with some errors in 3.45s

✔ Server
  Compiled successfully in 3.67s

ℹ Waiting for file changes                                                                                                                            11:29:36

   ╭─────────────────────────────────────────────╮
   │                                             │
   │   Nuxt.js v2.5.0-25816328.fb13b41c          │
   │   Running in development mode (universal)   │
   │   Memory usage: 134 MB (RSS: 203 MB)        │
   │                                             │
   │   Listening on: http://172.17.0.2:80        │
   │                                             │
   ╰─────────────────────────────────────────────╯
```

This was with `nuxt-edge` version `2.5.0-25816328.fb13b41c`.

**Comment by manniL** [comment]
@djbingham can you try it with `yarn` (just for the sake of testing)?

**Comment by djbingham** [comment]
@manniL With `yarn` I don't seem to get the `postinstall` error that `npm` gave, but the `nuxt` compile error still occurs:

```
yarn run v1.13.0
warning package.json: No license field
$ nuxt
ℹ Preparing project for development                                                                                                                   12:00:12
ℹ Initial build may take a while                                                                                                                      12:00:12
✔ Builder initialized                                                                                                                                 12:00:12
✔ Nuxt files generated                                                                                                                                12:00:12

✖ Client
  Compiled with some errors in 2.29s

● Server █████████████████████████ building (14%) 39/40 modules 1 active
  node_modules/css-loader/dist/runtime/api.js


 ERROR  Failed to compile with 1 errors                                                                                               friendly-errors 12:00:18


 ERROR  in ./.nuxt/client.js                                                                                                          friendly-errors 12:00:18

Module build failed (from ./node_modules/babel-loader/lib/index.js):                                                                  friendly-errors 12:00:18
Error: ENOENT: no such file or directory, open '/srv/app/node_modules/babel-loader/package.json'
    at Object.openSync (fs.js:449:3)
    at Object.readFileSync (fs.js:349:35)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:751:22)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/srv/app/node_modules/babel-loader/lib/index.js:25:13)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
                                                                                                                                      friendly-errors 12:00:18
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
                                                                                                                                      friendly-errors 12:00:18

✖ Client
  Compiled with some errors in 2.29s

✔ Server
  Compiled successfully in 2.55s

ℹ Waiting for file changes                                                                                                                            12:00:18

   ╭─────────────────────────────────────────────╮
   │                                             │
   │   Nuxt.js v2.5.0-25816328.fb13b41c          │
   │   Running in development mode (universal)   │
   │   Memory usage: 114 MB (RSS: 191 MB)        │
   │                                             │
   │   Listening on: http://172.17.0.2:80        │
   │                                             │
   ╰─────────────────────────────────────────────╯

```

**Comment by manniL** [comment]
Interesting.

Maybe https://github.com/webpack/webpack/issues/1083 🤔

**Comment by djbingham** [comment]
@manniL Their problem seems to have been having `node_modules` outside the app root. In any case, I tried their solution just in case Webpack was somehow looking in the wrong place for modules: 
```
# nuxt.config.js
const path = require('path');

module.exports = {
    build: {
        resolveLoader: {
            root: path.resolve(__dirname, 'node_modules')
        }
    },
    watchers: {
        webpack: {
          aggregateTimeout: 300,
          poll: 1000
        }
    }
}
```

I still get the same error.

**Comment by wekenche** [comment]
hey did you solve this i facing same issue

**Comment by djbingham** [comment]
Hi @wekenche, I did not find a solution to this. I didn't put much time into it as I was only wanting to try out Vue with Nuxt.js but without HMR working in my setup I'm much less interested.

It certainly should be possible as I did get Next.js working with HMR from a Docker container quite painlessly - like Nuxt, Next also uses Webpack for its dev server. Here's my `next.config.js`:

```
module.exports = {
    webpackDevMiddleware: (config) => {
        config.watchOptions = {
            aggregateTimeout: 300,
            poll: 1000
        };
        return config;
    }
};
```

As mentioned above, the same watch options did not work with Nuxt.js. I don't know whether it's on a different Webpack version or if Nuxt does something weird that gets in the way of Webpack's HMR.

**Comment by lk77** [comment]
Hello,

any news on this ?
i have the same issue,
when i update a file, i need to restart the container,
or it will say file not found, which is not the case.

i've tried to increase the poll and aggregateTimeout, with no luck :

```
watchers: {
    webpack: {
      aggregateTimeout: 700,
      poll: 5000
    }
  }
```

thanks.

**Comment by danielroe** [comment]
I can confirm HMR works fine in Docker. I've updated the project but not the Docker setup: see https://github.com/danielroe/nuxt-dockerfile.

**Comment by djbingham** [comment]
That's great news, thank @danielroe! I've updated my test repository similarly to use Nuxt 2.x and also found it to work.

https://github.com/djbingham/nuxt-docker
