### ISSUE TITLE
vuetify a la carte no longer working

### ISSUE THREAD

**Issue by P4sca1** [nuxt/nuxt.js#3932]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://github.com/vuetifyjs/nuxt](https://github.com/vuetifyjs/nuxt)

### Steps to reproduce

You need to have vue-cli installed.

```
vue init vuetifyjs/nuxt my-project  
cd my-project                     
npm install nuxt@^2.0.0
npm install
npm run dev
```

Now visit http://localhost:3000

### What is expected ?

The page should be rendered.

### What is actually happening?

SyntaxError: Invalid or unexpected token.

### Additional comments?

Worked fine with previous version of nuxt.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7791">#c7791</a>)</em></sub></div>

**Comment by aldarund** [comment]
its probably something wrong with that template. Im using nuxt 2 + vuetify a la carte without any problem.
For some reason vue init dont work on my pc, so i cant check. Can you provide a full repo with error?

**Comment by P4sca1** [comment]
https://github.com/P4sca1/nuxt-vuetify

**Comment by P4sca1** [comment]
That works, thank you!
Do you know why the change is required since nuxtjs 2.0.0?

**Comment by aldarund** [comment]
@P4sca1 probably because of webpack 4 upgrade.

**Comment by p1pchenk0** [comment]
Hi, @P4sca1, I've tried your option with removing `nodeExternals` stuff and leave `transpile: [/^vuetify/]`, but now I'm getting an error:
```
× error Error: render function or template not defined in component: v-toolbar
  at normalizeRender (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:7407:13)
  at renderComponentInner (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:7531:3)
  at renderComponent (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:7502:5)
  at RenderContext.renderNode (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:7418:5)
  at RenderContext.next (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:2436:14)
  at cachedWrite (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:2295:9)
  at renderElement (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:7656:5)
  at renderNode (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:7420:5)
  at renderComponentInner (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:7538:3)
  at renderComponent (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:7502:5)
  at RenderContext.renderNode (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:7418:5)
  at RenderContext.next (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:2436:14)
  at cachedWrite (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:2295:9)
  at renderElement (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:7656:5)
  at RenderContext.renderNode (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:7420:5)
  at RenderContext.next (C:\projects\nuxt\node_modules\vue-server-renderer\build.js:2436:14)
```

**Comment by aldarund** [comment]
Create a reproduction and I'll take a look

**Comment by aldarund** [comment]
@p1pchenk0  transpile: [/^vuetify/], should go into build section of config 
https://nuxtjs.org/api/configuration-build/

**Comment by p1pchenk0** [comment]
@aldarund, sorry, fixed, and now it fires initial error:
`render function or template not defined in component: v-card`

**Comment by aldarund** [comment]
@p1pchenk0 its because you import VCard in your page/index.vue. If u want to use VCard you need to add it into plugins.vuetify like other components and dont import in pags

**Comment by P4sca1** [comment]
Or if you want to import it in pages you can do it like that:

``` pages/index.js
<template>
  <v-card>
    this is vuetify component
  </v-card>
</template>

<script>
import * as VCard from 'vuetify/es5/components/VCard'
export default {
  components: {
    ...VCard
  }
}
</script>
```

**Comment by aldarund** [comment]
Hi! I just wanted to let you know about Tenant Report!

Tenant Report makes it easy to get a credit, criminal, and eviction report from potential renters.

This includes: 
credit report from TransUnion
a nationwide criminal background check
a nationwide eviction search history

It costs you $0. The applicant will pay a $30 application fee. There are no other fees.
sign up here  http://localhost:3000/join/JPzaLt
