### ISSUE TITLE
Error: Cyclic dependency

### ISSUE THREAD

**Issue by ac88** [nuxt/nuxt.js#3951]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://github.com/vuejs/vue-cli/issues/1351](https://github.com/vuejs/vue-cli/issues/1351)

### Steps to reproduce

use nuxt2 ,cli display Error: Cyclic dependency

modifer node_modules/nuxt/dist/nuxt.js:3226

```js
new HTMLPlugin({
        filename: '../server/index.spa.html',
        template: this.options.appTemplatePath,
        minify: true,
        inject: true,
        chunksSortMode: 'none'
      })
```

chunksSortMode set 'none' but not 'dependency' or 'auto' could fix this error

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/build/resolveLibConfig.js#L61

### What is expected ?

same with vue-cli 3

### What is actually happening?

Error: Cyclic dependency

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7811">#c7811</a>)</em></sub></div>

**Comment by gerasimvol** [comment]
same

**Comment by aldarund** [comment]
I`m not quite follow how to reproduce this issue?

**Comment by ac88** [comment]
i solved this use 

```js
module.exports = (config) => {
  Object.assign(config.plugins.find(_ => _.constructor.name === 'HtmlWebpackPlugin').options, { chunksSortMode: 'none' })
}
```

**Comment by silverbackdan** [comment]
I get a similar issue even when extending the config as @ac88 has described, but like this:
```
const htmlPlugin = config.plugins.find(_ => _.constructor.name === 'HtmlWebpackPlugin')
if (htmlPlugin) {
  Object.assign(htmlPlugin.options, { chunksSortMode: 'none' })
}
```

I've read that this can happen if vue-loader and html-webpack-plugin both try and read the same file. I've just come across this while trying to upgrade to Nuxt 2.

Here's the output I have.
```
app_1      | yarn install v1.5.1
app_1      | [1/4] Resolving packages...
app_1      | success Already up-to-date.
app_1      | Done in 1.31s.
app_1      | yarn run v1.5.1
app_1      | $ nuxt
app_1      | [21:10:16] Building project
app_1      | ** Nuxt building...
app_1      | [21:10:25] Building project
app_1      | Manifest meta already provided!
app_1      | [21:10:31] Builder initialized
app_1      | [21:10:31] Builder initialized
app_1      | [21:10:32] Nuxt files generated
app_1      | [21:10:33] Compiling client
app_1      | [21:10:33] Compiling server
app_1      | (node:51) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
app_1      | [21:10:33] Nuxt files generated
app_1      | [21:11:17] Compiled server in 44s
app_1      | [21:11:17] Compiling server
app_1      | [21:11:17] Compiled server in 1ms
app_1      | /usr/src/app/node_modules/toposort/index.js:35
app_1      |       throw new Error('Cyclic dependency' + nodeRep)
app_1      |       ^
app_1      | 
app_1      | Error: Cyclic dependency
app_1      |     at visit (/usr/src/app/node_modules/toposort/index.js:35:13)
app_1      |     at visit (/usr/src/app/node_modules/toposort/index.js:53:9)
app_1      |     at visit (/usr/src/app/node_modules/toposort/index.js:53:9)
app_1      |     at visit (/usr/src/app/node_modules/toposort/index.js:53:9)
app_1      |     at visit (/usr/src/app/node_modules/toposort/index.js:53:9)
app_1      |     at Function.toposort [as array] (/usr/src/app/node_modules/toposort/index.js:22:22)
app_1      |     at Object.module.exports.dependency (/usr/src/app/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
app_1      |     at HtmlWebpackPlugin.sortChunks (/usr/src/app/node_modules/html-webpack-plugin/index.js:364:35)
app_1      |     at /usr/src/app/node_modules/html-webpack-plugin/index.js:113:21
app_1      |     at _err3 (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:40:1)
app_1      |     at /usr/src/app/node_modules/@nuxtjs/manifest/index.js:68:9
app_1      |     at _err2 (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:33:1)
app_1      |     at /usr/src/app/node_modules/@nuxtjs/manifest/index.js:68:9
app_1      |     at _err1 (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:26:1)
app_1      |     at /usr/src/app/node_modules/@nuxtjs/icon/index.js:105:13
app_1      |     at _err0 (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:19:1)
```

**Comment by benfavre** [comment]
@silverbackdan thanks.
