### ISSUE TITLE
Nuxt 2 build starter template

### ISSUE THREAD

**Issue by magisters-org** [nuxt/nuxt.js#3973]
Just init starter template and try to `nuxt build`

ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin 0 specified in "C:\\Users\\Vlad\\AppData\\Roaming\\npm\\node_modules\\nuxt\\node_modules\\@nuxtjs\\babel-preset-app\\index.js" provided an invalid property of "default" (While processing preset: "C:\\Users\\Vlad\\AppData\\Roaming\\npm\\node_modules\\nuxt\\node_modules\\@nuxtjs\\babel-preset-app\\index.js")
    at Plugin.init (C:\dev\magisters.io\front\node_modules\babel-core\lib\transformation\plugin.js:131:13)
    at Function.normalisePlugin (C:\dev\magisters.io\front\node_modules\babel-core\lib\transformation\file\options\option-manager.js:152:12)
    at C:\dev\magisters.io\front\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\dev\m.io\front\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\dev\magisters.io\front\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at C:\dev\m.io\front\node_modules\babel-core\lib\transformation\file\options\option-manager.js:265:14
    at C:\dev\m.io\front\node_modules\babel-core\lib\transformation\file\options\option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\dev\m.io\front\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\dev\m.io\front\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\dev\m.io\front\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\dev\m.io\front\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\dev\magisters.io\front\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\dev\magisters.io\front\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\dev\magisters.io\front\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
 @ multi ./.nuxt/client.js app[0]
× fatal Nuxt Build Error
Nuxt Fatal Error :(

**Comment by aldarund** [comment]
use create nuxt app
https://github.com/nuxt-community/create-nuxt-app
