### ISSUE TITLE
ExtractCSS causes an error

### ISSUE THREAD

**Issue by jericopulvera** [nuxt/nuxt.js#3996]
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://codesandbox.io/s/733yqx3n0q](https://codesandbox.io/s/733yqx3n0q)

### Steps to reproduce

go to https://codesandbox.io/s/733yqx3n0q
navigate to server control panel
click yarn build

### What is expected ?

Builds successfully.

### What is actually happening?

ERROR in ./assets/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property '0' of undefined
    at /sandbox/assets/sass/app.scss:822:1
    at /sandbox/assets/sass/app.scss:824:3
    at exports.default.v (/sandbox/node_modules/postcss-merge-longhand/dist/lib/parseTrbl.js:11:14)
    at mergeRedundant (/sandbox/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:144:41)
    at rule.walkDecls.decl (/sandbox/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:460:16)
    at /sandbox/node_modules/postcss/lib/container.js:205:16
    at /sandbox/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/sandbox/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/sandbox/node_modules/postcss/lib/container.js:131:17)
    at Rule.walkDecls (/sandbox/node_modules/postcss/lib/container.js:203:17)
    at Object.merge (/sandbox/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:436:10)
    at _decl2.default.forEach.p (/sandbox/node_modules/postcss-merge-longhand/dist/index.js:22:19)
    at Array.forEach (<anonymous>)
    at css.walkRules.rule (/sandbox/node_modules/postcss-merge-longhand/dist/index.js:20:28)
    at /sandbox/node_modules/postcss/lib/container.js:239:18
    at /sandbox/node_modules/postcss/lib/container.js:135:18
    at Root.each (/sandbox/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/sandbox/node_modules/postcss/lib/container.js:131:17)
    at runLoaders (/sandbox/node_modules/webpack/lib/NormalModule.js:286:20)
    at /sandbox/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /sandbox/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/sandbox/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/sandbox/node_modules/postcss-loader/src/index.js:208:9)
    at <anonymous>
 @ ./.nuxt/App.js 3:0-33
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7852">#c7852</a>)</em></sub></div>

**Comment by aldarund** [comment]
@jericopulvera it has nothing to do with extractCss or import.
It is due to scss content, and i suspect its something to blame in node sass or sass loader.
Here is more basic reporduction
https://codesandbox.io/s/p5q44n2m77
Basically it is caused by this code
```
a {
  border: 1px solid #3060b1;
  border-bottom: 1px solid #3060b1 !important;
}
```

**Comment by manniL** [comment]
Related: https://github.com/postcss/postcss-loader/issues/159

**Comment by manniL** [comment]
@jericopulvera It looks like that's an issue with `https://github.com/webpack-contrib/mini-css-extract-plugin` and `https://github.com/postcss/postcss-loader/issues/159`. Could you open up an issue with the example there?

**Comment by manniL** [comment]
As @aldarund said, it's 
```scss
a {
  border: 1px solid #3060b1;
  border-bottom: 1px solid #3060b1 !important;
}
```

If you remove the `!important;` it'll work:

```scss
a {
  border: 1px solid #3060b1;
  border-bottom: 1px solid #3060b1;
}
```

**Comment by manniL** [comment]
This isn't related to `SASS` as well: https://codesandbox.io/s/qzx1zl9q5j
