### ISSUE TITLE
Object rest spread is not supported in template element attributes

### ISSUE THREAD

**Issue by pbastowski** [nuxt/nuxt.js#4043]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://codesandbox.io/s/7korqkqvo6](https://codesandbox.io/s/7korqkqvo6)

### Steps to reproduce

Please see `about.vue` line 5. This line contains the following statement

```html
:style="{ ...{ color: 'red' } }"
```

### What is expected ?

That the rest spread is supported in template element attributes. The above line should transpile to 

```html
:style="{ color: 'red' }"
```

### What is actually happening?

```
ERROR in ./pages/about.vue?vue&type=template&id=0a606064&scoped=true& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./pages/about.vue?vue&type=template&id=0a606064&scoped=true&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
Error
    at Node.transpile (/sandbox/node_modules/vue-template-es2015-compiler/buble.js:12676:11)
    at Node.transpile (/sandbox/node_modules/vue-template-es2015-compiler/buble.js:5866:10)
    at Node.transpile (/sandbox/node_modules/vue-template-es2015-compiler/buble.js:5866:10)
    at Node.transpile (/sandbox/node_modules/vue-template-es2015-compiler/buble.js:12839:28)
    at /sandbox/node_modules/vue-template-es2015-compiler/buble.js:5864:59
    at Array.forEach (<anonymous>)
    at Node.transpile (/sandbox/node_modules/vue-template-es2015-compiler/buble.js:5864:10)
    at Node.transpile (/sandbox/node_modules/vue-template-es2015-compiler/buble.js:12655:28)
    at /sandbox/node_modules/vue-template-es2015-compiler/buble.js:5864:59
    at Array.forEach (<anonymous>)
    at Node.transpile (/sandbox/node_modules/vue-template-es2015-compiler/buble.js:5864:10)
    at Node.transpile (/sandbox/node_modules/vue-template-es2015-compiler/buble.js:6553:28)
    at /sandbox/node_modules/vue-template-es2015-compiler/buble.js:5864:59
    at Array.forEach (<anonymous>)
    at Node.transpile (/sandbox/node_modules/vue-template-es2015-compiler/buble.js:5864:10)
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7900">#c7900</a>)</em></sub></div>

**Comment by manniL** [comment]
This looks more like a Vue issue on the first glimpse 🤔

**Comment by aldarund** [comment]
https://github.com/vuejs/vue/issues/6307#issuecomment-345751066

**Comment by pbastowski** [comment]
@aldarund thanks, good spotting :)

So, where in nuxt config could I add the following line, which configures buble option for vue-loader?

```js
buble: { objectAssign: 'Object.assign' }
```

**Comment by clarkdo** [comment]
Try:

```js
build: {
  loaders: {
    vue: {
      transpileOptions: {
        ...
      }
    }
  }
}

**Comment by pbastowski** [comment]
Found it:

```js
        vueLoader: {
            options: {
                transpileOptions: {
                    objectAssign: 'Object.assign'
                }
            }
        },
```

**Comment by pbastowski** [comment]
@clarkdo thanks for your help 👍
