### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by yenesey** [nuxt/nuxt.js#4065]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://github.com/yenesey/nuxt-test.git](https://github.com/yenesey/nuxt-test.git)

### Steps to reproduce

So, it's just:
npx create-nuxt-app 'nuxt-test'
..with one addition package - 'vue-tinymce-editor'

and pages/index.vue

```html
<template>
  <div id="app">
    <tinymce id="d1" v-model="data"></tinymce>
  </div>
</template>
```
```javascript
<script>
import Vue from 'vue'
import tinymce from 'vue-tinymce-editor'
Vue.component('tinymce', tinymce)

export default{
    data(){
        return {
            data : ''
        };
    }
}
</script>
```
it can be reproduced like this:
git clone https://github.com/yenesey/nuxt-test.git
cd nuxt-test
npm install
npm run dev

...then open http://localhost:3000

### What is expected ?

Expected to see editor in start page

### What is actually happening?

× error C:\dev\test\nuxt-test\node_modules\vue-tinymce-editor\src\index.js:1
  (function (exports, require, module, __filename, __dirname) { import tinymce from './components/TinymceVue'
  ^^^^^^^

  SyntaxError: Unexpected identifier
  at new Script (vm.js:74:7)
  at createScript (vm.js:246:10)
  at Object.runInThisContext (vm.js:298:10)
  at Module._compile (internal/modules/cjs/loader.js:657:28)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
  at Module.load (internal/modules/cjs/loader.js:599:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
  at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  at Module.require (internal/modules/cjs/loader.js:637:17)
  at require (internal/modules/cjs/helpers.js:20:18)
  at r (C:\dev\test\nuxt-test\node_modules\vue-server-renderer\build.js:8341:16)
  at Object.vue-tinymce-editor (server-bundle.js:2615:18)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module../node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./pages/index.vue?vue&type=script&lang=js& (pages/index.vue?a625:1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module../pages/index.vue?vue&type=script&lang=js& (pages/index.vue?ff57:1:0)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7926">#c7926</a>)</em></sub></div>

**Comment by manniL** [comment]
1. Use `build.transpile` to transpile ES6 dependencies/packages (like `vue-tinymce-editor`)
2. Don't initialize the component "globally" on one page. Use a plugin for it.
3. Exclude the editor, which clearly needs the `window`/`document` object from SSR.

All done in https://codesandbox.io/s/v6yn598v0

**Comment by yenesey** [comment]
Many thanks!
How can I perform recomendation of (3.)?
Should I use <no-ssr> component?
