### ISSUE TITLE
TypeError: Cannot read property 'req' of undefined when "npm run generate" with asyncData 

### ISSUE THREAD

**Issue by sebastianmacias** [nuxt/nuxt.js#453]
I have my asyncData like this:

```javascript
  asyncData({ params }) {
    return axios.get('https://api.mydomain.com/v1/....')
      .then((res) => {
        return { pageData: res.data.object.metadata }
      })
  }
```

I'm able to run the project with 'npm run dev', and render my pages both client side and server side, however, when I try to generate the static site with 'npm run generate' I'm getting the following error:

```shell
TypeError: Cannot read property 'req' of undefined
    at VueComponent.data (2.server-bundle.js:54:19)
    at getData (/home/dev/go/src/bitbucket.org/latamvapor/vape-city/frontend/node_modules/vue/dist/vue.runtime.common.js:2748:17)
    at initData (/home/dev/go/src/bitbucket.org/latamvapor/vape-city/frontend/node_modules/vue/dist/vue.runtime.common.js:2717:7)
    at initState (/home/dev/go/src/bitbucket.org/latamvapor/vape-city/frontend/node_modules/vue/dist/vue.runtime.common.js:2658:5)
    at VueComponent.Vue._init (/home/dev/go/src/bitbucket.org/latamvapor/vape-city/frontend/node_modules/vue/dist/vue.runtime.common.js:3740:5)
    at new VueComponent (/home/dev/go/src/bitbucket.org/latamvapor/vape-city/frontend/node_modules/vue/dist/vue.runtime.common.js:3906:12)
    at createComponentInstanceForVnode (/home/dev/go/src/bitbucket.org/latamvapor/vape-city/frontend/node_modules/vue-server-renderer/build.js:5170:10)
    at renderComponent (/home/dev/go/src/bitbucket.org/latamvapor/vape-city/frontend/node_modules/vue-server-renderer/build.js:6684:40)
    at renderNode (/home/dev/go/src/bitbucket.org/latamvapor/vape-city/frontend/node_modules/vue-server-renderer/build.js:6669:7)
    at renderComponent (/home/dev/go/src/bitbucket.org/latamvapor/vape-city/frontend/node_modules/vue-server-renderer/build.js:6692:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vapecity@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vapecity@1.0.0 generate script 'nuxt generate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vapecity package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt generate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vapecity
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vapecity
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```

If I remove the asyncData method,  'npm run generate'  works fine.

I'm running nuxt latest.

Thanks

**Comment by Atinux** [comment]
I can't reproduce your issue.

Can you create a repo to reproduce this issue please?

**Comment by sebastianmacias** [comment]
Yes, here you will find how reproduce:

https://github.com/sebastianmacias/nuxt-asyncdata-ssr

**Comment by alexchopin** [comment]
The `data`method is not async and doesn't receive the context anymore.
If you want to use it has an async method please use `asyncData` instead of `data` here:
https://github.com/sebastianmacias/nuxt-asyncdata-ssr/blob/master/pages/about.vue#L22

**Comment by sebastianmacias** [comment]
That was it, thanks

**Comment by Darkside73** [comment]
nuxt/starter template still generate ```data ({ req })```

**Comment by ausir0726** [comment]
@Darkside73  
hi , I think your template is outdate .
the latest nuxt/starter template is asyncData() { }
check template folder in source code 
https://github.com/nuxt/starter

**Comment by Darkside73** [comment]
It generates via ```vue init``` command with latest vue and nuxt

**Comment by ausir0726** [comment]
@Darkside73 
vue init will use git clone a version in your home directory , like ~/.vue-template folder
you can kill it , and when you use vue init will get a latest version template ...

first time vue init => git clone nuxt/starter
sec time vue init => git clone nuxt/starter to first time folder
so , if online repo have delete some file ...
your template will keep that file until you delete ..

I was report this issue , but vue-init said , that be design .
best practice is kill that folder when you want a new template .

**Comment by ausir0726** [comment]
@alexchopin  
should re-make that about.vue file make sure people get the correct file ?
if you just delete that file , will not update users local template , they will still see old file ( but don't know what version )

thanks .
