### ISSUE TITLE
0.10.5 babel preset es2015 not installed 

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxt.js#474]
after upgrading to 0.10.5 i'm seeing the error when nuxt attempts to build. I've checked the node_modules directory and can confirm that babel-preset-es2015 does not exist. 

https://ipfs.io/ipfs/QmRnBi6mSF2uWdFduSF9LTCFiTZy78cGpKP3UbybhciBQF

I've tried clearing my yarn.lock and node_modules and still running into this issue. Anyone else?

```
ERROR in ./.nuxt/server.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/uptown/Projects/Products/Bambee/bambee/www/.nuxt"
    at /home/uptown/Projects/Products/Bambee/bambee/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/uptown/Projects/Products/Bambee/bambee/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/uptown/Projects/Products/Bambee/bambee/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/uptown/Projects/Products/Bambee/bambee/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/uptown/Projects/Products/Bambee/bambee/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/uptown/Projects/Products/Bambee/bambee/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/uptown/Projects/Products/Bambee/bambee/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/uptown/Projects/Products/Bambee/bambee/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/uptown/Projects/Products/Bambee/bambee/www/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/home/uptown/Projects/Products/Bambee/bambee/www/node_modules/babel-loader/lib/index.js:163:20)
```

**Comment by uptownhr** [comment]
I also incrementally downgraded to 0.10.0 and version after 10.x has this issue. The moment I downgraded to 0.9.9, I can see that babel-preset-es2015 is installed again.

**Comment by uptownhr** [comment]
Not really sure what caused it, but I tried one more time and I can no longer reproduce this.

**Comment by uptownhr** [comment]
Looking at package.json I can see that the presets were moved into devDepenencies in 10.x from depenencies in 9.9.

**Comment by Atinux** [comment]
@uptownhr `babel-preset-es2015` is required only to build nuxt.js, I don't know why this error appears. But I believe we should put it in `dependencies` since some module requires it but have them in `devPendencies`too.

**Comment by uptownhr** [comment]
@Atinux I think it's mostly an issue with me as I was able to pre 0.10 set the babel preset settings without an issue. I assumed es2015 presets were a part of nuxt before since it just worked. Once it moved to devDepencies, it is not longer installed when a user uses nuxt.

**Comment by Aameer** [comment]
Hey guys, I am facing the same issue on ubuntu 14.04 is there a solution to this? My package.json dependencies are as under:
```node
  "dependencies": {
    "autoprefixer": "^6.7.2",
    "aws-sdk-webpack": "^2.18.0",
    "axios": "^0.15.3",
    "babel-polyfill": "^6.23.0",
    "body-parser": "^1.16.1",
    "chart.js": "^2.5.0",
    "clipboard": "^1.6.1",
    "cookie-parser": "^1.4.3",
    "express": "^4.14.0",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "moment-duration-format": "^1.3.0",
    "morgan": "^1.8.1",
    "node-sass": "^4.5.0",
    "nuxt": "^0.10.5",
    "pikaday": "^1.5.1",
    "postcss-cli": "^2.6.0",
    "raven-js": "^3.12.0",
    "sass-loader": "^5.0.1",
    "ua-parser-js": "^0.7.12",
    "vue-clickaway": "^2.1.0",
    "vuelidate": "^0.3.0",
    "winston": "^2.3.1",
    "winston-sentry": "^0.1.5"
  },
  "devDependencies": {
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-stage-2": "^6.22.0",
    "brfs": "^1.4.3",
    "eslint": "^3.13.1",
    "eslint-config-standard": "^6.2.1",
    "eslint-plugin-html": "^1.7.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",
    "grunt": "^1.0.1",
    "grunt-shell": "^2.1.0",
    "grunt-webfont": "^1.6.0",
    "json-loader": "^0.5.4",
    "nodemon": "^1.11.0",
    "pre-commit": "^1.2.2",
    "transform-loader": "^0.2.3"
  }
```

**Comment by Atinux** [comment]
It should works now with the last version of Nuxt.js now
