### ISSUE TITLE
Error: Cyclic dependency after updating nuxt to v2.3.4

### ISSUE THREAD

**Issue by prakashbharti786** [nuxt/nuxt.js#4794]
**stucked at `after chunk asset optizization (93%)`**

**Showing error like this**
`
/node_modules/toposort/index.js:35
`
`     
throw new Error('Cyclic dependency' + nodeRep)
`

I am getting this error continusoly. To update my app i follow the steps carefully but still nothing come out.
Please look into it. 
Thank you.

```
/var/www/html/app/node_modules/toposort/index.js:35
      throw new Error('Cyclic dependency' + nodeRep)
      ^

Error: Cyclic dependency
    at visit (/var/www/html/app/node_modules/toposort/index.js:35:13)
    at visit (/var/www/html/app/node_modules/toposort/index.js:53:9)
    at visit (/var/www/html/app/node_modules/toposort/index.js:53:9)
    at visit (/var/www/htmlapp/node_modules/toposort/index.js:53:9)
    at Function.toposort [as array] (/var/www/html/app/node_modules/toposort/index.js:22:22)
    at Object.module.exports.dependency (/var/www/html/app/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (/var/www/html/app/node_modules/html-webpack-plugin/index.js:364:35)
    at /var/www/html/raxter/raxter-desktop/node_modules/html-webpack-plugin/index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/raxter/raxter-desktop/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/var/www/html/raxter/raxter-desktop/node_modules/webpack/lib/Compiler.js:367:19)
    at onCompiled (/var/www/html/app/node_modules/webpack/lib/Compiler.js:235:9)
    at hooks.afterCompile.callAsync.err (/var/www/html/app/node_modules/webpack/lib/Compiler.js:556:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/htmlapp/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/app/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/var/www/html/app/node_modules/webpack/lib/Compiler.js:553:30)

```

**Comment by prakashbharti786** [comment]
> **stucked at `after chunk asset optizization (93%)`**
> 
> **Showing error like this**
> `/node_modules/toposort/index.js:35`
> ` throw new Error('Cyclic dependency' + nodeRep)`
> 
> I am getting this error continusoly. To update my app i follow the steps carefully but still nothing come out.
> Please look into it.
> Thank you.
> 
> ```
> /var/www/html/app/node_modules/toposort/index.js:35
>       throw new Error('Cyclic dependency' + nodeRep)
>       ^
> 
> Error: Cyclic dependency
>     at visit (/var/www/html/app/node_modules/toposort/index.js:35:13)
>     at visit (/var/www/html/app/node_modules/toposort/index.js:53:9)
>     at visit (/var/www/html/app/node_modules/toposort/index.js:53:9)
>     at visit (/var/www/htmlapp/node_modules/toposort/index.js:53:9)
>     at Function.toposort [as array] (/var/www/html/app/node_modules/toposort/index.js:22:22)
>     at Object.module.exports.dependency (/var/www/html/app/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
>     at HtmlWebpackPlugin.sortChunks (/var/www/html/app/node_modules/html-webpack-plugin/index.js:364:35)
>     at /var/www/html/raxter/raxter-desktop/node_modules/html-webpack-plugin/index.js:113:21
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
>     at AsyncSeriesHook.lazyCompileHook (/var/www/html/raxter/raxter-desktop/node_modules/tapable/lib/Hook.js:154:20)
>     at Compiler.emitAssets (/var/www/html/raxter/raxter-desktop/node_modules/webpack/lib/Compiler.js:367:19)
>     at onCompiled (/var/www/html/app/node_modules/webpack/lib/Compiler.js:235:9)
>     at hooks.afterCompile.callAsync.err (/var/www/html/app/node_modules/webpack/lib/Compiler.js:556:14)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/htmlapp/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
>     at AsyncSeriesHook.lazyCompileHook (/var/www/html/app/node_modules/tapable/lib/Hook.js:154:20)
>     at compilation.seal.err (/var/www/html/app/node_modules/webpack/lib/Compiler.js:553:30)
> ```
> _This question is available on [Nuxt](https://cmty.app/nuxt) community ([#c8501](https://cmty.app/nuxt/nuxt.js/issues/c8501))_

this is a bug.

**Comment by PrimozRome** [comment]
I have the same problem:

This works fine:

```
export default {
  components: {
    VPopover,
    PartnerPopover: () => import('@/components/sections/partners/Popover')
  }
}
```

but this will throw me “Error: Cyclic dependency”

```
export default {
  components: {
    VPopover,
    PartnerPopover: () => import('@/components/sections/partners/Popover'),
    ProductPopover: () => import('@/components/sections/products/Popover')
  }
}
```

What is the problem here?

**Comment by gquinteros93** [comment]
@prakashpie, I had the same issue when I tried to lazy load more than one child component in a Component as @PrimozRome was doing.

After researching I found the following solution.

**nuxt.config.js**
```
const HtmlWebpackPlugin = config.plugins.find(plugin => {
  return plugin.constructor.name === 'HtmlWebpackPlugin'
})

HtmlWebpackPlugin.options.chunksSortMode = 'none'
```

I got that solution from the following issues reported in the `nuxt` and `vue-cli` repositories:
-  https://github.com/vuejs/vue-cli/issues/1669#issuecomment-446595864
- https://github.com/nuxt/nuxt.js/issues/3951#issuecomment-424871594

Also, it was the solution applied in `vue-cli`:
- https://github.com/vuejs/vue-cli/commit/744c375fba8b2055706f38b524a83fd5ea845686
