### ISSUE TITLE
ERROR custom keyword definition is invalid: data/errors should be boolean

### ISSUE THREAD

**Issue by egstad** [nuxt/nuxt.js#4995]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://github.com/nuxt/create-nuxt-app](https://github.com/nuxt/create-nuxt-app)

### Steps to reproduce

Install Nuxt (I've tried both stable and edge versions): npx create-nuxt-app pretty
— A. Select all features (PWA support, linter, prettier, axios) 
— B. No custom ui framework
— C. No test framework
— D. Rendering mode: universal

After installing, the prompt to run npm run dev appears (after cd into proper directory). After running that, this error is produced:

 ERROR  custom keyword definition is invalid: data/errors should be boolean

  at Ajv.addKeyword (node_modules/ajv/lib/keyword.js:65:13)
  at module.exports (node_modules/ajv-errors/index.js:10:7)
  at Object.<anonymous> (node_modules/schema-utils/src/validateOptions.js:22:1)
  at Module._compile (internal/modules/cjs/loader.js:721:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
  at Module.load (internal/modules/cjs/loader.js:620:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
  at Function.Module._load (internal/modules/cjs/loader.js:552:3)
  at Module.require (internal/modules/cjs/loader.js:657:17)
  at require (internal/modules/cjs/helpers.js:22:18)

### What is expected ?

Nuxt to build.

### What is actually happening?

Nuxt is not building.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8633">#c8633</a>)</em></sub></div>

**Comment by rideron89** [comment]
Looks like the `ajv` package is breaking in `webpack`, per this issue: [https://github.com/webpack/webpack/issues/8768](https://github.com/webpack/webpack/issues/8768)

Looks like there is a pull request with a fix in place: [epoberezkin/ajx$943](https://github.com/epoberezkin/ajv/pull/943)

If you can't wait for the fix to make it upstream, some people have had luck following this comment:
[https://github.com/webpack/webpack/issues/8768#issuecomment-462090847](https://github.com/webpack/webpack/issues/8768#issuecomment-462090847)

**Comment by manniL** [comment]
As @rideron89 said.

A fix has been published. `yarn upgrade` / `npm update` or nuking lock files + node modules should resolve the issue.
