### ISSUE TITLE
TypeError on dev/generate

### ISSUE THREAD

**Issue by Berkmann18** [nuxt/nuxt.js#5238]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/Berkmann18/nuxty](https://github.com/Berkmann18/nuxty)

### Steps to reproduce

1. Follow [this tutorial](https://medium.com/@marcmintel/quickly-develop-static-websites-with-vuejs-a-headless-cms-and-graphql-bf64e75910d6) (up to the point where you run `npm run generate` or `npm run dev`).
2. See the output on the CLI.

### What is expected ?

No errors.

### What is actually happening?
```
%cError background: red; color: white; padding: 2px 4px; border-radius: 3px; font-weight: bold; Network error: Response not successful: Received status code 401
/mnt/c/Users/max/Projects/nuxty/node_modules/zen-observable/lib/Observable.js:63
     throw e;
     ^
TypeError: Cannot read property 'delete' of undefined
    at /mnt/c/Users/max/Projects/nuxty/node_modules/apollo-link-dedup/lib/dedupLink.js:48:47
    at cleanupSubscription (/mnt/c/Users/max/Projects/nuxty/node_modules/zen-observable/lib/Observable.js:90:7)
    at notifySubscription (/mnt/c/Users/max/Projects/nuxty/node_modules/zen-observable/lib/Observable.js:145:41)
    at onNotify (/mnt/c/Users/max/Projects/nuxty/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/mnt/c/Users/max/Projects/nuxty/node_modules/zen-observable/lib/Observable.js:224:7)
    at /mnt/c/Users/max/Projects/nuxty/node_modules/apollo-link-dedup/lib/dedupLink.js:42:81
    at Set.forEach (<anonymous>)
    at Object.error (/mnt/c/Users/max/Projects/nuxty/node_modules/apollo-link-dedup/lib/dedupLink.js:42:45)
    at notifySubscription (/mnt/c/Users/max/Projects/nuxty/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/mnt/c/Users/max/Projects/nuxty/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/mnt/c/Users/max/Projects/nuxty/node_modules/zen-observable/lib/Observable.js:224:7)
    at notifySubscription (/mnt/c/Users/max/Projects/nuxty/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/mnt/c/Users/max/Projects/nuxty/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/mnt/c/Users/max/Projects/nuxty/node_modules/zen-observable/lib/Observable.js:224:7)
    at /mnt/c/Users/max/Projects/nuxty/node_modules/apollo-upload-client/lib/index.js:104:20
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8831">#c8831</a>)</em></sub></div>

**Comment by manniL** [comment]
Please open a bug report at https://github.com/nuxt-community/apollo-module :relaxed:

**Comment by Berkmann18** [comment]
Done. cf. https://cmty.app/nuxt/apollo-module/issues/c188
