### ISSUE TITLE
core-js problems with 2.5.0

### ISSUE THREAD

**Issue by andrewgorpenko** [nuxt/nuxt.js#5313]
### Version

[v2.5.0](https://github.com/nuxt.js/releases/tag/v2.5.0)

### Reproduction link

[http://not-needed.com](http://not-needed.com)

### Steps to reproduce

Do the fresh install of the Nuxt(via cli) with the following options:

- Project name project
- Project description Cool project
- Use a custom server framework none
- Choose features to install Axios
- Use a custom UI framework element-ui
- Use a custom test framework none
- Choose rendering mode Universal
- Author name Andrew Gorpenko
- Choose a package manager npm

After running the npm run dev I am getting the error:

```bash
 ERROR  Failed to compile with 3 errors

These dependencies were not found:
* core-js/library/fn/object/assign in ./node_modules/babel-runtime/core-js/object/assign.js
* core-js/library/fn/symbol in ./node_modules/babel-runtime/core-js/symbol.js
* core-js/library/fn/symbol/iterator in ./node_modules/babel-runtime/core-js/symbol/iterator.js
```

### What is expected ?

Clean install without errors

### What is actually happening?

Fails to compile because of missing dependencies

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8883">#c8883</a>)</em></sub></div>

**Comment by tmorehouse** [comment]
We are having similar issues with upgrading from 2.4.5 to 2.5.0 when building the BootstrapVue docs:

```
SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at r (/root/bootstrap-vue/node_modules/vue-server-renderer/build.dev.js:9295:16)
    at Object.<anonymous> (webpack:/external "@babel/runtime/helpers/esm/asyncToGenerator":1:0)
    at o (webpack/bootstrap:36:0)
    at Module.<anonymous> (.nuxt/middleware.js:1:19)
    at o (webpack/bootstrap:36:0)
    at Object.<anonymous> (node_modules/@nuxt/webpack/node_modules/core-js/internals/own-keys.js:4:43)
    at o (webpack/bootstrap:36:0)
```

And getting warning about `core-js` version not being specified:
```
WARNING: We noticed you're using the useBuiltIns option without declaring a core-js version.
Currently, we assume version 2.x when no version is passed. Since this default version will
likely change in future versions of Babel, we recommend explicitly setting the core-js
version you are using via the corejs option.

You should also be sure that the version you pass to the corejs option matches the version
specified in your package.json's dependencies section. If it doesn't, you need to run one
of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3
```

**Comment by LookinGit** [comment]
@andrewgorpenko try:
`~/plugins/element-ui.js`
```js
import Vue from 'vue'
import Element from 'element-ui**/lib**'
import locale from 'element-ui/lib/locale/lang/en'

export default () => {
  Vue.use(Element, { locale })
}
```
 as temporary solution, while element-ui a plugin for nuxt not updated

**Comment by andrewgorpenko** [comment]
This works fine with this temporary fix, thanks.

**Comment by pi0** [comment]
Thanks for reporting issues. All inconsistencies should be resolved with [v2.5.1](https://github.com/nuxt/nuxt.js/releases/tag/v2.5.1). Please upgrade and ping us if still, any problem exists regarding core-js.

**Comment by digitalcrafted** [comment]
Hey @pi0 Thanks for everything and the quick response. 

Still getting a lot of core-js issues with v2.5.1 upgrade.

**Comment by pi0** [comment]
@digitalcrafted Do you have a `babel.config.js` or `.babelrc` file in your project? Otherwise is there any chance you can share the project with us or giving more details?

PS: Cleaning up `yarn.lock`/`package-lock.js` may help.

**Comment by digitalcrafted** [comment]
Thanks @pi0  => Cleaning up `package-lock.js` did it.

**Comment by rodrigopedra** [comment]
I am still getting the same errors... removed everything `node_modules`, `.nuxt`, `yarn.lock`, tried with npm instead of yarn and still am getting this error.

I already checked file by file from a clean `npx create-nuxt-app` install and all files are ok, including the package.json and .babelrc

**Comment by pi0** [comment]
@rodrigopedra Can you please manually add `core-js@2` in your project?

**Comment by rodrigopedra** [comment]
Tried and still getting the same error, below are my `package.json` dependencies (with core-js added):

~~~json
{
"dependencies": {
    "@nuxtjs/auth": "^4.5.3",
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/dotenv": "^1.3.0",
    "@nuxtjs/proxy": "^1.3.3",
    "@nuxtjs/pwa": "^2.6.0",
    "axios": "^0.18.0",
    "core-js": "2",
    "cross-env": "^5.2.0",
    "date-fns": "^1.30.1",
    "nuxt": "^2.4.0",
    "portal-vue": "^1.5.1",
    "vue-avatar": "^2.1.7",
    "vue-svg-loader": "^0.12.0"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^0.0.1",
    "@vue/test-utils": "^1.0.0-beta.27",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^8.2.1",
    "babel-jest": "^23.6.0",
    "email-validator": "^2.0.4",
    "eslint": "^5.0.1",
    "eslint-config-prettier": "^3.1.0",
    "eslint-config-standard": ">=12.0.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-import": ">=2.14.0",
    "eslint-plugin-jest": ">=21.24.1",
    "eslint-plugin-node": ">=7.0.1",
    "eslint-plugin-prettier": "2.6.2",
    "eslint-plugin-promise": ">=4.0.1",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-plugin-vue": "^5.2.0",
    "jest": "^23.6.0",
    "node-sass": "^4.11.0",
    "nodemon": "^1.18.9",
    "prettier": "1.14.3",
    "sass": "^1.17.0",
    "sass-loader": "^7.1.0",
    "vue-jest": "^3.0.2"
  }
}
~~~

**Comment by pi0** [comment]
@rodrigopedra I tried provided package.json locally and it was working fine. What error do you get? Is it related to a specific library? Sharing full error may help.

**Comment by MasterHiei** [comment]
@pi0 I have the same issue with v2.5.1.
I exec `npm run dev` and print errors like below.
```bash
ERROR  Failed to compile with 452 errors                                                                                                                                                                      friendly-errors 19:47:28

These dependencies were not found:                                                                                                                                                                             friendly-errors 19:47:28
                                                                                                                                                                                                               friendly-errors 19:47:28
* core-js/modules/es.array.concat in ./.nuxt/utils.js, ./.nuxt/auth/utilities.js and 14 others                                                                                                                 friendly-errors 19:47:28
* core-js/modules/es.array.fill in ./node_modules/vuetify/lib/components/VDatePicker/VDatePickerMonthTable.js, ./node_modules/vuetify/lib/components/VExpansionPanel/VExpansionPanel.js and 1 other            friendly-errors 19:47:28
* core-js/modules/es.array.filter in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 14 others                                                                                                   friendly-errors 19:47:28
* core-js/modules/es.array.find in ./.nuxt/client.js, ./.nuxt/nuxt-i18n/plugin.main.js and 10 others                                                                                                           friendly-errors 19:47:28
* core-js/modules/es.array.find-index in ./node_modules/vuetify/lib/components/VExpansionPanel/VExpansionPanel.js, ./node_modules/vuetify/lib/components/VItemGroup/VItemGroup.js and 4 others                 friendly-errors 19:47:28
* core-js/modules/es.array.flat in ./node_modules/vuetify/lib/components/VBtn/VBtn.js, ./node_modules/vuetify/lib/components/VCard/VCard.js and 2 others                                                       friendly-errors 19:47:28
* core-js/modules/es.array.from in ./node_modules/vuetify/lib/components/VCalendar/VCalendarWeekly.js, ./node_modules/vuetify/lib/components/VDataTable/mixins/head.js and 10 others                           friendly-errors 19:47:28
* core-js/modules/es.array.includes in ./.nuxt/client.js, ./.nuxt/auth/auth.js and 18 others                                                                                                                   friendly-errors 19:47:28
* core-js/modules/es.array.iterator in ./.nuxt/client.js                                                                                                                                                       friendly-errors 19:47:28
* core-js/modules/es.array.join in ./.nuxt/utils.js, ./.nuxt/auth/utilities.js and 10 others                                                                                                                   friendly-errors 19:47:28
* core-js/modules/es.array.map in ./.nuxt/client.js, ./.nuxt/auth/utilities.js and 24 others                                                                                                                   friendly-errors 19:47:28
* core-js/modules/es.array.slice in ./.nuxt/utils.js, ./.nuxt/auth/utilities.js and 10 others                                                                                                                  friendly-errors 19:47:28
* core-js/modules/es.array.splice in ./node_modules/vuetify/lib/components/VCombobox/VCombobox.js, ./node_modules/vuetify/lib/components/VExpansionPanel/VExpansionPanel.js and 5 others                       friendly-errors 19:47:28
* core-js/modules/es.array.unscopables.flat in ./node_modules/vuetify/lib/components/VBtn/VBtn.js, ./node_modules/vuetify/lib/components/VCard/VCard.js and 2 others                                           friendly-errors 19:47:28
* core-js/modules/es.function.name in ./.nuxt/client.js, ./.nuxt/auth/schemes/oauth2.js and 13 others                                                                                                          friendly-errors 19:47:28
* core-js/modules/es.map in ./node_modules/vuetify/lib/components/VSelect/VSelect.js, ./node_modules/vuetify/lib/components/VTreeview/VTreeview.js                                                             friendly-errors 19:47:28
* core-js/modules/es.math.cbrt in ./node_modules/vuetify/lib/util/color/transformCIELAB.js                                                                                                                     friendly-errors 19:47:28
* core-js/modules/es.math.sign in ./node_modules/vuetify/lib/components/VDatePicker/VDatePickerDateTable.js, ./node_modules/vuetify/lib/components/VTimePicker/VTimePickerClock.js                             friendly-errors 19:47:28
* core-js/modules/es.number.constructor in ./node_modules/vuetify/lib/components/VAvatar/VAvatar.js, ./node_modules/vuetify/lib/components/VBottomNav/VBottomNav.js and 43 others                              friendly-errors 19:47:28
* core-js/modules/es.number.max-safe-integer in ./node_modules/vuetify/lib/components/VCalendar/VCalendarWeekly.js                                                                                             friendly-errors 19:47:28
* core-js/modules/es.number.to-fixed in ./node_modules/vuetify/lib/components/VSlider/VSlider.js                                                                                                               friendly-errors 19:47:28
* core-js/modules/es.object.assign in ./.nuxt/client.js                                                                                                                                                        friendly-errors 19:47:28
* core-js/modules/es.object.freeze in ./node_modules/vuetify/lib/util/colors.js                                                                                                                                friendly-errors 19:47:28
* core-js/modules/es.object.is-extensible in ./node_modules/vuetify/lib/util/helpers.js                                                                                                                        friendly-errors 19:47:28
* core-js/modules/es.object.keys in ./.nuxt/utils.js, ./.nuxt/auth/utilities.js and 5 others                                                                                                                   friendly-errors 19:47:28
* core-js/modules/es.object.to-string in ./.nuxt/client.js, ./.nuxt/auth/auth.js and 25 others                                                                                                                 friendly-errors 19:47:28
* core-js/modules/es.object.values in ./.nuxt/auth/utilities.js, ./node_modules/vuetify/lib/components/VForm/VForm.js and 1 other                                                                              friendly-errors 19:47:28
* core-js/modules/es.promise in ./.nuxt/client.js                                                                                                                                                              friendly-errors 19:47:28
* core-js/modules/es.promise.finally in ./.nuxt/client.js                                                                                                                                                      friendly-errors 19:47:28
* core-js/modules/es.regexp.constructor in ./.nuxt/utils.js, ./.nuxt/nuxt-i18n/plugin.main.js and 1 other                                                                                                      friendly-errors 19:47:28
* core-js/modules/es.regexp.to-string in ./.nuxt/utils.js, ./.nuxt/nuxt-i18n/plugin.main.js and 14 others                                                                                                      friendly-errors 19:47:28
* core-js/modules/es.set in ./node_modules/vuetify/lib/components/VTreeview/VTreeview.js, ./node_modules/vuetify/lib/mixins/data-iterable.js                                                                   friendly-errors 19:47:28
* core-js/modules/es.string.ends-with in ./node_modules/vuetify/lib/components/VCombobox/VCombobox.js                                                                                                          friendly-errors 19:47:28
* core-js/modules/es.string.fixed in ./node_modules/vuetify/lib/components/VBottomNav/VBottomNav.js, ./node_modules/vuetify/lib/components/VBtn/VBtn.js and 5 others                                           friendly-errors 19:47:28
* core-js/modules/es.string.includes in ./.nuxt/client.js, ./.nuxt/auth/auth.js and 11 others                                                                                                                  friendly-errors 19:47:28
* core-js/modules/es.string.iterator in ./.nuxt/utils.js, ./.nuxt/auth/auth.js and 20 others                                                                                                                   friendly-errors 19:47:28
* core-js/modules/es.string.link in ./node_modules/vuetify/lib/components/VBtn/VBtn.js, ./node_modules/vuetify/lib/components/VTabs/VTab.js                                                                    friendly-errors 19:47:28
* core-js/modules/es.string.match in ./.nuxt/client.js, ./.nuxt/nuxt-i18n/middleware.js and 4 others                                                                                                           friendly-errors 19:47:28
* core-js/modules/es.string.pad-start in ./node_modules/vuetify/lib/components/VDatePicker/VDatePickerDateTable.js                                                                                             friendly-errors 19:47:28
* core-js/modules/es.string.repeat in ./.nuxt/utils.js, ./node_modules/vuetify/lib/components/VDatePicker/util/pad.js and 1 other                                                                              friendly-errors 19:47:28
* core-js/modules/es.string.replace in ./.nuxt/utils.js, ./.nuxt/auth/auth.js and 8 others                                                                                                                     friendly-errors 19:47:28
* core-js/modules/es.string.search in ./.nuxt/utils.js, ./.nuxt/auth/schemes/oauth2.js and 2 others                                                                                                            friendly-errors 19:47:28
* core-js/modules/es.string.small in ./node_modules/vuetify/lib/components/VBtn/VBtn.js, ./node_modules/vuetify/lib/components/VChip/VChip.js and 3 others                                                     friendly-errors 19:47:28
* core-js/modules/es.string.split in ./.nuxt/utils.js, ./.nuxt/auth/utilities.js and 10 others                                                                                                                 friendly-errors 19:47:28
* core-js/modules/es.string.starts-with in ./.nuxt/utils.js, ./node_modules/vuetify/lib/components/VGrid/grid.js and 3 others                                                                                  friendly-errors 19:47:28
* core-js/modules/es.string.trim in ./node_modules/vuetify/lib/components/VAutocomplete/VAutocomplete.js, ./node_modules/vuetify/lib/components/VAvatar/VAvatar.js and 13 others                               friendly-errors 19:47:28
* core-js/modules/es.symbol in ./.nuxt/axios.js, ./.nuxt/auth/auth.js and 13 others                                                                                                                            friendly-errors 19:47:28
* core-js/modules/es.symbol.description in ./.nuxt/axios.js, ./.nuxt/auth/auth.js and 13 others                                                                                                                friendly-errors 19:47:28
* core-js/modules/es.symbol.iterator in ./.nuxt/client.js, ./.nuxt/auth/auth.js and 12 others                                                                                                                  friendly-errors 19:47:28
* core-js/modules/web.dom-collections.for-each in ./.nuxt/client.js, ./.nuxt/components/nuxt-child.js and 5 others                                                                                             friendly-errors 19:47:28
* core-js/modules/web.dom-collections.iterator in ./.nuxt/axios.js, ./.nuxt/auth/auth.js and 12 others                                                                                                         friendly-errors 19:47:28
                                                                                                                                                                                                               friendly-errors 19:47:28
To install them, you can run: npm install --save core-js/modules/es.array.concat core-js/modules/es.array.fill core-js/modules/es.array.filter core-js/modules/es.array.find core-js/modules/es.array.find-index core-js/modules/es.array.flat core-js/modules/es.array.from core-js/modules/es.array.includes core-js/modules/es.array.iterator core-js/modules/es.array.join core-js/modules/es.array.map core-js/modules/es.array.slice core-js/modules/es.array.splice core-js/modules/es.array.unscopables.flat core-js/modules/es.function.name core-js/modules/es.map core-js/modules/es.math.cbrt core-js/modules/es.math.sign core-js/modules/es.number.constructor core-js/modules/es.number.max-safe-integer core-js/modules/es.number.to-fixed core-js/modules/es.object.assign core-js/modules/es.object.freeze core-js/modules/es.object.is-extensible core-js/modules/es.object.keys core-js/modules/es.object.to-string core-js/modules/es.object.values core-js/modules/es.promise core-js/modules/es.promise.finally core-js/modules/es.regexp.constructor core-js/modules/es.regexp.to-string core-js/modules/es.set core-js/modules/es.string.ends-with core-js/modules/es.string.fixed core-js/modules/es.string.includes core-js/modules/es.string.iterator core-js/modules/es.string.link core-js/modules/es.string.match core-js/modules/es.string.pad-start core-js/modules/es.string.repeat core-js/modules/es.string.replace core-js/modules/es.string.search core-js/modules/es.string.small core-js/modules/es.string.split core-js/modules/es.string.starts-with core-js/modules/es.string.trim core-js/modules/es.symbol core-js/modules/es.symbol.description core-js/modules/es.symbol.iterator core-js/modules/web.dom-collections.for-each core-js/modules/web.dom-collections.iterator
```

**Comment by rodrigopedra** [comment]
Hi @pi0 thanks for the patience, here is the browser output:

```
SyntaxError
Unexpected token export

vm.js:80:10
createScript

vm.js:139:10
Object.runInThisContext

module.js:617:28
Module._compile

module.js:664:10
Module._extensions..js

module.js:566:32
Module.load

module.js:506:12
tryModuleLoad

module.js:498:3
Module._load

module.js:597:17
Module.require

internal/module.js:11:18
require

webpack:/external "@babel/runtime/helpers/esm/defineProperty":1:
Object.@babel/runtime/helpers/esm/defineProperty

webpack/bootstrap:25:
__webpack_require__

server.js:8327:99
Module../services/AuthService.js

webpack/bootstrap:25:
__webpack_require__

store/users.js:1:
Module../store/users.js

webpack/bootstrap:25:
__webpack_require__ 
```

The only userland file it is complaining about is a store. I checked this store in my code and it imports a class that defined a static property. Maybe some change disallowed this feature.

These are the changes I made in my code, in case someone faces the same issue:

## Before

```js
// /store/users.js
import AuthService from '@/services/AuthService';

// state, mutations, actions, ...

export const getters = {
    socialLoginUrl() {
        return AuthService.SOCIAL_LOGIN_URL;
    },
};
```

```js
// /sevice/AuthService.js

export default class AuthService {
    static SOCIAL_LOGIN_URL = '/social/login'; // this is where the error occurs

    // other class methods
}
```

## After

```js
// /store/users.js
import AuthService, { SOCIAL_LOGIN_URL } from '@/services/AuthService';

// state, mutations, actions, ...

export const getters = {
    socialLoginUrl() {
        return SOCIAL_LOGIN_URL;
    },
};
```

```js
// /sevice/AuthService.js
export const SOCIAL_LOGIN_URL = '/social/login'; // no more errors

export default class AuthService {
    // other class methods
}
```

**Comment by pi0** [comment]
@rodrigopedra I've seen similar "Unexpected token export" error in projects having `babel.config.js` file. Do you have one? And if yes, can you please remove if it to see it works?

**Comment by rodrigopedra** [comment]
The only babel file I have is the `.babelrc` generated by create-nuxt-app

Sorry if I wasn't clear before, but I got it working from changing the static class constant to a named const export. 

See the before and after in my previous comment, after this change everything is working for me.

**Comment by alanaasmaa** [comment]
I fixed that with `npm install --save-dev core-js@2`

**Comment by simllll** [comment]
So now I'm stick with 2.5.0 if we "need" to stay with core-js3.0? This is kind of unsatisfying. Could we solve this somehow by a "flag" to use core js 3 via "opt in"?

**Comment by alanaasmaa** [comment]
@simllll 2.5.1 rollbacked core-js 2

**Comment by lichunshan** [comment]
**I also reported a similar mistake.**
Failed to compile with 6 errors                                                                                                                                                         friendly-errors 17:51:56

These dependencies were not found:                                                                                                                                                              friendly-errors 17:51:56
                                                                                                                                                                                                friendly-errors 17:51:56
* core-js/library/fn/get-iterator in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/get-iterator.js                                                                                 friendly-errors 17:51:56
* core-js/library/fn/is-iterable in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/is-iterable.js                                                                                   friendly-errors 17:51:56
* core-js/library/fn/object/assign in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/assign.js                                                                               friendly-errors 17:51:56
* core-js/library/fn/object/keys in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/keys.js                                                                                   friendly-errors 17:51:56
* core-js/library/fn/symbol in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/symbol.js                                                                                             friendly-errors 17:51:56
* core-js/library/fn/symbol/iterator in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/symbol/iterator.js                                                                           friendly-errors 17:51:56
                                                                                                                                                                                                friendly-errors 17:51:56
To install them, you can run: npm install --save core-js/library/fn/get-iterator core-js/library/fn/is-iterable core-js/library/fn/object/assign core-js/library/fn/object/keys core-js/library/fn/symbol core-js/library/fn/symbol/iterator

**this is the package.json**
```
"dependencies": {
    "axios": "^0.18.0",
    "element-ui": "^2.4.11",
    "js-cookie": "^2.2.0",
    "nuxt": "2.5.0",
    "nuxt-clipboard2": "^0.2.1",
    "nuxt-stripe-module-https": "^1.0.0",
    "rollup": "^0.67.4",
    "vant": "^1.4.2",
    "vue-i18n": "^8.3.1",
    "vue-lazyload": "^1.2.6",
    "vue-paypal-checkout": "^3.2.0",
    "vue-social-sharing": "^2.3.3",
    "vuex-persistedstate": "^2.5.4"
  },
  "devDependencies": {
    "@nuxtjs/axios": "^5.3.4",
    "@vue/test-utils": "^1.0.0-beta.29",
    "autoprefixer": "^9.3.1",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.7.1",
    "babel-plugin-component": "^1.1.1",
    "babel-plugin-import": "^1.11.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "cross-env": "^5.2.0",
    "eslint": "^4.19.1",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-vue": "^4.0.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^24.7.1",
    "jest-transform-stub": "^2.0.0",
    "node-sass": "^4.10.0",
    "nuxt-sass-resources-loader": "^2.0.5",
    "postcss-pxtorem": "^4.0.1",
    "sass-loader": "^7.1.0",
    "vue-jest": "^3.0.4"
  }
```

**Comment by aKaigege** [comment]
> **I also reported a similar mistake.**
> Failed to compile with 6 errors friendly-errors 17:51:56
> 
> These dependencies were not found: friendly-errors 17:51:56
> friendly-errors 17:51:56
> 
> * core-js/library/fn/get-iterator in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/get-iterator.js                                                                                 friendly-errors 17:51:56
> * core-js/library/fn/is-iterable in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/is-iterable.js                                                                                   friendly-errors 17:51:56
> * core-js/library/fn/object/assign in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/assign.js                                                                               friendly-errors 17:51:56
> * core-js/library/fn/object/keys in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/keys.js                                                                                   friendly-errors 17:51:56
> * core-js/library/fn/symbol in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/symbol.js                                                                                             friendly-errors 17:51:56
> * core-js/library/fn/symbol/iterator in ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/symbol/iterator.js                                                                           friendly-errors 17:51:56
>   friendly-errors 17:51:56
>   To install them, you can run: npm install --save core-js/library/fn/get-iterator core-js/library/fn/is-iterable core-js/library/fn/object/assign core-js/library/fn/object/keys core-js/library/fn/symbol core-js/library/fn/symbol/iterator
> 
> **this is the package.json**
> 
> ```
> "dependencies": {
>     "axios": "^0.18.0",
>     "element-ui": "^2.4.11",
>     "js-cookie": "^2.2.0",
>     "nuxt": "2.5.0",
>     "nuxt-clipboard2": "^0.2.1",
>     "nuxt-stripe-module-https": "^1.0.0",
>     "rollup": "^0.67.4",
>     "vant": "^1.4.2",
>     "vue-i18n": "^8.3.1",
>     "vue-lazyload": "^1.2.6",
>     "vue-paypal-checkout": "^3.2.0",
>     "vue-social-sharing": "^2.3.3",
>     "vuex-persistedstate": "^2.5.4"
>   },
>   "devDependencies": {
>     "@nuxtjs/axios": "^5.3.4",
>     "@vue/test-utils": "^1.0.0-beta.29",
>     "autoprefixer": "^9.3.1",
>     "babel-core": "^6.26.3",
>     "babel-eslint": "^10.0.1",
>     "babel-jest": "^24.7.1",
>     "babel-plugin-component": "^1.1.1",
>     "babel-plugin-import": "^1.11.0",
>     "babel-preset-env": "^1.7.0",
>     "babel-preset-es2015": "^6.24.1",
>     "cross-env": "^5.2.0",
>     "eslint": "^4.19.1",
>     "eslint-friendly-formatter": "^4.0.1",
>     "eslint-loader": "^2.1.1",
>     "eslint-plugin-vue": "^4.0.0",
>     "identity-obj-proxy": "^3.0.0",
>     "jest": "^24.7.1",
>     "jest-transform-stub": "^2.0.0",
>     "node-sass": "^4.10.0",
>     "nuxt-sass-resources-loader": "^2.0.5",
>     "postcss-pxtorem": "^4.0.1",
>     "sass-loader": "^7.1.0",
>     "vue-jest": "^3.0.4"
>   }
> ```

remove .nuxt

**Comment by rchl** [comment]
For the benefit of people coming here from search engine, this error can trigger depending on what dependencies one has installed and can be fixed by explicitly installing `core-js@2` dependency.

**Comment by troffel** [comment]
Here is the solution:
https://nuxtjs.org/guide/release-notes#core-js
