### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema

### ISSUE THREAD

**Issue by jingxinxin** [nuxt/nuxt.js#5384]
The command `nuxt` fails throwing an error `Error: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema. `

Stack trace:
```
- configuration.entry should be one of these:
   function | object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string]
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry should be an instance of function
      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
    * configuration.entry['1'] should be a string.
      -> The string is resolved to a module which is loaded upon startup.
    * configuration.entry['1'] should be an array:
      [non-empty string]
    * configuration.entry should be a string.
      -> An entry point without name. The string is resolved to a module which is loaded upon startup.
    * configuration.entry should be an array:
      [non-empty string]

  - configuration.entry should be one of these:
  function | object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string]
  -> The entry point(s) of the compilation.
  Details:
  * configuration.entry should be an instance of function
  -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
  * configuration.entry['1'] should be a string.
  -> The string is resolved to a module which is loaded upon startup.
  * configuration.entry['1'] should be an array:
  [non-empty string]
  * configuration.entry should be a string.
  -> An entry point without name. The string is resolved to a module which is loaded upon startup.
  * configuration.entry should be an array:
  [non-empty string]
  at webpack (node_modules/webpack/lib/webpack.js:31:9)
  at compilers.compilersOptions.map (node_modules/@nuxt/webpack/dist/webpack.js:5252:24)
  at Array.map (<anonymous>)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5251:39)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5578:30)
```

Environment:
```
node :10.15.3
npm: 6.9.0
```

package.json
```json
...
 "dependencies": {
    "@nuxtjs/axios": "^5.4.1",
    "@nuxtjs/google-analytics": "^2.2.0",
    "axios": "^0.18.0",
    "body-parser": "^1.18.3",
    "express": "^4.16.4",
    "express-session": "^1.15.6",
    "nuxt": "^2.5.1",
    "vee-validate": "^2.2.0",
    "vuetify": "^1.5.7",
    "vuetify-loader": "^1.2.1"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "babel-plugin-transform-imports": "^1.5.1",
    "babel-polyfill": "^6.26.0",
    "eslint": "^5.15.3",
    "eslint-config-standard": "^12.0.0",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-node": "^8.0.1",
    "eslint-plugin-promise": "^4.0.0",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^5.2.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1"
  },
...
```

nuxt.config.js
```js
import bodyParser from 'body-parser'
import VuetifyLoaderPlugin from 'vuetify-loader/lib/plugin'
import nodeExternals from 'webpack-node-externals'

module.exports = {
  head            : {
    titleTemplate: '%s - xxx',
    meta         : [
      { charset: 'utf-8' },
      {
        name   : 'viewport',
        content: 'width=device-width, initial-scale=1, user-scalable=no'
      }
    ],
  },
  plugins         : [
    '~/plugins/vuetify.js',
    '~/plugins/vee-validate.js'
  ],
  css             : [
    '~/assets/style/app.styl'
  ],
  loading         : { color: '#3B8070' },
  build           : {
    extractCSS: true,
    extend (config, ctx) {
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test   : /\.(js|vue)$/,
          loader : 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
      if (ctx.isClient) {
        config.entry = [].concat(...[ 'babel-polyfill', config.entry ])
      }
      if (process.server) {
        config.externals = [
          nodeExternals({
            whitelist: [ /^vuetify/ ]
          })
        ]
      }
    },
    transpile : [ /^vuetify/ ],
    plugins   : [
      new VuetifyLoaderPlugin()
    ]
  },
  modules         : [
    '@nuxtjs/axios',
    [ '@nuxtjs/google-analytics', { id: 'UA-xxxxxx-1' } ]
  ],
  axios           : {
    baseURL: 'http://xxx.xx.xx.xx',
    timeout: 10000,
    retry  : { retries: 3 },
    debug  : false
 },
  router          : {
    middleware: [ 'auth', 'user-agent' ]
  },
  serverMiddleware: [
    bodyParser.json(),
    '~/server/api'
  ]
}

```

**Comment by jurra** [comment]
I have the same problem , and haven't been able to find an answer. If you already solved it please share how :)

**Comment by jingxinxin** [comment]
@jurra 
The `configuration.entry` should be one of these:
   function | object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string]

```js
if (ctx.isClient) {
        config.entry = [].concat(...[ 'babel-polyfill', config.entry ])
}
```

change to

```js
 if (isClient) {
        if (!config.entry) config.entry = {}
        config.entry.polyfill = [ 'babel-polyfill' ]
}
```
