### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by msudgh** [nuxt/nuxt.js#541]
When I navigate to an address directly by entering in address bar I got below error.

```js
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at serialize (/home/masoud/Sources/cynthia-mobile/node_modules/serialize-javascript/index.js:72:20)
    at _callee2$ (/home/masoud/Sources/cynthia-mobile/node_modules/nuxt/dist/nuxt.js:1343:132)
    at tryCatch (/home/masoud/Sources/cynthia-mobile/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/masoud/Sources/cynthia-mobile/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/masoud/Sources/cynthia-mobile/node_modules/regenerator-runtime/runtime.js:116:21)
    at onFulfilled (/home/masoud/Sources/cynthia-mobile/node_modules/co/index.js:65:19)
```

**Comment by alexchopin** [comment]
Hi, can you be more specific about your issue with some code snippets for example?

**Comment by msudgh** [comment]
In Album page I have a component with name of player that pass **`albumInfo`** as props to player component.

![screenshot_20170412_104444](https://cloud.githubusercontent.com/assets/11756815/24943722/297f5f1e-1f6d-11e7-8778-9843fd2a583d.png)

**Comment by msudgh** [comment]
Oh, I figure out that I can't use route object in the albumInfo.
Isn't possible to use route object like above example?

**Comment by pi0** [comment]
@msudgh Generally you can't store any function in data. This example throws foo() is not a function exception!
```js
       asyncData() {
            return {
                foo() {
                    console.log("Bar")
                }
            }
        },
        mounted() {
          console.log(this.foo())
        },
```

BTW route is injected to component instance and you can access route using `this.$route` and router using `this.$router`

**Comment by msudgh** [comment]
Yeah, I got it. it was just a bad mistake.
By the way, Thanks.
