### ISSUE TITLE
Run `nuxt`: events.js:160       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by alexmoreno** [nuxt/nuxt.js#563]
Any "nuxt" command gives me the same error.
I reinstalled `nodejs`, `npm`, I created a new folder and reinstalled everything. Nothing works.

See below my error output.

```

npm run dev

> cachorro@1.0.0 dev /home/alex/workspace/marketplace2/cachorro
> nuxt

  nuxt:build App root: /home/alex/workspace/marketplace2/cachorro +0ms
  nuxt:build Generating .nuxt/ files... +1ms
Ready on http://127.0.0.1:3000
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/alex/workspace/marketplace2/cachorro/nuxt.config.js ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at createFsWatchInstance (/home/alex/workspace/marketplace2/cachorro/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/alex/workspace/marketplace2/cachorro/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/alex/workspace/marketplace2/cachorro/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/alex/workspace/marketplace2/cachorro/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/alex/workspace/marketplace2/cachorro/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cachorro@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cachorro@1.0.0 dev script 'nuxt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cachorro package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cachorro
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cachorro
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2017-04-13T13_15_38_098Z-debug.log


```

Thanks in advance.

**Comment by alexmoreno** [comment]
Well, it's solved by [this answer](http://stackoverflow.com/a/32600959/2299450). I'm not sure if it's appropriate to keep this issue with solution here. If you think it's not appropriate, we can delete it.

` echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p `
