### ISSUE TITLE
Unexpected token export error ” with NUXT/VUE when i have a class/entity file and import it in a util/helper js file

### ISSUE THREAD

**Issue by chandreshSpringer** [nuxt/nuxt.js#5670]
i am getting response from a get call[a list of proposals]. So i created a class with code
```

export default class ProposalRow {
  constructor(status, title, lastModificationDate, id) {
    this.status = status
    this.title = title
    this.id = id
    this.lastModificationDate = lastModificationDate
  }
  static fromJsonData = responseData => {
    return new ProposalRow(
      responseData.status,
      responseData.title,
      responseData.lastModificationDate,
      responseData.id
    )
  }
}
```
i try to use it into on of the apiHandlers[service js file]
```

import ProposalRow from '../types/proposalRow'
.
.

.
.
.
resultArray.push(ProposalRow.fromJsonData(proposal))

```

now then i issue command "npm run dev" no compile error[in console atleast] are there but on UI i get error

[or npm run generate] i get error

```
SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at D:\JFLOW\Development\journal-opportunity-management-ui\node_modules\vue-server-renderer\build.prod.js:1:77688
    at Object.<anonymous> (webpack/bootstrap:2:0)
    at o (webpack/bootstrap:2:0)
    at Object.<anonymous> (src/components/VCounter/index.ts:4:0)
    at o (webpack/bootstrap:2:0)
    at Module.<anonymous> (src/components/VCounter/index.ts:4:0)
```
but if I stage the generated dist folder application runs fine. thanks in advance for help.

**Comment by chandreshSpringer** [comment]
Please let me know if you need any more information as well.
