### ISSUE TITLE
TypeError: fsevents.watch is not a functio

### ISSUE THREAD

**Issue by PTiCA1** [nuxt/nuxt.js#5725]
### Version

[v2.7.0](https://github.com/nuxt.js/releases/tag/v2.7.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/releases/tag/v2.7.0](https://github.com/nuxt/nuxt.js/releases/tag/v2.7.0)

### Steps to reproduce

After updating to version 2.7 after running "yarn dev" displays the following error: 

~~~~
/node_modules/@nuxt/builder/node_modules/chokidar/lib/fsevents-handler.js:57
  const stop = fsevents.watch(path, callback);
                        ^

TypeError: fsevents.watch is not a function
    at createFSEventsInstance (/Applications/MAMP/htdocs/chatbot-admin/node_modules/@nuxt/builder/node_modules/chokidar/lib/fsevents-handler.js:57:25)
    at setFSEventsListener (/Applications/MAMP/htdocs/chatbot-admin/node_modules/@nuxt/builder/node_modules/chokidar/lib/fsevents-handler.js:111:16)
    at FsEventsHandler._watchWithFsEvents (/Applications/MAMP/htdocs/chatbot-admin/node_modules/@nuxt/builder/node_modules/chokidar/lib/fsevents-handler.js:296:18)
    at initWatch (/Applications/MAMP/htdocs/chatbot-admin/node_modules/@nuxt/builder/node_modules/chokidar/lib/fsevents-handler.js:433:27)
    at LOOP (fs.js:1830:14)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error Command failed with exit code 1.
~~~~

![error.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/1758fa10-764c-11e9-a62f-a796438531d3.png)

### What is expected ?

run on localhost:3000

### What is actually happening?

It is not possible to launch a development environment

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9211">#c9211</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. What node.js version do you use?

**Comment by zedix** [comment]
Same issue here on macOS Mojave with node `v12.1.0`. 

A a side note, I also add this warning after the upgrade:

```
 WARN  node-fetch@^2.5.0 is required but node-fetch@2.3.0 is installed!
```

**Comment by pi0** [comment]
Cab you please try cleaning up yarn.lock and try again?

**Comment by zedix** [comment]
It works after deleted the `yarn.lock` and `yarn` again 👍🏻

**Comment by flower-pp** [comment]
update nodejs to v12.7.0  can make it ,too.
