### ISSUE TITLE
不能正确排除node_modules

### ISSUE THREAD

**Issue by Hareis** [nuxt/nuxt.js#5926]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://bug.nuxtjs.org/ ](https://bug.nuxtjs.org/ )

### Steps to reproduce

我使用的是deepin  15.10 linux
nodejs 8.11.2
在使用nuxt -starter 创建项目后发现 

ERROR  watch /media/hareis/DATA/Solution_WebApp/fangqun_web2/node_modules/_@nuxt_vue-app@2.8.1@@nuxt/vue-app/template/layouts/default.vue ENOSPC

  at _errnoException (util.js:992:11)
  at FSWatcher.start (fs.js:1382:19)
  at Object.fs.watch (fs.js:1408:11)
  at createFsWatchInstance (node_modules/_chokidar@3.0.1@chokidar/lib/nodefs-handler.js:64:15)
  at setFsWatchListener (node_modules/_chokidar@3.0.1@chokidar/lib/nodefs-handler.js:113:15)
  at NodeFsHandler._watchWithNodeFs (node_modules/_chokidar@3.0.1@chokidar/lib/nodefs-handler.js:280:14)
  at NodeFsHandler._handleFile (node_modules/_chokidar@3.0.1@chokidar/lib/nodefs-handler.js:311:23)
  at NodeFsHandler._addToNodeFs (node_modules/_chokidar@3.0.1@chokidar/lib/nodefs-handler.js:558:21)
  at <anonymous>
  at process._tickDomainCallback (internal/process/next_tick.js:228:7)

![深度截图_选择区域_201906132205181111111111111.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/54fa4ae0-8de4-11e9-bb9f-2dc69d4072b3.png)

然后是用官网中最简单的hello-world 例子 还是 会发现类似的错误
怀疑是不能正确排除node_modules 导致watch 溢出

在nuxt.config.js 手动指定watch  watchers 任然发生此错误

### What is expected ?

期望能修复错误

### What is actually happening?

什么也没做

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9355">#c9355</a>)</em></sub></div>

**Comment by clarkdo** [comment]
谢谢， 能否提供一个可重现问题的代码仓库和操作步骤？

这部分看起来很奇怪

![image](https://user-images.githubusercontent.com/4312154/59505864-98bcd580-8e9e-11e9-8195-55276d9f2ff9.png)

**Comment by Hareis** [comment]
> 谢谢，能否提供一个可重现问题的代码仓库和操作步骤？
> 
> 这部分看起来很奇怪
> 
> ![图片](https://user-images.githubusercontent.com/4312154/59505864-98bcd580-8e9e-11e9-8195-55276d9f2ff9.png)

使用cnpm 安装了nuxt.js 和相关依赖 ，然后正常启动项目就这样了

**Comment by clarkdo** [comment]
@Hareis 
抱歉, 因为之前的描述比较笼统,很难定位问题
我使用cnpm进行安装,并没有发现问题,能否提供详细步骤以及仓库?

**Comment by Hareis** [comment]
@clarkdo 
我怀疑的deepin的问题  同样的代码 放在win下就是正常的，现在已经转到win下了

**Comment by suisun2015** [comment]
https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve/32600959#32600959
