### ISSUE TITLE
Errors when using vue-function-api plugin in IE11

### ISSUE THREAD

**Issue by mattwaler** [nuxt/nuxt.js#6108]
Tried leaving a comment in CMTY, but could not submit the bug, so I am doing so here.

Source files: https://github.com/mattwaler/personal-site

Nuxt Version: 2.8.1

Bug:
I am attempting to use the new function-api plugin within Nuxt. It appears to work across all browsers EXCEPT for IE11, and I cannot figure out how to fix this.

The plugin works on IE11 when using vue-cli, which is why I am opening an issue here instead of the plugin itself.

Steps:
1. View https://mattwaler.com in IE11
2. Errors in console:

```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
mattwaler.com
HTML1300: Navigation occurred.
mattwaler.com
ReferenceError: 'Reflect' is undefined
   {
      [functions]: ,
      __proto__: { },
      __symbol:0.0810015742477939216: undefined,
      __symbol:0.0810015742477939217: undefined,
      __symbol:__symbol:react.element0.08100157424779392: undefined,
      __symbol:__symbol:vfa.key.postFlushQueue0.08100157424779392: undefined,
      __symbol:__symbol:vfa.key.preFlushQueue0.08100157424779392: undefined,
      __symbol:iterator0.081001574247793921: undefined,
      __symbol:species0.081001574247793922: undefined,
      __symbol:Symbol._hidden0.081001574247793927: undefined,
      __symbol:Symbol.asyncIterator0.081001574247793926: undefined,
      __symbol:Symbol.hasInstance0.081001574247793929: undefined,
      __symbol:Symbol.isConcatSpreadable0.0810015742477939210: undefined,
      __symbol:Symbol.match0.0810015742477939211: undefined,
      __symbol:Symbol.replace0.0810015742477939212: undefined,
      __symbol:Symbol.search0.0810015742477939213: undefined,
      __symbol:Symbol.split0.0810015742477939214: undefined,
      __symbol:Symbol.toPrimitive0.081001574247793928: undefined,
      __symbol:Symbol.toStringTag0.081001574247793925: undefined,
      __symbol:Symbol.unscopables0.0810015742477939215: undefined,
      __symbol:undef0.081001574247793923: undefined,
      __symbol:undef0.081001574247793924: undefined,
      description: "'Reflect' is undefined",
      message: "'Reflect' is undefined",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'Reflect' is undefined
   at t (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:168103)
   at Anonymous function (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:168051)
   at created (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:168973)
   at Qt (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:18665)
   at fn (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:33004)
   at t.prototype._init (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:40737)
   at f (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:38258)
   at Anonymous function (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:26900)
   at He.init (https://d33wubrfki0l68.cloudfront.net/bundles"
   }

ReferenceError: 'Reflect' is undefined
   {
      [functions]: ,
      __proto__: { },
      __symbol:0.0810015742477939216: undefined,
      __symbol:0.0810015742477939217: undefined,
      __symbol:__symbol:react.element0.08100157424779392: undefined,
      __symbol:__symbol:vfa.key.postFlushQueue0.08100157424779392: undefined,
      __symbol:__symbol:vfa.key.preFlushQueue0.08100157424779392: undefined,
      __symbol:iterator0.081001574247793921: undefined,
      __symbol:species0.081001574247793922: undefined,
      __symbol:Symbol._hidden0.081001574247793927: undefined,
      __symbol:Symbol.asyncIterator0.081001574247793926: undefined,
      __symbol:Symbol.hasInstance0.081001574247793929: undefined,
      __symbol:Symbol.isConcatSpreadable0.0810015742477939210: undefined,
      __symbol:Symbol.match0.0810015742477939211: undefined,
      __symbol:Symbol.replace0.0810015742477939212: undefined,
      __symbol:Symbol.search0.0810015742477939213: undefined,
      __symbol:Symbol.split0.0810015742477939214: undefined,
      __symbol:Symbol.toPrimitive0.081001574247793928: undefined,
      __symbol:Symbol.toStringTag0.081001574247793925: undefined,
      __symbol:Symbol.unscopables0.0810015742477939215: undefined,
      __symbol:undef0.081001574247793923: undefined,
      __symbol:undef0.081001574247793924: undefined,
      description: "'Reflect' is undefined",
      message: "'Reflect' is undefined",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'Reflect' is undefined
   at t (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:168103)
   at Anonymous function (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:168051)
   at created (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:168973)
   at Qt (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:18665)
   at fn (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:33004)
   at t.prototype._init (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:40737)
   at f (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:38258)
   at Anonymous function (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:26900)
   at He.init (https://d33wubrfki0l68.cloudfront.net/bundles"
   }

ReferenceError: 'Reflect' is undefined
   {
      [functions]: ,
      __proto__: { },
      __symbol:0.0810015742477939216: undefined,
      __symbol:0.0810015742477939217: undefined,
      __symbol:__symbol:react.element0.08100157424779392: undefined,
      __symbol:__symbol:vfa.key.postFlushQueue0.08100157424779392: undefined,
      __symbol:__symbol:vfa.key.preFlushQueue0.08100157424779392: undefined,
      __symbol:iterator0.081001574247793921: undefined,
      __symbol:species0.081001574247793922: undefined,
      __symbol:Symbol._hidden0.081001574247793927: undefined,
      __symbol:Symbol.asyncIterator0.081001574247793926: undefined,
      __symbol:Symbol.hasInstance0.081001574247793929: undefined,
      __symbol:Symbol.isConcatSpreadable0.0810015742477939210: undefined,
      __symbol:Symbol.match0.0810015742477939211: undefined,
      __symbol:Symbol.replace0.0810015742477939212: undefined,
      __symbol:Symbol.search0.0810015742477939213: undefined,
      __symbol:Symbol.split0.0810015742477939214: undefined,
      __symbol:Symbol.toPrimitive0.081001574247793928: undefined,
      __symbol:Symbol.toStringTag0.081001574247793925: undefined,
      __symbol:Symbol.unscopables0.0810015742477939215: undefined,
      __symbol:undef0.081001574247793923: undefined,
      __symbol:undef0.081001574247793924: undefined,
      description: "'Reflect' is undefined",
      message: "'Reflect' is undefined",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'Reflect' is undefined
   at t (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:168103)
   at Anonymous function (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:168051)
   at created (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:168973)
   at Qt (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:18665)
   at fn (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:33004)
   at t.prototype._init (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:40737)
   at f (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:38258)
   at Anonymous function (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:26900)
   at He.init (https://d33wubrfki0l68.cloudfront.net/bundles"
   }

ReferenceError: 'Reflect' is undefined
   {
      [functions]: ,
      __proto__: { },
      __symbol:0.0810015742477939216: undefined,
      __symbol:0.0810015742477939217: undefined,
      __symbol:__symbol:react.element0.08100157424779392: undefined,
      __symbol:__symbol:vfa.key.postFlushQueue0.08100157424779392: undefined,
      __symbol:__symbol:vfa.key.preFlushQueue0.08100157424779392: undefined,
      __symbol:iterator0.081001574247793921: undefined,
      __symbol:species0.081001574247793922: undefined,
      __symbol:Symbol._hidden0.081001574247793927: undefined,
      __symbol:Symbol.asyncIterator0.081001574247793926: undefined,
      __symbol:Symbol.hasInstance0.081001574247793929: undefined,
      __symbol:Symbol.isConcatSpreadable0.0810015742477939210: undefined,
      __symbol:Symbol.match0.0810015742477939211: undefined,
      __symbol:Symbol.replace0.0810015742477939212: undefined,
      __symbol:Symbol.search0.0810015742477939213: undefined,
      __symbol:Symbol.split0.0810015742477939214: undefined,
      __symbol:Symbol.toPrimitive0.081001574247793928: undefined,
      __symbol:Symbol.toStringTag0.081001574247793925: undefined,
      __symbol:Symbol.unscopables0.0810015742477939215: undefined,
      __symbol:undef0.081001574247793923: undefined,
      __symbol:undef0.081001574247793924: undefined,
      description: "'Reflect' is undefined",
      message: "'Reflect' is undefined",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'Reflect' is undefined
   at t (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:168103)
   at Anonymous function (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:168051)
   at created (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:168973)
   at Qt (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:18665)
   at fn (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:33004)
   at t.prototype._init (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:40737)
   at f (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:38258)
   at Anonymous function (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:26900)
   at He.init (https://d33wubrfki0l68.cloudfront.net/bundles"
   }

TypeError: Unable to get property 'headline' of undefined or null reference
   {
      [functions]: ,
      __proto__: { },
      __symbol:0.0810015742477939216: undefined,
      __symbol:0.0810015742477939217: undefined,
      __symbol:__symbol:react.element0.08100157424779392: undefined,
      __symbol:__symbol:vfa.key.postFlushQueue0.08100157424779392: undefined,
      __symbol:__symbol:vfa.key.preFlushQueue0.08100157424779392: undefined,
      __symbol:iterator0.081001574247793921: undefined,
      __symbol:species0.081001574247793922: undefined,
      __symbol:Symbol._hidden0.081001574247793927: undefined,
      __symbol:Symbol.asyncIterator0.081001574247793926: undefined,
      __symbol:Symbol.hasInstance0.081001574247793929: undefined,
      __symbol:Symbol.isConcatSpreadable0.0810015742477939210: undefined,
      __symbol:Symbol.match0.0810015742477939211: undefined,
      __symbol:Symbol.replace0.0810015742477939212: undefined,
      __symbol:Symbol.search0.0810015742477939213: undefined,
      __symbol:Symbol.split0.0810015742477939214: undefined,
      __symbol:Symbol.toPrimitive0.081001574247793928: undefined,
      __symbol:Symbol.toStringTag0.081001574247793925: undefined,
      __symbol:Symbol.unscopables0.0810015742477939215: undefined,
      __symbol:undef0.081001574247793923: undefined,
      __symbol:undef0.081001574247793924: undefined,
      description: "Unable to get property 'headline' of undefined or null reference",
      message: "Unable to get property 'headline' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to get property 'headline' of undefined or null reference
   at Anonymous function (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:4605)
   at t.prototype._render (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:43205)
   at r (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:72595)
   at xn.prototype.get (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:34430)
   at xn (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:34329)
   at Anonymous function (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:72505)
   at Pn.prototype.$mount (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:72476)
   at He.init (https://d33wubrfki0l68.cloudfront.net/bundles/2ced277c0f2a615da421d945f0b9ff770e736456.js:1:"
   }
```

**Comment by mattwaler** [comment]
FIXED! Woo!

I manually added a plugin that imported  `core-js/fn/reflect` and registered it in nuxt.config.js

```
// plugins/coreJS.js
import 'core-js/fn/reflect'
```

```
// nuxt.config.js
...
plugins: [
...,
~/plugins/coreJS
]

```

Hope this helps anybody else seeing this issue.

**Comment by mattwaler** [comment]
Reopening this issue as it should probably be viewed by the Nuxt team, my solution seems like a workaround instead of an actual fix.

**Comment by manniL** [comment]
@mattwaler 	would it work by adding the plugin to the [`build.transpile` array](https://nuxtjs.org/api/configuration-build/#transpile)?

**Comment by mattwaler** [comment]
@manniL Just tried and it was unsuccessful.

**Comment by mattwaler** [comment]
Probably not worth working on this since the package has been moved/renamed to the composition-api.

Closing.
