### ISSUE TITLE
Cannot find module 'babel-core' error for fresh create-nuxt-app project

### ISSUE THREAD

**Issue by seenickcode** [nuxt/nuxt.js#6176]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/seenickcode/felix-site-fcc](https://github.com/seenickcode/felix-site-fcc)

### Steps to reproduce

```
npx create-nuxt-app felix-site-fcc 
cd felix-site-fcc
yarn install
yarn test
yarn run v1.16.0
$ jest
 FAIL  test/Logo.spec.js
  ● Test suite failed to run

    Cannot find module 'babel-core'
    Require stack:
    - C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\lib\compilers\babel-compiler.js
    - C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\lib\process.js
    - C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\vue-jest.js
    - C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\transform\build\ScriptTransformer.
js
    - C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\transform\build\index.js
    - C:\Users\seenickcode\code\felix-site-fcc\node_modules\jest-runtime\build\index.js
    - C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\core\build\cli\index.js
    - C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\core\build\jest.js
    - C:\Users\seenickcode\code\felix-site-fcc\node_modules\jest-cli\build\cli\index.js
    - C:\Users\seenickcode\code\felix-site-fcc\node_modules\jest-cli\bin\jest.js
    - C:\Users\seenickcode\code\felix-site-fcc\node_modules\jest\bin\jest.js

      at Object.<anonymous> (node_modules/vue-jest/lib/compilers/babel-compiler.js:1:15)

Running coverage on untested files...Failed to collect coverage from C:\Users\seenickcode\code\felix
-site-fcc\pages\index.vue
ERROR: Cannot find module 'babel-core'
Require stack:
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\lib\compilers\babel-compiler.js    
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\lib\process.js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\vue-jest.js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\transform\build\ScriptTransformer.js  
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\transform\build\index.js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\reporters\build\generateEmptyCoverage.
js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\reporters\build\coverage_worker.js    
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\jest-worker\build\workers\processChild.js   
STACK: Error: Cannot find module 'babel-core'
Require stack:
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\lib\compilers\babel-compiler.js    
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\lib\process.js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\vue-jest.js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\transform\build\ScriptTransformer.js  
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\transform\build\index.js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\reporters\build\generateEmptyCoverage.
js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\reporters\build\coverage_worker.js    
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\jest-worker\build\workers\processChild.js   
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\lib\compil
ers\babel-compiler.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
Failed to collect coverage from C:\Users\seenickcode\code\felix-site-fcc\components\Logo.vue        
ERROR: Cannot find module 'babel-core'
Require stack:
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\lib\compilers\babel-compiler.js    
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\lib\process.js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\vue-jest.js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\transform\build\ScriptTransformer.js  
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\transform\build\index.js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\reporters\build\generateEmptyCoverage.
js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\reporters\build\coverage_worker.js    
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\jest-worker\build\workers\processChild.js   
STACK: Error: Cannot find module 'babel-core'
Require stack:
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\lib\compilers\babel-compiler.js    
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\lib\process.js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\vue-jest.js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\transform\build\ScriptTransformer.js  
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\transform\build\index.js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\reporters\build\generateEmptyCoverage.
js
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\@jest\reporters\build\coverage_worker.js    
- C:\Users\seenickcode\code\felix-site-fcc\node_modules\jest-worker\build\workers\processChild.js   
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\seenickcode\code\felix-site-fcc\node_modules\vue-jest\lib\compil
ers\babel-compiler.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.949s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What is expected ?

Tests to run.

### What is actually happening?

ERROR: Cannot find module 'babel-core'

### Additional comments?

Windows 10 Pro
node v12.4.0
npm v6.9.0

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9596">#c9596</a>)</em></sub></div>

**Comment by matheuschimelli** [comment]
Have you ever tried to install using `npm install` instead `yarn`?

**Comment by charlesBochet** [comment]
@matheuschimelli I'm facing the same issue on MacOS node v8.15.1 and `npm install`.

**Comment by clarkdo** [comment]
Fixed in create-nuxt-app@2.9.1

**Comment by webcoderkz** [comment]
@clarkdo not fixed even in latest create-nuxt-app

**Comment by clarkdo** [comment]
@webcoderkz Can you show me your ` create-nuxt-app` and detail log ?

**Comment by webcoderkz** [comment]
@clarkdo 

```
info "create-nuxt-app@3.0.0" has binaries:
   - create-nuxt-app
```

**Comment by clarkdo** [comment]
Can you please provide log as original issue ?

**Comment by webcoderkz** [comment]
It's the same as above:

"Test suite failed to run Cannot find module 'babel-core'"

**Comment by clarkdo** [comment]
@webcoderkz This is my local screeshot, it works fine and `"babel-core": "7.0.0-bridge.0` is in `devDependencies`.

<img width="868" alt="截屏2020-07-13 20 04 22" src="https://user-images.githubusercontent.com/4312154/87343042-29536280-c544-11ea-8496-81fa6480413f.png">

Can you check your `package.json` ? If there is `babel-core`, I think you can re-install node_modules without `--production` flag in `yarn` or `npm` or  setting NODE_ENV to be `production`

**Comment by webcoderkz** [comment]
@clarkdo i installed myself `babel-core` bridge 0, then it worked. But you said that with the newer version of nuxt-create-app it's working out of the box, hence i said - it doesn't.
