### ISSUE TITLE
console throw error: Callback must be a function. in nuxt 2.8.1 in node 10.2.1

### ISSUE THREAD

**Issue by ssly** [nuxt/nuxt.js#6219]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)

### Steps to reproduce

1. create a program by nuxt 2.8.1
2. npm run dev
3. error in console is
```
 ERROR  Callback must be a function                                                                                                                         

  at makeStatsCallback (fs.js:178:11)
  at ReaddirpStream.fs.lstat (fs.js:905:14)
  at ReaddirpStream._statMethod (internal/util.js:280:30)
  at ReaddirpStream._stat (node_modules\@nuxt\builder\node_modules\readdirp\index.js:171:19)
  at ReaddirpStream._formatEntry (node_modules\@nuxt\builder\node_modules\readdirp\index.js:186:28)
  at Promise.all.files.map.dirent (node_modules\@nuxt\builder\node_modules\readdirp\index.js:150:65)
  at Array.map (<anonymous>)
  at ReaddirpStream._exploreDirectory (node_modules\@nuxt\builder\node_modules\readdirp\index.js:150:45)

```

### What is expected ?

no error in console

### What is actually happening?

throw error in console

### Additional comments?

node -v
v10.2.1
npm -v
5.6.0
nuxt version 
2.8.1

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9629">#c9629</a>)</em></sub></div>

**Comment by manniL** [comment]
![image](https://user-images.githubusercontent.com/640208/62876524-6bb56380-bd25-11e9-8bd0-ea5cd95c7786.png)

Can't reproduce.

**Comment by pi0** [comment]
This might be due to old fs-extra dependency i your project. Try cleaning node_modules and lock file
