### ISSUE TITLE
TypeError: Cannot read property '$createElement' of null

### ISSUE THREAD

**Issue by krasevych** [nuxt/nuxt.js#630]
I use Nuxt and I have a code:
```
@Component({
  functional: true
})
class KrTransition extends Vue {
  render() {
    return <h1>hello</h1>;
  }
}

export default KrTransition;
```
when I try use it, I get a error:
```
Nuxt.js Error:

TypeError: Cannot read property '$createElement' of null
    at render (src/components/KrTransition/KrTransition.js:8:11)
    at createFunctionalComponent (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3073:35)
    at createComponent (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3027:12)
    at _createElement (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3327:15)
    at createElement (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3281:10)
    at vm._c (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3569:42)
    at Proxy.render (src/components/ImageSlider/ImageSlider.vue?92ca:2:0)
    at VueComponent.Vue._render (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3605:22)
    at renderComponent (D:\Projects\Vue\smart-landing\node_modules\vue-server-renderer\build.js:6698:25)
    at RenderContext.renderNode (D:\Projects\Vue\smart-landing\node_modules\vue-server-renderer\build.js:6681:7)
```

**Comment by krasevych** [comment]
it was a auto-injection problems, the PR fix it - https://github.com/vuejs/vue/pull/5534
