### ISSUE TITLE
 nuxt.js 2.9 typescript About error after deploying Google App Engine

### ISSUE THREAD

**Issue by usacoasts** [nuxt/nuxt.js#6364]
# Contents of question

I am Japanese,
Sorry, it's hard to understand

Introducing typescript in Nuxt.js 2.9
After checking the operation in the local environment,
When you deploy to Google App Engine
An error occurs that the external module cannot be used.

In the subsequent URL referral,
```
Nuxt TypeScript Support mainly comes through a Nuxt module, @nuxt/typescript-build.
```
It has been described as

(https://typescript.nuxtjs.org/guide/setup.html#installation)

I think
When deploying GAE
Whether `@nuxt/typescript-build` failed when installing on `package.json`
I think that `@nuxt/typescript-build` part of `buildModules` of `nuxt.config.ts` is not working well.

If you know anyone, would you please teach me?

Thank you in advance.

# Source Code

package.json
```
{
  "name": "test",
  "version": "2.8.0",
  "description": "nuxt.js project",
  "author": "test",
  "private": true,
  "scripts": {
    "dev": "nuxt-ts",
    "build": "nuxt-ts build",
    "start": "nuxt-ts start",
    "generate": "nuxt-ts generate",
    "lint": "eslint --ext .ts,.js,.vue --ignore-path .eslintignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "@nuxt/typescript-runtime": "^0.1.5",
    "@nuxtjs/axios": "^5.6.0",
    "@nuxtjs/google-tag-manager": "^2.2.1",
    "@nuxtjs/proxy": "^1.3.3",
    "@nuxtjs/sitemap": "^1.2.0",
    "@nuxtjs/toast": "^3.2.1",
    "@sentry/browser": "^5.5.0",
    "@sentry/integrations": "^5.5.0",
    "@types/node": "^12.7.4",
    "algoliasearch": "^3.33.0",
    "anchorify": "^1.0.2",
    "autocomplete.js": "^0.36.0",
    "autolinker": "^3.1.0",
    "aws-serverless-express": "^3.3.6",
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "^2.0.0-rc.26",
    "card-validator": "^6.2.0",
    "cookie": "^0.4.0",
    "cookie-universal-nuxt": "^2.0.16",
    "cookieparser": "^0.1.0",
    "cross-env": "^5.2.0",
    "date-time-format-timezone": "^1.0.21",
    "dotenv": "^8.0.0",
    "emoji-js": "^3.4.1",
    "env-parser": "^1.0.1",
    "escape-goat": "^2.1.0",
    "express": "^4.17.1",
    "japan-postal-code": "^0.2.0",
    "jquery": "^3.4.1",
    "jspdf": "^1.5.3",
    "laravel-echo": "^1.5.4",
    "luxon": "^1.17.1",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.26",
    "msgdown": "^1.0.2",
    "nuxt": "^2.8.1",
    "nuxt-basic-auth-module": "^1.2.0",
    "nuxt-client-init-module": "^0.1.4",
    "nuxt-device-detect": "^1.1.5",
    "popper.js": "^1.15.0",
    "pusher-js": "^4.4.0",
    "sanitize-html": "^1.20.1",
    "ts-node": "^8.3.0",
    "v-tooltip": "^2.0.2",
    "vue-autosuggest": "^2.0.1",
    "vue-awesome-swiper": "^3.1.3",
    "vue-clipboard2": "^0.3.0",
    "vue-datetime": "^1.0.0-beta.8",
    "vue-html2canvas": "0.0.4",
    "vue-instantsearch": "^2.2.2",
    "vue-intercom": "^1.0.14",
    "vue-kindergarten": "^0.3.3",
    "vue-loading-template": "^1.3.2",
    "vue-property-decorator": "^8.2.1",
    "vue-slide-up-down": "^1.7.2",
    "vue-the-mask": "^0.11.1",
    "vue-tippy": "^2.1.3",
    "vuejs-datepicker": "^1.6.2",
    "vuelidate": "^0.7.4",
    "vuex-persistedstate": "^2.5.4",
    "vuex-storage-sync": "^1.1.6",
    "weekstart": "^1.0.0"
  },
  "devDependencies": {
    "@nuxt/typescript-build": "^0.2.1",
    "@typescript-eslint/eslint-plugin": "^1.12.0",
    "@typescript-eslint/parser": "^1.12.0",
    "acorn": "^6.2.0",
    "acorn-dynamic-import": "^4.0.0",
    "babel-eslint": "^10.0.2",
    "eslint": "^5.0.0",
    "eslint-config-prettier": "^6.0.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.2.1",
    "eslint-plugin-prettier": "3.1.0",
    "eslint-plugin-vue": "^5.2.3",
    "node-sass": "^4.12.0",
    "nodemon": "^1.19.1",
    "npm-run-all": "^4.1.5",
    "prettier": "^1.18.2",
    "sass-loader": "^7.1.0"
  },
  "browserslist": [
    "last 2 version",
    "android >= 4.4",
    "IE 11"
  ]
}
```

nuxt.config.ts
```
import generateUrlFromResource from './services/GenerateUrlFromResource'
const webpack = require('webpack')
const path = require('path')
const axios = require('axios')

let envPath = './.env'
if (process.env.NODE_ENV === 'production') {
  envPath = './.env.prod'
} else if (process.env.NODE_ENV === 'staging') {
  envPath = './.env.stg'
}
const Parsed = require('dotenv').config({
  path: envPath
}).parsed

module.exports = {
buildModules: [
    ['@nuxt/typescript-build', {
      typeCheck: true,
      ignoreNotFoundWarnings: true
    }]
  ],
  typescript: {
    typeCheck: true,
    ignoreNotFoundWarnings: true
  },
  router: {
    linkExactActiveClass: 'active-link'
  },
  env: {
    ...Parsed
  },
  head: {
    title: 'test',
    meta: [
      { charset: 'utf-8' },
      { hid: 'viewport', name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { name: 'google-site-verification', content: '9st-McgIso5v__qoLTVTrX81FXW2HxbAI5c3-6U1LX0' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
      { rel: 'stylesheet', href: '//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' }
    ],
    script: [
      { src: '//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js'},
      { src: '/fitie.js' },
      { src: 'https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch,Object.entries,String.prototype.repeat,Array.prototype.find,Array.prototype.findIndex,Math.trunc,Intl.~locale.ja' }
    ]
  },
  watchQuery: true,
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/proxy',
    '@nuxtjs/toast',
    '@nuxtjs/sitemap',
    'bootstrap-vue/nuxt',
    'nuxt-device-detect',
    'cookie-universal-nuxt',
    'nuxt-client-init-module',
    'nuxt-basic-auth-module',
    ['@nuxtjs/google-tag-manager', {id: Parsed.GTM_TAG_ID, pageTracking: true }]
  ],
  basic: {
    name: 'test',
    pass: 'test',
    enabled: process.env.NODE_ENV === 'staging'
  },
  axios: {
    credentials: true,
    baseUrl: '/api'
  },
  proxy: {
    '/api/': JSON.stringify(Parsed.API_URL)
  },
  build: {
    plugins: [
      new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery'
      })
    ],
    vendor: [
      'vue-awesome-swiper'
    ],
    extend (config, { isDev, isClient }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
      config.resolve.alias['services'] = path.join(__dirname, 'services')
    }
  },
  plugins: [
    '~/plugins/axios.js',
    '~/plugins/algoliasearch.js',
    '~/plugins/bootstrap.js',
    '~/plugins/filters.js',
    '~/plugins/global.js',
    '~/plugins/moment.js',
    '~/plugins/mixins/flash.js',
    '~/plugins/mixins/form-handler.js',
    '~/plugins/mixins/user.js',
    '~/plugins/v-tooltip',
    '~/plugins/vue-autosuggest',
    '~/plugins/vue-clipboard2',
    '~/plugins/vue-datetime',
    '~/plugins/vue-intercom',
    '~/plugins/vue-the-mask',
    '~/plugins/vuelidate.js',
    '~/plugins/truncate.js',
    { src: '~/plugins/sentry.js' },
    { src: '~/plugins/tippy.js', ssr: false },
    { src: '~/plugins/laravel-echo.js', ssr: false },
    { src: '~/plugins/vue-loading.js', ssr: false },
    { src: '~/plugins/vuex-persistedstate', ssr: false },
    { src: '~/plugins/jspdf', ssr: false },
    { src: '~/plugins/html2canvas', ssr: false },
    { src: '~plugins/vue-awesome-swiper', ssr: false },
    { src: '~/plugins/router-option.js', ssr: false }
  ],
  toast: {
    position: 'bottom-left',
    duration: 2000
  },
  loading: {
    name: 'chasing-dots',
    color: '#ff5638',
    background: 'white',
    height: '4px'
  },
  sitemap: {
    path: '/sitemap.xml',
    hostname: Parsed.BASE_URL,
    cacheTime: 1000 * 60 * 15,
    gzip: true,
    generate: false, // Enable me when using nuxt generate
    exclude: [
      '/test',
      '/test1',
      '/test2/**'
    ],
    routes (callback) {
      axios.get(Parsed.API_URL + '/sitemap')
        .then(response => {
          const productRoutes = generateUrlFromResource(response.data.products, 'product')
          const categoryRoutes = generateUrlFromResource(response.data.categories, 'category')
          callback(null, productRoutes.concat(categoryRoutes))
        })
        .catch(callback)
    }
  }
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": [
      "esnext",
      "esnext.asynciterable",
      "dom"
    ],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": false,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "./*"
      ],
      "@/*": [
        "./*"
      ]
    },
    "types": [
      "@types/node",
      "@nuxt/types"
    ]
  },
  "exclude": [
    "node_modules"
  ]
}

```

# Error log
` gcloud app logs tail -s default`
```
Waiting for new log entries...
2019-09-05 09:31:08 default[20190905t175655]    at VueComponent.created (server.js:1:0)
2019-09-05 09:31:08 default[20190905t175655]    at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)
2019-09-05 09:31:08 default[20190905t175655]    at callHook (node_modules/vue/dist/vue.runtime.common.dev.js:4201:7)
2019-09-05 09:31:08 default[20190905t175655]    at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:4983:5)
2019-09-05 09:31:08 default[20190905t175655]
2019-09-05 09:31:09 default[20190905t175655]  "GET /favicon.ico HTTP/1.1" 204
2019-09-05 09:31:09 default[20190905t175655]  "GET / HTTP/1.1" 500
2019-09-05 09:31:09 default[20190905t175655]
2019-09-05 09:31:09 default[20190905t175655]   ERROR  [vuex] unknown action type: products/fetch
2019-09-05 09:31:09 default[20190905t175655]
2019-09-05 09:31:09 default[20190905t175655]
2019-09-05 09:31:09 default[20190905t175655]   ERROR  [Vue warn]: Error in getter for watcher "function () { return getter(this$1.state, this$1.getters); }": "TypeError: Cannot read property 'user' of undefined"
2019-09-05 09:31:09 default[20190905t175655]
2019-09-05 09:31:09 default[20190905t175655]  (found in <Root>)
2019-09-05 09:31:09 default[20190905t175655]
2019-09-05 09:31:09 default[20190905t175655]
2019-09-05 09:31:09 default[20190905t175655]   ERROR  [Vue warn]: Error in created hook: "TypeError: Cannot read property 'user' of undefined"
2019-09-05 09:31:09 default[20190905t175655]
2019-09-05 09:31:09 default[20190905t175655]  found in
2019-09-05 09:31:09 default[20190905t175655]
2019-09-05 09:31:09 default[20190905t175655]  ---> <Anonymous>
2019-09-05 09:31:09 default[20190905t175655]         <Root>
2019-09-05 09:31:09 default[20190905t175655]
2019-09-05 09:31:09 default[20190905t175655]
2019-09-05 09:31:09 default[20190905t175655]   ERROR  Cannot read property 'user' of undefined
2019-09-05 09:31:09 default[20190905t175655]
2019-09-05 09:31:09 default[20190905t175655]    at $store.watch.t (server.js:1:0)
2019-09-05 09:31:09 default[20190905t175655]    at Vue.<anonymous> (node_modules/vuex/dist/vuex.common.js:471:54)
2019-09-05 09:31:09 default[20190905t175655]    at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4459:25)
2019-09-05 09:31:09 default[20190905t175655]    at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4448:12)
2019-09-05 09:31:09 default[20190905t175655]    at Vue.$watch (node_modules/vue/dist/vue.runtime.common.dev.js:4923:19)
2019-09-05 09:31:09 default[20190905t175655]    at Store.watch (node_modules/vuex/dist/vuex.common.js:471:26)
2019-09-05 09:31:09 default[20190905t175655]    at VueComponent.created (server.js:1:0)
2019-09-05 09:31:09 default[20190905t175655]    at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)
2019-09-05 09:31:09 default[20190905t175655]    at callHook (node_modules/vue/dist/vue.runtime.common.dev.js:4201:7)
2019-09-05 09:31:09 default[20190905t175655]    at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:4983:5)
2019-09-05 09:31:09 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]  "GET / HTTP/1.1" 500
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]   ERROR  [vuex] unknown action type: products/fetch
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]   ERROR  [Vue warn]: Error in getter for watcher "function () { return getter(this$1.state, this$1.getters); }": "TypeError: Cannot read property 'user' of undefined"
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]  (found in <Root>)
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]   ERROR  [Vue warn]: Error in created hook: "TypeError: Cannot read property 'user' of undefined"
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]  found in
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]  ---> <Anonymous>
2019-09-05 09:31:10 default[20190905t175655]         <Root>
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]   ERROR  Cannot read property 'user' of undefined
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]    at $store.watch.t (server.js:1:0)
2019-09-05 09:31:10 default[20190905t175655]    at Vue.<anonymous> (node_modules/vuex/dist/vuex.common.js:471:54)
2019-09-05 09:31:10 default[20190905t175655]    at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4459:25)
2019-09-05 09:31:10 default[20190905t175655]    at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4448:12)
2019-09-05 09:31:10 default[20190905t175655]    at Vue.$watch (node_modules/vue/dist/vue.runtime.common.dev.js:4923:19)
2019-09-05 09:31:10 default[20190905t175655]    at Store.watch (node_modules/vuex/dist/vuex.common.js:471:26)
2019-09-05 09:31:10 default[20190905t175655]    at VueComponent.created (server.js:1:0)
2019-09-05 09:31:10 default[20190905t175655]    at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)
2019-09-05 09:31:10 default[20190905t175655]    at callHook (node_modules/vue/dist/vue.runtime.common.dev.js:4201:7)
2019-09-05 09:31:10 default[20190905t175655]    at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:4983:5)
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]  "GET /favicon.ico HTTP/1.1" 204
2019-09-05 09:31:10 default[20190905t175655]  "GET / HTTP/1.1" 500
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]   ERROR  [vuex] unknown action type: products/fetch
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]   ERROR  [Vue warn]: Error in getter for watcher "function () { return getter(this$1.state, this$1.getters); }": "TypeError: Cannot read property 'user' of undefined"
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]  (found in <Root>)
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]   ERROR  [Vue warn]: Error in created hook: "TypeError: Cannot read property 'user' of undefined"
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]  found in
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:10 default[20190905t175655]  ---> <Anonymous>
2019-09-05 09:31:10 default[20190905t175655]         <Root>
2019-09-05 09:31:10 default[20190905t175655]
2019-09-05 09:31:11 default[20190905t175655]
2019-09-05 09:31:11 default[20190905t175655]   ERROR  Cannot read property 'user' of undefined
2019-09-05 09:31:11 default[20190905t175655]
2019-09-05 09:31:11 default[20190905t175655]    at $store.watch.t (server.js:1:0)
2019-09-05 09:31:11 default[20190905t175655]    at Vue.<anonymous> (node_modules/vuex/dist/vuex.common.js:471:54)
2019-09-05 09:31:11 default[20190905t175655]    at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4459:25)
2019-09-05 09:31:11 default[20190905t175655]    at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4448:12)
2019-09-05 09:31:11 default[20190905t175655]    at Vue.$watch (node_modules/vue/dist/vue.runtime.common.dev.js:4923:19)
2019-09-05 09:31:11 default[20190905t175655]    at Store.watch (node_modules/vuex/dist/vuex.common.js:471:26)
2019-09-05 09:31:11 default[20190905t175655]    at VueComponent.created (server.js:1:0)
2019-09-05 09:31:11 default[20190905t175655]    at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)
2019-09-05 09:31:11 default[20190905t175655]    at callHook (node_modules/vue/dist/vue.runtime.common.dev.js:4201:7)
2019-09-05 09:31:11 default[20190905t175655]    at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:4983:5)
2019-09-05 09:31:11 default[20190905t175655]
2019-09-05 09:31:11 default[20190905t182804]  "GET / HTTP/1.1" 500
2019-09-05 09:31:21 default[20190905t182804]
2019-09-05 09:31:21 default[20190905t182804]   WARN  vendor has been deprecated due to webpack4 optimization
2019-09-05 09:31:21 default[20190905t182804]
2019-09-05 09:31:23 default[20190905t182804]  ℹ Register basic auth module to server middleware
2019-09-05 09:31:23 default[20190905t182804]  ℹ Listening on: http://192.168.1.1:8080/
2019-09-05 09:31:24 default[20190905t182804]  App is listening on port 8080, it should instead listen on the port defined by the PORT environment variable. As a consequence, nginx cannot be started. Performance may be degraded. Please listen on the port defined by the PORT environment variable.
2019-09-05 09:31:24 default[20190905t182804]   ERROR  [vuex] unknown action type: products/fetch
2019-09-05 09:31:24 default[20190905t182804]
2019-09-05 09:31:24 default[20190905t182804]
2019-09-05 09:31:24 default[20190905t182804]   ERROR  [Vue warn]: Error in getter for watcher "function () { return getter(this$1.state, this$1.getters); }": "TypeError: Cannot read property 'user' of undefined"
2019-09-05 09:31:24 default[20190905t182804]
2019-09-05 09:31:24 default[20190905t182804]  (found in <Root>)
2019-09-05 09:31:24 default[20190905t182804]
2019-09-05 09:31:24 default[20190905t182804]
2019-09-05 09:31:24 default[20190905t182804]   ERROR  [Vue warn]: Error in created hook: "TypeError: Cannot read property 'user' of undefined"
2019-09-05 09:31:24 default[20190905t182804]
2019-09-05 09:31:24 default[20190905t182804]  found in
2019-09-05 09:31:24 default[20190905t182804]
2019-09-05 09:31:24 default[20190905t182804]  ---> <Anonymous>
2019-09-05 09:31:24 default[20190905t182804]         <Root>
2019-09-05 09:31:24 default[20190905t182804]
2019-09-05 09:31:24 default[20190905t182804]
2019-09-05 09:31:24 default[20190905t182804]   ERROR  Cannot read property 'user' of undefined
2019-09-05 09:31:24 default[20190905t182804]
2019-09-05 09:31:24 default[20190905t182804]    at $store.watch.t (server.js:1:0)
2019-09-05 09:31:24 default[20190905t182804]    at Vue.<anonymous> (node_modules/vuex/dist/vuex.common.js:471:54)
2019-09-05 09:31:24 default[20190905t182804]    at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4459:25)
2019-09-05 09:31:24 default[20190905t182804]    at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4448:12)
2019-09-05 09:31:24 default[20190905t182804]    at Vue.$watch (node_modules/vue/dist/vue.runtime.common.dev.js:4923:19)
2019-09-05 09:31:24 default[20190905t182804]    at Store.watch (node_modules/vuex/dist/vuex.common.js:471:26)
2019-09-05 09:31:24 default[20190905t182804]    at VueComponent.created (server.js:1:0)
2019-09-05 09:31:24 default[20190905t182804]    at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)
2019-09-05 09:31:24 default[20190905t182804]    at callHook (node_modules/vue/dist/vue.runtime.common.dev.js:4201:7)
2019-09-05 09:31:24 default[20190905t182804]    at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:4983:5)
2019-09-05 09:31:24 default[20190905t182804]
2019-09-05 09:31:24 default[20190905t182804]  "GET /favicon.ico HTTP/1.1" 204
2019-09-05 09:31:29 default[20190905t182804]  "GET / HTTP/1.1" 500
2019-09-05 09:31:29 default[20190905t182804]
2019-09-05 09:31:29 default[20190905t182804]   ERROR  [vuex] unknown action type: products/fetch
2019-09-05 09:31:29 default[20190905t182804]
2019-09-05 09:31:29 default[20190905t182804]
2019-09-05 09:31:29 default[20190905t182804]   ERROR  [Vue warn]: Error in getter for watcher "function () { return getter(this$1.state, this$1.getters); }": "TypeError: Cannot read property 'user' of undefined"
2019-09-05 09:31:29 default[20190905t182804]
2019-09-05 09:31:29 default[20190905t182804]  (found in <Root>)
2019-09-05 09:31:29 default[20190905t182804]
2019-09-05 09:31:29 default[20190905t182804]
2019-09-05 09:31:29 default[20190905t182804]   ERROR  [Vue warn]: Error in created hook: "TypeError: Cannot read property 'user' of undefined"
2019-09-05 09:31:29 default[20190905t182804]
2019-09-05 09:31:29 default[20190905t182804]  found in
2019-09-05 09:31:29 default[20190905t182804]
2019-09-05 09:31:29 default[20190905t182804]  ---> <Anonymous>
2019-09-05 09:31:29 default[20190905t182804]         <Root>
2019-09-05 09:31:29 default[20190905t182804]
2019-09-05 09:31:29 default[20190905t182804]
2019-09-05 09:31:29 default[20190905t182804]   ERROR  Cannot read property 'user' of undefined
2019-09-05 09:31:29 default[20190905t182804]
2019-09-05 09:31:29 default[20190905t182804]    at $store.watch.t (server.js:1:0)
2019-09-05 09:31:29 default[20190905t182804]    at Vue.<anonymous> (node_modules/vuex/dist/vuex.common.js:471:54)
2019-09-05 09:31:29 default[20190905t182804]    at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4459:25)
2019-09-05 09:31:29 default[20190905t182804]    at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4448:12)
2019-09-05 09:31:29 default[20190905t182804]    at Vue.$watch (node_modules/vue/dist/vue.runtime.common.dev.js:4923:19)
2019-09-05 09:31:29 default[20190905t182804]    at Store.watch (node_modules/vuex/dist/vuex.common.js:471:26)
2019-09-05 09:31:29 default[20190905t182804]    at VueComponent.created (server.js:1:0)
2019-09-05 09:31:29 default[20190905t182804]    at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)
2019-09-05 09:31:29 default[20190905t182804]    at callHook (node_modules/vue/dist/vue.runtime.common.dev.js:4201:7)
2019-09-05 09:31:29 default[20190905t182804]    at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:4983:5)
2019-09-05 09:31:29 default[20190905t182804]
2019-09-05 09:31:29 default[20190905t182804]  "GET /favicon.ico HTTP/1.1" 204`
```

# FW Version
```
Nuxt.js(SSR) v2.9.2 
Vue.js 3.8.4
```

# Reference
https://typescript.nuxtjs.org/

**Comment by usacoasts** [comment]
Excuse me
I had to run nuxt-ts build during deployment,
A nuxt build was executed by mistake.


Nuxt.js2.9 (SSR) typescript works without problems on GAE.

**Comment by usacoasts** [comment]
Excuse me
I had to run nuxt-ts build during deployment,
A nuxt build was executed by mistake.


Nuxt.js2.9 (SSR) typescript works without problems on GAE.
