### ISSUE TITLE
Multiple Assets Emit to the Same Filename

### ISSUE THREAD

**Issue by phillipcurl** [nuxt/nuxt.js#6409]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://github.com/phillipcurl/nuxt-test](https://github.com/phillipcurl/nuxt-test)

### Steps to reproduce

- Clone repo
- `npm i`
- `npm run dev`
- save any page, layout, component, etc.

### What is expected ?

The dev server re-builds the necessary files and hot-reloads.

### What is actually happening?

The dev server crashes and emits the following error:

```
/Users/PC/projects/nuxt-test/node_modules/webpack/lib/Compilation.js:1994
				throw new Error(
				^

Error: Conflict: Multiple assets emit to the same filename 1debded57fadef5ec63a.hot-update.json
    at Compilation.emitAsset (/Users/PC/projects/nuxt-test/node_modules/webpack/lib/Compilation.js:1994:11)
    at /Users/PC/projects/nuxt-test/node_modules/webpack/lib/Compiler.js:333:28
    at /Users/PC/projects/nuxt-test/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/PC/projects/nuxt-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/PC/projects/nuxt-test/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/PC/projects/nuxt-test/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/PC/projects/nuxt-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/PC/projects/nuxt-test/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/PC/projects/nuxt-test/node_modules/webpack/lib/Compilation.js:1404:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/PC/projects/nuxt-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/PC/projects/nuxt-test/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/PC/projects/nuxt-test/node_modules/webpack/lib/Compilation.js:1395:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/PC/projects/nuxt-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/PC/projects/nuxt-test/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/PC/projects/nuxt-test/node_modules/webpack/lib/Compilation.js:1390:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/PC/projects/nuxt-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9770">#c9770</a>)</em></sub></div>

**Comment by fitztrev** [comment]
Webpack v4.40.1 has been released and fixes this.

**Comment by fontzter** [comment]
I am also getting the relative path issue with Webpack 4.40.1 and 4.40.2

```
 ERROR  Failed to compile with 2 errors                                                                                                                                                           friendly-errors 12:37:06

These relative modules were not found:                                                                                                                                                            friendly-errors 12:37:06
                                                                                                                                                                                                  friendly-errors 12:37:06
* ../node_modules/vuetify/dist/vuetify.css in ./.nuxt/App.js                                                                                                                                      friendly-errors 12:37:06
* ../layouts/error.vue in ./.nuxt/index.js  
```
any ideas?

**Comment by phillipcurl** [comment]
@fontzter What do your imports look like for those files? I haven't run into this issue again since the 4.40.1 release of Webpack like @fitztrev mentioned. A demo repo would be helpful as well.

**Comment by phillipcurl** [comment]
I'm going to close this because I think it might cause confusion for people running into a similar error, as it's likely not related to Webpack unless they're on the 4.40.0 release.
