### ISSUE TITLE
nuxt build error

### ISSUE THREAD

**Issue by b-m-9** [nuxt/nuxt.js#6502]
Nuxt 2.10.0 error build project
```
 ERROR   /en/                                                                                                              18:19:39

TypeError: Cannot read property 'renderRoute' of undefined
    at Generator.generateRoute (/home/exchanger/exchanger-admin-web/node_modules/@nuxt/generator/dist/generator.js:222:42)
    at /home/exchanger/exchanger-admin-web/node_modules/@nuxt/generator/dist/generator.js:120:24
    at async Promise.all (index 140)
    at async Generator.generateRoutes (/home/exchanger/exchanger-admin-web/node_modules/@nuxt/generator/dist/generator.js:115:7)
    at async Generator.generate (/home/exchanger/exchanger-admin-web/node_modules/@nuxt/generator/dist/generator.js:48:20)
    at async Object.run (/home/exchanger/exchanger-admin-web/node_modules/@nuxt/cli/dist/cli-build.js:101:5)
    at async NuxtCommand.run (/home/exchanger/exchanger-admin-web/node_modules/@nuxt/cli/dist/cli-command.js:2575:7)


 FATAL  Cannot read property 'renderRoute' of undefined                                                                    18:19:39

  at Generator.afterGenerate (node_modules/@nuxt/generator/dist/generator.js:168:43)
  at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:50:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:101:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-command.js:2575:7)


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │   ✖ Nuxt Fatal Error                                           │
   │                                                                │
   │   TypeError: Cannot read property 'renderRoute' of undefined   │


```

**Comment by b-m-9** [comment]
why

**Comment by b-m-9** [comment]
this is bug

**Comment by pirmax** [comment]
I've the same error with this red error : `TypeError: Cannot read property 'keyName' of undefined`

**Comment by LukaszRatajczyk** [comment]
Same thing, while build TypeError: Cannot read property 'renderRoute' of undefined
and in Dev TypeError: Cannot read property 'keyName' of undefined

**Comment by b-jan** [comment]
I have the same error for each route of my app: `Cannot read property 'renderRoute' of undefined` when I run `nuxt-ts build`

**Comment by charlieBriab** [comment]
I get the same problem, errors on on my routes Cannot read property 'renderRoute' of undefined when I run build

**Comment by eddieebeling** [comment]
Exact same issue. I just downgraded to 2.9.2 and it's building again.

**Comment by pirmax** [comment]
I've the same error with `nuxt-ts` command (_yarn dev_).

Using `yarn add --dev @nuxt/typescript-build`

**Comment by jjhesk** [comment]
whats the problem? i keep getting the problem..

**Comment by lifenautjoe** [comment]
Why is this closed? 😭

**Comment by Musbell** [comment]
Same issue

**Comment by gringolalia** [comment]
Also me

**Comment by gringolalia** [comment]
I was trying to build my Nuxt project with Node version 10.16.0 and received the error in question.

But and so as it is often worth trying I set the version using `nvm use stable` to the latest stable release which is 12.6.0 ... and my project now builds ... my NPM version is 6.12.0.

**Comment by marcoadasilvaa** [comment]
Same issue here, somebody help?
