### ISSUE TITLE
nuxt build fails with spa mode

### ISSUE THREAD

**Issue by vinayakkulkarni** [nuxt/nuxt.js#6519]
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://github.com/vinayakkulkarni/nuxt-2.10-bug](https://github.com/vinayakkulkarni/nuxt-2.10-bug)

### Steps to reproduce

npm install
npm run build

### What is expected ?

Nuxt to build all routes and files post build success. 

### What is actually happening?

```
ℹ Generating pages                                                                                                                                                                                  18:52:53

 ERROR   /                                                                                                                                                                                          18:52:53

TypeError: Cannot read property 'renderRoute' of undefined
    at Generator.generateRoute (/Users/vinayak/Development/Personal/nuxt/nuxt-2.10-bug/node_modules/@nuxt/generator/dist/generator.js:222:42)
    at /Users/vinayak/Development/Personal/nuxt/nuxt-2.10-bug/node_modules/@nuxt/generator/dist/generator.js:120:24
    at async Promise.all (index 0)
    at async Generator.generateRoutes (/Users/vinayak/Development/Personal/nuxt/nuxt-2.10-bug/node_modules/@nuxt/generator/dist/generator.js:115:7)
    at async Generator.generate (/Users/vinayak/Development/Personal/nuxt/nuxt-2.10-bug/node_modules/@nuxt/generator/dist/generator.js:48:20)
    at async Object.run (/Users/vinayak/Development/Personal/nuxt/nuxt-2.10-bug/node_modules/@nuxt/cli/dist/cli-build.js:101:5)
    at async NuxtCommand.run (/Users/vinayak/Development/Personal/nuxt/nuxt-2.10-bug/node_modules/@nuxt/cli/dist/cli-command.js:2575:7)


 FATAL  Cannot read property 'renderRoute' of undefined                                                                                                                                             18:52:53

  at Generator.afterGenerate (node_modules/@nuxt/generator/dist/generator.js:168:43)
  at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:50:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:101:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-command.js:2575:7)


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │   ✖ Nuxt Fatal Error                                           │
   │                                                                │
   │   TypeError: Cannot read property 'renderRoute' of undefined   │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxt-2.10-bug@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxt-2.10-bug@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vinayak/.npm/_logs/2019-10-06T13_22_53_417Z-debug.log
```

### Additional comments?

Related issues: #6500, #6513 & #6514

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9867">#c9867</a>)</em></sub></div>

**Comment by kajcula** [comment]
Instead 'npm run build' use 'npm run generate' - for me works fine

**Comment by AndrewBogdanovTSS** [comment]
@kajcula it's not a real solution for the problem

**Comment by aldarund** [comment]
its bug, i`l check what wrong

**Comment by ricardogobbosouza** [comment]
@aldarund  problem its here https://github.com/nuxt/nuxt.js/commit/95e043f1679f9d3bf1f6508282ac0c6ec468f4d8#diff-487be8dbf9747ee9db4e19a779085840R64

**Comment by hkdAdminHkGithub** [comment]
hmm

**Comment by cron13** [comment]
It affect not only spa mode.
I use universal mode and I have self made page level cache module where i use this.nuxt.renderer - in development everything is ok, but in prod i got TypeError

**Comment by aldarund** [comment]
@cron13 ist different issue. You need to check for renderer to be exist in your module

**Comment by alaxcc** [comment]
it's appear only on linux.
