### ISSUE TITLE
webpack@2.4.1 breaks nuxt

### ISSUE THREAD

**Issue by lmj0011** [nuxt/nuxt.js#657]
```
Nuxt.js Error:

TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.eval (eval at 148 (2.server-bundle.js:15:1), <anonymous>:283:16)
    at eval (eval at 148 (2.server-bundle.js:15:1), <anonymous>:285:30)
    at Object.148 (2.server-bundle.js:15:1)
    at __webpack_require__ (server-bundle.js:27:30)
    at eval (eval at 182 (2.server-bundle.js:96:1), <anonymous>:2:71)
    at Object.182 (2.server-bundle.js:96:1)
    at __webpack_require__ (server-bundle.js:27:30)
    at eval (eval at 240 (2.server-bundle.js:140:1), <anonymous>:7:3)
    at Object.240 (2.server-bundle.js:140:1)
    at __webpack_require__ (server-bundle.js:27:30)
```

This is the error I get after upgrading to `nuxt@0.10.7` and running `yarn dev`, I believe `webpack@2.4.1` is the culprit. 

Reverting back to `nuxt@0.10.5` which uses `webpack@2.3.2` is what I'm doing now, to avoid this.

**Comment by Capati** [comment]
This is indeed related to webpack, I had this problem too in one of my custom libraries that exports a class using `module.exports`. I solved this by using `export default class` instead and import it using the `import` statement instead of `require`.

I don't know if that is your case, but this was the only place causing the error.

**Comment by alexchopin** [comment]
Have you tried with [webpack 2.5](https://github.com/webpack/webpack/releases/tag/v2.5.0) if it fix the issue?

**Comment by lmj0011** [comment]
@alexchopin I haven't, don't have much time at the moment to make a fork and test nuxt with webpackv2.5

**Comment by Atinux** [comment]
The next version of nuxt.js coming soon will use Webpack 2.5.

I close this issue for now and you can re-open it if it still fail after the next release.

**Comment by ruslankonev** [comment]
So strange, but now, with last `nuxt@1.0.0-alpha3` I have the same error with reference to store

```
Nuxt.js Error:

TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.<anonymous> (config.js:5:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:1901:30)
    at __webpack_require__ (webpack:/webpack/bootstrap 8746bb1d9632da9e17c3:25:0)
    at Object.<anonymous> (server-bundle.js:1234:66)
    at __webpack_require__ (webpack:/webpack/bootstrap 8746bb1d9632da9e17c3:25:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:2051:73)
    at __webpack_require__ (webpack:/webpack/bootstrap 8746bb1d9632da9e17c3:25:0)
    at webpackContext (webpack:/frontend/store ^\.\/.*\.(js|ts)$:6:0)
    at getModule (.nuxt/store.js:50:15)
    at Object.<anonymous> (.nuxt/store.js:16:14)
    at __webpack_require__ (webpack:/webpack/bootstrap 8746bb1d9632da9e17c3:25:0)
    at Object.<anonymous> (server-bundle.js:811:68)
    at __webpack_require__ (webpack:/webpack/bootstrap 8746bb1d9632da9e17c3:25:0)
    at Object.<anonymous> (server-bundle.js:1486:65)
    at __webpack_require__ (webpack:/webpack/bootstrap 8746bb1d9632da9e17c3:25:0)
    at server-bundle.js:95:18
```

What that's can mean?

PS. Maybe because I have a different folder structure? 
```
- frontend/
-- pages/
-- store/
-- static/
-- ....
- modules/
-- nuxt/
--- index.js
--- nuxt.config.js
```
