### ISSUE TITLE
What is the best way to test routes on Nuxt with Jest?

### ISSUE THREAD

**Issue by leandromatos-hotmart** [nuxt/nuxt.js#6626]
I want to test if some pages exist, so I need to do an unit test, build the application and then test it.

I am trying to do this with the following code

`test/unit/locale.spec.js`
```js
/**
 * @jest-environment node
 */
import { resolve } from 'path'
import { Nuxt, Builder } from 'nuxt'
import getPort from 'get-port'

// Nuxt instance
let nuxt = null
let port = null
const url = (url) => `http://localhost:${port}${url}`

describe('homepage', () => {
  beforeAll(async () => {
    // Configuration
    const rootDir = resolve(__dirname, '../../')

    let config = {}
    config = require(resolve(rootDir, 'nuxt.config.js'))
    config.rootDir = rootDir
    config.dev = process.env.NODE_ENV !== 'production'
    config.test = true

    if (config.build) {
      if (!config.build.terser) {
        config.build.terser = false
      }
    } else {
      config.build = { terser: false }
    }

    nuxt = new Nuxt(config)
    // await new Builder(nuxt).build()

    if (config.dev) await new Builder(nuxt)

    // await nuxt.ready()
    port = await getPort()
    await nuxt.server.listen(port)
  }, 30000)

  test('/404 should display an error too', async () => {
    const { error } = await nuxt.server.renderRoute('/404')
    expect(error.message).toContain('This page could not be found')
  })

  test('/ with renderAndGetWindow()', async () => {
    await expect(nuxt.server.renderAndGetWindow(url('/error'))).rejects.toMatchObject({
      statusCode: 500
    })
  })

  test('Error: resolvePath()', () => {
    expect(() => nuxt.resolver.resolvePath()).toThrowError()
    expect(() => nuxt.resolver.resolvePath('@/pages/not-found.vue')).toThrowError(
      'Cannot resolve "@/pages/not-found.vue"'
    )
  })

  afterAll(async () => {
    await nuxt.close()
  })
})
```
But I can't get the expected result. See console output:
```bash
yarn run v1.19.1
$ jest test/unit/locale.spec.js
 FAIL  test/unit/locale.spec.js
  homepage
    ✕ /404 should display an error too (2ms)
    ✕ / with renderAndGetWindow() (719ms)
    ✓ Error: resolvePath() (4ms)

  ● homepage › /404 should display an error too

    TypeError: Cannot read property 'message' of undefined

      42 |   test('/404 should display an error too', async () => {
      43 |     const { error } = await nuxt.server.renderRoute('/404')
    > 44 |     expect(error.message).toContain('This page could not be found')
         |                  ^
      45 |   })
      46 |
      47 |   test('/ with renderAndGetWindow()', async () => {

      at Object.message (test/unit/locale.spec.js:44:18)

  ● homepage › / with renderAndGetWindow()

    expect(received).rejects.toMatchObject(expected)

    - Expected
    + Received

    - Object {
    -   "statusCode": 500,
    - }
    + [Error: Could not load the nuxt app]

      46 |
      47 |   test('/ with renderAndGetWindow()', async () => {
    > 48 |     await expect(nuxt.server.renderAndGetWindow(url('/error'))).rejects.toMatchObject({
         |                                                                         ^
      49 |       statusCode: 500
      50 |     })
      51 |   })

      at Object.toMatchObject (node_modules/expect/build/index.js:242:20)
      at Object.toMatchObject (test/unit/locale.spec.js:48:73)

[fatal] Cannot read property 'close' of null
  at Builder.unwatch (node_modules/@nuxt/builder/dist/builder.js:6180:30)
  at Builder.close (node_modules/@nuxt/builder/dist/builder.js:6191:10)
  at node_modules/@nuxt/builder/dist/builder.js:5495:42
  at node_modules/hable/lib/hookable.js:50:45
  at node_modules/hable/lib/utils.js:15:67
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at Nuxt.callHook (node_modules/hable/lib/hookable.js:50:7)
  at Nuxt.close (node_modules/@nuxt/core/dist/core.js:675:5)
  at Object.<anonymous> (test/unit/locale.spec.js:61:5)
Test Suites: 1 failed, 1 total
Tests:       2 failed, 1 passed, 3 total
Snapshots:   0 total
Time:        3.06s
Ran all test suites matching /test\/unit\/locale.spec.js/i.
(node:22081) UnhandledPromiseRejectionWarning: RequestError: Error: connect ECONNREFUSED 127.0.0.1:60368
(node:22081) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22081) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Anyone can help me?

**Comment by t1mwillis** [comment]
@leandromatos-hotmart Did you ever find anything here?

**Comment by leandromatos-hotmart** [comment]
No @t1mwillis =(

**Comment by Gibbo3771** [comment]
I don't understand why this doesn't have more attention. [The example here](https://nuxtjs.org/guide/development-tools/) just doesn't work. The server never actually opens for me. Even pasting this into a bare app doesn't work.

**Comment by leandromatos-hotmart** [comment]
Unfortunately, my issue was a close without attention. If I discover an solution, I post here.

**Comment by manniL** [comment]
> 
> 
> Unfortunately, my issue was a close without attention. If I discover an solution, I post here.

Because you didn't use the issue template.

**Comment by slidenerd** [comment]
SOLVED https://stackoverflow.com/questions/60343354/how-to-test-server-api-endpoints-using-scaffolded-nuxt-app-with-express/

**Comment by fs-innonova** [comment]
This is no longer valid, can someone please point me to where can unit test a server/api ? ty

**Comment by JessRascal** [comment]
> This is no longer valid, can someone please point me to where can I find a unit test that tests a server/api ? ty

Did you ever find an example for this?

I'm currently struggling to figure out how to test Nuxt endpoints. I'd have thought this would be a very common scenario but I can't find much about it.
