### ISSUE TITLE
«Error occurred when calling nuxtServerInit: Client network socket disconnected before secure TLS connection was established»

### ISSUE THREAD

**Issue by sader99** [nuxt/nuxt.js#6666]
Everything worked well for more than half a year. An error has occurred.

```
Error occurred when calling nuxtServerInit: Client network socket disconnected before secure TLS connection was established
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Client network socket disconnected before secure TLS connection w as established
at connResetException (internal/errors.js:575:14)
at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
at Object.onceWrapper (events.js:299:28)
at TLSSocket.emit (events.js:215:7)
at TLSSocket.EventEmitter.emit (domain.js:478:20)
at endReadableNT (_stream_readable.js:1198:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

package.json

  ```
"config": {
    "nuxt": {
      "host": "0.0.0.0",
      "port": "3003"
    }
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.8.0",
    "@nuxtjs/device": "^1.2.3",
    "@nuxtjs/pwa": "^2.6.0",
    "@nuxtjs/yandex-metrika": "^0.1.2",
    "axios": "^0.19.0",
    "cli-progress": "^3.3.1",
    "compression": "^1.7.4",
    "core-js": "^3.4.0",
    "cross-env": "^5.2.1",
    "express": "^4.17.1",
    "firebase": "^7.2.2",
    "helmet": "^3.21.2",
    "helmet-crossdomain": "^0.3.0",
    "https-proxy-agent": "^3.0.1",
    "kinopoisk-ru": "^1.0.3",
    "mongodb": "^3.3.3",
    "needle": "^2.4.0",
    "nuxt": "^2.10.2",
    "pm2": "^3.5.1",
    "socket.io": "^2.3.0",
    "socket.io-client": "^2.3.0",
    "yandex-pictures": "^1.4.88"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^0.0.1",
    "babel-eslint": "^8.2.1",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^3.1.0",
    "eslint-config-standard": "^13.0.1",
    "eslint-loader": "^2.2.1",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jest": "^22.21.0",
    "eslint-plugin-node": "^9.2.0",
    "eslint-plugin-nuxt": "^0.4.3",
    "eslint-plugin-prettier": "2.6.2",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-vue": "^5.2.3",
    "nodemon": "^1.19.4",
    "prettier": "1.14.3",
    "stylus": "^0.54.7",
    "stylus-loader": "^3.0.2"
  }
```
nuxt.config

```
  /*
  ** Axios module configuration
  */
  axios: {
    // See https://github.com/nuxt-community/axios-module#options
    baseURL: 'https://my.domain'
  },
```
`node -v 10.15.0`
Update does not give result.

Thanks for the help.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9997">#c9997</a>)</em></sub></div>

**Comment by invisor** [comment]
The same issue
