### ISSUE TITLE
Frustrated - Trying to use vue-particles in nuxt.js without success

### ISSUE THREAD

**Issue by creotip** [nuxt/nuxt.js#673]
I developed a plugin called [vue-particles](https://github.com/creotip/vue-particles) and i want it to be Compatible with Nuxt.js. 
Tried to read all relevant issues in this repository, but without success.
Lets do it step by step:
Created vue-particles.js file and added this code :
```
import Vue from 'vue'
import VueParticles from 'vue-particles'
Vue.use(VueParticles)
```

Then i get this error:
```
Nuxt.js Error:

/Users/roslanelyashiv/Desktop/VUEJS/nuxt-starter/node_modules/vue-particles/src/vue-particles/index.js:2
import particles from './vue-particles.vue'
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at r (/Users/roslanelyashiv/Desktop/VUEJS/nuxt-starter/node_modules/vue-server-renderer/build.js:6964:16)
    at Object.<anonymous> (webpack:/external "vue-particles":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7eaa50f5c611e7151c2d:25:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:2231:72)
    at __webpack_require__ (webpack:/webpack/bootstrap 7eaa50f5c611e7151c2d:25:0)
    at Object.module.exports.module.exports.list (.nuxt/index.js:88:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7eaa50f5c611e7151c2d:25:0)
    at Object.<anonymous> (server-bundle.js:1908:65)
```

So probably node does not recognizing ES2015 syntax?
Tried to change the syntax inside the plugin:
```
/* eslint-disable */
var particles = require('./vue-particles.vue')

var VueParticles = {

    install (Vue, options) {
        Vue.component('vue-particles', particles)
    }

}
/* eslint-disable */
module.exports.VueParticles = VueParticles;

```

Then i get this error:
```
Nuxt.js Error:

/Users/roslanelyashiv/Desktop/VUEJS/nuxt-starter/node_modules/vue-particles/src/vue-particles/vue-particles.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^
SyntaxError: Unexpected token <
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/roslanelyashiv/Desktop/VUEJS/nuxt-starter/node_modules/vue-particles/src/vue-particles/index.js:2:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

The problem is with vue file, "template" tag.
Tried to remove 
```
    extend (config, ctx) {
      if (ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader'
          exclude: /(node_modules)/
        })
      }
    }
```

No success.

**Comment by alexchopin** [comment]
Hi, you should use [vue-plugin-template](https://github.com/posva/vue-plugin-template) to compile your project into an UMD (Universal Module Definition).

**Comment by creotip** [comment]
@alexchopin 
I'm getting many errors when only trying to install vue-plugin-template

**Comment by Atinux** [comment]
Hi @creotip

I will take a look at it, nice plugin BTW :-)

I think you need to compile your vue files to JS to make it work properly. Indeed, when importing vue-particles, Nuxt will not compile your vue files since it's in the node_modules/ folder an defined as an external.

**Comment by creotip** [comment]
Tried to compile with rollup.js , but still i'm getting bunch of errors

**Comment by pi0** [comment]
@creotip Please take a look at [rollup.config.js](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/build/rollup.config.js) that we use to compile Vue components for BootstrapVue project & output is compatible with Nuxt.js

**Comment by creotip** [comment]
@pi0
Tried with your configuration for rollup.config.js and with all formats, but without success.
```
ReferenceError: window is not defined
```
Tried to disable ssr in nuxt.config.js:
```
  plugins: [
    { src: '~plugins/vue-particles', ssr: true }
  ]
```

getting bunch of errors as well:
![screen shot 2017-05-06 at 23 44 43 1](https://cloud.githubusercontent.com/assets/3135968/25775825/e8f2b8b2-32b6-11e7-923d-8f8a488c9950.png)

**Comment by Atinux** [comment]
To disable the ssr, you need to set the variable to `false` @creotip 

```js
plugins: [
  { src: '~plugins/vue-particles', ssr: false }
]
```

**Comment by Atinux** [comment]
I just tried your library @creotip and it seems that `particles.js` is not compatible with SSR.

You can merge my PR to make vue-particles works with SSR: https://github.com/creotip/vue-particles/pull/3

**Comment by kodekrendel** [comment]
@creotip awesome library, thank you!

**Comment by renztoygwapo** [comment]
is the issue closed ? still not getting the right answer, if the particles.js is not compatible in SSR then why they have put in their landing page that it is compatible in SSR ?

**Comment by qm3ster** [comment]
Yet another person publishing their plugin to `npm` without compiling `.vue` files and ES6 imports.
What a damn shame.

**Comment by zyw327** [comment]
import particles from './vue-particles.vue'
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at r (E:\front\pblog\ssr\demo\node_modules\vue-server-renderer\build.js:8330:16)
    at Object.<anonymous> (server-bundle.js:3478:18)
    at __webpack_require__ (webpack:/webpack/bootstrap 598d4e2acc3b5c0b5eea:25:0)
    at Object.<anonymous> (plugins/vue-particles.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 598d4e2acc3b5c0b5eea:25:0)
    at Object.<anonymous> (.nuxt/index.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 598d4e2acc3b5c0b5eea:25:0)
    at Object.<anonymous> (.nuxt/server.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 598d4e2acc3b5c0b5eea:25:0)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10)
    at evaluateModule (E:\front\pblog\ssr\demo\node_modules\vue-server-renderer\build.js:8338:21) statusCode: 500, name: 'SyntaxError' }

**Comment by jpt** [comment]
@renztoygwapo  wrote:

> is the issue closed ? still not getting the right answer, if the particles.js is not compatible in SSR then why they have put in their landing page that it is compatible in SSR ?

This has been what's so confusing to me.
