### ISSUE TITLE
Cannot find module 'babel-loader!./xxx.js'

### ISSUE THREAD

**Issue by lc60005457** [nuxt/nuxt.js#685]
I want to use babel-loader like [https://webpack.js.org/concepts/loaders/#via-require](https://webpack.js.org/concepts/loaders/#via-require)

but nuxt@0.10.6 nuxt@0.10.7:

```
.(aaa)
├── index.js
├── xxx.babel.js
├── node_modules
│   ├── @xxx-f2e
│   │   ├── bbb
│   │   │    ├── index.js => require('babel-loader!./xxx.babel.js')  Nuxt.js Error: ...
│   │   │    ├── xxx.babel.js
```

in ~(aaa) /index.js

```
// when 
require('@xxx-f2e/bbb') // show Nuxt.js Error

// when
require('@xxx-f2e/bbb/index.js') // valid

// when
require('babel-loader!./index.babel.js') // valid
```

```
Nuxt.js Error:

Error: Cannot find module 'babel-loader!./index.babel.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Bolt/gitProjects/xxx/git.fis-projects/aaa/node_modules/@xxx-f2e/bbb/index.js:25:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at r (/Users/Bolt/gitProjects/xxx/git.fis-projects/aaa/node_modules/vue-server-renderer/build.js:6964:16)
    at Object.<anonymous> (webpack:/external "@xxx-f2e/bbb":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap d295ba2b76e41840be0c:25:0)
    at Object.<anonymous> (0.server-bundle.js:2280:106)
```

Nuxt.js Error only on server render. Browser render is normal.

**Comment by Atinux** [comment]
You should compile your node module into a valid ES5 library @lc60005457 to make it work with Nuxt.js.

Then, you should be able to do `require('@xxx-f2e/bbb')`

**Comment by lc60005457** [comment]
Normally, I should compile to ES5。But, used `babel-loader!` should be valid, too.

`require('@xxx-f2e/bbb/index.js')` is valid, `require('@xxx-f2e/bbb')` is error.

I just can't understand why `'@xxx-f2e/bbb/index.js' !== '@xxx-f2e/bbb'` when field `main` is `index.js` in `package.json`. @Atinux
