### ISSUE TITLE
Compatibility issue with Nuxt@2.11 and @vue/test-utils

### ISSUE THREAD

**Issue by sobolevn** [nuxt/nuxt.js#6852]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/wemake-services/wemake-vue-template](https://github.com/wemake-services/wemake-vue-template)

### Steps to reproduce

Link to the failing CI: https://travis-ci.com/wemake-services/wemake-vue-template/builds/143178639

0. Create new project
1. Install dependencies with `npm i`
2. Run `npm run test:unit`

### What is expected ?

I expect tests to be run as usual.

### What is actually happening?

Tests are not executed.
See this comment https://github.com/vuejs/vue-test-utils/issues/1399#issuecomment-572660312 about my experiments. The latest `nuxt` version is not working together with `@vue/test-utils@1.0.0-beta.29` and `@vue/test-utils@1.0.0-beta.30`

- Jest config: https://github.com/wemake-services/wemake-vue-template/blob/master/template/jest.config.js
- package.json: https://github.com/wemake-services/wemake-vue-template/blob/master/template/package.json
- Actual tests: https://github.com/wemake-services/wemake-vue-template/tree/master/template/tests

Exception:

```
> cross-env NODE_ENV=test jest

 FAIL  tests/components/action-bar.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

 FAIL  tests/components/comment.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

 FAIL  tests/pages/index.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        9.111s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! name@0.0.0 test:unit: `cross-env NODE_ENV=test jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the name@0.0.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobolev/.npm/_logs/2020-01-09T13_49_48_645Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! name@0.0.0 test: `npm run test:engine && npm run test:unit && npm run lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the name@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobolev/.npm/_logs/2020-01-09T13_49_48_684Z-debug.log
> cross-env NODE_ENV=test jest

 FAIL  tests/components/action-bar.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

 FAIL  tests/components/comment.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

 FAIL  tests/pages/index.spec.ts
  ● Test suite failed to run

    Cannot find module 'vue-template-compiler' from 'vue-test-utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:27)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        9.111s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! name@0.0.0 test:unit: `cross-env NODE_ENV=test jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the name@0.0.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobolev/.npm/_logs/2020-01-09T13_49_48_645Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! name@0.0.0 test: `npm run test:engine && npm run test:unit && npm run lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the name@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobolev/.npm/_logs/2020-01-09T13_49_48_684Z-debug.log

```

### Additional comments?

Related bug report in `@vue/test-utils` repo: https://github.com/vuejs/vue-test-utils/issues/1399 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10190">#c10190</a>)</em></sub></div>

**Comment by aldarund** [comment]
It just seems that in your project deps not resolved properly. Did u tried with yarn for example?

**Comment by aldarund** [comment]
And/or try to remove package-lock.json	 and reinstall from new

**Comment by sobolevn** [comment]
@aldarund thanks! It was related to `10` -> `12` node migration process: https://github.com/wemake-services/wemake-vue-template/compare/aedfddb452bf...1165ffb99cb8
