### ISSUE TITLE
npm run dev failing on brand new app

### ISSUE THREAD

**Issue by neiled** [nuxt/nuxt.js#6872]
Hi,

Sorry for creating an issue for this but I'm out of ideas.
Creating a brand new app using the defaults for everything.

`npx create-nuxt-app test_app`

Using node 13.0.1

Gives me this when I run

`npm run dev`

Any ideas?

> ℹ Preparing project for development                                                                                                                                                               19:12:41
> ℹ Initial build may take a while                                                                                                                                                                  19:12:41
> ✔ Builder initialized                                                                                                                                                                             19:12:41
> ✔ Nuxt files generated                                                                                                                                                                            19:12:41
> 
> ● Client █████████████████████████ building (10%) 3/3 modules 0 active
> 
> 
> ✖ Server
>   Compiled with some errors in 612.32ms
> 
> 
> ✖ Client
>   Compiled with some errors in 2.05s
> 
> ✖ Server
>   Compiled with some errors in 612.32ms
> 
> 
>  ERROR  Failed to compile with 1 errors                                                                                                                                           friendly-errors 19:12:45
> 
> 
>  ERROR  in ./.nuxt/client.js                                                                                                                                                      friendly-errors 19:12:45
> 
> Module build failed (from ./node_modules/babel-loader/lib/index.js):                                                                                                              friendly-errors 19:12:45
> Error: [BABEL] /Users/neiled/dev/personal/test_app/.nuxt/client.js: Package exports for '/Users/neiled/dev/personal/test_app/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath (While processing: "/Users/neiled/dev/personal/test_app/node_modules/@nuxt/babel-preset-app/src/index.js")
>     at resolveExports (internal/modules/cjs/loader.js:419:17)
>     at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
>     at Function.Module._load (internal/modules/cjs/loader.js:693:27)
>     at Module.require (internal/modules/cjs/loader.js:864:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/Users/neiled/dev/personal/test_app/node_modules/@babel/preset-env/lib/debug.js:8:33)
>     at Module._compile (internal/modules/cjs/loader.js:971:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
>     at Module.load (internal/modules/cjs/loader.js:822:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:730:14)
>     at Module.require (internal/modules/cjs/loader.js:864:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/Users/neiled/dev/personal/test_app/node_modules/@babel/preset-env/lib/index.js:11:14)
>     at Module._compile (internal/modules/cjs/loader.js:971:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
>                                                                                                                                                                                   friendly-errors 19:12:45
>  @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js

**Comment by neiled** [comment]
Never mind sorry, upgrading node version to 13.6 fixed it...
