### ISSUE TITLE
Build fails if type definition file (d.ts) is placed in pages or layouts directory

### ISSUE THREAD

**Issue by dadajam4** [nuxt/nuxt.js#6940]
### What problem does this feature solve?

I rely on translations to write this sentence, so if you find something wrong, I'm sorry.
I generated the sfc type definition file using the following cli.

[@kahirokunn/vuedts](https://www.npmjs.com/package/@kahirokunn/vuedts)

This has successfully generated `/src/pages/index.vue.d.ts`

### /src/pages/index.vue
```
<template>
  <div>
    <h1>OK ({{ hoge }})</h1>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { Component } from 'nuxt-property-decorator';

type Hoge = RecursivePartial<{
  a: {
    b: number;
    c: {
      d: string;
    };
  };
}>;

@Component({})
export default class IndexView extends Vue {
  private hoge: number = 101;

  fuga(str: string): number {
    return parseInt(str, 10);
  }

  aaa(b: Hoge): Hoge {
    return b;
  }
}
</script>

```

### /src/pages/index.vue.d.ts
```
import Vue from 'vue';
declare type Hoge = RecursivePartial<{
    a: {
        b: number;
        c: {
            d: string;
        };
    };
}>;
export default class IndexView extends Vue {
    private hoge;
    fuga(str: string): number;
    aaa(b: Hoge): Hoge;
}
export {};

```

### What does the proposed changes look like?

You can put the type definition file in any directory and use it as needed.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10258">#c10258</a>)</em></sub></div>

**Comment by dadajam4** [comment]
I apologize for two.

·The first one
I was worried about submitting this as a bug report.

・ Second
The log when the build failed is as follows. I guess this is probably because the `dts` file matches the dynamic routing generation in the` pages` directory.

```
Module build failed (from ./node_modules/ts-loader/index.js):                                                                   friendly-errors 22:07:19
Error: Debug Failure. Output generation failed
    at Object.transpileModule (/Users/dadajam4/projects/develops/demo2/node_modules/typescript/lib/typescript.js:116867:29)
    at getTranspilationEmit (/Users/dadajam4/projects/develops/demo2/node_modules/ts-loader/dist/index.js:318:74)
    at successLoader (/Users/dadajam4/projects/develops/demo2/node_modules/ts-loader/dist/index.js:66:15)
    at Object.loader (/Users/dadajam4/projects/develops/demo2/node_modules/ts-loader/dist/index.js:22:12)
```
