### ISSUE TITLE
auth-routes example is broken

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/nuxt.js#698]
When I run there `npm run dev` after `npm i` I got error

```
module.js:472
    throw err;
    ^

Error: Cannot find module './dist/nuxt.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/qman/Desktop/NUXT/nuxt.js/index.js:10:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by kodekrendel** [comment]
Also, the code is using `axios`, while documentation explains with `fetch`. What should I use?

**Comment by Atinux** [comment]
Hi @kodekrendel 

This example will be fixed in the next release.
