### ISSUE TITLE
Nuxt does not work when generated with `nuxtServerInit` in the Vuex Store

### ISSUE THREAD

**Issue by frbuceta** [nuxt/nuxt.js#7016]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Steps to reproduce

With a serverNuxtInit in the Vuex Store, nuxt does not generate the application
```
export const actions = {
  async nuxtServerInit({ dispatch }) {
    await dispatch('captions/get')
  }
}
```

```
ERROR   /                                                                                                                                                                                      17:57:31

Error: Request failed with status code 401
    at createError (/Users/fran/Projects/xxxx/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/fran/Projects/xxxx/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/fran/Projects/xxxx/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:333:22)
    at IncomingMessage.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

ERROR   /tracking                                                                                                                                                                        17:57:31

Error: Request failed with status code 401
    at createError (/Users/fran/Projects/xxxx/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/fran/Projects/xxxx/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/fran/Projects/xxxx/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:333:22)
    at IncomingMessage.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

### What is expected ?

I should compile with the nuxtServerInit

### What is actually happening?

Currently not compiling, showing the errors that I have put in the previous comment

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10322">#c10322</a>)</em></sub></div>

**Comment by matteo-rigon** [comment]
The HTTP request you are performing inside `captions/get` is returning a 401 status code and an exception is raised by Axios. You are most likely missing the authentication method.

**Comment by frbuceta** [comment]
> The HTTP request you are performing inside `captions/get` is returning a 401 status code and an exception is raised by Axios. You are most likely missing the authentication method.

For authentication I am using @nuxtjs/auth

**Comment by matteo-rigon** [comment]
You are passing wrong username/password or api token

**Comment by frbuceta** [comment]
> You are passing wrong username/password or api token

He just answered me when I was editing the other message.

Thank you for helping me realize my mistake. Apologies
