### ISSUE TITLE
Cannot server-side render content within <noscript> tag

### ISSUE THREAD

**Issue by bengineer19** [nuxt/nuxt.js#7147]
### Version

[v2.12.1](https://github.com/nuxt.js/releases/tag/v2.12.1)

### Reproduction link

[https://codesandbox.io/s/github/bengineer19/nuxt-noscript-demo](https://codesandbox.io/s/github/bengineer19/nuxt-noscript-demo)

### Steps to reproduce

[Github repo](https://github.com/bengineer19/nuxt-noscript-demo/blob/master/pages/index.vue)
[CodeSandbox](https://codesandbox.io/s/github/bengineer19/nuxt-noscript-demo)

Adding any Vue component within a `<noscript>` tag causes errors.
```
<noscript>
    <TestComp></TestComp>
 </noscript>
```
The same applies to `<noscript>` alternatives, such as `<noscript inline-template>`, `<span is="noscript">` or `<component is="noscript">`.

### What is expected ?

For **statically generated** pages, it is a legitimate and common requirement to be able to provide a fallback for users without Javascript (for example, the Google adsense bot, unlike the Google search crawler bot, does not execute Javascript, and will refuse to serve ads on your site if it does not find content on it).

This is also useful for providing a fallback for where lazy-loading is not available etc. 

Naturally, there is no point in generating content within a `<noscript>` tag in the client. But it is extremely useful in a number of cases for a server-side rendered page to contain `<noscript>` fallbacks.

### What is actually happening?

The following console errors are produced: 
`The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

```
Cannot read property 'toLowerCase' of undefined
    at emptyNodeAt (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:5857:42)
    at VueComponent.patch [as __patch__] (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6498:22)
    at VueComponent.Vue._update (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3939:19)
    at VueComponent.updateComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4054:10)
    at Watcher.get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4473:25)
    at new Watcher (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4462:12)
    at mountComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4067:3)
    at VueComponent.Vue.$mount (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:8405:10)
    at init (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3115:13)
    at hydrate (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6368:56)
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10451">#c10451</a>)</em></sub></div>

**Comment by Geminii** [comment]
Hi @bengineer19 

You need to use `inline-template` like this : 
```
<template>
  <noscript inline-template>
    <TestComp></TestComp>
  </noscript>
</template>
```

I tested it and it works ;) 
The problem is due to Vue which try to mount an undefined element.

**Comment by bengineer19** [comment]
Thanks very much for your help. I realise that my reproduction wasn't fully representative of the problem, since using `inline-template` works for situations where the <noscript> tag is nested
