### ISSUE TITLE
Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by niteshkumarniranjan** [nuxt/nuxt.js#7203]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://nowandme.com/](https://nowandme.com/)

### Steps to reproduce

Need to add the website to the home screen in either android or iOS
When opening from the homescreen (randomly) hamburger click stops working. 
Shadow on the header on scroll stop working.
It seems If no JS event is working.

### What is expected ?

To properly work.

### What is actually happening?

```
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://nowandme.com/_nuxt/7da16d1ed51a25a74049.js:2:41280)
    at y (https://nowandme.com/_nuxt/7da16d1ed51a25a74049.js:2:54203)
    at v (https://nowandme.com/_nuxt/7da16d1ed51a25a74049.js:2:53834)
    at _ (https://nowandme.com/_nuxt/7da16d1ed51a25a74049.js:2:54289)
    at N (https://nowandme.com/_nuxt/7da16d1ed51a25a74049.js:2:57675)
    at N (https://nowandme.com/_nuxt/7da16d1ed51a25a74049.js:2:57610)
    at f.__patch__ (https://nowandme.com/_nuxt/7da16d1ed51a25a74049.js:2:58087)
    at f.t._update (https://nowandme.com/_nuxt/7da16d1ed51a25a74049.js:2:35026)
    at f.r (https://nowandme.com/_nuxt/7da16d1ed51a25a74049.js:2:65490)
    at _n.get (https://nowandme.com/_nuxt/7da16d1ed51a25a74049.js:2:27202)
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10510">#c10510</a>)</em></sub></div>

**Comment by manniL** [comment]
Please provide more info and some code. We can't help you without it.

**Comment by niteshkumarniranjan** [comment]
@manniL What kind of info can I provide to make it more debuggable.
Also, I can't share the whole codebase as the project isn't open source. I'll try to make an open-source version demo of it.

**Comment by manniL** [comment]
The best way is to boil it down to a minimal example which you provide then ☺️

**Comment by niteshkumarniranjan** [comment]
Okay! I will try to build a demo.

**Comment by manniL** [comment]
BTW: Released a [blog post](https://blog.lichter.io/posts/vue-hydration-error/) that might help you tracing down the problem.

**Comment by niteshkumarniranjan** [comment]
Sorry! I am very busy with my work will try to build a sample soon.

Thanks for the blog.
