### ISSUE TITLE
Unable to run dev script with static target and modern client

### ISSUE THREAD

**Issue by hannes-k** [nuxt/nuxt.js#7562]
### Version

[v2.13.0](https://github.com/nuxt.js/releases/tag/v2.13.0)

### Reproduction link

[https://github.com/hannes-k/nuxt-modern](https://github.com/hannes-k/nuxt-modern)

### Steps to reproduce

Create new nuxt project
add `target: 'static'` and `modern: 'client'` to `nuxt.config.js`
`npm run dev`
ctrl + c
`npm run dev`

### What is expected ?

Developer mode should be started.

### What is actually happening?

```
 ERROR  Cannot read property 'filter' of undefined                                                                                                                                                     14:27:24

  at node_modules/@nuxt/webpack/dist/webpack.js:176:12
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

### Additional comments?

The error does not always occur. Sometimes it works, but the next time it does not.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10805">#c10805</a>)</em></sub></div>

**Comment by MrJmpl3** [comment]
I have same problem in SSR mode.

**Comment by ThibaultVlacich** [comment]
I'm getting the same error here since Nuxt 2.13. Also, navigation from page to page is not working anymore. When I click a `nuxt-link`, the whole page reloads instead of just updating the content.

**Comment by jjelev** [comment]
We have discussed this here also:
https://cmty.app/nuxt/nuxt.js/issues/c10826#comment-5ef328c011200fb6dea89a4b

**Comment by jjelev** [comment]
On my build the issue is modern browsers can't open the build but legacy one can.
I suppose modern build is failing.
I observe this issue on `yarn dev` but not on `yarn build && yarn export` (for production).
So I am cheating a little and setting `modern: process.env.NODE_ENV === 'production'` in **nuxt.config.js**

**Comment by kreig303** [comment]
fwiw this has impacted us as well. we don't have `target: static` defined in our `nuxt.config.js`, just `modern: client` (per initial description)

`2.13.1` +`2.13.2`, same `Cannot read property 'filter' of undefined` webpackish looking error. build fails
`2.13.3`, build succeeds but render pinwheels in browser

so this is half-fixed in our use case. 😕

**Comment by clarkdo** [comment]
@kreig303 Can you please provide us more details about your problem? It would be great if you can create a minimal reproducible repo as well.
