### ISSUE TITLE
Express error after yarn upgrade

### ISSUE THREAD

**Issue by vadimsg** [nuxt/nuxt.js#766]
```
/var/www/default/dev/node_modules/express/lib/application.js:210
    throw new TypeError('app.use() requires middleware functions');
    ^

TypeError: app.use() requires middleware functions
    at Function.use (/var/www/default/dev/node_modules/express/lib/application.js:210:11)
    at Object.<anonymous> (/var/www/default/dev/server.js:66:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```
/var/www/default/dev/server.js:66:5
```
const nuxt = new Nuxt(config)
app.use(nuxt.render)
```

Did this project with auth-routes example minimum month ago, today after upgrade it broke. 

Why, what, how to fix?

**Comment by pi0** [comment]
Please see #754. Also do this with caution as 1.0.0 is still an alpha release ;)

**Comment by vadimsg** [comment]
@pi0 thanks!
I was wondering why for this release you cant find any info in github releases tab.
