### ISSUE TITLE
Socket Hang Up - during generate

### ISSUE THREAD

**Issue by o2bj** [nuxt/nuxt.js#7689]
### Versions

- nuxt: 2.13.3
- node: v12.16.2

### What is actually happening?

after "yarn generate" i get many 

```
 Error: socket hang up
    at connResetException (internal/errors.js:608:14)
    at Socket.socketOnEnd (_http_client.js:460:23)
    at Socket.emit (events.js:322:22)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

And 

```
 ERROR  Request failed with status code 404                                                                                                                                                                                        14:08:51

  at createError (node_modules\axios\lib\core\createError.js:16:15)
  at settle (node_modules\axios\lib\core\settle.js:18:12)
  at IncomingMessage.handleStreamEnd (node_modules\axios\lib\adapters\http.js:202:11)
  at IncomingMessage.emit (events.js:322:22)
  at IncomingMessage.EventEmitter.emit (domain.js:482:12)
  at endReadableNT (_stream_readable.js:1187:12)
  at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

There is no tried set 
```
generate: {
    interval: 1000,
}
```
But this didn't make a different

I made axios plugin to see any errors 

```
export default function({ $axios, redirect }) {
 $axios.onError((error) => {
    console.log('axios error')
    console.log(error)
  })
}
```

but i do not see any output from axios

**Comment by Atinux** [comment]
Please provide a reproduction to get help.

**Comment by zhanglong12138** [comment]
how to solve the second problem

**Comment by igolka97** [comment]
Same Issue. I have Strapi Backend running at docker, and getting all my data at nuxtServerInit, using `@nuxtjs/proxy`. When I use `dev` or `build` command everything completed successfully, but `generate` is not. Where I should look for?
<img width="587" alt="Снимок экрана 2021-08-15 в 21 32 00" src="https://user-images.githubusercontent.com/3520658/129488751-918fe90a-b884-41e2-862d-4e4c78df5bcb.png">
