### ISSUE TITLE
new version add css lint?

### ISSUE THREAD

**Issue by bimohxh** [nuxt/nuxt.js#777]
I just update nuxt to` v1.0.0-alpha1` ,when I run dev, I got the error:

```
Nuxt.js Error:

/home/hxh/share/new-awesomes/node_modules/animate.css/animate.css:1
(function (exports, require, module, __filename, __dirname) { @charset "UTF-8";
                                                              ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at r (/home/hxh/share/new-awesomes/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5817:16)
    at Object.<anonymous> (webpack:/external "animate.css":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7111d3b01c2e80a856c0:25:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:3156:70)
    at __webpack_require__ (webpack:/webpack/bootstrap 7111d3b01c2e80a856c0:25:0)
    at Object.<anonymous> (.nuxt/App.vue:3:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7111d3b01c2e80a856c0:25:0)
```

the before version didn't has this error.

**Comment by egoist** [comment]
Hopefully https://github.com/nuxt/nuxt.js/pull/780 will solve this,

**Comment by bimohxh** [comment]
@egoist thanks,I will wait for the next stable version
