### ISSUE TITLE
Nuxt build fail when adding babelrc: true on build.babel in nuxt.config

### ISSUE THREAD

**Issue by sykes10** [nuxt/nuxt.js#7846]
### Versions

- nuxt: v2.14.0
- node: v10.21.0
- @nuxt/typescript-build: v2.0.2
- @nuxt/typescript-runtime: v1.0.0

### Reproduction Link
https://codesandbox.io/s/cocky-wave-fj9fs

### Steps to reproduce

Install a new app using npx create-nuxt-app.
Select ts configuration.
Add in nuxt.config.js
the following config.

`build: {
    babel: {
      babelrc: true,
      presets() {
        return [["@nuxt/babel-preset-app"]];
      },
    },
}`

Add .babelrc file.

run code with nuxt-ts

### What is Expected?
Build without errors.

### What is actually happening?
terminal is throwing an error

`
 ERROR  Failed to compile with 1 errors               friendly-errors 10:42:45

 ERROR  in ./.nuxt/client.js                          friendly-errors 10:42:45

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .presets must be an array, or undefined
    at assertArray (/sandbox/node_modules/@babel/core/lib/config/validation/option-assertions.js:150:11)
    at assertPluginList (/sandbox/node_modules/@babel/core/lib/config/validation/option-assertions.js:219:15)
    at Object.keys.forEach.key (/sandbox/node_modules/@babel/core/lib/config/validation/options.js:109:5)
    at Array.forEach (<anonymous>)
    at validateNested (/sandbox/node_modules/@babel/core/lib/config/validation/options.js:85:21)
    at validate (/sandbox/node_modules/@babel/core/lib/config/validation/options.js:76:10)
    at loadPrivatePartialConfig (/sandbox/node_modules/@babel/core/lib/config/partial.js:76:50)
    at loadPrivatePartialConfig.next (<anonymous>)
    at Function.<anonymous> (/sandbox/node_modules/@babel/core/lib/config/partial.js:125:25)
    at Generator.next (<anonymous>)
    at evaluateSync (/sandbox/node_modules/gensync/index.js:244:28)
    at Function.sync (/sandbox/node_modules/gensync/index.js:84:14)
    at Object.<anonymous> (/sandbox/node_modules/@babel/core/lib/config/index.js:43:61)
    at Object.<anonymous> (/sandbox/node_modules/babel-loader/lib/index.js:151:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/sandbox/node_modules/babel-loader/lib/index.js:3:103)
                                                      friendly-errors 10:42:45
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js`

**Comment by farnabaz** [comment]
When `bable.babelrc` is true, Nuxt does not process `babel` object.  Eventually combination on `bablerc = true` and `presets = function` is a invalid config.  
Replace function with an array:
```js
build: {
    babel: {
      babelrc: true,
      presets: [["@nuxt/babel-preset-app"]],
    },
}
```

Or remove `bablerc: true`

**Comment by sykes10** [comment]
Is there a way to replace `{
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
  ]
}` from .babelrc and add it into the nuxt config?

**Comment by pi0** [comment]
(unrelated) @sykes10 dynamic import syntax should be handled by webpack anyway ([docs](https://webpack.js.org/guides/code-splitting/#dynamic-imports))

**Comment by sykes10** [comment]
Thanks for the answer. We managed to remove .babelrc and make it work.

The point of creating this issues was that before updating to the latest version of nuxt our configuration was working with that setup and then after updating it starts failing.
