### ISSUE TITLE
FATAL  Cannot find module 'detab'   after yarn dev 

### ISSUE THREAD

**Issue by huaiguoguo** [nuxt/nuxt.js#8008]
### Versions
- win10 1909 x64
- nuxt:   v2.14.4
- node:  v12.18.3

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
yarn create nuxt-app app

in terminal yarn dev after create success  

### What is Expected?
i am expected its run success

### What is actually happening?

```
$ yarn dev
yarn run v1.22.4
$ nuxt-ts

 FATAL  Cannot find module 'detab'                                                                                                                                                                                  00:33:33  
Require stack:
- D:\phpstudy_pro\WWW\ecomm\app\node_modules\@nuxt\content\parsers\markdown\handlers\code.js
- D:\phpstudy_pro\WWW\ecomm\app\node_modules\@nuxt\content\parsers\markdown\handlers\index.js
- D:\phpstudy_pro\WWW\ecomm\app\node_modules\@nuxt\content\parsers\markdown\index.js
- D:\phpstudy_pro\WWW\ecomm\app\node_modules\@nuxt\content\parsers\index.js
- D:\phpstudy_pro\WWW\ecomm\app\node_modules\@nuxt\content\lib\database.js
- D:\phpstudy_pro\WWW\ecomm\app\node_modules\@nuxt\content\lib\index.js
- D:\phpstudy_pro\WWW\ecomm\app\node_modules\@nuxt\core\dist\core.js
- D:\phpstudy_pro\WWW\ecomm\app\node_modules\@nuxt\cli\dist\cli-index.js
- D:\phpstudy_pro\WWW\ecomm\app\node_modules\@nuxt\cli\dist\cli.js
- D:\phpstudy_pro\WWW\ecomm\app\node_modules\@nuxt\typescript-runtime\bin\nuxt-ts.js

  Error: Cannot find module 'detab'
  Require stack:
  - node_modules\@nuxt\content\parsers\markdown\handlers\code.js
  - node_modules\@nuxt\content\parsers\markdown\handlers\index.js
  - node_modules\@nuxt\content\parsers\markdown\index.js
  - node_modules\@nuxt\content\parsers\index.js
  - node_modules\@nuxt\content\lib\database.js
  - node_modules\@nuxt\content\lib\index.js
  - node_modules\@nuxt\core\dist\core.js
  - node_modules\@nuxt\cli\dist\cli-index.js
  - node_modules\@nuxt\cli\dist\cli.js
  - node_modules\@nuxt\typescript-runtime\bin\nuxt-ts.js
  at Object.<anonymous> (node_modules\@nuxt\content\parsers\markdown\handlers\code.js:2:15)
  at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
  at Object.require.extensions.<computed> (node_modules\ts-node\src\index.ts:851:44)
```

package.json
```
{
  "name": "app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt-ts",
    "build": "nuxt-ts build",
    "start": "nuxt-ts start",
    "generate": "nuxt-ts generate",
    "lint:js": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "lint:style": "stylelint **/*.{vue,css} --ignore-path .gitignore",
    "lint": "yarn lint:js && yarn lint:style",
    "test": "jest"
  },
  "lint-staged": {
    "*.{js,vue}": "eslint",
    "*.{css,vue}": "stylelint"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "dependencies": {
    "@nuxt/content": "^1.5.0",
    "@nuxt/typescript-runtime": "^1.0.0",
    "@nuxtjs/axios": "^5.12.0",
    "@nuxtjs/pwa": "^3.0.0-beta.20",
    "ant-design-vue": "^1.6.4",
    "detab": "^2.0.3",
    "nuxt": "^2.14.0"
  },
  "devDependencies": {
    "@nuxt/types": "^2.14.0",
    "@nuxt/typescript-build": "^2.0.2",
    "@nuxtjs/eslint-config": "^3.1.0",
    "@nuxtjs/eslint-config-typescript": "^3.0.0",
    "@nuxtjs/eslint-module": "^2.0.0",
    "@nuxtjs/stylelint-module": "^4.0.0",
    "@vue/test-utils": "^1.0.3",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.1.0",
    "eslint": "^7.5.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-nuxt": "^1.0.0",
    "eslint-plugin-prettier": "^3.1.4",
    "husky": "^4.2.5",
    "jest": "^26.1.0",
    "lint-staged": "^10.2.11",
    "prettier": "^2.0.5",
    "stylelint": "^13.6.1",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-standard": "^20.0.0",
    "ts-jest": "^26.1.3",
    "vue-jest": "^3.0.4"
  }
}

```

**Comment by stefanwuthrich** [comment]
same here, with same Node LTS version as reported above, on Manjaro Linux

**Comment by rclement** [comment]
Apparently, it is related to some sub-dependency from `@nuxt/content`: https://github.com/nuxt/content/issues/448

**Comment by manniL** [comment]
As @rclement said, this is a `@nuxt/content` specific bug. Please follow along in https://github.com/nuxt/content/issues/448
