### ISSUE TITLE
Getting error while using nuxt-class-component

### ISSUE THREAD

**Issue by piyushchauhan2011** [nuxt/nuxt.js#803]
I copy pasted the example code from `vue-class-component` examples directory and getting this error with latest nuxt

```javascript
Nuxt.js Error:

TypeError: Cannot read property '_init' of undefined
    at VueComponent (/Users/piyushchauhan/Documents/testcodes/nuxt-component/node_modules/vue/dist/vue.runtime.common.js:4167:11)
    at server-bundle.js:2252:17
    at F (~/core-js/library/modules/_export.js:35:0)
    at server-bundle.js:2247:22
    at Array.map (native)
    at Object._callee$ (.nuxt/server.js:53:65)
    at tryCatch (~/regenerator-runtime/runtime.js:65:14)
    at Generator.invoke [as _invoke] (~/regenerator-runtime/runtime.js:303:0)
    at Generator.prototype.(anonymous function) [as next] (~/regenerator-runtime/runtime.js:117:0)
    at step (~/babel-runtime/helpers/asyncToGenerator.js:17:0)
    at server-bundle.js:1105:13
```

**Comment by piyushchauhan2011** [comment]
Test repo: https://github.com/piyushchauhan2011/nuxt-component

**Comment by nidin** [comment]
I am also getting this error

**Comment by pengchongfu** [comment]
@piyushchauhan2011 @nidin @alexchopin it seems that this [pr](https://github.com/nuxt/nuxt.js/pull/765) has fixed this bug.
I also get this error, but after checkout to `dev` branch, it works well.

**Comment by piyushchauhan2011** [comment]
Working with 1.0.0-alpha2
