### ISSUE TITLE
Contains invalid WIN32 path when i do yarn generate

### ISSUE THREAD

**Issue by devpaps** [nuxt/nuxt.js#8031]
### Versions

- nuxt: 2.14.4
- node: v14.9.0

### Reproduction

https://github.com/devpaps/rellow

My Nuxt.config file:

```js
export default {
  mode: "universal",
  generate: {
    fallback: "404.html",
  },
  /*
   ** Headers of the page
   */
  head: {
    title: "Rellow | Webb & Design",
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      {
        hid: "description",
        name: "description",
        content:
          "Med bred kompetens inom, design och webbproduktion erbjuder vi allt från koncept, webbdesign, webbproduktion"
      },
      {
        name: "google-site-verification",
        content: "tU1pNQmReCvUry3nsFppsFry53nj9A87M8YTW5RzqVE"
      },
      { hid: "og:url", property: "og:url", content: "https://rellow.se" },
      {
        hid: "og:image",
        property: "og:image",
        content:
          "https://d33wubrfki0l68.cloudfront.net/1804272da21d2cff66adb5add2f7a0c12abcc17d/cc1da/_nuxt/img/header-test2.1600bec.png"
      },
      {
        hid: "og:title",
        property: "og:title",
        content: "Rellow - Webb & Design"
      },
      { hid: "og:type", property: "og:type", content: "website" },
      { hid: "og:site_name", property: "og:site_name", content: "Rellow" },
      {
        hid: "og:description",
        property: "og:description",
        content:
          "Gör dig mer synlig på nätet med en snygg och funktionell hemsida."
      }
    ],
    script: [
      {
        src: "https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.2/TweenMax.min.js"
      },
      {
        src: "https://kit.fontawesome.com/c0cbddae0d.js",
        crossorigin: "anonymous"
      }
    ],
    link: [
      { rel: "icon", type: "image/x-icon", href: "/favicon.ico" },
      {
        rel: "stylesheet",
        as: "style",
        href:
          'https://fonts.googleapis.com/css?family=Lato:400,700,900|Playfair+Display:400,700|Alice&display="swap"'
      }
    ]
  },

  /*
   ** Customize the progress-bar color
   */
  loading: { color: "#71DDE3" },

  /*
   ** Global CSS
   */
  css: [
    { src: "~/assets/css/reboot.min.css", lang: "css" },
    { src: "~/assets/css/fonts.css", lang: "css" }
  ],

  /*
   ** Plugins to load before mounting the App
   */
  plugins: [
    { src: "~/plugins/vue-scroll-reveal", ssr: false },
    { src: "~/plugins/ga.js", ssr: false },
    { src: "~/plugins/vee-validate.js", ssr: false }
  ],

  /*
   ** Nuxt.js modules
   */
  modules: [
    // Doc: https://github.com/nuxt-community/axios-module#usage
    "@nuxtjs/axios",
    "@nuxtjs/pwa",
    [
      "nuxt-imagemin",
      {
        optipng: { optimizationLevel: 5 },
        jpegtran: { optimizationLevel: 5 }
      }
    ],
    [
      "@nuxtjs/sitemap",
      {
        path: "/sitemap.xml",
        hostname: "https://rellow.se",
        generate: true,
        gzip: true
      }
    ],
    [
      "nuxt-validate",
      {
        lang: "sv"
      }
    ]
  ],
  manifest: {
    name: "Rellow",
    short_name: "Rellow",
    lang: "sv",
    display: "standalone",
    background_color: "#fff",
    description: "Rellows egna webbapp"
  },
  /*
   ** Axios module configuration
   */
  axios: {
    // See https://github.com/nuxt-community/axios-module#options
  },

  /*
   ** Build configuration
   */
  build: {
    extractCSS: true,
    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {
      // Run ESLint on save
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: "pre",
          test: /\.(js|vue)$/,
          loader: "eslint-loader",
          exclude: /(node_modules)/
        });
      }
    }
  }
};
```

### Steps to reproduce
run yarn generate with the flag cli:buildError, and tell me if this error you get is causing my problems at Netlify.

### What is Expected?
That it will deploy on Netlify.

### What is actually happening?

```
This is the error code when i run, yarn generate with the flag cli:buildError.
<br>
`Error: C:\Users\maja_\Desktop\Code\Vue\rellow\cli:buildError\node_modules\.cache\nuxt\build-lock-4eda4298 contains invalid WIN32 path characters.`
<br>
And when i run without the flag cli:buildError, i get no error.
<br>
However, when i deploy it to Netlify i get this error code:
<br>
`8:55:42 PM: Build ready to start
8:55:44 PM: build-image version: 8e315e54bc4032a32e73290be556cde4f8348c12
8:55:44 PM: build-image tag: v2.8.2
8:55:44 PM: buildbot version: 45cd00068410d70db72c9672cdd014995488e12a
8:55:44 PM: No cache source specified, skip fetching cache
8:55:44 PM: Starting to prepare the repo for build
8:55:44 PM: No cached dependencies found. Cloning fresh repo
8:55:44 PM: git clone https://github.com/devpaps/rellow
8:55:45 PM: Preparing Git Reference refs/heads/master
8:55:45 PM: Starting build script
8:55:45 PM: Installing dependencies
8:55:47 PM: Downloading and installing node v8.17.0...
8:55:47 PM: Downloading https://nodejs.org/dist/v8.17.0/node-v8.17.0-linux-x64.tar.xz...
8:55:47 PM: 
###################
8:55:47 PM: ###############                                        48.
8:55:47 PM: 4%
8:55:47 PM: 
##############################################
8:55:47 PM: ########################## 100.0%
8:55:47 PM: Computing checksum with sha256sum
8:55:47 PM: Checksums matched!
8:55:49 PM: Now using node v8.17.0 (npm v6.13.4)
8:55:50 PM: Attempting ruby version 2.3.6, read from environment
8:55:51 PM: Using ruby version 2.3.6
8:55:51 PM: Using PHP version 5.6
8:55:51 PM: Started restoring cached node modules
8:55:51 PM: Finished restoring cached node modules
8:55:51 PM: Installing NPM modules using NPM version 6.13.4
8:56:28 PM: > node-sass@4.14.1 install /opt/build/repo/node_modules/node-sass
8:56:28 PM: > node scripts/install.js
8:56:28 PM: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-57_binding.node
8:56:29 PM: Download complete
8:56:29 PM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-57/binding.node
8:56:29 PM: Caching binary to /opt/buildhome/.npm/node-sass/4.14.1/linux-x64-57_binding.node
8:56:29 PM: > core-js@3.6.5 postinstall /opt/build/repo/node_modules/@babel/node/node_modules/core-js
8:56:29 PM: > node -e "try{require('./postinstall')}catch(e){}"
8:56:29 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
8:56:29 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
8:56:29 PM: > https://opencollective.com/core-js 
8:56:29 PM: > https://www.patreon.com/zloirock 
8:56:29 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
8:56:29 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/core-js
8:56:29 PM: > node -e "try{require('./postinstall')}catch(e){}"
8:56:30 PM: > ejs@2.7.4 postinstall /opt/build/repo/node_modules/ejs
8:56:30 PM: > node ./postinstall.js
8:56:30 PM: Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)
8:56:30 PM: > scrollreveal@4.0.7 postinstall /opt/build/repo/node_modules/scrollreveal
8:56:30 PM: > node -e "console.log('\u001b[35m\u001b[1mLove ScrollReveal? 🔑  Buy a license!\u001b[22m\u001b[35m\n >> \u001b[33mhttps://scrollrevealjs.org/pricing/\u001b[0m\n')"
8:56:30 PM: Love ScrollReveal? 🔑  Buy a license!
8:56:30 PM:  >> https://scrollrevealjs.org/pricing/
8:56:30 PM: > gifsicle@4.0.1 postinstall /opt/build/repo/node_modules/gifsicle
8:56:30 PM: > node lib/install.js
8:56:31 PM:   ✔ gifsicle pre-build test passed successfully
8:56:31 PM: > jpegtran-bin@4.0.0 postinstall /opt/build/repo/node_modules/jpegtran-bin
8:56:31 PM: > node lib/install.js
8:56:31 PM:   ✔ jpegtran pre-build test passed successfully
8:56:31 PM: > optipng-bin@5.1.0 postinstall /opt/build/repo/node_modules/optipng-bin
8:56:31 PM: > node lib/install.js
8:56:32 PM:   ✔ optipng pre-build test passed successfully
8:56:32 PM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
8:56:32 PM: > node lib/install.js
8:56:32 PM:   ✔ pngquant pre-build test passed successfully
8:56:32 PM: > node-sass@4.14.1 postinstall /opt/build/repo/node_modules/node-sass
8:56:32 PM: > node scripts/build.js
8:56:32 PM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-57/binding.node
8:56:32 PM: Testing binary
8:56:33 PM: Binary is fine
8:56:33 PM: > nodemon@2.0.4 postinstall /opt/build/repo/node_modules/nodemon
8:56:33 PM: > node bin/postinstall || exit 0
8:56:33 PM: Love nodemon? You can now support the project via the open collective:
8:56:33 PM:  > https://opencollective.com/nodemon/donate
8:56:33 PM: > nuxt@2.14.4 postinstall /opt/build/repo/node_modules/nuxt
8:56:33 PM: > opencollective || exit 0
8:56:33 PM:                                      :-:
8:56:33 PM:                                    .==-+:
8:56:33 PM:                                   .==. :+- .-=-
8:56:33 PM:                                  .==.   :==++-+=.
8:56:33 PM:                                 :==.     -**: :+=.
8:56:33 PM:                                :+-      :*+++. .++.
8:56:33 PM:                               :+-      -*= .++: .=+.
8:56:33 PM:                              -+:      =*-   .+*: .=+:
8:56:33 PM:                             -+:     .=*-     .=*-  =+:
8:56:33 PM:                           .==:     .+*:        -*-  -+-
8:56:33 PM:                          .=+:.....:+*-.........:=*=..=*-
8:56:33 PM:                          .-=------=++============++====:
8:56:33 PM:                           Thanks for installing nuxtjs
8:56:33 PM:                  Please consider donating to our open collective
8:56:33 PM:                         to help us maintain this package.
8:56:33 PM:                            Number of contributors: 229
8:56:33 PM:                               Number of backers: 362
8:56:33 PM:                             Annual budget: US$ 77,528
8:56:33 PM:                            Current balance: US$ 34,027
8:56:33 PM:                  Donate: https://opencollective.com/nuxtjs/donate
8:56:36 PM: npm
8:56:36 PM:  WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
8:56:36 PM: npm WARN notsup
8:56:36 PM:  SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
8:56:36 PM: npm
8:56:36 PM:  WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/@babel/cli/node_modules/fsevents):
8:56:36 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
8:56:36 PM: npm
8:56:36 PM: WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
8:56:36 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
8:56:36 PM: added 1912 packages from 787 contributors and audited 1858 packages in 43.79s
8:56:38 PM: 63 packages are looking for funding
8:56:38 PM:   run `npm fund` for details
8:56:38 PM: found 0 vulnerabilities
8:56:38 PM: NPM modules installed
8:56:39 PM: Started restoring cached go cache
8:56:39 PM: Finished restoring cached go cache
8:56:39 PM: Installing Go version 1.10
8:56:45 PM: unset GOOS;
8:56:45 PM: unset GOARCH;
8:56:45 PM: export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64';
8:56:45 PM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64/bin:${PATH}";
8:56:45 PM: go version >&2;
8:56:45 PM: export GIMME_ENV="/opt/buildhome/.gimme_cache/env/go1.10.linux.amd64.env"
8:56:45 PM: go version go1.10 linux/amd64
8:56:45 PM: Installing missing commands
8:56:45 PM: Verify run directory
8:56:45 PM: Executing user command: npm run generate
8:56:45 PM: > rellow_site@1.0.0 generate /opt/build/repo
8:56:45 PM: > nuxt generate
8:56:46 PM:  FATAL  Unexpected token {
8:56:46 PM:   } catch {
8:56:46 PM:   ^
8:56:46 PM:   SyntaxError: Unexpected token {
8:56:46 PM:   at Object.Module._extensions..js (module.js:664:10)
8:56:46 PM:   at Object.Module._extensions..js (module.js:664:10)
8:56:46 PM:    ╭─────────────────────────────────────╮
8:56:46 PM:    │                                     │
8:56:46 PM:    │   ✖ Nuxt Fatal Error                │
8:56:46 PM:    │                                     │
8:56:46 PM:    │   SyntaxError: Unexpected token {   │
8:56:46 PM:    │                                     │
8:56:46 PM:    ╰─────────────────────────────────────╯
8:56:46 PM: npm
8:56:46 PM:  ERR! code ELIFECYCLE
8:56:46 PM: npm ERR! errno 1
8:56:46 PM: npm ERR! rellow_site@1.0.0 generate: `nuxt generate`
8:56:46 PM: npm ERR! Exit status 1
8:56:46 PM: npm
8:56:46 PM: ERR!
8:56:46 PM: npm ERR! Failed at the rellow_site@1.0.0 generate script.
8:56:46 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
8:56:46 PM: npm
8:56:46 PM:  ERR! A complete log of this run can be found in:
8:56:46 PM: npm ERR!     /opt/buildhome/.npm/_logs/2020-09-07T18_56_46_360Z-debug.log
8:56:46 PM: Skipping functions preparation step: no functions directory set
8:56:46 PM: Caching artifacts
8:56:46 PM: Started saving node modules
8:56:46 PM: Finished saving node modules
8:56:46 PM: Started saving pip cache
8:56:46 PM: Finished saving pip cache
8:56:46 PM: Started saving emacs cask dependencies
8:56:46 PM: Finished saving emacs cask dependencies
8:56:46 PM: Started saving maven dependencies
8:56:46 PM: Finished saving maven dependencies
8:56:46 PM: Started saving boot dependencies
8:56:46 PM: Finished saving boot dependencies
8:56:46 PM: Started saving go dependencies
8:56:48 PM: Finished saving go dependencies
8:56:51 PM: Error running command: Build script returned non-zero exit code: 1
8:56:51 PM: Failing build: Failed to build site
8:56:51 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
8:56:51 PM: Finished processing build request in 1m7.23423107s
```

**Comment by manniL** [comment]
Hey 👋 
Could you please format your bug report properly? ☺️

**Comment by pi0** [comment]
(reformatted. repro link was hidden)

**Comment by lihbr** [comment]
Behavior is reproduced as described under Windows: `npm run generate` exits 0, and `npm run generate cli:buildError` exits 1, didn't tried for Netlify.

I think [it's a misunderstanding](https://github.com/devpaps/rellow/commit/6ed303a666a4cb3afa013cb836feca6edbee2e99) of what `cli:buildError` is as it's not a command flag but a hook you can subscribe to do things when build error (also I think it's being deprecated given the lack of reference in the documentation, only one remains here: https://nuxtjs.org/guide/release-notes, at version 2.10.0 under "Features")

Here some reference about Nuxt hooks:
- Using hooks in `nuxt.config.js`: https://nuxtjs.org/guides/configuration-glossary/configuration-hooks
- Using hooks in modules: https://nuxtjs.org/guides/directory-structure/modules#run-tasks-on-specific-hooks

Also I note that you're missing `options.target: static` in your `nuxt.config.js` file, is that desired? See: https://nuxtjs.org/guides/configuration-glossary/configuration-target

**Comment by devpaps** [comment]
Hi! You're right, my mistake to use with the flag cli:buildError. I removed it. But when i have removed it, it still dosen't deploy on Netlify. But on my local machine it's fine to run npm run generate.

`options.target: static` As far as i understand `mode: "universal"` is the same as static?

- I can confirm that i got npm run generate in my build command on Netlify. However when i change it to nuxt generate, i still got the same fatal error as above.

- I was trying to look what the error log was. But it was my bad. :)

So, my question is, what is causing the` SyntaxError: Unexpected token {` i get on Netlify...? Nuxt is updated to the latest.

**Comment by lihbr** [comment]
Hey @devpaps, sorry for the delay~

I've forked your repo an deployed it with Netlify without any issue: [sharp-volhard-250b6c.netlify.app](https://sharp-volhard-250b6c.netlify.app)
<details>
<summary>Deploy log</summary>
<br />

```log
10:05:43 AM: Build ready to start
10:05:45 AM: build-image version: b0258b965567defc4a2d7e2f2dec2e00c8f73ad6
10:05:45 AM: build-image tag: v3.4.1
10:05:45 AM: buildbot version: 8c957a6d09a03023cea4239847cc73a9cb64eeb7
10:05:46 AM: Fetching cached dependencies
10:05:46 AM: Failed to fetch cache, continuing with build
10:05:46 AM: Starting to prepare the repo for build
10:05:46 AM: No cached dependencies found. Cloning fresh repo
10:05:46 AM: git clone https://github.com/lihbr/rellow
10:05:47 AM: Preparing Git Reference refs/heads/master
10:05:48 AM: Starting build script
10:05:48 AM: Installing dependencies
10:05:48 AM: Python version set to 2.7
10:05:50 AM: v12.18.0 is already installed.
10:05:50 AM: Now using node v12.18.0 (npm v6.14.4)
10:05:50 AM: Started restoring cached build plugins
10:05:50 AM: Finished restoring cached build plugins
10:05:51 AM: Attempting ruby version 2.7.1, read from environment
10:05:52 AM: Using ruby version 2.7.1
10:05:52 AM: Using PHP version 5.6
10:05:52 AM: 5.2 is already installed.
10:05:52 AM: Using Swift version 5.2
10:05:52 AM: Started restoring cached node modules
10:05:52 AM: Finished restoring cached node modules
10:05:53 AM: Installing NPM modules using NPM version 6.14.4
10:06:29 AM: > node-sass@4.14.1 install /opt/build/repo/node_modules/node-sass
10:06:29 AM: > node scripts/install.js
10:06:29 AM: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-72_binding.node
10:06:30 AM: Download complete
10:06:30 AM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
10:06:30 AM: Caching binary to /opt/buildhome/.npm/node-sass/4.14.1/linux-x64-72_binding.node
10:06:30 AM: > core-js@3.6.5 postinstall /opt/build/repo/node_modules/@babel/node/node_modules/core-js
10:06:30 AM: > node -e "try{require('./postinstall')}catch(e){}"
10:06:30 AM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/core-js
10:06:30 AM: > node -e "try{require('./postinstall')}catch(e){}"
10:06:31 AM: > ejs@2.7.4 postinstall /opt/build/repo/node_modules/ejs
10:06:31 AM: > node ./postinstall.js
10:06:31 AM: > scrollreveal@4.0.7 postinstall /opt/build/repo/node_modules/scrollreveal
10:06:31 AM: > node -e "console.log('\u001b[35m\u001b[1mLove ScrollReveal? 🔑  Buy a license!\u001b[22m\u001b[35m\n >> \u001b[33mhttps://scrollrevealjs.org/pricing/\u001b[0m\n')"
10:06:31 AM: Love ScrollReveal? 🔑  Buy a license!
10:06:31 AM:  >> https://scrollrevealjs.org/pricing/
10:06:31 AM: > gifsicle@4.0.1 postinstall /opt/build/repo/node_modules/gifsicle
10:06:31 AM: > node lib/install.js
10:06:32 AM:   ✔ gifsicle pre-build test passed successfully
10:06:32 AM: > jpegtran-bin@4.0.0 postinstall /opt/build/repo/node_modules/jpegtran-bin
10:06:32 AM: > node lib/install.js
10:06:32 AM:   ✔ jpegtran pre-build test passed successfully
10:06:33 AM: > optipng-bin@5.1.0 postinstall /opt/build/repo/node_modules/optipng-bin
10:06:33 AM: > node lib/install.js
10:06:33 AM:   ✔ optipng pre-build test passed successfully
10:06:33 AM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
10:06:33 AM: > node lib/install.js
10:06:34 AM:   ✔ pngquant pre-build test passed successfully
10:06:34 AM: > node-sass@4.14.1 postinstall /opt/build/repo/node_modules/node-sass
10:06:34 AM: > node scripts/build.js
10:06:34 AM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
10:06:34 AM: Testing binary
10:06:34 AM: Binary is fine
10:06:34 AM: > nodemon@2.0.4 postinstall /opt/build/repo/node_modules/nodemon
10:06:34 AM: > node bin/postinstall || exit 0
10:06:34 AM: Love nodemon? You can now support the project via the open collective:
10:06:34 AM:  > https://opencollective.com/nodemon/donate
10:06:34 AM: > nuxt@2.14.4 postinstall /opt/build/repo/node_modules/nuxt
10:06:34 AM: > opencollective || exit 0
10:06:36 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
10:06:36 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:06:36 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/@babel/cli/node_modules/fsevents):
10:06:36 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:06:36 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
10:06:36 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:06:36 AM: added 1858 packages from 771 contributors and audited 1867 packages in 42.701s
10:06:38 AM: 67 packages are looking for funding
10:06:38 AM:   run `npm fund` for details
10:06:38 AM: found 0 vulnerabilities
10:06:38 AM: NPM modules installed
10:06:38 AM: Started restoring cached go cache
10:06:38 AM: Finished restoring cached go cache
10:06:38 AM: go version go1.14.4 linux/amd64
10:06:38 AM: go version go1.14.4 linux/amd64
10:06:38 AM: Installing missing commands
10:06:38 AM: Verify run directory
10:06:40 AM: ​
10:06:40 AM: ┌─────────────────────────────┐
10:06:40 AM: │        Netlify Build        │
10:06:40 AM: └─────────────────────────────┘
10:06:40 AM: ​
10:06:40 AM: ❯ Version
10:06:40 AM:   @netlify/build 3.3.5
10:06:40 AM: ​
10:06:40 AM: ❯ Flags
10:06:40 AM:   deployId: 5f59de576c5284a12b44f34b
10:06:40 AM:   mode: buildbot
10:06:40 AM: ​
10:06:40 AM: ❯ Current directory
10:06:40 AM:   /opt/build/repo
10:06:40 AM: ​
10:06:40 AM: ❯ Config file
10:06:40 AM:   No config file was defined: using default values.
10:06:40 AM: ​
10:06:40 AM: ❯ Context
10:06:40 AM:   production
10:06:40 AM: ​
10:06:40 AM: ┌───────────────────────────────────┐
10:06:40 AM: │ 1. Build command from Netlify app │
10:06:40 AM: └───────────────────────────────────┘
10:06:40 AM: ​
10:06:40 AM: $ npm run generate
10:06:40 AM: > rellow_site@1.0.0 generate /opt/build/repo
10:06:40 AM: > nuxt generate
10:07:20 AM: ​
10:07:20 AM: (build.command completed in 40.9s)
10:07:20 AM: ​
10:07:20 AM: ┌─────────────────────────────┐
10:07:20 AM: │   Netlify Build Complete    │
10:07:20 AM: └─────────────────────────────┘
10:07:20 AM: ​
10:07:20 AM: (Netlify Build completed in 40.9s)
10:07:20 AM: Caching artifacts
10:07:20 AM: Started saving node modules
10:07:21 AM: Finished saving node modules
10:07:21 AM: Started saving build plugins
10:07:21 AM: Finished saving build plugins
10:07:21 AM: Started saving pip cache
10:07:21 AM: Finished saving pip cache
10:07:21 AM: Started saving emacs cask dependencies
10:07:21 AM: Finished saving emacs cask dependencies
10:07:21 AM: Started saving maven dependencies
10:07:21 AM: Finished saving maven dependencies
10:07:21 AM: Started saving boot dependencies
10:07:21 AM: Finished saving boot dependencies
10:07:21 AM: Started saving go dependencies
10:07:21 AM: Finished saving go dependencies
10:07:23 AM: Build script success
10:07:23 AM: Starting to deploy site from 'dist'
10:07:23 AM: Creating deploy tree 
10:07:23 AM: Creating deploy upload records
10:07:24 AM: 53 new files to upload
10:07:24 AM: 0 new functions to upload
10:07:25 AM: Starting post processing
10:07:25 AM: Post processing - HTML
10:07:26 AM: Post processing - header rules
10:07:26 AM: Post processing - redirect rules
10:07:26 AM: Post processing done
10:07:26 AM: Site is live
10:07:43 AM: Finished processing build request in 1m57.235866363s
```
</details>

**Comment by devpaps** [comment]
No problem at all @lihbr! Just happy for the help i'm getting.

Hm, i can see you got node v.12 in your log, in my log i got 8.17.0 and  npm v6.13.4. This is whats causing the error! Oh, my god! Thank you! 😀

And thanks for the info about the target option. 👌🏻

**Comment by lihbr** [comment]
Oh yes indeed! Node 8 reached EOL in January 🙂

Please close the issue if that sorted everything for you~
