### ISSUE TITLE
-

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/nuxt.js#8117]

**Comment by stephenjason89** [comment]
Update:
i run npm run start and waited for the cpu to go up
turns out, there's an error in my graphql tls


```
/var/www/html/test-nuxt/node_modules/zen-observable/lib/Observable.js:65
      throw e;
      ^
FetchError: request to https://ip-171-51-27-327.ap-southeast-1.compute.internal/api/graphql failed, reason: Hostname/IP does not match certificate's altnames: Host: ip-171-51-27-327.ap-southeast-1.compute.internal. is not in the cert's altnames: DNS:foodat.ph
    at ClientRequest.<anonymous> (/var/www/html/test-nuxt/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ERR_TLS_CERT_ALTNAME_INVALID',
  code: 'ERR_TLS_CERT_ALTNAME_INVALID'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foodat@1.0.0 start: `nuxt start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foodat@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2020-09-25T17_59_54_624Z-debug.log
```

I'm running an nginx proxy which proxies my graphqlserver to
foodat.ph/api/graphql

and im running a nuxt project node server at foodat.ph/

i did not use         '@nuxtjs/proxy',
to proxy it anymore because both are in foodat.ph domain right? 
why am i getting this error?
