### ISSUE TITLE
Unable to start a new project

### ISSUE THREAD

**Issue by palfaro91** [nuxt/nuxt.js#8151]
### Versions

- nuxt: latest
- node: 13.1
- npm: 6.14.8
- MacOs Mojave 10.14.6

### Steps to reproduce
Run npm init nuxt-app my-project-name

### What is Expected?
A new project is created

### What is actually happening?
An error is thrown and a new project is not created.
```
internal/modules/cjs/loader.js:548
  throw e;
  ^

Error: Package exports for '/Users/me/.config/yarn/global/node_modules/cac' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/pablo/.config/yarn/global/node_modules/create-nuxt-app/lib/cli.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by samkes** [comment]
Same issue for me but running with `yarn create nuxt-app <app-name>`

**Versions**
nuxt: latest
node: 13.1
npm: 6.14.8
Windows 10

**Comment by samkes** [comment]
Problem is solved with a node upgrade. See https://github.com/nodejs/modules/issues/446 for details on the issue.
