### ISSUE TITLE
Nuxt Build Error. Seems to fail on trying to compile Sass for VuetifyJS

### ISSUE THREAD

**Issue by timothymarois** [nuxt/nuxt.js#8369]
Running the `npm run dev` works perfectly, BUT

About a dozen of these errors on the `npm run build` 

There is something that nuxt does not like, this should not happen, you are testing locally and when you go to build it fails?? 

You go through hours possibly days of building, and yet when you actually want to finish your project and start setting up  towards production. you cant... This is not good for Nuxt. 

All these errors are coming from files I do not modify or access. 

```
ERROR in ./node_modules/vuetify/src/components/VGrid/_grid.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-1-3!./node_modules/vuetify/src/components/VGrid/_grid.sass)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'prependData'. These properties are valid:
   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }
    at validate (/Users/..../Documents/Development/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:104:11)
    at Object.loader (/Users/...../Documents/Development/node_modules/sass-loader/dist/index.js:30:29)
 @ ./node_modules/vuetify/src/components/VGrid/_grid.sass 4:14-204
 @ ./node_modules/vuetify/lib/components/VGrid/VContainer.js
 @ ./node_modules/vuetify/lib/components/VGrid/index.js
 @ ./pages/settings/general.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js
```

**Comment by timothymarois** [comment]
Just to rule out any of the project code, I deleted all the pages except the index.vue which I placed a simple div that says test, I removed all components, and simplified the default.vue layout. I removed all plugins, and middleware. I do not use SCSS/SASS. so that part cant even be me. 

This is the second time I've seen build problems with Nuxt. its becoming an issue. You can not work on the dev site and then move to production build and then everything fails. That makes no sense. This build process needs to be trusted.

**Comment by timothymarois** [comment]
I'm starting to think its related to wepback in some missing dependency. Looking at package.json and comparing it to fresh nuxt builds, its identical. I have added packages previously which I removed, that was a while ago, could be related. But still doesnt make sense.

**Comment by timothymarois** [comment]
After further investigation and testing. I cleared out the node_modules and ran a fresh install of dependencies. It looks like previously something happened with a sass package (probably from another npm package) and installing from package.json didnt solve the issue, had to completely clear out the node packages, makes no sense why it was caught up in some mysterious problem unrelated to anything I was working on. I'll close this, doesn't look like its directly impacted from Nuxt.
