### ISSUE TITLE
Unexpected token export error

### ISSUE THREAD

**Issue by pratiktmg19** [nuxt/nuxt.js#8427]
Unexpected token export                                                                               14:43:39

  export default function setupIcons(preset) {
  ^^^^^^
  
  SyntaxError: Unexpected token export
  at new Script (vm.js:83:7)
  at createScript (vm.js:277:10)
  at Object.runInThisContext (vm.js:329:10)
  at Module._compile (internal/modules/cjs/loader.js:712:26)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
  at Module.load (internal/modules/cjs/loader.js:653:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
  at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  at Module.require (internal/modules/cjs/loader.js:692:17)
  at require (internal/modules/cjs/helpers.js:25:18)

**Comment by pratiktmg19** [comment]
Huh? 
I didn't found the solution but it is working for now when i remove all the CDN present on presetCDN.
can you provide me any other solution.

**Comment by danielroe** [comment]
@pratiktmg19 I'd suggest you provide a bit more information - ideally a reproduction at https://template.nuxtjs.org/

But something about this looks like it might by solved by deleting `node_modules` or your package lockfile (or both) and reinstalling your packages.

**Comment by pratiktmg19** [comment]
Yes, i have tried reinstalling both but it didn't worked out.
It only works  when i comment out those presets in icons.js of veutify

**Comment by pratiktmg19** [comment]
Okay solved it by updating nuxt to latest version and vuetify to stable version.
