### ISSUE TITLE
Errors in production

### ISSUE THREAD

**Issue by TroyDota** [nuxt/nuxt.js#8431]
### Versions

- nuxt: ^2.14.6
- node: v14.15.1

### Reproduction

might be related to this as the stack trace is #1214

```
6383e8d.js:2 TypeError: Cannot read property '_transitionClasses' of undefined
    at Array.Er (6383e8d.js:2)
    at j (6383e8d.js:2)
    at 6383e8d.js:2
    at j (6383e8d.js:2)
    at f.__patch__ (6383e8d.js:2)
    at f.t._update (6383e8d.js:2)
    at f.r (6383e8d.js:2)
    at _n.get (6383e8d.js:2)
    at _n.run (6383e8d.js:2)
    at gn (6383e8d.js:2)
te @ 6383e8d.js:2
Zt @ 6383e8d.js:2
Yt @ 6383e8d.js:2
(anonymous) @ 6383e8d.js:2
ie @ 6383e8d.js:2
Promise.then (async)
ee @ 6383e8d.js:2
ue @ 6383e8d.js:2
(anonymous) @ 6383e8d.js:2
_n.update @ 6383e8d.js:2
_t.notify @ 6383e8d.js:2
set @ 6383e8d.js:2
Nt @ 6383e8d.js:2
value @ e738b80.js:2
value @ e738b80.js:2
value @ e738b80.js:2
t.$watch @ 6383e8d.js:2
value @ e738b80.js:2
value @ e738b80.js:2
value @ e738b80.js:2
J @ e738b80.js:2
Qt @ 6383e8d.js:2
cn @ 6383e8d.js:2
t._init @ 6383e8d.js:2
f @ 6383e8d.js:2
(anonymous) @ 6383e8d.js:2
init @ 6383e8d.js:2
n @ 6383e8d.js:2
R @ 6383e8d.js:2
(anonymous) @ 6383e8d.js:2
t._update @ 6383e8d.js:2
r @ 6383e8d.js:2
_n.get @ 6383e8d.js:2
_n @ 6383e8d.js:2
t @ 6383e8d.js:2
Tn.$mount @ 6383e8d.js:2
init @ 6383e8d.js:2
R @ 6383e8d.js:2
(anonymous) @ 6383e8d.js:2
t._update @ 6383e8d.js:2
r @ 6383e8d.js:2
_n.get @ 6383e8d.js:2
_n @ 6383e8d.js:2
t @ 6383e8d.js:2
Tn.$mount @ 6383e8d.js:2
init @ 6383e8d.js:2
R @ 6383e8d.js:2
R @ 6383e8d.js:2
(anonymous) @ 6383e8d.js:2
t._update @ 6383e8d.js:2
r @ 6383e8d.js:2
_n.get @ 6383e8d.js:2
_n @ 6383e8d.js:2
t @ 6383e8d.js:2
Tn.$mount @ 6383e8d.js:2
init @ 6383e8d.js:2
R @ 6383e8d.js:2
R @ 6383e8d.js:2
(anonymous) @ 6383e8d.js:2
t._update @ 6383e8d.js:2
r @ 6383e8d.js:2
_n.get @ 6383e8d.js:2
_n @ 6383e8d.js:2
t @ 6383e8d.js:2
Tn.$mount @ 6383e8d.js:2
init @ 6383e8d.js:2
R @ 6383e8d.js:2
R @ 6383e8d.js:2
(anonymous) @ 6383e8d.js:2
t._update @ 6383e8d.js:2
r @ 6383e8d.js:2
_n.get @ 6383e8d.js:2
_n @ 6383e8d.js:2
t @ 6383e8d.js:2
Tn.$mount @ 6383e8d.js:2
c @ e738b80.js:2
(anonymous) @ e738b80.js:2
h @ 6383e8d.js:2
(anonymous) @ 6383e8d.js:2
(anonymous) @ 6383e8d.js:2
r @ 6383e8d.js:2
l @ 6383e8d.js:2
Promise.then (async)
r @ 6383e8d.js:2
l @ 6383e8d.js:2
Promise.then (async)
r @ 6383e8d.js:2
l @ 6383e8d.js:2
(anonymous) @ 6383e8d.js:2
(anonymous) @ 6383e8d.js:2
F @ e738b80.js:2
(anonymous) @ e738b80.js:2
Promise.then (async)
(anonymous) @ e738b80.js:2
(anonymous) @ e738b80.js:2
c @ runtime.bb96482d97b311e4102a.js:1
(anonymous) @ e738b80.js:2
c @ runtime.bb96482d97b311e4102a.js:1
t @ runtime.bb96482d97b311e4102a.js:1
r @ runtime.bb96482d97b311e4102a.js:1
(anonymous) @ e738b80.js:2
Show 51 more frames from Library code

DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://cdn.admiralbulldog.live/static/vods/6383e8d.js:2:41280)
    at m (https://cdn.admiralbulldog.live/static/vods/6383e8d.js:2:54203)
    at v (https://cdn.admiralbulldog.live/static/vods/6383e8d.js:2:53940)
    at _ (https://cdn.admiralbulldog.live/static/vods/6383e8d.js:2:54289)
    at R (https://cdn.admiralbulldog.live/static/vods/6383e8d.js:2:57675)
    at R (https://cdn.admiralbulldog.live/static/vods/6383e8d.js:2:57610)
    at f.__patch__ (https://cdn.admiralbulldog.live/static/vods/6383e8d.js:2:58087)
    at f.t._update (https://cdn.admiralbulldog.live/static/vods/6383e8d.js:2:35026)
    at f.r (https://cdn.admiralbulldog.live/static/vods/6383e8d.js:2:65490)
    at _n.get (https://cdn.admiralbulldog.live/static/vods/6383e8d.js:2:27202)
```

### Steps to reproduce

No idea, when I am using SSR and when i reload the page uncaching it renders correctly, but then if I reload again after that it fails to mount. Production only, the development server does not produce this issue.

### What is Expected?

The vue objects mount correctly.

### What is actually happening?

No idea. Navigating from one page to the main page renders the object, only when the object is rendered serverside does it cause the hydration to fail.

You actually can go and test for yourself at 
https://vods.admiralbulldog.live/vods/d5f1f299-8d2a-4b20-8f0d-4b28590fc780

**Comment by TroyDota** [comment]
it seems that this causes the error 
```
middleware({ store, error }) {
   if (!store.state.vod && process.server) {
      error({ statusCode: 404, message: 'vod' })
    }
 },
```

**Comment by danielroe** [comment]
@TroyDota As you say, it's a hydration error, often produced by mismatching client/server state or invalid html. Check out https://html-validator.nuxtjs.org/ and https://blog.lichter.io/posts/vue-hydration-error/

**Comment by TroyDota** [comment]
Strange thing, is that it only happens after the page was rendered client side, the page is reloaded without redirection (which means it gets rendered serverside) but if the page is rendered serverside without first being rendered client-side it doesnt not error.
I also tested by wrapping stuff in the client-only tag but it doesnt do anything to the outcome still throws an error. ALso to note this error causes the page to be completely broken, no buttons/js works.

**Comment by TroyDota** [comment]
debugged it down to passing parameters to a child component

**Comment by TroyDota** [comment]
It seems
```<comp></comp>```
is not 
```<comp />```

**Comment by danielroe** [comment]
Likely they changed the HTML enough that Vue was unable to mount to it.

**Comment by TroyDota** [comment]
nginx was modifying dom in google-pagefast.
