### ISSUE TITLE
[2.14.12] "Package subpath './package.json' is not defined by "exports" in @nuxt/ufo/package.json"

### ISSUE THREAD

**Issue by ThibaultVlacich** [nuxt/nuxt.js#8500]
New release 2.14.12 seems to introduce a new bug when running `nuxt build`:
```
$ nuxt build
[fatal] Package subpath './package.json' is not defined by "exports" in <redacted>/@nuxt/ufo/package.json
  at applyExports (internal/modules/cjs/loader.js:487:9)
  at resolveExports (internal/modules/cjs/loader.js:503:23)
  at Function.Module._findPath (internal/modules/cjs/loader.js:631:31)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:949:27)
  at Function.Module._load (internal/modules/cjs/loader.js:838:27)
  at Module.require (internal/modules/cjs/loader.js:1022:19)
  at require (internal/modules/cjs/helpers.js:72:18)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:618:26)
  at Builder.validateTemplate (node_modules/@nuxt/builder/dist/builder.js:5674:38)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5602:12)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:109:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2803:7)

   ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                   │
   │   ✖ Nuxt Fatal Error                                                                                              │
   │                                                                                                                   │
   │   Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not                                  │
   │   defined by "exports" in                                                                                         │
   │   <redacted>/@nuxt/ufo/package.json                                                                            │
   │                                                                                                                   │
   ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
```

### Versions

- nuxt: 2.14.12
- node: 14.15.2

### What is Expected?

Nuxt is compiling.

### What is actually happening?

Nuxt does not compile.

**Comment by ThibaultVlacich** [comment]
My bad, there's already a closed issue ##8498
