### ISSUE TITLE
net::ERR_ABORTED 400 (Bad Request)

### ISSUE THREAD

**Issue by wensaint** [nuxt/nuxt.js#8561]
bugs:
fail to load js files, return 400 error

env:
nuxt: 2.14.12
node: 10.20.1
npm :6.14.4

------------details------------------------------------
```
runtime.js:919 GET http://localhost:3000/manage/_nuxt/layouts/blank.js net::ERR_ABORTED 400 (Bad Request)
requireEnsure @ runtime.js:919
fn.e @ runtime.js:177
_77180f1e @ App.js?efe7:14
loadLayout @ App.js?efe7:215
_callee3$ @ App.js?efe7:172
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
errorChanged @ App.js?efe7:172
run @ vue.runtime.esm.js?2b0e:4568
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4310
eval @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4402
update @ vue.runtime.esm.js?2b0e:4544
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
error @ index.js?f26e:115
_callee4$ @ client.js?06a0:197
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_throw @ asyncToGenerator.js?1da1:29
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?1da1:13
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
loadAsyncComponents @ client.js?06a0:147
iterator @ vue-router.esm.js?8c4f:2300
step @ vue-router.esm.js?8c4f:1947
step @ vue-router.esm.js?8c4f:1951
runQueue @ vue-router.esm.js?8c4f:1955
confirmTransition @ vue-router.esm.js?8c4f:2330
transitionTo @ vue-router.esm.js?8c4f:2203
push @ vue-router.esm.js?8c4f:2544
push @ vue-router.esm.js?8c4f:2966
push @ router.js?5783:343
handler @ vue-router.esm.js?8c4f:1133
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6917
runtime.js:896 Uncaught (in promise) ChunkLoadError: Loading chunk pages/Studenteducations/index failed.
(error: http://localhost:3000/manage/_nuxt/pages/Studenteducations/index.js)
    at Function.requireEnsure [as e] (http://localhost:3000/manage/_nuxt/runtime.js:896:26)
    at Function.fn.e (http://localhost:3000/manage/_nuxt/runtime.js:177:40)
    at _6fefd18f (webpack-internal:///./.nuxt/router.js:200:92)
    at _callee$ (webpack-internal:///./.nuxt/utils.js:280:22)
    at tryCatch (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:5:24)
    at _next (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:27:9)
    at eval (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:34:7)
requireEnsure @ runtime.js:896
fn.e @ runtime.js:177
_6fefd18f @ router.js?5783:53
_callee$ @ utils.js?ebed:134
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
eval @ utils.js?ebed:134
eval @ utils.js?ebed:123
eval @ utils.js?ebed:121
flatMapComponents @ utils.js?ebed:120
resolveRouteComponents @ utils.js?ebed:133
_callee2$ @ utils.js?ebed:145
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
getRouteData @ utils.js?ebed:145
_callee3$ @ utils.js?ebed:160
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
setContext @ utils.js?ebed:160
_callee6$ @ client.js?06a0:263
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
render @ client.js?06a0:263
iterator @ vue-router.esm.js?8c4f:2300
step @ vue-router.esm.js?8c4f:1947
eval @ vue-router.esm.js?8c4f:1948
eval @ vue-router.esm.js?8c4f:2322
_callee4$ @ client.js?06a0:199
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_throw @ asyncToGenerator.js?1da1:29
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?1da1:13
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
render @ client.js?06a0:263
iterator @ vue-router.esm.js?8c4f:2300
step @ vue-router.esm.js?8c4f:1947
eval @ vue-router.esm.js?8c4f:1948
eval @ vue-router.esm.js?8c4f:2322
_callee4$ @ client.js?06a0:199
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_throw @ asyncToGenerator.js?1da1:29
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?1da1:13
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
loadAsyncComponents @ client.js?06a0:147
iterator @ vue-router.esm.js?8c4f:2300
step @ vue-router.esm.js?8c4f:1947
step @ vue-router.esm.js?8c4f:1951
runQueue @ vue-router.esm.js?8c4f:1955
confirmTransition @ vue-router.esm.js?8c4f:2330
transitionTo @ vue-router.esm.js?8c4f:2203
push @ vue-router.esm.js?8c4f:2544
push @ vue-router.esm.js?8c4f:2966
push @ router.js?5783:343
handler @ vue-router.esm.js?8c4f:1133
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6917
Show 23 more frames
```

**main part of packages.json:**
```
 "dependencies": {
    "@nuxtjs/auth-next": "^5.0.0-1595320532.a4b460f",
    "@nuxtjs/axios": "^5.11.0",
    "@nuxtjs/style-resources": "^1.0.0",
    "@tinymce/tinymce-vue": "^3.2.2",
    "ant-design-vue": "^1.6.5",
    "autoprefixer": "^9.8.5",
    "babel-plugin-import": "^1.13.0",
    "jsencrypt": "^3.0.0-rc.1",
    "node-sass": "^4.14.1",
    "nuxt": "^2.14.12",
    "tinymce": "^5.4.1"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^3.0.0",
    "@nuxtjs/eslint-module": "^2.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-nuxt": "^1.0.0",
    "eslint-plugin-prettier": "^3.1.4",
    "less": "^3.12.2",
    "less-loader": "^6.2.0",
    "postcss-loader": "^3.0.0",
    "prettier": "^2.0.5",
    "sass-loader": "^9.0.2",
    "scss-loader": "^0.0.1",
    "vue-particles": "^1.0.9"
  },
```

**Comment by wensaint** [comment]
it turns out to be size of cookie issue.  my cookie is to long , so the nuxt-auth fail. 
I'll Close this issue
