### ISSUE TITLE
Problem to implement vue-simplemde

### ISSUE THREAD

**Issue by ArnoBuschmann** [nuxt/nuxt.js#857]
Hello,

I tried to integrate the vue-simplemde markdown editor (https://github.com/F-loat/vue-simplemde) in Nuxt and got this error:
```
  nuxt:render Rendering url / +11m
[vue-router] Failed to resolve async component default: SyntaxError: Unexpected token <
[vue-router] uncaught error during route navigation:
/home/arno/Projekte/Arno/test/nuxt-lebensraum/node_modules/vue-simplemde/markdown-editor.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^
SyntaxError: Unexpected token <
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/arno/Projekte/Arno/test/nuxt-lebensraum/node_modules/vue-simplemde/index.js:6:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```
The import was done like this:
```javascript
import { markdownEditor } from 'vue-simplemde'
export default {
  components: {
    markdownEditor
  }
```
while the template looked like this:
```
<markdown-editor v-model="content" ref="markdownEditor"></markdown-editor>
```
Has anyone an idea, how I could fix this problem? Thanks for having a look at this! :)

**Comment by alexchopin** [comment]
Hi, this library is not compile into a bundle.
You should use the [component](https://github.com/F-loat/vue-simplemde/blob/master/markdown-editor.vue) directly in Nuxt by copying it into your components directory.

**Comment by LiChangyi** [comment]
I also have this problem. I want to ask you how to solve it.

**Comment by ArnoBuschmann** [comment]
@LiChangyi I used https://www.npmjs.com/package/simplemde instead of vue-simplemde. That worked out well. Hope this helps?
