### ISSUE TITLE
bug in Nuxt Build

### ISSUE THREAD

**Issue by YallaDealz** [nuxt/nuxt.js#8671]
when i run "Nuxt build"  in my project i got this error 

 ERROR   /                                                                                                                                                      18:37:36

TypeError: Cannot read property 'renderRoute' of undefined
    at Generator.generateRoute (/home/yalladealz/Frontend/node_modules/@nuxt/generator/dist/generator.js:400:42)
    at async /home/yalladealz/Frontend/node_modules/@nuxt/generator/dist/generator.js:266:13
    at async Promise.all (index 0)
    at async Generator.generateRoutes (/home/yalladealz/Frontend/node_modules/@nuxt/generator/dist/generator.js:261:7)
    at async Generator.generate (/home/yalladealz/Frontend/node_modules/@nuxt/generator/dist/generator.js:139:20)
    at async Object.run (/usr/local/share/.config/yarn/global/node_modules/@nuxt/cli/dist/cli-build.js:100:7)
    at async NuxtCommand.run (/usr/local/share/.config/yarn/global/node_modules/@nuxt/cli/dist/cli-index.js:2759:7)

 FATAL  Cannot read property 'renderRoute' of undefined                                                                                                         18:37:36

  at Generator.afterGenerate (node_modules/@nuxt/generator/dist/generator.js:314:43)
  at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:141:5)
  at async Object.run (/usr/local/share/.config/yarn/global/node_modules/@nuxt/cli/dist/cli-build.js:100:7)
  at async NuxtCommand.run (/usr/local/share/.config/yarn/global/node_modules/@nuxt/cli/dist/cli-index.js:2759:7)

**Comment by YallaDealz** [comment]
but project run normally if i use " Npm run build"

**Comment by danielroe** [comment]
This was resolved via Discord - issue was mistakenly running `nuxt build` instead of `nuxt-ts build` (as specified in `package.json` build script).
