### ISSUE TITLE
Nuxt Module - Cannot read property 'registerModule' of undefined

### ISSUE THREAD

**Issue by savyir** [nuxt/nuxt.js#8737]
### Versions

- nuxt:  v2.14.12
- node: 12.3

### Reproduction
Hi,
I want to create a module for nuxt but I have an error. 

when I want to register store in plugin, I have this error 
``` 
TypeError: Cannot read property 'registerModule' of undefined
      at module.exports../.nuxt/src.plugin.25f524b6.js.__webpack_exports__.default (server.js:6804:15)
      at createApp (server.js:6085:98)
      at async module.exports../.nuxt/server.js.__webpack_exports__.default ```
```

in module file:

```
export default async function Module(moduleOptions) {
this.addPlugin({
      src: path.resolve(__dirname, 'plugin.js'),
      options
    })
}
```

in plugin file:
```
export default async (ctx, inject) => {
  try {
    ctx.store.registerModule('common', CommonStore)
    ctx.store.registerModule('commonSelect', CommonSelectStore)
  } catch (e) {
    console.error({e}, 'error on loading strore')
  }
}
```

thanks a lot

**Comment by savyir** [comment]
I think it was because I had no file in ``` store``` folder. the error disappeared once I created an empty store file.
is it possible to have ```ctx.store``` without any store file?
