### ISSUE TITLE
how to host nuxt+koa  with multi instances by pm2?

### ISSUE THREAD

**Issue by bi-kai** [nuxt/nuxt.js#8789]
I wanna to start `nuxt+koa` by pm2 with max instances.

# case 1
**restarting all  the time.** 
```
//pm2 start pm2.json
{
  "apps": [
    {
      "name": "software-measurement-platform-with-json",
      "script": "server/index.js",
      "instances": "1",
      "exec_mode": "cluster",
      "watch": false,
      "ignore_watch": ["node_modules", "lib/chromium", "test", "logs", "data", ".git", ".vscode"],
      "instance_var": "INSTANCE_ID",
      "env": {
        "DEBUG": "starlab:*",
        "NODE_ENV": "production"
      },
      "log_date_format": "YYYY-MM-DD HH:mm Z"
    }
  ]
}

```
comes with error:
```
0|software |
0|software | 2021-02-10 14:50 +08:00: [HPM] Proxy created: /api/  -> http://127.0.0.1:3010
0|software | 2021-02-10 14:50 +08:00: [HPM] Proxy rewrite rule created: "^/api/" ~> "/api"
0|software | 2021-02-10 14:50 +08:00: › baseURL: http://localhost:3000/api/v1
0|software | 2021-02-10 14:50 +08:00: › browserBaseURL: /api/v1
0|software | 2021-02-10 14:50 +08:00:
0|software |  READY  Server listening on http://localhost:3000
0|software |
0|software | 2021-02-10 14:50 +08:00: [HPM] Proxy created: /api/  -> http://127.0.0.1:3010
0|software | 2021-02-10 14:50 +08:00: [HPM] Proxy rewrite rule created: "^/api/" ~> "/api"
0|software | 2021-02-10 14:50 +08:00: › baseURL: http://localhost:3000/api/v1
0|software | 2021-02-10 14:50 +08:00: › browserBaseURL: /api/v1
0|software | 2021-02-10 14:50 +08:00:
0|software |  READY  Server listening on http://localhost:3000
0|software |

/root/.pm2/logs/software-measurement-platform-with-json-error-0.log last 15 lines:
0|software |     at processEmit [as emit] (/starlab/www/nodejs/software-measurement-platform/node_modules/signal-exit/index.js:161:32)
0|software |     at emit (internal/child_process.js:832:12)
0|software |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|software | 2021-02-10 14:50 +08:00:
0|software |  WARN  mode option is deprecated. You can safely remove it from nuxt.config
0|software |
0|software | Error: bind EADDRINUSE null:3000
0|software |     at listenOnMasterHandle (net.js:1347:16)
0|software |     at rr (internal/cluster/child.js:126:12)
0|software |     at Worker.send (internal/cluster/child.js:93:7)
0|software |     at process.onInternalMessage (internal/cluster/utils.js:45:8)
0|software |     at process.emit (events.js:203:15)
0|software |     at processEmit [as emit] (/starlab/www/nodejs/software-measurement-platform/node_modules/signal-exit/index.js:161:32)
0|software |     at emit (internal/child_process.js:832:12)
0|software |     at process._tickCallback (internal/process/next_tick.js:63:19)

0|software-measurement-platform-with-json  | 2021-02-10 14:50 +08:00:
0|software-measurement-platform-with-json  |  WARN  mode option is deprecated. You can safely remove it from nuxt.config
0|software-measurement-platform-with-json  | 2021-02-10 14:50 +08:00: [HPM] Proxy created: /api/  -> http://127.0.0.1:3010
0|software-measurement-platform-with-json  | 2021-02-10 14:50 +08:00: [HPM] Proxy rewrite rule created: "^/api/" ~> "/api"
0|software-measurement-platform-with-json  | 2021-02-10 14:50 +08:00: › baseURL: http://localhost:3000/api/v1
0|software-measurement-platform-with-json  | 2021-02-10 14:50 +08:00: › browserBaseURL: /api/v1
0|software-measurement-platform-with-json  | 2021-02-10 14:50 +08:00:
0|software-measurement-platform-with-json  |  READY  Server listening on http://localhost:3000
0|software-measurement-platform-with-json  | Error: bind EADDRINUSE null:3000
0|software-measurement-platform-with-json  |     at listenOnMasterHandle (net.js:1347:16)
0|software-measurement-platform-with-json  |     at rr (internal/cluster/child.js:126:12)
0|software-measurement-platform-with-json  |     at Worker.send (internal/cluster/child.js:93:7)
0|software-measurement-platform-with-json  |     at process.onInternalMessage (internal/cluster/utils.js:45:8)
0|software-measurement-platform-with-json  |     at process.emit (events.js:203:15)
0|software-measurement-platform-with-json  |     at processEmit [as emit] (/starlab/www/nodejs/software-measurement-platform/node_modules/signal-exit/index.js:161:32)
0|software-measurement-platform-with-json  |     at emit (internal/child_process.js:832:12)
0|software-measurement-platform-with-json  |     at process._tickCallback (internal/process/next_tick.js:63:19)
PM2                                        | App name:software-measurement-platform-with-json id:0 disconnected
PM2                                        | App [software-measurement-platform-with-json:0] exited with code [0] via signal [SIGINT]
PM2                                        | App [software-measurement-platform-with-json:0] starting in -cluster mode-
PM2                                        | App [software-measurement-platform-with-json:0] online
```

**Comment by bi-kai** [comment]
# case 2
I saw "ecosystem.config.js" mentioned in doc:https://nuxtjs.org/docs/2.x/deployment/deployment-pm2

page shows correctly, error log shown in pm2 log, no more logs any more.
```
//pm2 start
module.exports = {
  apps: [
    {
      name: 'software-measurement-platform-with-eco',
      exec_mode: 'cluster',
      instances: 'max', // Or a number of instances
      script: 'npm', // './node_modules/nuxt/bin/nuxt.js',
      args: 'run start',
      env: {
        NODE_ENV: 'production'
        // HOST: '0.0.0.0',
        // PORT: 3010
      }
    }
  ]
}

```
only the first instance is correctly, others are with error below:
```
/root/.pm2/logs/software-measurement-platform-with-eco-error-1.log last 15 lines:
1|software | npm ERR! code ELIFECYCLE
1|software | npm ERR! errno 1
1|software | npm ERR! software-measurement-platform-service@1.0.0 start: `cross-env NODE_ENV=production node server/index.js`
1|software | npm ERR! Exit status 1
1|software | npm ERR!
1|software | npm ERR! Failed at the software-measurement-platform-service@1.0.0 start script.
1|software | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by bi-kai** [comment]
# case 3
I saw "ecosystem.config.js" mentioned in doc:https://nuxtjs.org/docs/2.x/deployment/deployment-pm2
```
module.exports = {
  apps: [
    {
      name: 'software-measurement-platform',
      exec_mode: 'cluster',
      instances: '1', // Or a number of instances
      script: 'npm', // './node_modules/nuxt/bin/nuxt.js',
      args: 'run start',
      env: {
        NODE_ENV: 'production'
        // HOST: '0.0.0.0',
        // PORT: 3010
      }
    }
  ]
}
```
service is ok, pm2 log shows in `/root/.pm2/pm2.log` correctly.

**Comment by danielroe** [comment]
@bi-kai I appreciate you replying with more information. Could you provide a minimal reproduction - ie all the code needed to replicate these issues, ideally in a github repo?

**Comment by bi-kai** [comment]
# case 4
```
pm2 start npm --name "my-nuxt" -- run start
```
Start 1 instance with fork mode, logs shows in `pm2 log`, not in `/root/.pm2/pm2.log`.

```
pm2 start npm --name "my-nuxt" --cwd /starlab/www/nodejs/software-measurement-platform/ -i max -- run start
```
comes error:
```
READY  Server listening on http://127.0.0.1:3010

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3010
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Application.listen (/starlab/www/nodejs/software-measurement-platform/node_modules/koa/lib/application.js:82:19)
    at start (/starlab/www/nodejs/software-measurement-platform/server/index.js:172:7)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by danielroe** [comment]
@bi-kai Is there any chance you are hard coding the port in your koa server entrypoint?

**Comment by bi-kai** [comment]
@danielroe no, I am using the default code generated by nuxt-app.

**Comment by danielroe** [comment]
@bi-kai create-nuxt-app no longer generates any custom server presets. So you are likely using an old version.

It would be difficult to help with this unless you provide a full minimal reproduction. However, from looking at your error messages I would suggest a misconfiguration as it seems to be starting all your instances with the same port.

You may also find joining the Nuxt Discord to be helpful.

**Comment by bi-kai** [comment]
@danielroe yes, I am confused with the latest nuxt, I need koa as a server, so I selected nuxt@2.0.0.

**Comment by bi-kai** [comment]
@danielroe Is there any official doc could guide me, how to use koa with the latest nuxt?

**Comment by bi-kai** [comment]
The summary is as bellow:
pm2 start ecosystem.config.js # 1 个实例，日志输出到/root/.pm2/pm2.log
pm2 start npm --name "software-measurement-platform-with-cmd" -- run start # 1 个实例，日志输出到控制台，不会记录到 pm2 日志文件
