### ISSUE TITLE
ERROR  Error: Callback was already called.   (on ver 2.15.0)

### ISSUE THREAD

**Issue by nelsonlarocca** [nuxt/nuxt.js#8828]
I got the error, clean node_modules, run install and the issue appeared again

```
   ╭──────────────────────────────────────────╮
   │                                          │
   │   Nuxt @ v2.15.0                         │
   │                                          │
   │   ▸ Environment: development             │
   │   ▸ Rendering:   server-side             │
   │   ▸ Target:      server                  │
   │                                          │
   │   Listening: http://10.179.0.194:8080/   │
   │                                          │
   ╰──────────────────────────────────────────╯

i Preparing project for development                                                                               06:42:52
i Initial build may take a while                                                                                  06:42:52
√ Builder initialized                                                                                             06:42:53
√ Nuxt files generated                                                                                            06:42:53

* Client █████████████████████████ building (70%) 386/416 modules 30 active
 babel-loader » node_modules\vuetify\lib\components\VResponsive\index.js

* Server █████████████████████████ building (35%) 210/254 modules 44 active
 babel-loader » node_modules\vuetify\lib\install.js


 ERROR  Error: Callback was already called.                                                                       06:43:33  
    at throwError (C:\Projects\YaMenu\YaMenu-Frontend\YaMenu-Website\node_modules\neo-async\async.js:16:11)
    at C:\Projects\YaMenu\YaMenu-Frontend\YaMenu-Website\node_modules\neo-async\async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)


 ERROR  Error: Callback was already called.                                                                       06:43:33  
    at throwError (C:\Projects\node_modules\neo-async\async.js:16:11)
    at C:\Projects\node_modules\neo-async\async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)


 ERROR  Error: Callback was already called.                                                                       06:43:33  
    at throwError (C:\Projects\node_modules\neo-async\async.js:16:11)
    at C:\Projects\node_modules\neo-async\async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

it seems compiling is interrupted on the same point every time
```

**Comment by edsonbraz** [comment]
I've got a similar issue while trying to use "extractCSS: true".
It turns out to be a problem with the project directory being case sensitive on Windows. 
Check your folder name and try running it with the exact same name.

**Comment by rahulkumarsingh73690** [comment]
Same error I tried everything but no luck :(

Nuxt.config.js - https://goonlinetools.com/snapshot/code/#rytalq1mm7nmnlk8wh3qmg

**Comment by nelsonlarocca** [comment]
@rahulkumarsingh73690 

try to:
1- remove the node_modules folder
2- verify no eslint cache file exists

then run 'npm install' or 'yarn' depending on the tool you use

let me know if that works

**Comment by nelsonlarocca** [comment]
Try removing yarn.lock also

**Comment by rahulkumarsingh73690** [comment]
@nelsonlarocca 

Still same error

**Comment by rahulkumarsingh73690** [comment]
> Same error I tried everything but no luck :(
> 
> Nuxt.config.js - https://goonlinetools.com/snapshot/code/#rytalq1mm7nmnlk8wh3qmg

Solution - Turn off Vuetify default assets

**Comment by squonk11** [comment]
Hello,

I have the same problem but I am new to vuetify - how can I turn off Vuetify default assets?
