### ISSUE TITLE
Nuxt Fetch working only on server side

### ISSUE THREAD

**Issue by filippolcr** [nuxt/nuxt.js#8830]
nuxt: v2.15.0
node: v14.15.4
@nuxtjs/sanity: ^0.7.0

### Reproduction
Nuxt 2.15 with Typescript support
🚧 I'm working on a reproduction link, but there's Sanity as cms, I don't clearly know how to prepare a reproduction for this issue

### Steps to reproduce
I've a class PageVue that extend Vue, with $sanity fetch to retrieve data from Sanity CMS in all my nuxt page components.

```
export default class PageBarIndex extends PageVue<SanityPageInterface> {
  async fetch(this: PageBarIndex) {
    const slug = 'bar'
    await this.retrievePage(slug)
    const query = groq`*[_type == "bar"]`
    const sanityBars: SanityProductInterface[] = await this.$sanity.fetch<SanityProductInterface[]>(query)
    this.sanityBars = this.sanityBars.concat(sanityBars)
  }
}
```

In PageVue class:

```
export class PageVue<T extends SanityPageInterface> extends Vue {
  page: Nullable<T> = null

  async retrievePage(slug: string) {
    try {
      const query = groq`*[slug.current == "${slug}"][0]`
      const page: T = await this.$sanity.fetch<T>(query)
      this.page = page
    } catch (error) {
      console.log('retrievePage error', error)
    }
  }
  
```

In page component I have:

```
 <fetch-pending v-if="$fetchState.pending" />
    <fetch-error
      v-else-if="$fetchState.error"
      :message="$fetchState.error.message"
    />
    <div v-else class="w-full">
     ....render data from sanity
    </div>
```

### What is Expected?
Fetch working properly and I'm able to render the proper fetched data from Sanity

### What is actually happening?
Fetch happens only on Server side, so if I inspect the source code server rendered by Nuxt, everything is ok, but when I navigate through page components with nuxt-router the $fetchState is not pending or error, but the data is not properly set in component, and, I think, vue not hydrate the components and the page is blank.

If I refresh the page everything is ok.

**Comment by lexcode** [comment]
Same error happening to me after upgrading nuxt 

```javascript
  async fetch () {
    this.results = await this.$strapi.$homepage.find({
      slug: 'homepage'
    })
    this.slice_component = this.results.slice_component
  }
```

```error
client.js?06a0:57 Error in fetch(): HTTPError: Forbidden
    at fn (server.js:9612:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Ky._retry (server.js:9710:16)
    at async HTTP.module.exports../.nuxt/http.js.HTTP.<computed> [as get] (server.js:1258:24)
    at async VueComponent.fetch (pages/index.js:63:20)
    at async VueComponent.serverPrefetch (server.js:1759:5)
    at async Promise.all (index 0) {
  response: Response {
    size: 0,
    timeout: 0,
    text: [Function],
    json: [Function],
    data: { statusCode: 403, error: 'Forbidden', message: 'Forbidden' },
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'http://localhost:1337/homepage?slug=homepage',
      status: 403,
      statusText: 'Forbidden',
      headers: [Headers],
      counter: 0
    }
  },
  statusCode: 403,
  original: { statusCode: 403, error: 'Forbidden', message: 'Forbidden' }
}
```

**Comment by danielroe** [comment]
If either of you could prepare a reproduction, that would be helpful 👍

**Comment by filippolcr** [comment]
@danielroe an update here! 🤪  I'm working on a fully working repo from the codebase (not ready yet)
This morning we simply put the fetchKey as follow for every page component.
We just follow this: [https://github.com/nuxt/nuxt.js/pull/8466](https://github.com/nuxt/nuxt.js/pull/8466) 🙏

```
@Component({
  fetchOnServer: true,
  fetchKey: 'just-a-string',
  components: {
    …
  }
})
```

For dynamic page, as _slug.vue:

```
fetchKey(getCounter) {
    if (condition) {
      return this.slug
    }
    return 'product' + getCounter('product')
},
```

With this implementation, after a nuxt-link clicking the page component is rendered correctly. 👍

Inspecting the network tab in Chrome dev tools, we found a payload.js as follow that we think did the work well.

```
__NUXT_JSONP__("/a-page-route", (function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x) {
    r._type = g;
    r.metaDescription = {
        _type: h,
        it: c
    };
    r.metaTitle = {
        _type: b,
        it: c
    };
    s._type = i;
    s.current = k;
    t._type = b;
    t.it = c;
    return {
        data: [{}],
        fetch: {
            "just-astring:0": {
                page: {  
     …

```

**Comment by lexcode** [comment]
@filippolcr @danielroe I can confirm that 2.15.1 version fix the issue for me. thank you!
