### ISSUE TITLE
✖ Nuxt Fatal Error   2.15.0 (for `npm run build`)

### ISSUE THREAD

**Issue by steklopod** [nuxt/nuxt.js#8840]
### Versions

- nuxt: 2.15.0
- node: v15.8.0

### Reproduction

1. Upgrade to `2.14.12` -> `2.15.0`
2. run `npm run dev` or `npm run build`

```sh
FATAL  ParseError: Support for the experimental syntax 'classProperties' isn't currently enabled (5:14):                                                                                 23:07:43



Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-class-properties (https://git.io/vb4yQ) to the 'plugins' section to enable parsing. 
 /Users/dmitrykoltovich/IdeaProjects/colaba/frontend/modules/socketClient.js:5:13

  
  
  
  Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
  If you want to leave it as-is, add @babel/plugin-syntax-class-properties (https://git.io/vb4yQ) to the 'plugins' section to enable parsing.
  modules/socketClient.js:5:13
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:381:29)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:182:38)
  at node_modules/@nuxt/utils/dist/utils.js:638:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)


   ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                                                 │
   │   ✖ Nuxt Fatal Error                                                                                                                            │
   │                                                                                                                                                 │
   │   Error: ParseError: Support for the experimental syntax 'classProperties' isn't currently enabled (5:14):                                      │
   │                                                                                                                                                 │
   │                                                                                                                                                 │
   │                                                                                                                                                 │
   │   Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.    │
   │   If you want to leave it as-is, add @babel/plugin-syntax-class-properties (https://git.io/vb4yQ) to the 'plugins' section to enable parsing.   │
   │   /Users/dmitrykoltovich/IdeaProjects/colaba/frontend/modules/socketClient.js:5:13                                                              │
   │                                                                                                                                                 │
   ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


### `package.json`

```json
{
  "name": "name",
  "description": "text",
  "author": "developers",
  "private": true,
  "homepage": "https://github.com",
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@mapbox/mapbox-gl-geocoder": "^4.7.0",
    "@nuxtjs/auth-next": "^5.0.0-1612791489.a5d8c28",
    "@nuxtjs/axios": "^5.13.1",
    "@nuxtjs/dotenv": "^1.4.1",
    "@stomp/stompjs": "^6.0.0",
    "js-cookie": "^2.2.1",
    "mapbox-gl": "^2.1.1",
    "nuxt": "^2.15.0",
    "sockjs-client": "^1.5.0",
    "vuetify": "^2.4.4"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.12.13",
    "@mdi/js": "latest",
    "@nuxt/types": "latest",
    "@nuxtjs/date-fns": "latest",
    "@nuxtjs/vuetify": "latest"
  }
}
```

#### `nuxt.config.js`

```js
require('dotenv').config();
const webpack = require('webpack');
import pkg from './package';
import ru from 'vuetify/es5/locale/ru';
import en from 'vuetify/es5/locale/en';
import colors from 'vuetify/lib/util/colors';
import overriddenMdiIcons from './assets/mdiJsSvgIcons';

export default {
    head: {
        title: pkg.name,
        meta: [
            {charset: 'utf-8'},
            {
                name: 'viewport',
                content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui'
            },
            {hid: 'description', name: 'description', content: pkg.description}
        ],
        link: [{rel: 'icon', type: 'image/x-icon', href: '/favicon.ico'}]
    },
    loading: {color: '#5864FF'},
    css: ['~assets/font/fonts.css', '~assets/style/index.scss', '~/assets/style/route_transitions.scss'],
    components: true,
    vuetify: {
        defaultAssets: false,
        treeShake: true,
        icons: {iconfont: 'mdiSvg', values: overriddenMdiIcons},
        lang: {locales: {ru, en}, current: 'ru'},
        customVariables: ['~/assets/style/variables.scss'],
        theme: {
            options: {
                customProperties: true
            }
        }
    },
    modules: ['@nuxtjs/axios', '@nuxtjs/auth-next'],
    buildModules: ['@nuxtjs/vuetify', '@nuxtjs/dotenv', '@/modules/socketClient', ['@nuxtjs/date-fns', { defaultLocale: 'ru', locales: ['ru'] }]],
    plugins: ['@/plugins/utils.js', '@/plugins/vuetify.js' /*,'@/plugins/axios'*/],
    axios: {debug: true /* credentials: true, https: true */},
    build: {
        transpile: ['vuetify/lib'],
        plugins: [new webpack.ProvidePlugin({mapboxgl: 'mapbox-gl', geocoder: '@mapbox/mapbox-gl-geocoder'})]
    }
}

```

**Comment by clarkdo** [comment]
Looks your code includes class properties which is not enabled in babel-preset-env by default, can you please try to add @babel/plugin-proposal-class-properties to build.babel.plugins in nuxt config ?

**Comment by clarkdo** [comment]
May I ask what does colaba/frontend/modules/socketClient.js look like and how is it imported in your repo?

**Comment by steklopod** [comment]
@clarkdo thanks for quick response.  My `modules/socketClient.js` is important. There are my `stompJs` configs and chat methods:
```js
import SockJS from "sockjs-client";
import {Client} from '@stomp/stompjs';

class SocketClient {
    wsClient = null;

    createStompClient() {
        const token = !!$nuxt.$auth.strategy.token.get() ? $nuxt.$auth.strategy.token.get() : null;
        // ....
    }

    subscribeToChats(chats) {
      // ....
    }
    // ... other methods
}

export let client = new SocketClient();
export default function () {
    return client;
}

```

**Comment by clarkdo** [comment]
@steklopod  Is this a new module in your repo ? I think it won't work for lower nuxt verisons as well.

**Comment by clarkdo** [comment]
Is that possible upgrading your node to 12+ which has started supporting class properties ?

Or you can move `wsClient` to constructor:

```js
class SocketClient {
    constructor() {
        this.wsClient = null;
    }

    createStompClient() {
        const token = !!$nuxt.$auth.strategy.token.get() ? $nuxt.$auth.strategy.token.get() : null;
        // ....
    }

    subscribeToChats(chats) {
      // ....
    }
    // ... other methods
}
```

**Comment by steklopod** [comment]
I have latest node: `v15.8.0`
