### ISSUE TITLE
new nuxt install with windcss ui , yarn build back crash..

### ISSUE THREAD

**Issue by anyban** [nuxt/nuxt.js#9020]
### Versions

- nuxt:  2.15.3
- node: 14

### Steps to reproduce
yarn create nuxt-app someone
add Wind CSS ui-framework
yarn build
### What is Expected?

 FATAL  Nuxt build error                                                                                                                                                  17:41:41

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at processTicksAndRejections (node:internal/process/task_queues:94:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:110:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)

   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

### What is actually happening?

after new install nuxt with wind css and when try yarn build we have crash...

**Comment by ChangJoo-Park** [comment]
It cause 0.4.5 nuxt-windicss-module. Please use 0.4.4

**Comment by harlan-zw** [comment]
Hey, this one is a windi issue. You can close this issue here as it's sorted in that repo anyway.

See: https://github.com/windicss/nuxt-windicss-module/issues/28 https://github.com/windicss/nuxt-windicss-module/issues/29
