### ISSUE TITLE
New release breaks production build 

### ISSUE THREAD

**Issue by gkatsanos** [nuxt/nuxt.js#9117]
```
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options.modules has an unknown property 'compileType'. These properties are valid:
   object { auto?, mode?, exportGlobals?, localIdentName?, localIdentRegExp?, context?, hashPrefix?, getLocalIdent? }
    at validate (/app/node_modules/schema-utils/dist/validate.js:98:11)
    at Object.loader (/app/node_modules/css-loader/dist/index.js:36:28)
```

Probably that's linked to : https://github.com/nuxt/nuxt.js/pull/9014

**Comment by gkatsanos** [comment]
We added css-loader in our package.json (it wasn't there) and yes, now things work. ?
```js
    "css-loader": "^5.2.0",
```
