### ISSUE TITLE
Unexpected token function in production

### ISSUE THREAD

**Issue by Jesus82** [nuxt/nuxt.js#9181]
Hi, I'm having an "unexpected token function" in my production server, while in local everything works perfect.

In both environments node version is `v12.16.3` and npm is `7.10.0`. Nuxt version is `2.15.4`

When doing `npm start` or `npm run build` in production, I get:

```
/myfolder/node_modules/@nuxt/cli/dist/cli-index.js:333
async function loadNuxtConfig (argv, configContext) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/myfolder/node_modules/@nuxt/cli/dist/cli.js:11:15)
```
In nuxt.config.js, I have it like this

```
module.exports = {
  target: 'server',
}
```

I checked all other answers regarding this, but in this case is a core nuxt file that is giving the error. Any ideas about what could be the issue here? Thanks in advance!

**Comment by Jesus82** [comment]
I fixed it by rolling back to `node v10.24.1` and `npm v6.14.12` in production server.

**Comment by Jesus82** [comment]
Hi @danielroe just in production, in local I'm still running `node v12.16.3` and npm `7.10.0` with no problem at all.

**Comment by Jesus82** [comment]
Yep, see screenshot attached. If you need I can give you access to the repo.

[https://i.ibb.co/tzHy8mz/nuxt.png](https://i.ibb.co/tzHy8mz/nuxt.png)
