### ISSUE TITLE
generate command fails on Windows.

### ISSUE THREAD

**Issue by HajifuDev** [nuxt/nuxt.js#9185]
Thank you for developing nuxt.
I don't know if it's a Windows problem, but I'm having trouble with the following situation.

### Versions

- nuxt: 2.15.4
- node: 12.16.3

### Reproduction

```json
// package.json
"dependencies": {
    "@nuxt/content": "^1.14.0",
    "@nuxtjs/axios": "^5.12.5",
    "@nuxtjs/composition-api": "^0.23.2",
    "@nuxtjs/dotenv": "^1.4.1",
    "dayjs": "^1.8.29",
    "firebase": "^8.4.1",
    "firebase-admin": "^9.6.0",
    "node-sass": "^5.0.0",
    "nuxt": "^2.15.4",
    "nuxt-device-detect": "^1.1.5",
    "nuxt-webfontloader": "^1.1.0",
    "sass-loader": "^11.0.1"
  },
  "devDependencies": {
    "@nuxt/types": "^2.15.4",
    "@nuxt/typescript-build": "^2.1.0",
    "@nuxtjs/vuetify": "^1.11.3",
    "ts-loader": "^9.1.0"
  }
```

### Steps to reproduce
Run the `npm run generate` command with the above dependencies.

### What is Expected?
I want the generate command to be executed.

### What is actually happening?
My console displays the following error and terminates the process.

```bash
✖ Nuxt Fatal Error
Error: Path C:/Users/User/OneDrive/Desktop/myPJ/firebase.json is not in cwd C:\Users\User\OneDrive\Desktop\myPJ
```
Is there a difference between a pass slash and a backslash?

```bash
// callstack
at ensureAbsolutePathForCwd (node_modules\globby\gitignore.js:55:9)
at node_modules\globby\gitignore.js:62:55
at node_modules\globby\index.js:135:47
at Array.filter (<anonymous>)
at Object.module.exports [as default] (node_modules\globby\index.js:135:30)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async snapshot (node_modules\@nuxt\cli\dist\cli-generate.js:193:17)
at async ensureBuild (node_modules\@nuxt\cli\dist\cli-generate.js:91:32)
at async Object.run (node_modules\@nuxt\cli\dist\cli-generate.js:283:7)
at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:413:7)
```

**Comment by HajifuDev** [comment]
@danielroe thanks to reply! 

I tried to use codesandbox to provide it, but I could not reproduce it.  
However, when I developed it in the WSL environment as you recommended, I was able to generate it without this error, thanks! I will use WSL from now on.  
Thanks also for pointing out sass-loader.

**Comment by febrihidayan** [comment]
@danielroe when can it support sass-loader 11?

**Comment by danielroe** [comment]
@febrihidayan `sass-loader` is for webpack 5 - so not until Nuxt releases support with webpack 5 with Nuxt 3.

**Comment by packaaa** [comment]
Hello, when will windows fit

**Comment by LKF123LKF** [comment]
windows 10:
 
ensureAbsolutePathForCwd (node_modules\globby\gitignore.js:56:9)

```
const ensureAbsolutePathForCwd = (cwd, p) => {
  
    cwd = slash(cwd);
	if (path.isAbsolute(p)) {
		if (slash(p).startsWith(cwd)) {
			return p;
		}

		throw new Error(`Path ${p} is not in cwd ${cwd}`);
	}

	return path.join(cwd, p);
};
```

change as
```
const ensureAbsolutePathForCwd = (cwd, p) => {
    p= path.normalize(p)
    cwd = slash(cwd);
	if (path.isAbsolute(p)) {
		if (slash(p).startsWith(cwd)) {
			return p;
		}

		throw new Error(`Path ${p} is not in cwd ${cwd}`);
	}

	return path.join(cwd, p);
};
```

 add this "   p= path.normalize(p)",and it work
