### ISSUE TITLE
Build error on creating a bare additional layout

### ISSUE THREAD

**Issue by SharadKumar** [nuxt/nuxt.js#928]
I created a new project using starter template and hardly much there yet. I am using Atom and create a new layout and app fails immediately with the following error:

```
Nuxt.js Error:

Error: Module build failed: Error: Couldn't find preset "vue-app" relative to directory "/Users/sharad/Github/project/.nuxt"
    at /usr/local/lib/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/usr/local/lib/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/nuxt/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/nuxt/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/usr/local/lib/node_modules/nuxt/node_modules/babel-loader/lib/index.js:48:20)
    at /usr/local/lib/node_modules/nuxt/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/usr/local/lib/node_modules/nuxt/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:419:13)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:8889:7)
    at __webpack_require__ (webpack:/webpack/bootstrap 3a7d60dfe999ae354580:25:0)
    at Object.<anonymous> (.nuxt/App.vue:3:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 3a7d60dfe999ae354580:25:0)
    at Object.<anonymous> (server-bundle.js:8110:68)
    at __webpack_require__ (webpack:/webpack/bootstrap 3a7d60dfe999ae354580:25:0)
    at Object.<anonymous> (server-bundle.js:8503:65)
    at __webpack_require__ (webpack:/webpack/bootstrap 3a7d60dfe999ae354580:25:0)
    at module.exports._toString (webpack:/webpack/bootstrap 3a7d60dfe999ae354580:93:0)
    at Object.<anonymous> (server-bundle.js:98:10)
    at evaluateModule (/usr/local/lib/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5820:21)
    at /usr/local/lib/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5878:18
    at Promise (<anonymous>)
    at /usr/local/lib/node_modules/nuxt/node_modules/vue-server-renderer/build.js:5870:14
    at Nuxt.renderToString (/usr/local/lib/node_modules/nuxt/node_modules/vue-server-renderer/build.js:6022:9)
    at P (/usr/local/lib/node_modules/nuxt/node_modules/pify/index.js:49:6)
```

My new layout can be any filename, but all I did was use snippet in Atom.
```
<template lang="html">

</template>

<script>
export default {}
</script>

<style lang="css">
</style>
```

I am pointed to "latest" nuxt in package.json.

**Comment by SharadKumar** [comment]
Okay, this is happening in route.js as I just noticed on terminal.
```
ERROR  Failed to compile with 1 errors
 error  in ./.nuxt/router.js
Module build failed: Error: Couldn't find preset "vue-app" relative to directory
...
```

**Comment by SharadKumar** [comment]
Ok, I can confirm this also happens as I add a new page, and not just a layout. Something is wrong here :)

**Comment by SharadKumar** [comment]
Odd... I cleared node_modules and .nuxt and it went away :-/

**Comment by cjestal** [comment]
Hi, @SharadKumar . I'm facing this as well.

> I cleared node_modules and .nuxt
By clearing, what did you do exactly?
