### ISSUE TITLE
Setting auth to false in Nuxt page is not working

### ISSUE THREAD

**Issue by Pacheco95** [nuxt/nuxt.js#9343]
### Versions

- nuxt: v2.14.6
- node: v14.15.4

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
```js
// nuxt.config.js
export default {
  srcDir: 'src',
  head: {
    title: 'dashboard',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
  },

  css: ['~/assets/style/variables', '~/assets/style/global'],

  publicRuntimeConfig: {
    baseURL: process.env.BASE_URL,
  },
  privateRuntimeConfig: {},

  plugins: [
    '@/plugins/antd-ui',
    '@/plugins/repository',
    '@/plugins/filters',
    '@/plugins/currency-input',
  ],

  components: false,

  ssr: false,

  buildModules: [
    '@nuxt/typescript-build',
    '@nuxtjs/stylelint-module',
  ],

  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/auth-next',
  ],

  axios: {
    baseURL: process.env.BASE_URL,
    headers: {
      common: {
        'Access-Control-Allow-Origin': '*',
      },
    },
  },

  loading: {
    color: '#db6889',
  },

  build: {
    loaders: {
      less: {
        lessOptions: {
          javascriptEnabled: true,
        },
      },
    },
    extend(config, ctx) {
      config.devtool = ctx.isClient ? 'eval-source-map' : 'inline-source-map'
    },
  },

  router: {
    middleware: ['auth'],
  },

  auth: {
    redirect: {
      home: '/',
      login: '/auth/signin',
      logout: '/auth/signin',
    },
    strategies: {
      local: {
        token: {
          property: 'authToken',
        },
        endpoints: {
          login: { url: '/auth/dash-login', method: 'post' },
          logout: { url: '/auth/logout', method: 'put' },
          user: { url: '/auth/self', method: 'get' },
        },
      },
    },
  },
}
```

```vue
// pages/signup/index.js
<template>
  <div></div>
</template>

<script lang="ts">
import { Component, Vue } from 'nuxt-property-decorator'

@Component({
  layout: 'auth',
  auth: false,
})
export default class SignUpPage extends Vue {}
</script>
```

### What is Expected?
Once signup page configured `auth: false`, accessing `/signup` route should not call `user` endpoint through `auth` settings 

### What is actually happening?
`/signup` route is calling `user` endpoint through `auth` settings even with `auth: false` causing this error

```
xhr.js?b50d:177 GET https://redacted/auth/self 401 (Unauthorized)
index.js?6fc5:378 Uncaught (in promise) Error: ERR_ACTION_ACCESS_UNDEFINED: Are you trying to access this.someMutation() or this.someGetter inside an @Action? 
That works only in dynamic modules. 
If not dynamic use this.context.commit("mutationName", payload) and this.context.getters["getterName"]
Error: Could not perform action fetchCategories
    at Store.eval (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:392:37)
    at step (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:137:23)
    at Object.eval [as throw] (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:118:53)
    at rejected (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:109:65)
Error: ERR_ACTION_ACCESS_UNDEFINED: Are you trying to access this.someMutation() or this.someGetter inside an @Action? 
That works only in dynamic modules. 
If not dynamic use this.context.commit("mutationName", payload) and this.context.getters["getterName"]
Error: Could not perform action performRequest
    at Store.eval (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:392:37)
    at step (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:137:23)
    at Object.eval [as throw] (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:118:53)
    at rejected (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:109:65)
Error: ERR_ACTION_ACCESS_UNDEFINED: Are you trying to access this.someMutation() or this.someGetter inside an @Action? 
That works only in dynamic modules. 
If not dynamic use this.context.commit("mutationName", payload) and this.context.getters["getterName"]
Error: Could not perform action getCompanyId
    at Store.eval (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:392:37)
    at step (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:137:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:118:53)
    at eval (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:111:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:107:12)
    at Store.action (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:352:20)
    at Array.wrappedActionHandler (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:860:23)
    at Store.dispatch (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:525:15)
    at Store.boundDispatch [as dispatch] (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:415:21)
TypeError: Cannot read property 'company' of null
    at Object.getCompanyId (webpack-internal:///./src/store/categories-store.ts:250:28)
    at Store.eval (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:365:65)
    at step (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:137:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:118:53)
    at eval (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:111:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:107:12)
    at Store.action (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:352:20)
    at Array.wrappedActionHandler (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:860:23)
    at Store.dispatch (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:525:15)
    at Store.eval (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:386:35)
    at step (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:137:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:118:53)
    at eval (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:111:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:107:12)
    at Store.action (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:352:20)
    at Array.wrappedActionHandler (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:860:23)
    at Store.dispatch (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:525:15)
    at Store.boundDispatch [as dispatch] (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:415:21)
    at Store.eval (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:386:35)
    at step (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:137:23)
    at Object.eval [as throw] (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:118:53)
    at rejected (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:109:65)
    at Store.eval (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:386:35)
    at step (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:137:23)
    at Object.eval [as throw] (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:118:53)
    at rejected (webpack-internal:///./node_modules/vuex-module-decorators/dist/esm/index.js:109:65)```
    
    This error breaks my vuex store and prevents my signup page to load correctly.
    I tried to ask this question in discord channel but with no answers yet.

**Comment by Pacheco95** [comment]
https://github.com/nuxt-community/auth-module/issues/1192
