### ISSUE TITLE
Module build failed: Error: No ESLint configuration found.

### ISSUE THREAD

**Issue by manhlinhit** [nuxt/nuxt.js#947]
I download start template and create new project.
I run `npm install`, every thing ok.
But when run `npm run dev` then error

```
ERROR  Failed to compile with 2 errors                                                                      7:01:54 PM

Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/home/manhlinhng/www/manhlinhng/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/home/manhlinhng/www/manhlinhng/node_modules/eslint/lib/config.js:260:26)
    at processText (/home/manhlinhng/www/manhlinhng/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/home/manhlinhng/www/manhlinhng/node_modules/eslint/lib/cli-engine.js:754:26)
    at lint (/home/manhlinhng/www/manhlinhng/node_modules/eslint-loader/index.js:211:17)
    at Object.module.exports (/home/manhlinhng/www/manhlinhng/node_modules/eslint-loader/index.js:206:21)

Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/home/manhlinhng/www/manhlinhng/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/home/manhlinhng/www/manhlinhng/node_modules/eslint/lib/config.js:260:26)
    at processText (/home/manhlinhng/www/manhlinhng/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/home/manhlinhng/www/manhlinhng/node_modules/eslint/lib/cli-engine.js:754:26)
    at lint (/home/manhlinhng/www/manhlinhng/node_modules/eslint-loader/index.js:211:17)
    at Object.module.exports (/home/manhlinhng/www/manhlinhng/node_modules/eslint-loader/index.js:206:21)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
```

![screenshot from 2017-06-21 19-05-10](https://user-images.githubusercontent.com/12053260/27383402-12fec5f2-56b5-11e7-92c6-3f93f4f32fdb.png)

**Comment by pi0** [comment]
@manhlinhit Please disable linter section inside nuxt.config.js file

**Comment by manhlinhit** [comment]
You talk about this section
![screenshot from 2017-06-21 19-13-28](https://user-images.githubusercontent.com/12053260/27383632-03bbcd5a-56b6-11e7-8b90-8fe2edd3307f.png)

**Comment by pi0** [comment]
Yep :) If you need eslint .eslint file and dev dependencies are then needed.

**Comment by BenRichter** [comment]
For a quick start, I installed the https://www.npmjs.com/package/**eslint-config-vue** package. Works like a charm

**Comment by BruceHem** [comment]
So sudden i get this error, can't figure out why, I do have .eslintrc.js in root.

**Comment by dubrod** [comment]
Found this Issue page during a Google Search for the same Linting error during webpack. 

in webpack.base.conf.js just comment out this line

```
module: {
    rules: [
      //...(config.dev.useEslint ? [createLintingRule()] : []),
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
```

I tried all the other suggestions first.

**Comment by jscottsf** [comment]
Just got this now. Completely out of nowhere. Digging.
