### ISSUE TITLE
[Nuxt Fatal Erro] TypeError: pattern.replace is not a function

### ISSUE THREAD

**Issue by mahammad-sixberries** [nuxt/nuxt.js#9475]
### Versions

- nuxt: 2.15.7
- node: v14.17.1

### Steps to reproduce
-  build throught ci/cd pipline using aws code deploy

### What is Expected?
- build properly throuhg ci/cd pipline

### What is actually happening?
[2021-06-23 12:24:45.992] [d-YO5ZEVSG9][stderr] FATAL  pattern.replace is not a function
[2021-06-23 12:24:45.992] [d-YO5ZEVSG9][stderr]
[2021-06-23 12:24:45.992] [d-YO5ZEVSG9][stderr]  at WebpackClientConfig.normalizeTranspile (node_modules/@nuxt/webpack/dist/webpack.js:4341:37)
[2021-06-23 12:24:45.992] [d-YO5ZEVSG9][stderr]  at new WebpackBaseConfig (node_modules/@nuxt/webpack/dist/webpack.js:4314:36)
[2021-06-23 12:24:45.993] [d-YO5ZEVSG9][stderr]  at new WebpackClientConfig (node_modules/@nuxt/webpack/dist/webpack.js:4731:5)
[2021-06-23 12:24:45.993] [d-YO5ZEVSG9][stderr]  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5133:26)
[2021-06-23 12:24:45.993] [d-YO5ZEVSG9][stderr]  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5518:30)
[2021-06-23 12:24:45.993] [d-YO5ZEVSG9][stderr]  at async Object.run (node_modules/@nuxt/cli/dist/cli-chunk6.js:89:7)
[2021-06-23 12:24:45.993] [d-YO5ZEVSG9][stderr]
[2021-06-23 12:24:46.013] [d-YO5ZEVSG9][stderr]
[2021-06-23 12:24:46.013] [d-YO5ZEVSG9][stderr]   ╭──────────────────────────────────────────────────╮
[2021-06-23 12:24:46.013] [d-YO5ZEVSG9][stderr]   │                                                  │
[2021-06-23 12:24:46.013] [d-YO5ZEVSG9][stderr]   │   :heavy_multiplication_x: Nuxt Fatal Error                             │
[2021-06-23 12:24:46.013] [d-YO5ZEVSG9][stderr]   │                                                  │
[2021-06-23 12:24:46.014] [d-YO5ZEVSG9][stderr]   │   TypeError: pattern.replace is not a function   │
[2021-06-23 12:24:46.014] [d-YO5ZEVSG9][stderr]   │                                                  │
[2021-06-23 12:24:46.014] [d-YO5ZEVSG9][stderr]   ╰──────────────────────────────────────────────────╯
[2021-06-23 12:24:46.014] [d-YO5ZEVSG9][stderr]

**Comment by xianxuzhen** [comment]
how to solve it?
