### ISSUE TITLE
FATAL Cannot find module 'typescript' 

### ISSUE THREAD

**Issue by alexchudnovsky** [nuxt/nuxt.js#9726]
### Versions

Nuxt @ v2.15.8 
Node v14.16.1
NPM: 6.14.12 

OS: Debian

### Reproduction

root@radiant-clean-server:/home/pm2/radiantclean# npm run build

> radiant-clean-2.0@1.0.0 build /home/pm2/radiantclean
> nuxt build

ℹ Production build                                                                                                                                                                          12:59:43
ℹ Bundling for server and client side                                                                                                                                                       12:59:43
ℹ Target: server                                                                                                                                                                            12:59:43
ℹ Using components loader to optimize imports                                                                                                                                               12:59:43
ℹ Discovered Components: .nuxt/components/readme.md                                                                                                                                         12:59:43
✔ Builder initialized                                                                                                                                                                       12:59:43
✔ Nuxt files generated                                                                                                                                                                      12:59:43

 FATAL  Cannot find module 'typescript'                                                                                                                                                     12:59:44
Require stack:
- /home/pm2/radiantclean/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/TypeScriptReporterConfiguration.js
- /home/pm2/radiantclean/node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPluginConfiguration.js
- /home/pm2/radiantclean/node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.js
- /home/pm2/radiantclean/node_modules/fork-ts-checker-webpack-plugin/lib/index.js
- /home/pm2/radiantclean/node_modules/@nuxt/typescript-build/dist/index.js

  Require stack:
  - node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/TypeScriptReporterConfiguration.js
  - node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPluginConfiguration.js
  - node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.js
  - node_modules/fork-ts-checker-webpack-plugin/lib/index.js
  - node_modules/@nuxt/typescript-build/dist/index.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
  at Function.a [as resolve] (node_modules/jiti/dist/v8cache.js:2:2508)
  at Object.createTypeScriptReporterConfiguration (node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/TypeScriptReporterConfiguration.js:16:70)
  at Object.createForkTsCheckerWebpackPluginConfiguration (node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPluginConfiguration.js:11:55)
  at ForkTsCheckerWebpackPlugin.apply (node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.js:47:73)
  at Object.webpack [as default] (node_modules/webpack/lib/webpack.js:51:13)
  at node_modules/@nuxt/webpack/dist/webpack.js:2056:51
  at Array.map (<anonymous>)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2055:37)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:110:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)

   ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                                     │
   │   ✖ Nuxt Fatal Error                                                                                                                │
   │                                                                                                                                     │
   │   Error: Cannot find module 'typescript'                                                                                            │
   │   Require stack:                                                                                                                    │
   │   - /home/pm2/radiantclean/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/TypeScriptReporterConfiguration.js   │
   │   - /home/pm2/radiantclean/node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPluginConfiguration.js               │
   │   - /home/pm2/radiantclean/node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.js                            │
   │   - /home/pm2/radiantclean/node_modules/fork-ts-checker-webpack-plugin/lib/index.js                                                 │
   │   - /home/pm2/radiantclean/node_modules/@nuxt/typescript-build/dist/index.js  

<details open>
<summary>Additional Details</summary>

package.json is below

{
  "name": "radiant-clean-2.0",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/strapi": "^0.3.1",
    "core-js": "^3.15.1",
    "nuxt": "^2.15.7",
    "qs": "^6.10.1",
    "vuetify": "^2.5.5"
  },
  "devDependencies": {
    "@nuxt/types": "^2.15.7",
    "@nuxt/typescript-build": "^2.1.0",
    "@nuxtjs/vuetify": "^1.12.1",
    "@vue/test-utils": "^1.2.1",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^27.0.5",
    "jest": "^27.0.5",
    "ts-jest": "^27.0.3",
    "vue-jest": "^3.0.4"
  }
}

I also have typescript installed globally 

root@radiant-clean-server:/home/pm2/radiantclean# npm list -g --depth=0
/usr/lib
├── npm@6.14.12
├── pm2@4.5.6
└── typescript@4.4.2

</details>

### Steps to reproduce
npm run build

### What is Expected?
It should build, but it saying can't find module typescript

### What is actually happening?
Fatal Error: Cannot find module 'typescript'

**Comment by alexchudnovsky** [comment]
I have fixed this issue, by doing a local install of typescript, for some reason global does not work.. 

I am not sure if this is a bug or not, but either way it is resolved :)
