### ISSUE TITLE
Nuxt/Bridge Error 

### ISSUE THREAD

**Issue by thomas4Bitcraft** [nuxt/nuxt.js#9943]
### Versions

- nuxt-bridge: 3.0.0-27235989.d52b1e8
- node: v12.14.0

### Reproduction

- Install nuxt/bridge as explained in the nuxt docs
- run `npm run dev`

### What is actually happening?
If I try to run the project an error occur ( see screenshot below )

 ```
FATAL  Cannot read property 'default' of undefined                                                                                                                                          01:45:23

  at nuxt.config.js:12:186
  at v (node_modules/jiti/dist/jiti.js:1:54801)
  at Object.loadNuxtConfig (node_modules/@nuxt/config-edge/dist/config.js:819:15)
  at loadNuxtConfig (node_modules/nuxt-edge/node_modules/@nuxt/cli-edge/dist/cli-index.js:310:36)
  at NuxtCommand.getNuxtConfig (node_modules/nuxt-edge/node_modules/@nuxt/cli-edge/dist/cli-index.js:412:26)
  at Object._listenDev (node_modules/nuxt-edge/node_modules/@nuxt/cli-edge/dist/cli-dev.js:69:30)
  at Object.startDev (node_modules/nuxt-edge/node_modules/@nuxt/cli-edge/dist/cli-dev.js:55:25)
  at Object.run (node_modules/nuxt-edge/node_modules/@nuxt/cli-edge/dist/cli-dev.js:50:16)
  at NuxtCommand.run (node_modules/nuxt-edge/node_modules/@nuxt/cli-edge/dist/cli-index.js:371:22)

```

![image](https://user-images.githubusercontent.com/44415527/137227687-2e1a5f54-8b5f-4da8-a451-1ba19a462a86.png)

**Comment by thomas4Bitcraft** [comment]
right - closing
