### ISSUE TITLE
Module not found: Error: Can't resolve 'vue-router' after install and build

### ISSUE THREAD

**Issue by davestewart** [nuxt/nuxt.js#9997]
### Versions

- nuxt: edge
- node: 14

### Steps to reproduce

Upgraded existing project as outlined in the upgrade doc: https://v3.nuxtjs.org/getting-started/bridge/

```
- "nuxt": "^2.15.0"
+ "nuxt-edge": "latest"
```
```
npm install
npm run build
```

The build fails (see terminal output below).

### Steps to mitigate

If I install Vue Router manually, the build works:

```
"vue-router": "^3.5.3",
```

The build also runs in the browser.

### What is Expected?

The build would complete.

### What is actually happening?

The build fails:

```
> finsbury@1.0.0 build /Volumes/Data/Work/Work/Finsbury/04_development/finsbury-news
> nuxt build

ℹ Production build                                                                                13:31:47
ℹ Bundling for server and client side                                                             13:31:47
ℹ Target: server                                                                                  13:31:47
ℹ Using components loader to optimize imports                                                     13:31:47
ℹ Discovered Components: .nuxt/components/readme.md                                               13:31:47
✔ Builder initialized                                                                             13:31:47
✔ Nuxt files generated                                                                            13:31:47
✖ Client
  Compiled with some errors in 19.44s
◯ Server
  
Hash: 3ac13c53c550a1fe2abe
Version: webpack 4.46.0
Time: 19424ms
Built at: 10/28/2021 1:32:09 PM
                           Asset       Size                                    Chunks               Chunk Names
                      02c3c4e.js   1.55 KiB                                        18  [immutable]  components/ui-form-item
                      0c1a8a7.js   19.4 KiB                     2, 10, 18, 19, 21, 23  [immutable]  pages/archive/companies/pages/archive/executives
                      0cef21e.js   3.11 KiB                                        25  [immutable]  pages/archive/companies
                      1d14dd9.js   2.18 KiB                                         6  [immutable]  components/article
                      26d9832.js   4.79 KiB                                      7, 6  [immutable]  components/article-preview
                      336dc39.js    1.3 KiB                                        23  [immutable]  components/ui-table-selectable
                      361b2de.js   43.3 KiB  39, 6, 7, 10, 14, 16, 18, 19, 20, 21, 24  [immutable]  pages/news/search
                      397d131.js   1.69 KiB                                        15  [immutable]  components/ui-actions
                      40d6abd.js   1.43 KiB                                         9  [immutable]  components/logo
                      4506a5b.js  244 bytes                                        10  [immutable]  components/page
                      497e709.js   4.42 KiB                                    17, 18  [immutable]  components/ui-date-select
                      540a1d4.js   7.78 KiB                                    40, 13  [immutable]  pages/test
                      6842ef3.js   1.08 KiB                                        14  [immutable]  components/two-columns
                      6dd13c0.js   43.9 KiB                                         1  [immutable]  vendors/components/ui-select/pages/archive/companies/pages/archive/executives/pages/archive/fast-sea/4aa3d4f7
                      71ad63c.js   4.29 KiB                                        28  [immutable]  pages/debug
                      828c125.js    2.5 KiB                                    30, 13  [immutable]  pages/lists
                      8ae2bbd.js   14.5 KiB                                    21, 18  [immutable]  components/ui-select
                      9039fea.js   1.66 KiB                                     3, 20  [immutable]  pages/mentions/view
                      93f0343.js  320 bytes                                        11  [immutable]  components/site-footer
                      95b8333.js  341 bytes                                         8  [immutable]  components/debug
                      969d86b.js   15.9 KiB                                        43  [immutable]  vendors/pages/news/report
                      9a5c5bb.js   2.97 KiB                                        26  [immutable]  pages/archive/executives
                      9ba4233.js   1.69 KiB                                        13  [immutable]  components/top-nav
                      9c5cb6a.js   9.35 KiB                                38, 10, 20  [immutable]  pages/news/report
                      9f431b5.js    225 KiB                                         5  [immutable]  commons/app
                        LICENSES  974 bytes                                                         
                      a10653b.js     21 KiB                                         0  [immutable]  vendors/components/article/components/article-preview/components/web-page/pages/archive/fast-search//b0c66db7
                      a28402d.js    960 KiB                                        42  [immutable]  vendors/app
                      a576a94.js   1.95 KiB                                    31, 20  [immutable]  pages/lists/index
                      b2e78fd.js   1.79 KiB                                        16  [immutable]  components/ui-date-range
                      b4035aa.js   22.6 KiB                    27, 10, 16, 18, 20, 21  [immutable]  pages/archive/fast-search
                      c80cc81.js   2.87 KiB                                        12  [immutable]  components/test-form
                      cbef088.js   2.02 KiB                                        22  [immutable]  components/ui-table-crud
                      d0ce9d9.js   5.91 KiB                            37, 10, 15, 20  [immutable]  pages/news/index
                      d2a2553.js   2.48 KiB                                    36, 13  [immutable]  pages/news
                      d422d4a.js   2.45 KiB                                    33, 13  [immutable]  pages/mentions
                      d722c4f.js   1.95 KiB                                    29, 10  [immutable]  pages/index
                      d72d7e3.js  932 bytes                                        20  [immutable]  components/ui-panel
                      dd06b31.js   20.9 KiB                        35, 18, 19, 20, 21  [immutable]  pages/mentions/search
                      e172ca2.js    2.7 KiB                                     24, 6  [immutable]  components/web-page
                      e6c5581.js    4.6 KiB                                    19, 18  [immutable]  components/ui-input
                      f485f9e.js   5.01 KiB                                    32, 20  [immutable]  pages/lists/journalists
                      fa2d15b.js   2.78 KiB                                        41  [immutable]  runtime
                      fa45fc2.js   1.63 KiB                                    34, 20  [immutable]  pages/mentions/index
fonts/element-icons.313f7da.woff   27.5 KiB                                            [immutable]  
 fonts/element-icons.4520188.ttf   54.6 KiB                                            [immutable]  
Entrypoint app = fa2d15b.js 9f431b5.js a28402d.js

ERROR in ./.nuxt/router.js
Module not found: Error: Can't resolve 'vue-router' in '/Volumes/Data/Work/Work/Finsbury/04_development/finsbury-news/.nuxt'
 @ ./.nuxt/router.js 17:0-32 132:8-14 215:19-25
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js

ERROR in chunk app [initial]
02e3f42.js
/Volumes/Data/Work/Work/Finsbury/04_development/finsbury-news/node_modules/@nuxt/webpack-edge/node_modules/babel-loader/lib/index.js??ref--2-0!/Volumes/Data/Work/Work/Finsbury/04_development/finsbury-news/.nuxt/index.js 80b4dcb79f38585a58088a7498283384
Unexpected token (180:19)
| function createRouter(ssrContext, config) {
|   var base = config._app && config._app.basePath || routerOptions.base;
|   var router = new !(function webpackMissingModule() { var e = new Error("Cannot find module 'vue-router'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())(_objectSpread(_objectSpread({}, routerOptions), {}, {
|     base: base
|   })); // TODO: remove in Nuxt 3

 FATAL  Nuxt build error                                                                          13:32:09

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack-edge/dist/webpack.js:1871:21)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack-edge/dist/webpack.js:1836:5)
  at async Builder.build (node_modules/@nuxt/builder-edge/dist/builder.js:262:5)
  at async Object.run (node_modules/nuxt-edge/node_modules/@nuxt/cli-edge/dist/cli-build.js:103:7)
  at async NuxtCommand.run (node_modules/nuxt-edge/node_modules/@nuxt/cli-edge/dist/cli-index.js:371:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! finsbury@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the finsbury@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Dave/.npm/_logs/2021-10-28T12_32_09_121Z-debug.log

Process finished with exit code 1
```

**Comment by arjan-kitchenstories** [comment]
Just found this report - I'm running into the same issue with a production app after trying out nuxt-bridge. The build fails, adding vue-router manually resolves it.

**Comment by Supriya-wil** [comment]
Hi, I'm using Nuxt@2.15.8 version I encountered the same issue.
ERROR in ./.nuxt/router.js
Step #2 - "build": Module not found: Error: Can't resolve '../pages/404.vue' in '/workspace/.nuxt'
Step #2 - "build":  @ ./.nuxt/router.js 22:24-77
Step #2 - "build":  @ ./.nuxt/index.js
Step #2 - "build":  @ ./.nuxt/client.js
Step #2 - "build":  @ multi ./.nuxt/client.js
Step #2 - "build": 
Step #2 - "build":  FATAL  Nuxt build error
Step #2 - "build": 
Step #2 - "build":   at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:1868:21)
Step #2 - "build":   at processTicksAndRejections (node:internal/process/task_queues:96:5)
Step #2 - "build":   at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:1833:5)
Step #2 - "build":   at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:249:5)
Step #2 - "build":   at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:99:7)
Step #2 - "build":   at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:356:7)
Step #2 - "build": 
Step #2 - "build": 
Step #2 - "build":    ╭─────────────────────────────╮
Step #2 - "build":    │                             │
Step #2 - "build":    │   ✖ Nuxt Fatal Error        │
Step #2 - "build":    │                             │
Step #2 - "build":    │   Error: Nuxt build error   │
Step #2 - "build":    │                             │
Step #2 - "build":    ╰─────────────────────────────╯
